### ISSUE TITLE
[Feature] Hierarchy and reuse of configuration

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#10]
A customer have many teams, each with their own Jenkins. The teams needs to inherit a standard configuration available, and then add their own team specific configuration.
The standard configuration should be able to be overwritten if the team want to use 99% and not only add to it.
What happens when the standard configuration is updated?

**Comment by ndeloof** [comment]
same issue applies to any *-as-code approach.
Simpler option is to have a reference branch/repository in company "jenkins-as-code" repository and get teams to use a custom branch / fork it. So they just have to pull on updates. Something comparable to updating a docker image on it's upstream `FROM` image updates.

**Comment by ewelinawilkosz** [comment]
since we've introduced support for folder as a location of multiple yaml files I do think this issue can be closed
what would help is support for repo + branch as a config location, but that's a separate issue
