### ISSUE TITLE
Create a CasC subproject and Documentation entry jenkins.io

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#102]
It's a follow-up to the discussions at FOSDEM.

* It would be great to have the project listed here: https://jenkins.io/projects/ . It could be an entry point to the documentation
* Maybe a special "Configuration-as-Code" documentation page would also help, but the plugin needs to be released first IMHO

**Comment by daniel-beck** [comment]
AFAIUI, solutions are about problems people have before they use Jenkins, and Jenkins helps them solve those.

That doesn't apply to C-as-C. Neither is there a Pipeline or Job DSL solution page to finally getting rid of overly complex manually configured freestyle jobs.

**Comment by oleg-nenashev** [comment]
@daniel-beck Replaced "Solution page" by "Documentation page" in the subject, would it work for you? I have already wanted to create such page to move/facelift the https://wiki.jenkins.io/display/JENKINS/Groovy+Hook+Script bits, so maybe we could start from there

**Comment by buep** [comment]
Related to #86 about making roadmap more clear, also discussing to be on Jenkins project page.

**Comment by ewelinawilkosz** [comment]
WiP in https://github.com/ewelinawilkosz/jenkins.io/tree/jcasc
Basically a copy of Blue Ocean layout - can I do it?
Content to be updated

**Comment by oleg-nenashev** [comment]
Draft PR is here: https://github.com/jenkins-infra/jenkins.io/pull/1618

**Comment by ewelinawilkosz** [comment]
merged and live at jenkins.io
we've decided maintaining a roadmap would be difficult, instead we're keeping (or trying to) github issues and milestones up to date
