### ISSUE TITLE
DataBoundConfigurator enforces Constructor fields when ParametersAreNonnullByDefault is set, regardless of the CheckForNull flag

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1025]
It is a follow-up to the discussion in https://github.com/SonarSource/sonar-scanner-jenkins/pull/124#discussion_r317989554 with @Smasherr . https://github.com/jenkinsci/configuration-as-code-plugin/blob/f72058445c0250041303a73b5d8566140d337c67/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L109-L137 checks `ParametersAreNonnullByDefault ` and fails for a null para,eter, even if a `CheckForNull` or `Nullable` annotation is set for a constructor parameter.

AFAICT it is a regression in https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.24 after the annotation handling enhancements in https://github.com/jenkinsci/configuration-as-code-plugin/pull/950. CC @AbhyudayaSharma

**Comment by AbhyudayaSharma** [comment]
Yes, the changes made in #950 do not consider either of those annotations. For reference, this is how IDEA checks for `Nonnull`ness: https://github.com/JetBrains/intellij-community/blob/be6247932aa9414ddf7831c0e3becba6940f4839/java/java-psi-api/src/com/intellij/codeInsight/NullableNotNullManager.java

**Comment by oleg-nenashev** [comment]
Probably it is a time when we include SpotBugs Core into JCasC :crazy:
