### ISSUE TITLE
Document JSON Schema as a Beta feature instead of production-ready

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1028]
Taking the current situation with jSON Schema generation (TL;DR: it does not work) and ongoing project by @sladyn98 , my suggestion would be to explicitly mark the feature as Beta in documentation and to add proper API annotations. It would allow us to introduce breaking changes while the community Bridge project is in progress.

Acceptance criteria:

* Documentation is updated to highlight the status
* All APIs are annotated accordingly so that we can break then

WDYT @sladyn98 @casz @timja ?

**Comment by casz** [comment]
http://stats.jenkins.io/pluginversions/hashicorp-vault-plugin.html
Plugin users on 2.138.4 or newer is 84% on 2.138.4
We have 87% on 2.138.1 (these can easily upgrade to 2.138.4)

**Comment by sladyn98** [comment]
Yeah, definitely adding annotations to the API's would make it easier to introduce changes to the plugin.As @casz suggested once the Schema Validation gets set up we could use it to validate before `configureWith()` is called making the schema indirectly used by the plugin.
1. The schema generation will not be explicitly used by the plugin.
2. The validation however will be used based on the schema generated.
3. The API for schema generation will be used to post the shcema on the URL:`configuration-as-code/schema`.Thus during the developement of this the annotations could become highly useful.
4.With respect to the document changes, I could create a PR with the beta feature description.

Thoughts: @oleg-nenashev @timja @casz

**Comment by sladyn98** [comment]
@casz  Could you provide me a link to the doc and I could make a PR stating that the shcema is in beta.

**Comment by casz** [comment]
Add to the readme ❓

**Comment by sladyn98** [comment]
Sounds cool :)

**Comment by oleg-nenashev** [comment]
Is there anything left to be done here @sladyn98 ?

**Comment by sladyn98** [comment]
No nothing.
