### ISSUE TITLE
Update multibranch job demo to include id

### ISSUE THREAD

**Issue by chris-mac** [jenkinsci/configuration-as-code-plugin#1033]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ x] Jenkins version 2.176.3

- [ x] Plugin version 1.29

- [ x] OS Docker Jenkins Alpine LTS

### Description

The current multibranch job demo no longer works as id is now mandatory
https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#migrating-to-175

**Comment by casz** [comment]
No need to create an issue sending pull requests provides the same level of information.

**Comment by chris-mac** [comment]
@casz do we need to update the Contribution guide as was trying to follow that?
```
Regarding source code contribution WoW
Create a GitHub issue for your feature/problem you want to solve
Implement solution on a branch in your fork
Make sure to include issue number in commit message, and make the message speak for itself
Once you're done create a pull request and ask at least one of the maintainers for review
Remember to title your pull request properly as it is used for release notes
```

**Comment by casz** [comment]
Well the guide could be updated, but for simple stuff a pull request is fine :)
