### ISSUE TITLE
Documentation generator does not filter out inapplicable tool installers

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1036]
Documentation generator uses the base type for `ToolInstaller`, but it does not filter out inapplicable implementation for a particular `ToolInstallation`. Likely it is a symptom of a wider issue in extension handling in the documentation generator

![image](https://user-images.githubusercontent.com/3000480/64030286-8752a380-cb46-11e9-8b96-c0fec17e7ea9.png)

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Jenkins version

- [ ] Plugin version

- [ ] OS

**Comment by timja** [comment]
I tried fixing this, it's not easy 😢. It seems to mostly affect Tools, not much else that I can see.

`getApplicableDescriptors()` needs to be called somewhere when loading values but I couldn't find a way to do it at least with how it's currently being built.

An example usage of it is in `GitTool`
https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/hudson/plugins/git/GitTool.java#L185
