### ISSUE TITLE
VsCode Autocompletion and validation via the newly Generated JSON Schema

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/configuration-as-code-plugin#1056]
The newly generated JSON Schema https://github.com/jenkinsci/configuration-as-code-plugin/pull/980 validates basic schemas. This can be leveraged in VScode via :

1. Plugin
2. Local JSON Schema uploaded on a JSON Schema Store

**Comment by oleg-nenashev** [comment]
Option 2 would be a nice thing to document as a quick win. We could also have  unified schema generation and deployment for https://github.com/jenkinsci/bom bundles (CC @jglick) 

Option 1 looks to be a preferred solution for usage IRL

**Comment by sladyn98** [comment]
Option 1 looks really cool because If I read correctly vscode api pulls the JSON Schema off the schema store.

**Comment by timja** [comment]
> Option 1 looks really cool because If I read correctly vscode api pulls the JSON Schema off the schema store. [joshuaavalon.io/intellisense-json-yaml-vs-code](https://joshuaavalon.io/intellisense-json-yaml-vs-code)

not sure how this related to option 1, you don't have to write a plugin as the redhat yaml plugin already does that, you just need an improved schema?

**Comment by sladyn98** [comment]
Progress on this front: We could do the following with respect to VSCode.
Instead of a plugin my thoughts on this are:
a) Addition of the `schema.json` to the work-space.
b) Addition of the settings required to invoke the schema with the help of the redhat-plugin
We could add this to the readme and users would then be able to leverage of the schema.

CC : @oleg-nenashev @timja @casz

**Comment by timja** [comment]
> Progress on this front: We could do the following with respect to VSCode.
> Instead of a plugin my thoughts on this are:
> a) Addition of the `schema.json` to the work-space.
> b) Addition of the settings required to invoke the schema with the help of the redhat-plugin
> We could add this to the readme and users would then be able to leverage of the schema.
> 
> CC : @oleg-nenashev @timja @casz

I think this is good for v1, v2 we could publish the full schema to schema store then it's one less step for users.

but we need to get the nested configuration working so the schema knows about required fields

**Comment by sladyn98** [comment]
@timja I could make a PR with the existing schema to schemaStore to get our schema included.So that users can test it out as a beta. Or we could wait for nesting to be supported.

**Comment by timja** [comment]
Lets get a better schema before sending it there

**Comment by timja** [comment]
when I used it I tested with this: https://github.com/hmcts/cnp-jenkins-docker/tree/fix-organisations-and-docs
and then did
CMD + SHIFT + P => Preferences: Open settings (JSON) =>
```
{
"yaml.schemas": {
        "schema.json": "/cac-*.yml"
    }
}
```

**Comment by sladyn98** [comment]
@timja +1

**Comment by sladyn98** [comment]
The uses of having Vs Code integration for the YAML files can be considered below:
1) Can be used for auto completion of fields , enabling users to find it easier to complete the YAML file.
2) Documentation of fields is subject to https://github.com/jenkinsci/configuration-as-code-plugin/pull/1060, this would help developers get more information about the fields.
3) Validation of the YAML would also be possible, however the same can be accomplished by using the `configurewith` method in JCasC, hence IMO we would not need the VSCode plugin to provide us with a validation, JCasC can do the same with verbose error reporting.
The above features can be provided without explicitly adding plugin support. Uploading the schema to schemaStore would enable VScode to pick up all of the information via the SchemaStore api and would just have 1-2 steps for the developers to perform, and a explicit plugin would not provide us with anything more.
cc @timja @oleg-nenashev @casz

**Comment by timja** [comment]
> The uses of having Vs Code integration for the YAML files can be considered below:
> 
> 1. Can be used for auto completion of fields , enabling users to find it easier to complete the YAML file.

👍 

> 2. Documentation of fields is subject to #1060, this would help developers get more information about the fields.

👍 
> 3. Validation of the YAML would also be possible, however the same can be accomplished by using the `configurewith` method in JCasC, hence IMO we would not need the VSCode plugin to provide us with a validation, JCasC can do the same with verbose error reporting.

This could be integrated with a plugin to make it seamless for the user though.

>    The above features can be provided without explicitly adding plugin support. Uploading the schema to schemaStore would enable VScode to pick up all of the information via the SchemaStore api and would just have 1-2 steps for the developers to perform, and a explicit plugin would not provide us with anything more.
>    cc @timja @oleg-nenashev @casz

uploading to schema store is difficult though because every plugin impacts the schema and any plugin update could require the schema to be re-generated.
I'm not sure if this would work well...

**Comment by sladyn98** [comment]
{
   "definitions": {},
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "http://example.com/root.json",
   "type": "object",
   "title": "The Root Schema",
   "required": [
     "git"
   ],
   "properties": {
     "git": {
       "$id": "#/properties/git",
       "type": "object",
       "title": "The Git Schema",
       "required": [
         "installations"
       ],
       "properties": {
         "installations": {
           "$id": "#/properties/git/properties/installations",
           "type": "array",
           "title": "The Installations Schema",
           "items": {
             "$id": "#/properties/git/properties/installations/items",
             "type": "object",
             "title": "The Items Schema",
             "required": [
               "home",
               "name"
             ],
             "properties": {
               "home": {
                 "$id": "#/properties/git/properties/installations/items/properties/home",
                 "type": "string",
                 "title": "The Home Schema",
                 "default": "",
                 "examples": [
                   "git"
                 ],
                 "pattern": "^(.*)$"
               },
               "name": {
                 "$id": "#/properties/git/properties/installations/items/properties/name",
                 "type": "string",
                 "title": "The Name Schema",
                 "default": "",
                 "examples": [
                   "Default"
                 ],
                 "pattern": "^(.*)$"
               }
             }
           }
         }
       }
     }
   }
 }

This is the generated correct json schema for the following yaml file 
git:
  installations:
  - home: "git"
    name: "Default"
I put it in vscode and it works pretty good barring the documentation.
Could you guys verify. It gave me suggestions as well

CC @timja @oleg-nenashev @casz

**Comment by timja** [comment]
Can you use markdown to format your yaml please?

**Comment by timja** [comment]
I've updated the schema to match the demo:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/git

and formatted appropriately,
what's wrong with the documentation? it works for me

**Comment by sladyn98** [comment]
Yep it works that's perfect :)

**Comment by timja** [comment]
Added `"additionalProperties": false,` throughout, it disallows unknown properties  , tested in vs-code and it works fine

**Comment by timja** [comment]
> Yep it works that's perfect :)
> Another case in point for having the schema in our schema store. As far as my research is concerned we might have to develop an LSP (language server protocol) for our own plugin. I am not quite sure if we need to go that far

We don't need it in schema store for version 1, also not convinced it's a great idea anyway, just need documentation on how to configure vs-code to use the schema for the initial iteration

**Comment by sladyn98** [comment]
Yeah agreed.Lets just add it to the readme.md

**Comment by sladyn98** [comment]
@timja Does this need any more work or can be closed ?

**Comment by timja** [comment]
Closing as other issues cover the remaining work
