### ISSUE TITLE
Dev tools: Blog post for end of phase 1

### ISSUE THREAD

**Issue by timja** [jenkinsci/configuration-as-code-plugin#1058]

**Comment by sladyn98** [comment]
I have a draft ready, should we wait before we add the nesting support because @oleg-nenashev mentioned that phase 1 would not be complete before addition of the nested support

**Comment by sladyn98** [comment]
https://medium.com/@sladynnunes98/community-bridge-with-jenkins-phase-1-78f811c975c0

cc @timja @oleg-nenashev @casz

**Comment by oleg-nenashev** [comment]
Thanks for the blogpost. Parts about the schema could  be more detailed,
but it should do the job.

W.r.t phase 1 Definition of Done, the final decision is up to mentors

**Comment by sladyn98** [comment]
Yeah I will add changes.Thanks

**Comment by sladyn98** [comment]
@timja This is already being dealt with in a new use case, since with respect to the personal Blog this issue is done, can be closed ?
