### ISSUE TITLE
Add field documentation to the JSON Schema

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1059]
The new schema from #980 works pretty well on my instance, and it already produces some useful data. Unfortunately the schema does not include documentation for fields, and it could be a nice improvement, especially when we start working on the IDE integration.

CC @sladyn98

**Comment by sladyn98** [comment]
@oleg-nenashev  We could add the `"description": ` attribute to the fields but from where exactly are we to find out the description of every node ? eg maven.

**Comment by timja** [comment]
does the existing schema have it?

**Comment by sladyn98** [comment]
No @timja the existing schema doesn't have it

**Comment by timja** [comment]
I guess we could allow custom configurators to contribute it, but the default autogenerated ones wouldn't have it?

**Comment by sladyn98** [comment]
I do not see any method giving away the description for nodes. I guess we could write a method that takes a note for every configurator, but we might have to initially add the information

**Comment by oleg-nenashev** [comment]
It can be retrieved from field documentation, e.g. see how Jelly or docs generator does it

**Comment by timja** [comment]
> It can be retrieved from field documentation, e.g. see how Jelly or docs generator does it

actually yeah, there's a getHelpFile method on the descriptor I believe

**Comment by sladyn98** [comment]
Yeah I will have a look :)

**Comment by timja** [comment]
You have access to the descriptor in HeteroDescribeableConfigurator
https://github.com/jenkinsci/configuration-as-code-plugin/blob/6ab460cb5a0aed7c495e50b69eae0ac80876f59e/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java#L111

**Comment by sladyn98** [comment]
@timja 
` } else {
            attributeSchema.put(attribute.getName(),
                new JSONObject()
                    .put("type", "object")
                    .put("$id", "#/definitions/" + attribute.type.getName()));
        }
    }`
is there a way to get it in this manner from the attribute because we would need to enter the field name of the attribute.

**Comment by timja** [comment]
This is how it's retrieved in the jelly documentation:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/1302e67d6e6743423cd74eb26ace0ac08d59bc86/plugin/src/main/resources/io/jenkins/plugins/casc/BaseConfigurator/documentation.jelly#L42
