### ISSUE TITLE
Update management link name and icon

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#107]
The management link under Manage Jenkins is called `configuration-as-code` and uses the default setting.png icon.

We propose to change name of the link to `Configuration as Code` as well as use our nice customized logo we already have https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/logo.png

**Comment by buep** [comment]
Our logo in https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/logo.png is 32K - shouldn't we make smaller versions that loads faster and follows the existing sized that also the `settings.png` have? 

E.g. `settings.png` comes in these sized - not sure what they are all used for...
images/48x48/setting.png
images/16x16/setting.png
images/24x24/setting.png
images/32x32/setting.png

@ksenia-nenasheva since you're the icon and logo wizard is that something you can help with? Not sure if we need all sizes, but at least the 48X48 and something less in file size than 32K would be nice.

**Comment by ksenia-nenasheva** [comment]
I could try, but I have no experience in drawing such icons. 
WDYT about these icon drafts (48x48)?
![icon-1](https://user-images.githubusercontent.com/5075432/36199771-d7b9774a-117a-11e8-941b-9727da683544.png)
![icon-2](https://user-images.githubusercontent.com/5075432/36199786-df64cf62-117a-11e8-869a-b0a044cc95e0.png)
![icon-3](https://user-images.githubusercontent.com/5075432/36199793-e249aeaa-117a-11e8-8435-4efddd667f5a.png)
![icon-4](https://user-images.githubusercontent.com/5075432/36199795-e40a91b4-117a-11e8-97f7-8133b047139d.png)

**Comment by ewelinawilkosz** [comment]
I like the first one a lot, only wondering if it's clear enough what it represents. On the other side there is a text next to icon so not a real problem...

Another idea I have is the one with the tool, like second or third picture, with a text file behind it - something like the one for 'Recent Changes' here: https://www.getpostman.com/img/v1/docs/integrating_with_jenkins/integrating_with_jenkins_7.png
it's a small icon so it may not be very clear with too many details, I will not try to force my idea unless you also like it

**Comment by daniel-beck** [comment]
That icon is just `accessories-text-editor` from the Tango Icon set (http://tango-project.org/). There's an SVG as well.

![screen shot](https://user-images.githubusercontent.com/1831569/36201935-154b7dd6-1182-11e8-8676-d528e5866b2f.png)

**Comment by daniel-beck** [comment]
We've also used RRZE in the past, which is a supplementary Tango-style icon set. It's where I got the "label" icon for (which used to be the same as computer).

https://rrze-pp.github.io/rrze-icon-set/tango/gallery.html

Perhaps there's some inspiration.

**Comment by ndeloof** [comment]
then "manage-students" https://raw.githubusercontent.com/RRZE-PP/rrze-icon-set/master/tango/48x48/actions/manage-students.png could be a good mix between  "document" and "configuration". Node of them do really ring a bell, to reflect the "_as code_" concept

**Comment by ewelinawilkosz** [comment]
I do like manage-students.png!

**Comment by buep** [comment]
I actually like the suggestions from @ksenia-nenasheva - I know they are just modification of the project logo, but as @ewelinawilkosz says there is a text next to it at having something with a "wrench" or tool is usually configuration-something.

At some point users will know this little icon, like we got used to every one of the other Jenkins icons I think.

So I suggest to go for a minimized version of the project logo, or just a small wrench tool like the one in our project logo.

When I filed this is issues, I just imagined a smaller version of our logo.

**Comment by ewelinawilkosz** [comment]
you mean the last one from Ksenia? I'm ok with that in general, but it looks a little bit blurry with all those details... so let's vote? react on the post with:
:smile: for just a head
:thumbsup: for mini version of our logo

**Comment by ksenia-nenasheva** [comment]
You can use only PNG icons, right? Otherwise, would SVG icons be fine?

**Comment by lanwen** [comment]
SVG should be fine - I've tried it with *github-plugin*

https://github.com/jenkinsci/github-plugin/blob/master/src/main/webapp/img/logo.svg
https://github.com/jenkinsci/github-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github/admin/GitHubHookRegisterProblemMonitor.java#L236

vote for head

**Comment by ksenia-nenasheva** [comment]
I can save these images in SVG in better quality [link](https://drive.google.com/drive/folders/1vfEwmfWygSjiGPtsvEm6Np_c4W4EsttZ).
// The letter "J" will be displayed correctly after download.
