### ISSUE TITLE
[Feature] Seedjob - genesis job is not part of CasC

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#11]
If we have all global configuration as CasC, we still need to get at least one job up and running to start with that can create all job- and view-related things. This is not part of CasC, so maybe this should be a feature of our container docker4jcasc much like the old one contribute with this genesis seedjob thing.

**Comment by ndeloof** [comment]
I think managing some job templates / reference jobs / etc from configuration-as-code is something we want to support as well. I'd like one could configure a master with just a github server URL and get organisations / repository / branches scanned to get CI/CD in one click.

**Comment by ndeloof** [comment]
See https://github.com/jenkinsci/configuration-as-code-plugin/commit/5561836f25b28a45fca66ed8d0bef914b7b47b25

a MAJOR limitation here is that most (all?) Items do rely on overriding `submit()` for configuration, with hand-written data binding. So not data model we can guess by reflection. Bad news as many of them are in jenkins-core so won't get easily updated.

**Comment by ndeloof** [comment]
My plan is to rely on job-dsl-plugin here for job configuration, running a dsl script as part of configuration-as-code to prepare jenkins instance with set of initial jobs.
