### ISSUE TITLE
Move several configurators outside of jenkins element

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#110]
to meet "mimic UI" requirement we need to configure nodes outside of `jenkins` root element, currently impossible

```
java.lang.IllegalArgumentException: no configurator for root element 'nodes'
```

In general current setup should be reviewed - if we handle security, cloud, etc in a right place - and 'right place' means under proper root element, following UI setup

**Comment by oleg-nenashev** [comment]
Related issue: https://github.com/jenkinsci/configuration-as-code-plugin/issues/348

**Comment by ewelinawilkosz** [comment]
@oleg-nenashev I agree, let's see what's current status and we can decide if it's enough for now

**Comment by ndeloof** [comment]
Ideally the root element should be determined based on `ManagementLink`s so we reflect the `/manage` page structure. Need to investigate how to use this as "meta-data" on jenkins data model

**Comment by ndeloof** [comment]
unfortunately most of the ManagementLinks are just shortcut to some child page of Jenkins root object. We can't rely on this. Maybe we will need some changes in Jenkins-core if we want to follow this direction

**Comment by ndeloof** [comment]
I hardly can find any way to reflect web UI as most of it is hand-written without discoverable link with components. Typically in many cases a `ManagementLink` only register a link to some `GlobalConfiguration`, and there's no API we can introspect to discover this relation.

I suggest to consider "mimic web UI" as a best-effort, inspirational wish, not a structural requirement
