### ISSUE TITLE
Verify if the order of running configurators (credentials) may be an issue

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#112]
to configure an ssh slave we need existing credentials
is it possible the plugin we'll try to configure slaves before it configures credentials?

- [ ] verify if above is an issue
- [ ] provide a way to force credentials creation be executed BEFORE anything that uses credentials is being configured

**Comment by MadsNielsen** [comment]
If it is an issue we could sort the list of root configurators before calling .configure(), we could make use of the Existing `Extension` annotation which already has a field `ordinal`. And sort the list prior to configuring each element.

**Comment by ndeloof** [comment]
SSHLauncher do [lookup credentials](https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L585) when it actually [tries to connect](https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L1346) 
so it's safe to only configure `credentialsId` and wait for jenkins to complete init process. I'm not sure when in the boot lifecycle agent will start trying to connect. Checking

**Comment by ewelinawilkosz** [comment]
when I was working on providing an example for nodes configuration I did have this problem, that Jenkins didn't accept my yaml until I provided an id of existing credentials - that's why this issue was created

**Comment by MadsNielsen** [comment]
It looks like we lookup existing credentials when we call the @DataBound constructor, so the crdentials must be present when the node is created?
https://github.com/jenkinsci/ssh-slaves-plugin/blob/ef45f1e373ce011ad72d266df1ba58ea0c7baec0/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L314

**Comment by ndeloof** [comment]
you're right, SSHLauncher's [DataBoundConstructor](https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L314) is actually resolving configured `credentialsId` into a Credentials instance, and then invoke [deprecated constructor](https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L536) which translate back this instance into an ID.

Sounds to me this is a bug in ssh-slaves plugin.

**Comment by ewelinawilkosz** [comment]
we can 
- fix it in SSHLauncher
- prepare workaround in our plugin
- both

any opinions?

**Comment by ndeloof** [comment]
I'm working on a fix for ssh-slaves-plugin

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/ssh-slaves-plugin/pull/82

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/ssh-slaves-plugin/pull/82 has been merged
