### ISSUE TITLE
adding configuration as code plugin

### ISSUE THREAD

**Issue by danseo-reisys** [jenkinsci/configuration-as-code-plugin#1124]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [ ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [ x] Jenkins version/:  2.176.3 (image stream from redhat)
- [ x] Plugin version
- [x ] OS  : running on openshift cluster 3.11
- [ x] Reproduction steps

### Description

we deployed jenkins image from redhat with preloaded openshift related plugins.
we want to enable the configuration as code plugin and script adding additional plugins.
it's not clear how to add the configuration as code to the running instance.  could you provide some guidance? 

thanks,

**Comment by oleg-nenashev** [comment]
If you have the admin access, you should be able to install it from the
plugin manager

**Comment by danseo-reisys** [comment]
thanks. i was able to install using oc cli rsync.

**Comment by danseo-reisys** [comment]
now i want to use the jcasc plugin to define new sonarqube server instead of using jenkins 'configure systems' UI.  can you shed some light?  is there a way to capture groovy script from jenkins UI?

**Comment by casz** [comment]
@danseo-reisys have a look in the demo folder: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/sonarqube

You can also configure all your plugins and than use the export feature.
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configExport.md
