### ISSUE TITLE
gson bump in 1.31 breaks job view and other plugins

### ISSUE THREAD

**Issue by reschex** [jenkinsci/configuration-as-code-plugin#1137]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

Bumping gson in plugin version 1.31 breaks the job view and some plugins, see https://issues.jenkins-ci.org/browse/JENKINS-59606 for an example. 

I've tested this using the official Jenkins docker images from https://hub.docker.com/r/jenkins/jenkins/, using the 2.197 and latest tags (2.199).

**Comment by casz** [comment]
gson is removed in the unrelased master branch

@timja perhaps we should make a release?

**Comment by timja** [comment]
Sure, I can do it?

**Comment by casz** [comment]
go for it @timja

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.32
