### ISSUE TITLE
When exporting ec2 cloud provider config, missing required parameters 

### ISSUE THREAD

**Issue by mlasevich** [jenkinsci/configuration-as-code-plugin#1138]
### Your checklist for this issue

- [x] Jenkins version
- [x] Plugin version
- [x] OS

Jenkins Version: CCOC 2..176.4.3
Plugin Version: 1.32
OS: Amazon Linux 2(EKS)

### Description

When exporting configuration that includes `amazonEC2` cloud provider, certain required parameters are not exported if not set (even if they were previous set to blank via JCASC) - some of the parameters I experienced this on: roleArn, roleSessionName, instanceCapStr, region(this one was set, not sure why it was not exported). Adding these with blank values instead of nulls it assumes fixes the issue

What is more interesting is that if the config is updated and is reloaded on a running server, it loads fine, but once the master is restarted, it fails to come up - leading to "timebomb" issues

**Comment by timja** [comment]
this  is an issue in the ec2 plugin

**Comment by mlasevich** [comment]
> this is an issue in the ec2 plugin

Can you elaborate?

**Comment by timja** [comment]
Please report this to the the ec2 plugin

**Comment by mlasevich** [comment]
Can you explain, in basic terms, what is happening there - it sounds like you have an idea. I am happy to report it to ec2 or even try to submit a PR for a fix to them, but I am trying to understand what I am looking at. I do not think me opening a bug with ec2 plugin saying nothing but "JCASC does not work" will fly - they will just tell me to file a bug with you... :-(

**Comment by casz** [comment]
They previously broke their plugin and comparability with JCasC some I am pretty sure they know what's up.

**Comment by mlasevich** [comment]
*sigh* sounds like I walked into some existing conflict :-( I will look into that.

**Comment by casz** [comment]
Properly best to update to the latest version of EC2 plugin

**Comment by mlasevich** [comment]
I am running the latest from my update site (Cloudbees, 1.42.1) but looking at EC2 releases, there are several later versions, including one that fixes at least some of this. So my issue is neither with JCASC or EC2, but with Cloudbees for carrying an old plugin :-/ Thanks.

**Comment by mlasevich** [comment]
(For someone who may find this later: https://issues.jenkins-ci.org/browse/JENKINS-56684 describes the issue and it is apparently fixed in 1.44 of ec2 plugin)

**Comment by timja** [comment]
> I am running the latest from my update site (Cloudbees, 1.42.1) but looking at EC2 releases, there are several later versions, including one that fixes at least some of this. So my issue is neither with JCASC or EC2, but with Cloudbees for carrying an old plugin :-/ Thanks.

nice find, best to raise a support ticket and ask for them to update it
