### ISSUE TITLE
Bitbucket team/project job

### ISSUE THREAD

**Issue by lcsfreire** [jenkinsci/configuration-as-code-plugin#1139]
### Description

Hello,
i'm trying to configure bitbucket jobs using jcasc. I've searched but i didn't found the parameters/api/example to create a bitbucket team/project job using jcasc. 
Can you please help? How can i adapt the example in this page https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jobs/bitbucket.yaml to a bitbucket team/project?
Thank you

**Comment by casz** [comment]
the demo file you linked to will generate a bitbucket team/project 😰

**Comment by lcsfreire** [comment]
so according the documentation: "Organization Folders enable Jenkins to monitor an entire GitHub Organization, or Bitbucket Team/Project and automatically create new Multibranch Pipelines for repositories which contain branches and pull requests containing a Jenkinsfile."
The example is showing how to create a organizationalFolder? How this works? i point serverUrl parameter to a url and it find a jenkinsfile and become a bitbucket team/project?

**Comment by casz** [comment]
organizationalFolder == bitbucket team/project

You basically point to a URL and a team `repoOwner` is considered the team
