### ISSUE TITLE
[PROPOSAL] Support for other sources of secrets

### ISSUE THREAD

**Issue by Ziomalon** [jenkinsci/configuration-as-code-plugin#114]
As far as I understand the currently supported/planned models for storing secrets would be environmental variables (for example passed to the Docker container using swarm/kubernetes) and Vault. Please correct me on this if I'm wrong.

I find these a little bit troublesome. 

First of all if any of the environment variables change during container runtime it causes the whole container to be recreated. That's not something you want to do on your production environment too often and yet credentials changes are often required due to corporate policies. 

Vault while being ridiculously feature-rich and secure is not really easy to maintain without putting a log of effort. 

The general proposal is to use AES encryption to securely store secrets directly in the configuration file so instead of a variable like `${LDAP_PASSWORD}` you could store the AES-encrypted secret. The AES key could be stored either as a file mounted to the container or a environment variable. Such keys change rather rarely so this would decrease the need of container recreation.

I'm currently utilizing something similar with much success so the concept is already "battle tested".

**Comment by ndeloof** [comment]
We do support 
- environment variable (for test / development, not to be used for production)
- Vault
- Docker secrets and kubernetes secrets (as volume mapping)

API makes it easy to create alternative implementations. Preferred approach is to create a sibling plugin to provide this specific feature and extend configuration-as-code. You just need your custom `SecretSource` to expand ${XXXX} into some other string using AES decrypt.

Considering your approach, it's more or less how docker secrets are implemented (but managed by infrastructure) with encrypted secret mounted as plain text files inside container within a tmpfs volume.

**Comment by ndeloof** [comment]
For the record: CodeShip uses this exact same approach to have some AES encrypted files stored in SCM and key registered on the platform so file can be read at runtime.
