### ISSUE TITLE
Move "Run Locally", "IntellijIDEA" and "CLI" sections to contributor guidelines

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1146]
These sections of REAME do not seem to address user use-cases. I suggest moving them to https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/CONTRIBUTING.md

* https://github.com/jenkinsci/configuration-as-code-plugin#run-locally
* https://github.com/jenkinsci/configuration-as-code-plugin#intellij-idea
* https://github.com/jenkinsci/configuration-as-code-plugin#cli

It would make the page smaller and highlight the user content

**Comment by balajipachai** [comment]
Hi, please look into #1148 

Thanks,
Balaji Shetty Pachai
