### ISSUE TITLE
Add readme to the /demos directory 

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1147]
It would be great to have a separate document for the Readme section which would include...

* Short overview of demos for users
  * How to use them?
  * Disclaimer that demos may not be applicable to all plugin versions
* "Adding new demos" section for contributors
  * How to submit a demo, which information to add?
  * How to add a demos to the integration test suite (thanks @v1v!)

**Comment by wpater** [comment]
I'm working on this one.

**Comment by timja** [comment]
Fixed in #1157
