### ISSUE TITLE
Invert the LDAP example on the README page so that the YAML goes first

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1149]
Currently the plugin site and other pages display a Web UI configuration screenshot for a plugin which is supposed to be about JCaaC. It would be great to have a YAML configuration snippet as a first item, and LDAP screenshot can be added as "was" example later, maybe even in a section which is collapsed by default

**Comment by wpater** [comment]
I'll do it.

**Comment by timja** [comment]
Resolved in above commit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
