### ISSUE TITLE
Move "Trigger Configuration Reload" to a new feature page

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1150]
Once #1143 is merged, there will be a new documentation section. Then we can move this section from README to a feature page.

* Documentation is moved to a new page under https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/docs/features
* A lin and former section link anchor are added to the Documentation section of README

**Comment by lunodesouza** [comment]
I will solve this issue.
