### ISSUE TITLE
error when using secret files

### ISSUE THREAD

**Issue by asiekkowa** [jenkinsci/configuration-as-code-plugin#1154]
### Your checklist for this issue

[x] Jenkins version
Jenkins ver. 2.199
[x] Plugin version
1.32
[x] OS
docker image: jenkins/jenkins:2.199-slim

### Description

Please describe your issue here.
Below error occurs when using credentials kind= secret file.
![image](https://user-images.githubusercontent.com/22298133/66653666-d5c08b00-ec38-11e9-99fd-3fd80f06b059.png)

**Comment by casz** [comment]
This is actually a bug in the credential API same exist for certificate 😭

**Comment by timja** [comment]
> This is actually a bug in the credential API same exist for certificate 😭

We don't put null constraints on the API here:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java#L146

Obviously we aren't expecting null but I think we should either handle it, or explicitly mark it in the API?
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L282

**Comment by casz** [comment]
Looking at the code
https://github.com/jenkinsci/sonar-quality-gates-plugin/blob/b87a0987c2b91ef63f5c6dd0f7a6839e341b3584/src/main/java/org/quality/gates/jenkins/plugin/GlobalConfig.java#L49

They are manually passing JSON data, this does not following coding standards setup by Jenkins plugin development. 

See this for reference
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#step-5

**Comment by casz** [comment]
Well the credential has it only configurator so 🤷‍♂

**Comment by timja** [comment]
> Well the credential has it own configurator so 🤷‍♂

Which extends `BaseConfigurator` and it has a poor API contract defined
