### ISSUE TITLE
[jobdsl] using repoOwner and configure block creates two organizations 

### ISSUE THREAD

**Issue by dilip-desing** [jenkinsci/configuration-as-code-plugin#1161]
I'm facing exactly the same issue as below link: 
https://issues.jenkins-ci.org/browse/JENKINS-54456?attachmentViewMode=list
I'm also using the similar code mentioned in the above link. 

"When combining the organizations & configure blocks the result  creates two Organizations" 
There is no solutions suggested for this so far. any help would be appreciated.

**Comment by timja** [comment]
I don't really understand what you are doing, but this works for me:
https://github.com/hmcts/cnp-jenkins-config/blob/master/jobdsl/organisations.groovy
