### ISSUE TITLE
Mapping#putIfNotEmpry

### ISSUE THREAD

**Issue by aheritier** [jenkinsci/configuration-as-code-plugin#1162]
### Description

- [ ] Please mark the incorrectly spelled method `putIfNotEmpry` deprecated 
- [ ] add new method called `putIfNotEmpty`
- [ ] old method should call new method (to avoid duplication)
- [ ] add a javadoc for old method to suggest use new method instead. (See [howto](https://stackoverflow.com/a/9031854/1103925))

The problem with IDEs is that everyone is using the autocompletion and doesn't see such misprint.

https://github.com/jenkinsci/configuration-as-code-plugin/blob/045631a8bf8b2fb0ac219128a82dca5b34716869/plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java#L50

@ndeloof one more 🍺 for me :-)

**Comment by casz** [comment]
Good candidate for hacktoberfest to fix the spelling.

**Comment by bojanfilipovic** [comment]
Hi! Can I pick this up as part of the hacktoberfest?

**Comment by casz** [comment]
@bojanfilipovic Please go ahead, please check the [CONTRIBUTING](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/CONTRIBUTING.md)
