### ISSUE TITLE
setting system credentials clobbers existing manually configured credentials

### ISSUE THREAD

**Issue by briceburg** [jenkinsci/configuration-as-code-plugin#1167]
## installation

Ubuntu Bionic Linux running:
  * casc: 1.3.2
  * jenkins:  2.190.1

## summary

CasC replaces credentials.xml instead of augmenting it, removing any system credentials that may have been manually added via the UI.

## description

our environment is dockerized (jenkins:lts) and the jenkins home directory (outside of some exclusions) is backed up to s3 periodically to persist any configuration or job information. the docker entrypoint restores this configuration from S3 on container start (just before jenkins is started and CasC fires). the CasC config is baked into the docker image and used to bootstrap our jenkins instances.

I am finding that the `$JENKINS_HOME/credentials.xml` (that gets restored from S3) is being overwritten by the CasC plugin -- removing anything that was manually entered via the UI.

Is there any way that CasC can enforce credentials configuration by augmenting `credentials.xml` instead of replacing it? E.g. an xml merge?  

or is something else going on... ?

Thanks!

**Comment by casz** [comment]
This is not a bug, this is the intended behavior.

Question is why are not all your secrets/credentials coming from one of the supported secret sources?

https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#secret-sources

**Comment by briceburg** [comment]
I see. For the credentials that casc configures, we are using docker
secrets to populate. I consider these are 'core' credentials.

Our users, however, evolve the instances by  creating additional jobs, some
of which use custom credentials our [admin] users enter ma ually. As such
not everything is tracked in casc, as we require the manual flexibility ...

Would the recommendation be to remove credential configuration from our
casc configs entirely and figure out how to populate the core creds somehow
else?

**Comment by timja** [comment]
The recommendation is don’t give your admins access to add the credentials manually. 

Get them to add them through your automation, then if you ever rebuild it your credentials will be there

**Comment by briceburg** [comment]
@timja  that would be ideal. the way we have things setup would require a redeployment to pickup on updated CasC. The yaml is baked into the image and not loaded dynamically. So, for instance, if the instance gets rebooted the creds would be missing. 

I may need to re-architect things... and it's hard to do in my spare time. it sure would be nice if the CasC plugin could enforce the existence of credentials (based on its IDs) instead of replacing everything. When we use the job DSL plugin it doesn't clobber all the other jobs.

**Comment by casz** [comment]
@briceburg this is not JCasC doing, it's how the code is implemented over at the credential plugin :) Although the code used to live here in JCasC
