### ISSUE TITLE
if secret file configured on Jenkins Credential - view configuration is throwing error

### ISSUE THREAD

**Issue by samitkumarpatel** [jenkinsci/configuration-as-code-plugin#1173]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ 2.190.1] Jenkins version

- [1.32 ] Plugin version

- [MacOS ] OS

### Description
After adding a secret file on Jenkins credential, the view configuration for configuration-as-code-plugin is throwing an error in the Jenkins log and showing the same error on the view configuration GUI

##################
error in the GUI
##################
credentials:
  system:
    domainCredentials:
    - credentials: |-
        FAILED TO EXPORT
        com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials: java.lang.NullPointerException
          at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:282)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:283)
          at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:283)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
          at io.vavr.control.Option.map(Option.java:392)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:239)
          at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:307)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:239)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:243)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)

#################
error in the log
#################
jenkins_1  | 2019-10-18 21:26:32.801+0000 [id=17]	WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl#file: type is abstract but not Describable.
jenkins_1  | 2019-10-18 21:26:32.804+0000 [id=17]	WARNING	i.jenkins.plugins.casc.Attribute#describe: Failed to export
jenkins_1  | java.lang.NullPointerException
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:282)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:283)
jenkins_1  | 	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:283)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
jenkins_1  | 	at io.vavr.control.Option.map(Option.java:392)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:239)
jenkins_1  | 	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:307)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:239)
jenkins_1  | 	at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)
jenkins_1  | 	at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:264)
jenkins_1  | 	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:243)
jenkins_1  | 	at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)
jenkins_1  | 	at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.export(ConfigurationAsCode.java:449)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.doViewExport(ConfigurationAsCode.java:427)
jenkins_1  | 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
jenkins_1  | 	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
jenkins_1  | 	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
jenkins_1  | 	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
jenkins_1  | 	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
jenkins_1  | 	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
jenkins_1  | 	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
jenkins_1  | 	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
jenkins_1  | 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
jenkins_1  | 	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:456)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
jenkins_1  | 	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
jenkins_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
jenkins_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
jenkins_1  | 	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
jenkins_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins_1  | 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
jenkins_1  | 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
jenkins_1  | 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
jenkins_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins_1  | 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
jenkins_1  | 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
jenkins_1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
jenkins_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
jenkins_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
jenkins_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
jenkins_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
jenkins_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
jenkins_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
jenkins_1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:505)
jenkins_1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
jenkins_1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
jenkins_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
jenkins_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
jenkins_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
jenkins_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
jenkins_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
jenkins_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
jenkins_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
jenkins_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
jenkins_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
jenkins_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)

Please describe your issue here.
Already describe above

**Comment by casz** [comment]
Duplicate of #1170

**Comment by samitkumarpatel** [comment]
Thanks, will  follow - #1170
