### ISSUE TITLE
unable to deactivate CSRF via JCasC

### ISSUE THREAD

**Issue by frank273** [jenkinsci/configuration-as-code-plugin#1184]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version 2.190.1+

- [X] Plugin version 1.32

- [ ] OS

### Description

With Jenkins configuration as code you can enable CSRF protection in Jenkins via specifying:
```
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
```
Problem is, there is no switch you could set to 'false' or disabled to temporarily disable JSRF protection. We have some scripts that use python jenkinsapi (i.e. plugin installation) that do not work reliably with csrf enabled, so we would like to temporarily switch it off ... 
As stated, enabling works, but you cannot deactivate as leaving out the crumbIssuer results in not changing anything.

**Comment by daverod24** [comment]
Good estimates

I have this problem activating CSRF Protection in the latest LTS version
Centos 7.7
Jenkins version. 2,190.1 (installed by yum, not in container)
 
I get the crumb
```bash
crumb = $ (curl -u "admin: admin" -s 'http://192.168.10.2:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
```

and then I pass it with the operation that I want to perform
```bash
curl -u "admin: admin" -H "$ crumb" -X POST 'http://192.168.10.2:8080/job/ENV/build?delay=0sec'
```


this is the way out
```html
<meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />
<title> Error 403 No valid crumb was included in the request </title>
</head>
<body> <h2> HTTP ERROR 403 </h2>
<p> Problem accessing / job / ENV / build. Reason:
<pre> No valid crumb was included in the request </pre>
```

I would like to know what state this is or what is the new way of working with the API to launch groovy scripts

Thanks in advance
Regards

**Comment by timja** [comment]
This likely needs a fix in the jenkinsci/jenkins repository they track issues with jira https://issues.jenkins-ci.org/ component core, it will have more visibility if it’s reported there

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timja** [comment]
Disabling CSRF is not recommended, the only way in the latest version of jenkins to do it is via SystemProperty now.

I don't think we need to support this, you should be using an API token and then you don't need to worry about CSRF

Ref: https://github.com/jenkinsci/jenkins/pull/4509
