### ISSUE TITLE
Is "Strict Crumb Issuer" supported?

### ISSUE THREAD

**Issue by webminster** [jenkinsci/configuration-as-code-plugin#1191]
our checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.190.2

- [ x] Plugin version
1.32

- [ x] OS
Docker container jenkins/jenkins:lts

### Description

Is the "strict crumb issuer" supported in some way?  If I try to set crumbIssuer: "strict" in my configuration, it causes multiple problems in the configured master, such as tracebacks, and "Oops" in the global configuration pages.

**Comment by lcsfreire** [comment]
Hello,
i got same problem. When loading configuration as code with crumbIssuer: "strict" i can't modify security parameters, i can't see the jcasc conf, sealed secrets issues, etc,  however, if i load jenkins as code with standard crumb and inside jenkins web interface i change to "strict" i don't have any issue. I've compared the xml files modified after change crumbissuer from standard to strict with a jenkins as code loaded with crumbissuer: "strict" and i didn't found any difference.
What am i missing?

**Comment by BipinXavier** [comment]
Hello,
I got the same problem. When loading configuration as code with crumbIssuer: "strict". I can't modify security parameters, I can't see the jcasc conf, sealed secrets issues, etc, however, if I load Jenkins as code with the standard crumb and inside Jenkins web interface if I change to "strict" I don't have any issue.

**Comment by usmonster** [comment]
I would classify this as a bug more than a question. I think the answer to the question is "no, but it should be." 😓

**Comment by casz** [comment]
Should be supported in the latest version.
Thanks to @Wadeck ? 🤔

**Comment by BipinXavier** [comment]
@usmonster It's fixed in the latest version configuration as a code plugin version.

**Comment by usmonster** [comment]
OK, thanks for the quick response! I guess this can be closed, then?

**Comment by abdennour** [comment]
any example for this feature?

**Comment by webminster** [comment]
I use a configuration similar to below in my jenkins.yaml to configure it:

jenkins:
  crumbIssuer:
    strict:
      checkSessionMatch: false
      hoursValid: 8

You can set it as you want in the Jenkins global security configuration, then use the manage / configuration as code / view configuration to model that.
-Alan
