### ISSUE TITLE
Verify Credentials plugin compatibility

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#12]
https://plugins.jenkins.io/credentials

**Comment by ndeloof** [comment]
I can't find a simple way to configure credentials plugin with the existing mechanism. Might require some glue code.
A possible option is for configuration-as-code to be extended to support `addXX(key, value)` so we can bind a yaml Map <domain, credentials> to an existing collection. Here we could then invoke `CredentialsStore#addDomain(Domain, List<Credentials>)` as long as we have _some_ way to retrieve extension SystemCredentialsProvider.ProviderImpl as a configurable root.

**Comment by ndeloof** [comment]
implemented as https://github.com/jenkinsci/configuration-as-code-plugin/commit/04036d315dc1b050ef55687690371f9b6c438994
