### ISSUE TITLE
Remove restriction from ConfigurationAsCode to be able to reload/dump configuration from another plugin

### ISSUE THREAD

**Issue by escoem** [jenkinsci/configuration-as-code-plugin#1202]
### Feature Request

Make JcasC ConfigurationAsCode not restricted in order to be able to reload/dump configuration automatically from another plugin.

**Comment by casz** [comment]
I am pretty sure this is an use case we would not support.

**Comment by casz** [comment]
I'd like to understand your use case and why you cannot add the feature to this plugin?

**Comment by amuniz** [comment]
> I'd like to understand your use case and why you cannot add the feature to this plugin?

We are using JCasC in a proprietary extension. This extension [uses other proprietary features](https://docs.cloudbees.com/docs/admin-resources/latest/plugin-management/configuring-plugin-catalogs). From that extension we need to reload the configuration when needed and also export the current config.

> Not sure why you want your own method for dumping configuration.

We are _decorating_ the normal export with additional data. I think it's a pretty common use case.

**Comment by casz** [comment]
My honest opinion I would hate to support this proprietary feature. Why can you not help improve configuration as code?

**Comment by amuniz** [comment]
> Why can you not help improve configuration as code plugin?

Really? Do you think we (CloudBees) are not helping improve JCasC?

> I'd love to support decorating the export directly from an extension point within the plugin

That's ok for me too, as long as an extension point without an OSS implementation is ok for you too!
I think the impact (and maintenance burden) of making a method public API is immensely smaller than making the export feature extensible.

**Comment by casz** [comment]
> Really? Do you think we (CloudBees) are not helping improve JCasC?

I do not doubt that your helping. My stab was at the effort to continue working on a proprietary feature over fixing issues in JCasC and Jenkins core.

**Comment by casz** [comment]
FYI I am also fine with the current state of #1203
