### ISSUE TITLE
Plugin site docs currently empty

### ISSUE THREAD

**Issue by timja** [jenkinsci/configuration-as-code-plugin#1206]
ref: https://plugins.jenkins.io/configuration-as-code

![image](https://user-images.githubusercontent.com/21194782/69429942-95225a00-0d2c-11ea-8833-44ae1949f98d.png)

_Originally posted by @jtnord in https://github.com/jenkinsci/configuration-as-code-plugin/pull/1204_

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/commit/daefe4e933c5dd22cbb2918e85d38842bae8c71d#diff-d595a8236f587264b34d376cb6831780 @timja
