### ISSUE TITLE
Error when applying the job DSL configuration extracted from your bitbucket example

### ISSUE THREAD

**Issue by ZeBidule** [jenkinsci/configuration-as-code-plugin#1211]
- Jenkins version : 2.190.3
- Plugins versions 
   - ace-editor:1.1
   - analysis-core:1.96
   - ansicolor:0.6.2
   - ant:1.10
   - antisamy-markup-formatter:1.6
   - apache-httpcomponents-client-4-api:4.5.10-2.0
   - artifactory:3.4.1
   - authentication-tokens:1.3
   - aws-credentials:1.28
   - aws-java-sdk:1.11.670
   - basic-branch-build-strategies:1.3.2
   - bitbucket:1.1.11
   - blueocean-autofavorite:1.2.4
   - blueocean-bitbucket-pipeline:1.21.0
   - blueocean-commons:1.21.0
   - blueocean-config:1.21.0
   - blueocean-core-js:1.21.0
   - blueocean-dashboard:1.21.0
   - blueocean-display-url:2.3.0
   - blueocean-events:1.21.0
   - blueocean-executor-info:1.21.0
   - blueocean-git-pipeline:1.21.0
   - blueocean-github-pipeline:1.21.0
   - blueocean-i18n:1.21.0
   - blueocean-jira:1.21.0
   - blueocean-jwt:1.21.0
   - blueocean-personalization:1.21.0
   - blueocean-pipeline-api-impl:1.21.0
   - blueocean-pipeline-editor:1.21.0
   - blueocean-pipeline-scm-api:1.21.0
   - blueocean-rest-impl:1.21.0
   - blueocean-rest:1.21.0
   - blueocean-web:1.21.0
   - blueocean:1.21.0
   - bouncycastle-api:2.17
   - branch-api:2.5.4
   - build-monitor-plugin:1.12+build.201809061734
   - build-name-setter:2.0.3
   - build-timeout:1.19
   - checkstyle:4.0.0
   - cloudbees-bitbucket-branch-source:2.6.0
   - cloudbees-folder:6.9
   - command-launcher:1.3
   - config-file-provider:3.6.2
   - configuration-as-code-groovy:1.1
   - configuration-as-code-support:1.18
   - configuration-as-code:1.33
   - credentials-binding:1.20
   - credentials:2.3.0
   - cucumber-reports:4.11.0
   - discard-old-build:1.05
   - display-url-api:2.3.2
   - docker-commons:1.15
   - docker-java-api:3.0.14
   - docker-plugin:1.1.9
   - docker-workflow:1.21
   - dtkit-api:2.1.1-1
   - durable-task:1.33
   - ec2:1.46.1
   - embeddable-build-status:2.0.3
   - external-monitor-job:1.7
   - favorite:2.3.2
   - git-client:3.0.0
   - git-server:1.8
   - git:4.0.0
   - github-api:1.95
   - github-branch-source:2.5.8
   - github:1.29.5
   - gradle:1.34
   - h2-api:1.4.199
   - handlebars:1.1.1
   - handy-uri-templates-2-api:2.1.8-1.0
   - hashicorp-vault-pipeline:1.3
   - hashicorp-vault-plugin:3.0.0
   - htmlpublisher:1.21
   - http_request:1.8.23
   - ivy:2.1
   - jackson2-api:2.10.0
   - javadoc:1.5
   - jdk-tool:1.4
   - jenkins-design-language:1.21.0
   - jira:3.0.11
   - job-dsl:1.76
   - jquery-detached:1.2.1
   - jquery-ui:1.0.2
   - jquery:1.12.4-1
   - jsch:0.1.55.1
   - junit:1.28
   - ldap:1.21
   - lockable-resources:2.7
   - mailer:1.29
   - matrix-auth:2.5
   - matrix-project:1.14
   - maven-plugin:3.4
   - mercurial:2.8
   - metrics:4.0.2.6
   - momentjs:1.1.1
   - node-iterator-api:1.5.0
   - pam-auth:1.6
   - pipeline-aws:1.39
   - pipeline-build-step:2.9
   - pipeline-graph-analysis:1.10
   - pipeline-input-step:2.11
   - pipeline-maven:3.8.2
   - pipeline-milestone-step:1.3.1
   - pipeline-model-api:1.4.0
   - pipeline-model-declarative-agent:1.1.1
   - pipeline-model-definition:1.4.0
   - pipeline-model-extensions:1.4.0
   - pipeline-rest-api:2.12
   - pipeline-stage-step:2.3
   - pipeline-stage-tags-metadata:1.4.0
   - pipeline-stage-view:2.12
   - pipeline-utility-steps:2.3.1
   - plain-credentials:1.5
   - publish-over:0.22
   - pubsub-light:1.13
   - rebuild:1.31
   - resource-disposer:0.14
   - role-strategy:2.15
   - saml:1.1.4
   - scm-api:2.6.3
   - scoverage:1.4.0
   - script-security:1.68
   - slack:2.34
   - sonar:2.10
   - sse-gateway:1.20
   - ssh-agent:1.17
   - ssh-credentials:1.18
   - ssh-slaves:1.31.0
   - structs:1.20
   - timestamper:1.10
   - token-macro:2.10
   - trilead-api:1.0.5
   - variant:1.3
   - windows-slaves:1.5
   - workflow-aggregator:2.6
   - workflow-api:2.37
   - workflow-basic-steps:2.18
   - workflow-cps-global-lib:2.15
   - workflow-cps:2.76
   - workflow-durable-task-step:2.35
   - workflow-job:2.36
   - workflow-multibranch:2.21
   - workflow-scm-step:2.9
   - workflow-step-api:2.21
   - workflow-support:3.3
   - ws-cleanup:0.37
   - xunit:2.3.6
- OS : Debian 4.9.189

### Description

Got `groovy.lang.MissingMethodException: No signature of method` (see stack trace attached:
[error_casc.log](https://github.com/jenkinsci/configuration-as-code-plugin/files/3892151/error_casc.log)) when applying the following job DSL configuration extracted from [your bitbucket example](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jobs/bitbucket.yaml) :
```yml
jobs:
  - script: >
      organizationFolder('Bitbucket Organization Folder') {
        description("Bitbucket orga folder configured with JCasC")
        displayName('My Project')
        organizations {
          bitbucket {
            serverUrl("https:BITBUCKET_URL")
            repoOwner("OWN")
            credentialsId("bitbucket-http")
            traits {
              submoduleOptionTrait {
                extension {
                  recursiveSubmodules(true)
                }
              }
            }
          }
        }
      } 
```

**Comment by casz** [comment]
Don't use `>` it becomes one long script.
Use `|` a literal block

**Comment by casz** [comment]
Also this seems like more of a Job DSL issue 😓

**Comment by casz** [comment]
I'd suggest using `file` or `url` block instead

jobs:
  - file: /src/jobdsl/organisations.groovy

**Comment by ZeBidule** [comment]
OK thanks for your really quick answers :)

**Comment by ZeBidule** [comment]
I have tried the both solutions and i still have the same error :
```
groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.plugin.structs.DescribableContext.traits() is applicable for argument types: (script$_run_closure1$_closure2$_closure3$_closure4) values: [script$_run_closure1$_closure2$_closure3$_closure4@39a9c913]
```

**Comment by casz** [comment]
Downgrade cloudbees-bitbucket-branch-source to something before 2.6.0 😓

**Comment by ZeBidule** [comment]
OK, i try the downgrade...

I manage to avoid the error by removing the `traits` section and replacing it with the none declarative-compatible syntax but I doesn't work for the `recursiveSubmodules` option :
```yml
jobs:
  - script: >
      organizationFolder('Bitbucket Organization Folder') {
        description("Bitbucket orga folder configured with JCasC")
        displayName('My Project')
        organizations {
          bitbucket {
            serverUrl("https://$BITBUCKET_URL")
            repoOwner("OWN")
            credentialsId("bitbucket-http")
          }
        }
        // "Traits" ("Behaviours" in the GUI) that are NOT "declarative-compatible"
        // For some 'traits, we need to configure this stuff by hand until JobDSL handles it
        // https://issues.jenkins.io/browse/JENKINS-45504
        configure { node ->
            def traits = node / navigators / 'com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator' / traits
            traits << 'com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait' {
                strategyId('3')
            }
            traits << 'com.cloudbees.jenkins.plugins.bitbucket.SSHCheckoutTrait' {
                credentialsId('bitbucket-ssh')
            }
            traits << 'jenkins.scm.impl.trait.WildcardSCMSourceFilterTrait' {
                includes('myjob')
                excludes('')
            }
            traits << 'com.cloudbees.jenkins.plugins.bitbucket.WebhookRegistrationTrait' {
                mode('ITEM')
            }
            traits << 'jenkins.plugins.git.traits.SubmoduleOptionTrait' {
                extension << 'hudson.plugins.git.extensions.impl.SubmoduleOption' {
                    recursiveSubmodules('true')
                }
            }
        }
```

**Comment by ZeBidule** [comment]
Ok the declarative-compatible traits syntax works with cloudbees-bitbucket-branch-source version 2.5.0 so the regression appeared in version 2.6.0.
Sorry for the inconvenience, I just figure out that an issue was already created in their repository : [https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/258](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/258)

**Comment by casz** [comment]
Should be fixed in recent version of cloudbees-bitbucket-branch-source https://github.com/jenkinsci/bitbucket-branch-source-plugin/releases/tag/cloudbees-bitbucket-branch-source-2.7.0

**Comment by solvingj** [comment]
I don't understand how this was every working: 

` def traits = node / navigators / 'com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator' / traits`

The `/` operator gets parsed as `div()` in my environment. 

```
groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.jobs.OrganizationFolderJob.div() is applicable for argument types: (java.lang.String) values: [navigators]
```
