### ISSUE TITLE
Document best practices

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/configuration-as-code-plugin#1216]
How to docker
How to persist
How to manage plugins
😊

**Comment by casz** [comment]
@oleg-nenashev and @timja we need to better at documenting best practices! 😁

**Comment by sladyn98** [comment]
What would we want included in the how to docker section, maybe I could get some sample documentation written and then iterate on it, I am not an expert in these sections but I could definitely learn.

**Comment by Jetersen** [comment]
https://opensource.com/article/20/4/getting-started-jcasc-jenkins#comment-198101 This is a good start only thing he got wrong was the plugin installation 😅

**Comment by sladyn98** [comment]
Cool :) So I am assuming these sections go into the readme section?

**Comment by Jetersen** [comment]
Nah I would properly start a separate readme and link to it perhaps? it depends how well the document get structured I guess.
