### ISSUE TITLE
JENKINS-60373: Read secret from file and encode it with base64

### ISSUE THREAD

**Issue by olivergondza** [jenkinsci/configuration-as-code-plugin#1219]
### Feature Request

I am looking for a way to practically and securely inject binary secrets from `/run/secret` into a `file` credential type (`plain-credentials` plugin). The challenge is, the input is [expected to be base64 encoded](https://github.com/jenkinsci/configuration-as-code-plugin/blob/80e556e277b9a9980659eb1131497758e49bf239/demos/credentials/credentials.yaml#L38) so reading the file as-is from `/run/secrets` does not work. Extending `plain-credentials` to read the file content instead of expecting inlined string is something that was proven challenging to secure. Several approaches to address that was discussed in JENKINS-60373 and I would like to propose the most straightforward one[1].

---

Introduce a new syntax, that would permit reading file from filesystem and encoding the content with base64 to close the gap between traditional secrets injection and `file` credential. The reasoning is that when the feature is specific for JCasC, it is by definition restricted to administrators eliminating possible arbitrary file read vulnerabilities.

[1] https://issues.jenkins-ci.org/browse/JENKINS-60373?focusedCommentId=381101&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-381101

**Comment by olivergondza** [comment]
The suggested declaration format is:

```
secretBytes: "$base64file(/run/secrets/whatever)" # Read the file and encode content
```

or perhaps

```
secretBytes: "$base64(${whatever})" # Inject secret and encode it
```

**Comment by timja** [comment]
Sounds like a reasonable approach that has caused pain for people using certain plugins for a long time

**Comment by olivergondza** [comment]
@timja, great to hear that. If you can point to some other use-cases to keep in mind while implementing that, that would be good.

**Comment by timja** [comment]
There's some google plugins that have similar issues, can't remember off the top of my head though

**Comment by jglick** [comment]
> The suggested declaration format is

Note that this was just a dashed-off example. Probably you can find a more intuitive / readable syntax studying some other configuration languages.

**Comment by casz** [comment]
${base64('')}
Test secret string whether it is path or base 64 string encoded?
Secret source reveal will should help here 🤔

**Comment by sshepel** [comment]
Any updates on this?

**Comment by jetersen** [comment]
@jglick @olivergondza @timja 
Switching to apache's StringSubstitutor would enable this
Though the default lookup might be too powerful for JCasC use case.

Though it will cleanup some of the code as StringSubstitutor already supports default value via `:-`

```
Default String Lookups
Key	Implementation	Factory Method	Since
"base64Decoder"	Base64DecoderStringLookup	base64DecoderStringLookup()	1.6
"base64Encoder"	Base64EncoderStringLookup	base64EncoderStringLookup()	1.6
"const"	ConstantStringLookup	constantStringLookup()	1.5
"date"	DateStringLookup	dateStringLookup()	1.5
"dns"	DnsStringLookup	dnsStringLookup()	1.8
"env"	EnvironmentVariableStringLookup	environmentVariableStringLookup()	1.3
"file"	FileStringLookup	fileStringLookup()	1.5
"java"	JavaPlatformStringLookup	javaPlatformStringLookup()	1.5
"localhost"	LocalHostStringLookup	localHostStringLookup()	1.3
"properties"	PropertiesStringLookup	propertiesStringLookup()	1.5
"resourceBundle"	ResourceBundleStringLookup	resourceBundleStringLookup()	1.6
"script"	ScriptStringLookup	scriptStringLookup()	1.5
"sys"	SystemPropertyStringLookup	systemPropertyStringLookup()	1.3
"url"	UrlStringLookup	urlStringLookup()	1.5
"urlDecoder"	UrlDecoderStringLookup	urlDecoderStringLookup()	1.5
"urlEncoder"	UrlEncoderStringLookup	urlEncoderStringLookup()	1.5
"xml"	XmlStringLookup	xmlStringLookup()	1.5
```

I would properly settle for:
```
"base64" Base64EncoderStringLookup
"file" FileStringLookup
```

**Comment by jetersen** [comment]
For my own sanity I will extend FileStringLookup to only allow UTF-8.

**Comment by jetersen** [comment]
ARGH... `StringSubstitutor` 😭 Does not have a nice way to handle our existing cases when it comes to defaulting and properly logging it.

I am left to use StrSubstitutor for replacing none replaced values...

**Comment by jetersen** [comment]
Really happy that we had such good test coverage of our SecretResolver.
I have made some code improvements that should clearly improve performance...

I would actually like to benchmark it @oleg-nenashev @AbhyudayaSharma 😅

**Comment by jetersen** [comment]
Syntax would look like this:
```
${base64:${file:path to file}}
```

Hopefully that is acceptable?

**Comment by AbhyudayaSharma** [comment]
@jetersen https://www.jenkins.io/blog/2019/06/21/performance-testing-jenkins/ should get you started. It will be great to have these benchmarks in JCasC. Please let me know if you need any help.

**Comment by jetersen** [comment]
@AbhyudayaSharma I did some quick initial simple tests.

![image](https://user-images.githubusercontent.com/1661688/83349637-bba5fb00-a336-11ea-8aa6-7c181cc70c6f.png)

Though SecretSourceResolver is actually on the critical path meaning all values in the JCasC yaml has to go through it.

So I have added a test that sort of simulates it by calling it 100 times, which is also really slow 😅.

I should try and add a test case for actually going through jcasc.Configure method though it might be terribly slow

**Comment by jetersen** [comment]
Ah I would need to use different `BenchmarkMode` lucky there are annotations for that.
