### ISSUE TITLE
Add release automate for first alpha release (Jenkins release job)

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#124]

**Comment by buep** [comment]
We followed the formalities and made a HOSTING issue and a PR for permissions.

https://issues.jenkins-ci.org/browse/HOSTING-515
https://github.com/jenkins-infra/repository-permissions-updater/pull/604

Now we just need to make a release job @ewelinawilkosz can click to do the release. 

It will be alpha version, and less that version 1.x as we see things might change making it not backwards compatible.

**Comment by buep** [comment]
@ndeloof @oleg-nenashev we need some help from the infrastructure team on the formalities :-)

**Comment by buep** [comment]
We will make the Jenkins job public visible, but only few people able to execute the release.

**Comment by rtyler** [comment]
@buep We do not have any credentials in ci.jenkins.io which are capable of releasing user-downloadable software. Instead we re-use the same Jenkins Pipeline (generally) for a project internal "trusted.ci" which is not routable on the public internet.

There are numerous reasons for this, but the most obvious (major) one is that we do not want any potential undisclosed vulnerability in Jenkins to allow a malicious attacker to distribute malicious code to Jenkins instances.

**Comment by buep** [comment]
@rtyler thanks for taking security serious :-) I also learned from your colleagues you don't offer hosting and release services to the community, but not directly why.

But no worries, we don't have any problems hosting a release job ourselves.

**Comment by ewelinawilkosz** [comment]
@buep can we close that one?

**Comment by buep** [comment]
yes
