### ISSUE TITLE
Reference documentation for JCasC YAML

### ISSUE THREAD

**Issue by cbpr** [jenkinsci/configuration-as-code-plugin#1242]
Hi,
I very appreciate the [JCasC project](https://jenkins.io/projects/jcasc/) and your ongoing work here (or related like https://jenkins.io/projects/jcasc/dev-tools/)

You, as insiders, might be fine with the [demos](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos) as documentation and with the tests on them.
But I mean for many developers it takes too much time to find an answer to simple questions, arising when trying to use JCasC, for instance:
 * Jenkins officially supports SSH connected agents (https://hub.docker.com/r/jenkins/ssh-slave), but nothing is to find how this could be addressed in JCasC, let alone a list of the supported keys and values in the YAML tree; only java tests hint
    ```
    agentProtocols:
        - "JNLP4-connect"
        - "Ping"
    ```
 * Is the JCasC root section `plugins` still relevant? (As for the chicken-egg problem an earlier `RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt` is needed anyway.)
 * Are the PNGs with these limited options trees meant to be _the_ documentation?

⇒

As a developer trying to achieve an end-to-end CI/CD, based on configuration-as-code, I would like to avoid scripted configuration via Groovy or Python, but to find
 * a (generated!) reference documentation for JCasC YAML with all relevant options listed and explained (like https://jenkinsci.github.io/job-dsl-plugin/)
 * a wiki summarizing the best-practices for frequent standard use cases and frequent stumble stones (similar to https://github.com/jenkinsci/job-dsl-plugin/wiki),

This relates to, but is not covered by [#1037](https://github.com/jenkinsci/configuration-as-code-plugin/issues/1037) and [#1216](https://github.com/jenkinsci/configuration-as-code-plugin/issues/1216).

Regards,
Tom

**Comment by casz** [comment]
There is already a reference documentation... 😢

Read this section: https://github.com/jenkinsci/configuration-as-code-plugin/blob/b53eb77810a9f1a0b8871b21d98d25206f8e0d9f/README.md#initial-configuration

Head to `https://YOUR_JENKINS_URL/configuration-as-code/reference`

**Comment by casz** [comment]
This is partly covered by JSON schema too: https://github.com/jenkinsci/configuration-as-code-plugin/issues/1076

**Comment by casz** [comment]
The best way to get started in most cases is actually you install JCasC, start configuring away and then use export feature.

**Comment by cbpr** [comment]
Joseph,
Thanks a lot for the fast response.

Cool feature (always up-to-date), when plugins like Job-DSL or JCasC document themselves in a running system, but you should find it w/o bothering forums :P

I scrolled through this several times and wondered _which_ page
> "Click the `Documentation` link at the bottom of the Configuration as Code page."

may refer too.

So could you please replace this sentence at [Initial Configuration](https://github.com/jenkinsci/configuration-as-code-plugin#initial-configuration) by something more precise like

> To see the Jenkins Master reference documentation go to [Manage Jenkins](http://YOUR_JENKINS:8080/manage/) > [Configuration as Code](http://YOUR_JENKINS:8080/configuration-as-code/) > [Documentation](http://YOUR_JENKINS:8080/configuration-as-code/reference).
> There you can also export or [View Configuration](http://YOUR_JENKINS:8080/configuration-as-code/viewExport).

(and change the label of #1242 to "documentation" — there wasn't a button for me)?

Your hint "This is partly covered by JSON schema too: #1076" might be correct, but me and others searching for YAML documentation and using another IDE would not expect to find the reference documentation under "JSON schema and VC Code".
Again, here you probably mean the running system http://YOUR_JENKINS:8080/configuration-as-code/.

As I can view my Jenkins Master JCasC YAML now, I'm fine. With a small change like proposed above this could be closed.

**Comment by casz** [comment]
Feel free to send a PR to improve documentation 😄
