### ISSUE TITLE
Exit Code for Reload is 255

### ISSUE THREAD

**Issue by jimbo8098** [jenkinsci/configuration-as-code-plugin#1255]
- Jenkins version 2.204.1
- Plugin version 1.35
- OS CentOS 7.6.1810 (Running on Docker, build with Chef)

When running:

```
"java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -"http" reload-jcasc-configuration
```

I find that the command exits with a 255 with no content in either the STDOUT or STDERR, however the command appears to reload the configuration file as expected since at next login it is confirmed to have all of the settings set up within the file. Is there any reason why this would happen?

**Comment by timja** [comment]
What's in your configuration file?

It works fine for me with:

```shell
java -jar jenkins-cli.jar -auth admin:admin -s http://localhost:8080/jenkins/ -webSocket reload-jcasc-configuration
```

```yaml
jenkins:
  systemMessage: "Configured by jcasc5"

```

**Comment by gaiksaya** [comment]
I am also seeing this issue randomly. Its transient but yeah sometimes it throws 255 error code causing the deployment to fail. No error seen. @jimbo8098 Where you able to figure out the root cause or solution to this?
Thanks!

**Comment by jimbo8098** [comment]
Nah I wasn't able to work around it because just after it happened I got put on furlough and now I'm not there.

Sorry! I wish I could have been more more assistance here.
