### ISSUE TITLE
pipeline model definition 1.5.1 added a symbol, broke my JCasC 

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/configuration-as-code-plugin#1260]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.219

- [x] Plugin version 1.35

- [x] OS - Debian Buster in a Docker image

### Description

I updated from pipeline model definition 1.5.0 to pipeline model definition 1.5.1.  The update caused my Jenkins server to fail to start.  The error report was that the JCasC DSL did not recognize the pipeline-model keyword.

The pipeline model definition 1.5.1 release seems to have added a new symbol, `pipeline-model-docker` which seems to be an alias for `pipeline-model`.

The failing JCasC file includes:
```
pipeline-model:
  dockerLabel: "docker"
```

A working JCasC file includes:
```
pipeline-model-docker:
  dockerLabel: "docker"
```

I assume that the working symbol precedes the failing symbol in the source code and that JCasC supports at most one symbol per item.

@jglick and @dwnusbaum have been alerted to the issue.

Described in the [pipeline mode definition 1.5.1 release notes](https://github.com/jenkinsci/pipeline-model-definition-plugin/releases/tag/v1.5.1)

**Comment by dwnusbaum** [comment]
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/372 for the change the caused the issue. The relevant part of the change is that two descriptors went from having one symbol like this:

```
@Extension @Symbol({"pipeline-model"})
public class SomeDescriptor...
```

to two symbols, like this:

```
@Extension @Symbol({"pipeline-model-docker", "pipeline-model"})
public class SomeDescriptor...
```

I think that CasC should allow users to use either symbol in configuration files, but that it should always use the first symbol when it generates a configuration file itself.

**Comment by jglick** [comment]
Well https://github.com/jenkinsci/configuration-as-code-plugin/blob/b68e82e7eb859519975f29bc5e3b5ca77a4ef2ce/plugin/src/main/java/io/jenkins/plugins/casc/impl/attributes/DescribableAttribute.java#L55 looks OK but https://github.com/jenkinsci/configuration-as-code-plugin/blob/b68e82e7eb859519975f29bc5e3b5ca77a4ef2ce/plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java#L65 and https://github.com/jenkinsci/configuration-as-code-plugin/blob/b68e82e7eb859519975f29bc5e3b5ca77a4ef2ce/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfigurator.java#L56 and https://github.com/jenkinsci/configuration-as-code-plugin/blob/b68e82e7eb859519975f29bc5e3b5ca77a4ef2ce/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java#L47 are potentially in violation of the spec

> Multiple symbols can be specified as aliases. The first one is used as the primary identifier for reverse-mapping.

depending on whether these are used for reading or generating YAML.

**Comment by timja** [comment]
Pull request here: https://github.com/jenkinsci/configuration-as-code-plugin/pull/1308
