### ISSUE TITLE
WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig#jsonKeyFileUpload: type is abstract but not Describable.

### ISSUE THREAD

**Issue by lcsfreire** [jenkinsci/configuration-as-code-plugin#1261]
Hello, 
we've got the following environment:
-  2/217 Jenkins version
- 1.35 JCASC Plugin version
- linux docker image OS to jenkins master
- 4.2.0 google compute engine plugin version

Our jenkins is reloading the jcasc conf in a infinite loop. 
We have two logs which could explain the issue:
1) logged 6 times/minute
INFO	i.j.p.casc.TokenReloadAction#doIndex: Configuration reload triggered via token
2) logged 10 times/min
i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig#jsonKeyFileUpload: type is abstract but not Describable.

There is a closed ticket related to the issue 2): https://github.com/jenkinsci/configuration-as-code-plugin/issues/924
Can you please check and advice?
Thank you

**Comment by casz** [comment]
This issue is with the google plugins and not JCasC.
https://github.com/jenkinsci/google-oauth-plugin
