### ISSUE TITLE
README claims JCasC is included when running as Docker, but it isn't

### ISSUE THREAD

**Issue by ChristianCiach** [jenkinsci/configuration-as-code-plugin#1288]
### Description

The README states this:

```
Those running Jenkins as a Docker container (and maybe also pre-installing plugins), do include Configuration as Code plugin.
```
I am not entirely sure what the part "and maybe also pre-installing plugins" means in this context, but when running `jenkins/jenkins:lts`, the JCasC plugin is not available without installing it manually.

**Comment by casz** [comment]
@ChristianCiach you have to pre-install plugins: https://github.com/jenkinsci/docker#preinstalling-plugins

**Comment by ChristianCiach** [comment]
Well, duh, of course the plugin is "included" when explicitly preinstalling it :) This is true even when *not* running Jenkins as a Docker container.

**Comment by casz** [comment]
That's one the readme is referring to, that you need to preinstall plugins.

if you want `jenkins/jenkins:lts` to include JCasC that is a PR for https://github.com/jenkinsci/docker

**Comment by casz** [comment]
Feel free to send a PR that updates the readme if you find that section confusing, no need to create an issue about it.

**Comment by ChristianCiach** [comment]
Well, if you think that it's okay when something claims "batteries included" but you still need to buy and insert them manually, then I seriously cannot help you.

**Comment by casz** [comment]
I do not maintain the jenkins docker image so 🤷‍♂ 
Again feel free to update the wording in the readme, I'll happily accept a PR.
The readme is best maintained by those who reads it.

Reading the section in context

>First, start a Jenkins instance with the [Configuration as Code](https://plugins.jenkins.io/configuration-as-code) plugin installed.
>
>- Those running Jenkins as a [Docker](https://github.com/jenkinsci/docker) container (and maybe also [pre-installing plugins](https://github.com/jenkinsci/docker#preinstalling-plugins)), do include [Configuration as Code](https://plugins.jenkins.io/configuration-as-code) plugin.

You could properly reword

> need to include [Configuration as Code](https://plugins.jenkins.io/configuration-as-code) plugin.

Clearly something was lost when the readme was last edited in the section.

**Comment by ChristianCiach** [comment]
I do not claim that there is something wrong with the docker image. I claim that the Readme of this project is  misleading and, if you omit the part inside the parenthesis, totally wrong. I was hoping that this could be corrected by someone with write access, without requiring me to jump through hoops (forking, branching, cloning, editing, pushing, creating PR). I was clearly wrong about that, so let's just run other people into this pitfall.

**Comment by casz** [comment]
you can edit the readme from github web page, I do not see the issue 🤔

**Comment by casz** [comment]
https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by ChristianCiach** [comment]
> you can edit the readme from github web page without the hassle, I do not see your issue

I didn't know about that :D Thanks for that. I will do that next time.
