### ISSUE TITLE
Jenkins config.xml changes via GUI doesn't persist with configuration-as-code plug in installed.

### ISSUE THREAD

**Issue by DavidRodHub** [jenkinsci/configuration-as-code-plugin#1304]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ X ] Jenkins version 2.204.4

- [ X ] Configuration as Code Plugin 1.36

- [ X ] Ubuntu 18.04

### Description
**REF:**  Jenkins Home config.xml reset upon restart
- https://issues.jenkins-ci.org/browse/JENKINS-55088

On new jenkins instance with configuration-as-code plugin:

1. Create 2 simple jobs. (test-env, test-job-1)
2. Created list-view 'VIEW-A"  and added 'test-job-1"
3. Restart jenkins: ---> https://jenkins-upgrade.internal.com/restart
4. List-view "VIEW-A" does NOT persist.

**Comment by casz** [comment]
Could you share your config?

In any case this working as intended.
You most likely have configured views in JCasC so that is where you need to export the manual changes and merge them into your configuration.
JCasC will only manage what you tell it to manage 😉

**Comment by DavidRodHub** [comment]
If I understand correctly, if  adding views using the Jenkins GUI,  before doing a restart,  I also have to manually update the $JENKINS_HOME/casc_configs/jenkins.yaml with the added view otherwise  I'll lose it at the restart. Bummer!

When  a new view is added and then select configuration-code -> 'View Configuration",  the new jenkins view that was added via the GUI is there.  Why doesn't the configuration-as-code plugin update the jenkins.yaml file automatically?

**Comment by timja** [comment]
It's designed so that you don't make configuration changes through the GUI.
Normally you remove permissions for users to make that sort of change,
and get them to send a pull request to your jenkins.yaml file to get their view added

**Comment by DavidRodHub** [comment]
Got it.  Thanks for the  quick response.
