### ISSUE TITLE
could not install/configure rich-text-publisher-plugin

### ISSUE THREAD

**Issue by gaurav517** [jenkinsci/configuration-as-code-plugin#1306]
### Description

Sorry, not sure whether this is right category.

I am not able to install/configure rich-text-publisher-plugin. I followed the instructions on README.md, installed it manually and checked reference `/configuration-as-code/reference` but there was no mention of this plugin anywhere. I searched with different keywords, couldn't find anything. I also double checked, jenkins shows it installed.

How do I configure this plugin? Would be great if you guys put some basic sample yaml for this plugin in demo folder.

Thanks

**Comment by Jetersen** [comment]
Plugin compatibility is must likely your issue.
Please report the issue to the plugin

**Comment by Jetersen** [comment]
Does the plugin even have any global plugin configuration?

**Comment by gaurav517** [comment]
Thanks. couldn't find any global configuration.
How do we add plugin in such cases?

**Comment by gaurav517** [comment]
Also raised it on plugin side: https://issues.jenkins-ci.org/browse/JENKINS-61376

**Comment by timja** [comment]
What are you expecting to configure here?

**Comment by Jetersen** [comment]
If there is no global configuration than there is nothing for JCasC to configure, so not sure how this an issue.

**Comment by Jetersen** [comment]
@gaurav517 https://jenkins.io/doc/book/managing/plugins/

Can we close this issue?

**Comment by gaurav517** [comment]
oh okay.. I was confused.. yep right, nothing to configure. 👍 thanks.
