### ISSUE TITLE
Jenkins credential changes every time redeploy and No longer useful

### ISSUE THREAD

**Issue by jawlitkp** [jenkinsci/configuration-as-code-plugin#1316]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x ] Plugin version

- [x ] OS

### Description
jenkins version : Jenkins ver. 2.225
Plugin version : 1.36

Steps:

1. Configured GitHub credentials from jenkins UI
2. Copy content from cofig as code yaml file 
3. Added connect to jenkins helm chart yaml 
4. Redeploy jenkins 

Issue: 
Credetial chages and no usefull anymore. deleted and added again from UI and started working. noticed original hash for password got changed

**Comment by Jetersen** [comment]
it's not a bug it's a security feature.
Jenkins stores a master key under `$JENKINS_HOME/secrets/`

Either you store this file together with the JCasC setup or use one of the many options to configure secrets, you can actually use kubernetes secrets.

**Comment by Jetersen** [comment]
Please see
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc

**Comment by jawlitkp** [comment]
Yes, I ended up moving to Kubernetes secrets since my solution is immutable Jenkins infra. Thanks for a quick reply. just curious if you can provide an example of how I can store Jenkins secrets file together with the JCasC setup?

**Comment by Jetersen** [comment]
Have a look here: https://github.com/hmcts/cnp-jenkins-config

**Comment by Jetersen** [comment]
Again using kubernetes you can create a secret file that your Jenkins master will consume.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1141 should also help. No ETA right now, but it is on my list

**Comment by jawlitkp** [comment]
How do I handle LDAP password? right now I have to use plain password because every time when I deployed it doesn't work if I use the string I am getting from config as code import

**Comment by jetersen** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/ldap

**Comment by jawlitkp** [comment]
managerPasswordSecret: ${LDAP_PASSWORD}.  what goes in ${LDAP_PASSWORD}. plain password or base64 encoded ?

**Comment by jetersen** [comment]
@jawlitkp see the plugin for that.

I would assume they take a regular password.
Please read about [Handling Secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc)

**Comment by jawlitkp** [comment]
Ok I think overall it comes to this limitation
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1141

**Comment by jetersen** [comment]
If your using Kubernetes, you can define all your Jenkins credentials from Kubernetes secrets. Not sure why your intent on using Jenkins encrypted credentials.

**Comment by alok15ee** [comment]
is there any extended support available to AWS Parameter store?

**Comment by jetersen** [comment]
@alok15ee https://github.com/jenkinsci/configuration-as-code-secret-ssm-plugin it's linked right in the docs :)

**Comment by alok15ee** [comment]
> @alok15ee https://github.com/jenkinsci/configuration-as-code-secret-ssm-plugin it's linked right in the docs :)
It does work for most of the creds-type but not for the username/password and that's where we need to delete and re-add after deployment.

**Comment by alok15ee** [comment]
> @alok15ee https://github.com/jenkinsci/configuration-as-code-secret-ssm-plugin it's linked right in the docs :)

Thanks, I was able to figure it out. Jenkins has a little bit of weird configuration for "SCOPE: System" and after I changed it to "Scope: Global", credentials started showing up. Thanks @jetersen !!

**Comment by jetersen** [comment]
I would consider this works as intended.

**Comment by longc** [comment]
It looks like there is a bug in JCasC, I tried the ldap plugin 2.7 in jenkins version 2.304, either set the value to environment var or plain text value by using JCasC, 
```
managerPasswordSecret: ${LDAP_PASSWORD}
```
the password will be encrypted to a hash value after restart, but this hash value doesn't work, jenkins throws out the exception error
```
SEVERE	o.s.s.w.a.AbstractAuthenticationProcessingFilter#doFilter: An internal error occurred while trying to authenticate the user.
javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580]
```
The only way to get it work is to change the password via jenkins console, then the managerPasswordSecret will be updated to a new hash value in "<jenkins_home>/config.xml", the new hash value will work in JCasC.
```
managerPasswordSecret: {hash_value}
```
It seems there is a difference between JCasC and Jenkins Console to encrypt the LDAP password.

**Comment by ningjunwei2** [comment]
> It looks like there is a bug in JCasC, I tried the ldap plugin 2.7 in jenkins version 2.304, either set the value to environment var or plain text value by using JCasC,
> 
> ```
> managerPasswordSecret: ${LDAP_PASSWORD}
> ```
> 
> the password will be encrypted to a hash value after restart, but this hash value doesn't work, jenkins throws out the exception error
> 
> ```
> SEVERE	o.s.s.w.a.AbstractAuthenticationProcessingFilter#doFilter: An internal error occurred while trying to authenticate the user.
> javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580]
> ```
> 
> The only way to get it work is to change the password via jenkins console, then the managerPasswordSecret will be updated to a new hash value in "<jenkins_home>/config.xml", the new hash value will work in JCasC.
> 
> ```
> managerPasswordSecret: {hash_value}
> ```
> 
> It seems there is a difference between JCasC and Jenkins Console to encrypt the LDAP password.

Should ${LDAP_PASSWORD} be a secrets or a base64 encrypted password? If you need to configure secrets, how should you write it in managerPasswordSecret: ${LDAP_PASSWORD}? Like managerPasswordSecret: ${ldappsd.data.password} ?
my ldap secrets are
  kubectl get secrets -n jenkins ldappsd -o yaml
apiVersion: v1
data:
   password: TmFyd2FsIzIwMjI=xx
kind: Secret
metadata:

**Comment by longc** [comment]
> Should LDAPPASSWORDbeasecretsorabase64encryptedpassword?Ifyouneedtoconfiguresecrets,howshouldyouwriteitinmanagerPasswordSecret:{LDAP_PASSWORD}? Like managerPasswordSecret: ${ldappsd.data.password} ? my ldap secrets are kubectl get secrets -n jenkins ldappsd -o yaml apiVersion: v1 data: password: TmFyd2FsIzIwMjI=xx kind: Secret metadata:

LDAPS is working for me, it is base64 encoded kubernetes secret, the secret name is the same as the key inside.
kubectl get secrets -n jenkins ldappsd.data.password -o yaml
apiVersion: v1
data:
ldappsd.data.password:  <base64 encoded>
kind: Secret
metadata:
When the secret is mounted, use the mount path
managerPasswordSecret: "${readFile:/<mount path>/ldappsd.data.password}"
