### ISSUE TITLE
disabling reloading secrets from vault

### ISSUE THREAD

**Issue by emelianrus** [jenkinsci/configuration-as-code-plugin#1317]
Hi could you help me with issue please 
i have case when token expired after some time, and from security reasons we can't allow to renew it
and casc trying to update secrets and change previous loaded secrets with empty string
Is there any procedure to disable reloading tokens from vault? or load them only one time?

**Comment by Jetersen** [comment]
remove the environment variables after initial startup.

**Comment by Jetersen** [comment]
JCasC expects to have access to these secrets.
I suggest you either adapt or change the approach turning vault secrets into files as a sidecar container.

**Comment by Jetersen** [comment]
another approach is to use one JCasC config with credentials on initial startup

**Comment by emelianrus** [comment]
but it non-secured approaches....
may be better to provide something like ENV variable like  "VAULT_UPDATE_TOKEN=false" ?

**Comment by ipleten** [comment]
MB CasC  just shouldn't replace credentials with empty values if it can't connect to Vault?

**Comment by Jetersen** [comment]
@emelianrus depends how secure you want to be.
The problem is not with vault secret resolver. You will still end up with blank credentials base of your jenkins yaml config file.

**Comment by sanyamaz** [comment]
I have the same security issue and didn't find any workaround for this problem 
should be provide some way to do this?

**Comment by timja** [comment]
I think it would be reasonable to add some config property to allow throwing an error if a secret can not be found by the vault secret source, or if vault can’t be contacted

**Comment by Jetersen** [comment]
I do not see a way forward without changes to JCasC removing the credentials from yaml after initial startup.
Any secrets used outside of the credentials block would still end up blank.

Unless someone has a bright idea to how this increased security model should work. I do not see a way forward.
