### ISSUE TITLE
Usuck

### ISSUE THREAD

**Issue by themasterofscrumpets** [jenkinsci/configuration-as-code-plugin#1329]
[jenkins-jira]: https://issues.jenkins-ci.org
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [ ] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [ ] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [x] Link to [Jenkins JIRA issue][jenkins-jira]

- [x] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to plugin's GitHub repository

u

### Description

Please describe your issue here.
I'm being stopped

**Comment by themasterofscrumpets** [comment]
Yo

**Comment by Jetersen** [comment]
@jenkinsci/github-admins not sure this or #1330 is helpful

**Comment by oleg-nenashev** [comment]
Thanks to @daniel-beck for banning the user

**Comment by oleg-nenashev** [comment]
user reported
