### ISSUE TITLE
User documentation - a specific use case example

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#133]
My colleague Sofus provided us this little user-story, as I told him Jenkins Configuration as Code is _the thing_ to use going forward:

> As an instructor i would like to setup jenkins credentials and install a list of plugins when I start jenkins so that I do not need to make the students do this individually.

Implicitly this means using docker to deploy.

I thinks we can do all this already, but having this wrapped as a simple example in our documentation would create some value I think and allows others to use the same setup.

Relates to #70 #85

**Comment by sofusalbertsen** [comment]
In this specific use-case, having a credentials as well as the artifactory plugin with a server setup would be awesome as well.

**Comment by daniel-beck** [comment]
> artifactory plugin

Given the mess that JFrog make of their plugin, would not consider it a good example for best practices.

**Comment by ndeloof** [comment]
With multiple yaml document supported it's not easy to just cherry pick samples from various demos, typically we already have some for credentials, just miss one for plugin management.

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/436
