### ISSUE TITLE
Leavemebe

### ISSUE THREAD

**Issue by themasterofscrumpets** [jenkinsci/configuration-as-code-plugin#1330]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Describe your feature request here.

**Comment by Jetersen** [comment]
Not sure what this is about can you upate the description to describe your feature request?
