### ISSUE TITLE
Ambiguous use of the variable "SECRETS"

### ISSUE THREAD

**Issue by slangdaddy** [jenkinsci/configuration-as-code-plugin#1336]
### Checklist

- [x] Jenkins version: 2.204.5
- [x] Plugin version: 1.36
- [x] OS: Mac OS

### Description

I believe that the environment variable "SECRETS" has become ambiguous with the implementation of #1160. Before the implementation, one could use this variable to point to a directory, where secrets could be found. Now, this variable is interpreted as a pointer to a properties file. You can see this in the documentation: https://github.com/jenkinsci/configuration-as-code-plugin/blame/master/docs/features/secrets.adoc#L85 vs https://github.com/jenkinsci/configuration-as-code-plugin/blame/master/docs/features/secrets.adoc#L188

I personally would prefer the old handling and maybe introduce a new variable "SECRETS_FILE", which can be used to point to the properties file.

**Comment by ThinkBriK** [comment]
it's really annoying, especially to feed Kubernetes secrets !

**Comment by peterloron** [comment]
Making these use cases have explicit variables would be very good.

**Comment by jetersen** [comment]
PRs are always welcome.

In any case here you go: #1435
