### ISSUE TITLE
Found multiple implementations for symbol = kubernetes

### ISSUE THREAD

**Issue by gvfnix** [jenkinsci/configuration-as-code-plugin#1337]
### Your checklist for this issue

- [x] Jenkins version: Jenkins ver. 2.204.2

- [x] Plugin version: configuration-as-code:1.36

- [x] OS: Docker container built from jenkins/jenkins:lts

### Description
One of configuration files looks like this:
```
jenkins:
  clouds:
    - kubernetes:
        name: "basic-k8s"
```
When applying this configuration, I get the configuration for KubernetesCloud class in azure-container-agents plugin, although I mean to configure KubernetesCloud in kubernetes plugin. In jenkins log I can see the message saying
```
2020-03-25 16:07:26.871+0000 [id=315]   WARNING i.j.p.c.i.c.HeteroDescribableConfigurator#handleDuplicateSymbols: Found multiple implementations for symbol = kubernetes: [com.microsoft.jenkins.containeragents.KubernetesCloud$DescriptorImpl@6c6e627f, org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$DescriptorImpl@1dc15430]. Please report to plugin maintainer.
```
I think there should be some way to choose the descriptor but I did not find any.

**Comment by timja** [comment]
This can't be fixed here, the symbol is the same in both plugins and the target type is the same (cloud)

This isn't allowed and one of the plugins needs to add a symbol, I would suggest the azure-container-agents plugin adds it

**Comment by oleg-nenashev** [comment]
FTR https://github.com/jenkinsci/configuration-as-code-plugin/issues/964 for a better handling on the JCasC side (also cannot be resolved by the plugin on its own, symbol management lib patches are needed)

**Comment by timja** [comment]
> FTR #964 for a better handling on the JCasC side (also cannot be resolved by the plugin on its own, symbol management lib patches are needed)

not sure if that is relevant here,
This is the same extension point and there's no additional context
