### ISSUE TITLE
Add category to system settings for modern Jenkins releases

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkinsci/configuration-as-code-plugin#1357]
### Feature Request

I think this (great) plugin should show up in category "System Configuration" in "Manage Jenkins" page of modern Jenkins releases (currently it is "Uncategorized"): implementation in analog to e.g. https://github.com/jenkinsci/credentials-plugin/compare/credentials-2.3.3...credentials-2.3.4; see https://github.com/jenkinsci/jenkins/pull/4546 for more background, `ManagementLink.Category.CONFIGURATION`

![image](https://user-images.githubusercontent.com/145182/79300232-6d53ae80-7ee6-11ea-8bab-b315abece0de.png)

**Comment by jetersen** [comment]
I need more context... Where is this screenshot taken from?
Could you take of the whole browser window?

What version of Jenkins is this screenshot taken from?

**Comment by reinholdfuereder** [comment]
Jenkins >= 2.226 (2020-03-15), see https://github.com/jenkinsci/jenkins/pull/4546 for more details

**Comment by jetersen** [comment]
submitted #1358 hopefully it does the job for you @reinholdfuereder 😅

**Comment by jetersen** [comment]
![image](https://user-images.githubusercontent.com/1661688/79302757-8875ec80-7eed-11ea-8938-b5754e09db75.png)

**Comment by reinholdfuereder** [comment]
@jetersen Thanks for your extremely quick response => looks good, thanks!
