### ISSUE TITLE
Support export setting "Global Tool Configuration -> Maven Configuration"

### ISSUE THREAD

**Issue by kwin** [jenkinsci/configuration-as-code-plugin#1370]
The Maven Configuration below `/configureTools/` is currently not exported to the YAML. That is handy as it allows to bind specific configuration files which can already be configured via `unclassified.globalConfigFiles` (as outlined in https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/config-file-provider)

**Comment by jetersen** [comment]
This is a issue for Jenkins core: https://github.com/jenkinsci/jenkins/blob/d688c154907d17e75ea31067c8fc2525aa679584/core/src/main/java/hudson/tasks/Maven.java#L491

Which is best reported to https://issues.jenkins-ci.org

cc @oleg-nenashev @timja

**Comment by kwin** [comment]
I reported this now in https://issues.jenkins-ci.org/browse/JENKINS-62446. Thanks for the input.
