### ISSUE TITLE
Is there a way to export CASC config from the pipeline?

### ISSUE THREAD

**Issue by AlexPykavy** [jenkinsci/configuration-as-code-plugin#1373]
Hello,

As shown in the documentation users are not being exported by the plugin:
![image](https://user-images.githubusercontent.com/32162928/81320299-a0c6ca80-9099-11ea-9191-ba2e998a9ffb.png)

Of course, I have tried anyway 😄 and it doesn't work. But if you adjust a configuration file a bit: remove some attributes and add default password it's becoming working.

Due to the fact that Jenkins pipeline support `readYaml` operator I got an idea to implement a Jenkins pipeline which will export the CASC config, modify it, and publish somewhere.

Is it possible or not? Is it an acceptable approach? Maybe it's forbidden by security reasons

Thanks in advance.

**Comment by umlublin** [comment]
import io.jenkins.plugins.casc.ConfigurationAsCode
def stream = new ByteArrayOutputStream()
ConfigurationAsCode.get().export(stream)
stream.toString()

**Comment by AlexPykavy** [comment]
This helps, thanks!

**Comment by y0zg** [comment]
@umlublin , @AlexPykavy 
Hello, if I need to export job settings to pipeline.yaml, do you have any ideas how to do this? I need some extra settings which are not available in examples and have no clue how to get those

Thanks!
