### ISSUE TITLE
Can't install v1.40: does not match expected SHA-256

### ISSUE THREAD

**Issue by sbourlon** [jenkinsci/configuration-as-code-plugin#1377]
- [x] Jenkins version: Jenkins ver. 2.222.3 in Docker (image: jenkins/jenkins:lts)
- [x] Plugin version: 1.40
- [x] OS: Linux

### Description

I am getting the error `does not match expected SHA-256, expected` while installing the plugin:

```
java.io.IOException: Downloaded file /var/jenkins_home/plugins/configuration-as-code.jpi.tmp does not match expected SHA-256, expected 'GY0T+9OSMa1UDYYInN59BsYHQpAil1PPhuEFPMYnE+E=', actual 'qYQpkSE9v4JY1oGsaOXdmVVb+h8UIRQAyqFhL1A/I9Q='
	at hudson.model.UpdateCenter.throwVerificationFailure(UpdateCenter.java:1982)
	at hudson.model.UpdateCenter.verifyChecksums(UpdateCenter.java:2017)
	at hudson.model.UpdateCenter$InstallationJob.replace(UpdateCenter.java:2196)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.install(UpdateCenter.java:1306)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1835)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2110)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1806)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
	at java.lang.Thread.run(Thread.java:748)
```

I can confirm that the Docker container can reach internet:

```
% docker exec -it gitlab_jenkins_1 curl --head https://www.jenkins.io/
HTTP/2 200 
server: openresty/1.15.8.2
[...]
```

**Comment by jetersen** [comment]
Not really a issue for us, please report it at https://issues.jenkins-ci.org/
cc @olblak @daniel-beck

**Comment by daniel-beck** [comment]
I filed https://issues.jenkins-ci.org/browse/INFRA-2613 for this.

**Comment by sbourlon** [comment]
Thanks @daniel-beck :+1:

**Comment by sbourlon** [comment]
I am now able to install the plugin.

**Comment by JorgePenaranda-Incontact** [comment]
what was your solution?

**Comment by JorgePenaranda-Incontact** [comment]
I still have a  lot of the same problem with different plugins :
java.io.IOException: Downloaded file /var/lib/jenkins/plugins/blueocean-core-js.jpi.tmp does not match expected SHA-256, expected 'D3fkc/z/CHgzW7t8XpORENe9RCvJGiNiWUFPWg+1/WM=', actual 'dFkhztUVPbsLd2tn+xDm447gjU8ExkyxnTALcmJ0mJg='

java.io.IOException: Downloaded file /var/lib/jenkins/plugins/blueocean-commons.jpi.tmp does not match expected SHA-256, expected 

Also Fresh installations are broke, tried multiple times with different methods docker,ubuntu,centos and I got the same error

**Comment by douglasawh** [comment]
@JorgePenaranda-Incontact did you get your issue resolved? it seems like restarting a docker container might resolve the issue: https://stackoverflow.com/questions/56416277/jenkins-plugins-installation-giving-sha-256-mismatch-error

**Comment by douglasawh** [comment]
@JorgePenaranda-Incontact nm, looks like you got it resolved here: https://issues.jenkins-ci.org/browse/INFRA-2613?page=com.atlassian.streams.streams-jira-plugin%3Aactivity-stream-issue-tab

**Comment by vpernankil** [comment]
Downloaded file /opt/tomcat/.jenkins/plugins/ec2.jpi.tmp does not match expected SHA-256, expected '/MKQ9Me8RVsgVuFLVzFVnB2l93WQ/sacbNK3Cqdfb+I=', actual '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='

**Comment by vpernankil** [comment]
same issue

**Comment by rahulbhange** [comment]
same issue from 3 days... unable to install plugins.

**Comment by timja** [comment]
which plugins?

**Comment by debug510** [comment]
same issue from yesteday

**Comment by timja** [comment]
The yesterday issue should be fixed can you be more specific please

**Comment by daniel-beck** [comment]
Commenting on similar looking issues relating to infra problems from half a year ago is not helpful, please file a new issue instead.
