### ISSUE TITLE
Update the JSON Schema documentation page

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1382]
It looks line the https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/jsonSchema.md page has not been updated after the completion of the [JCasC Dev Tools](https://www.jenkins.io/projects/jcasc/dev-tools/) project.

It would be great to...

- [ ] Fix headings which are currently broken
- [ ] Update the state to reflect improvements in the project and remaining issues
- [ ] Update the documentation to include contents of the [blogpost ](https://www.jenkins.io/blog/2020/02/25/vscode-caseStudy/) by @sladyn98 
- [ ] Add references to the VS Code plugin
- [ ] Add reference to the online meetup by @sladyn98 : https://www.meetup.com/Jenkins-online-meetup/events/268823268
- [ ] Document REST API for JSON schema generation

These changes can be delivered incrementally by multiple pull requests

CC @sladyn98

**Comment by Chinmay922** [comment]
I would love to work on this.

**Comment by Chinmay922** [comment]
may I get access to work on this?

**Comment by oleg-nenashev** [comment]
You could fork it and submit a pull request from your fork

**Comment by Chinmay922** [comment]
Thank you! I have just forked and will start the work now.

**Comment by Chinmay922** [comment]
I have fixed the first two issues and submitted a pull request. I will work on the others too. Please check and let me know about the fixes.

**Comment by oleg-nenashev** [comment]
Not stale, but needs a status review
