### ISSUE TITLE
multiple jcasc open file handlers

### ISSUE THREAD

**Issue by MorZaroor** [jenkinsci/configuration-as-code-plugin#1385]
- [ x ] Jenkins version: 2.190.3

- [ x ] Plugin version: 1.35

- [ x ] OS: Debian 9

Using Jenkins stable helm chart version 1.0.33

### Description

Jenkins is yelling about too many open files ( which is a quite known issue with jenkins as far as i know ) and after investigating which file handlers are open i noticed that jcasc configuration files are open multiple times (well, 65536 times to be exact), I attached an example picture of the container's "ls -la /proc/JENKINS_PID/fd":
![image](https://user-images.githubusercontent.com/21296102/81930041-aa4bb780-95f0-11ea-9890-4ceeabcc3c0d.png)

As you can see, we added multiple configuration files instead of one main file (for better code management) but each configuration file is open multiple times which over time causes the OS to reach max open files.

I also ran GC multiple times but it only closed about 4 files ( not much compared to 65536 open files).

Is this a known issue? Is that a Jenkins issue or a Jcasc issue? Restarting the Pod or raising the the container's limits seems to be the unprofessional solution so please let me know if you know of any better solution instead 👍

**Comment by timja** [comment]
Not a known issue, my production instance doesn't have this problem, so not sure why this is happening for you

**Comment by jetersen** [comment]
I really want to rewrite how files are accessed. Currently it is a mess 😓

**Comment by MorZaroor** [comment]
Just a quick update, because its a production jenkins i had to restart it as a quick fix and obviously all of the open files were gone.
Unfortunately it seems the issue persists, it started with 1000 open files when it just got up (makes sense with all of the builds and plugins) and after about 2 hours it got to 1500 open files when all of the new open files are the same as the ones i sent (jcasc configuration files).

Before that restart the jenkins was up for 8 days, which kinda makes sense if i get about 250 new open files per hour.... Any opinions?

**Comment by jetersen** [comment]
Tried to reduce the scope for when the Reader needed to be called. Hopefully keeping it inside a try with resource block will solve the issue.

**Comment by jetersen** [comment]
The fix is included in [v1.41](https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.41)

**Comment by jetersen** [comment]
@MorZaroor any word on if the update helps?

**Comment by jetersen** [comment]
@MorZaroor I would really appreciate if you could update us on whether the issue is fixed or not.
