### ISSUE TITLE
Is there any support for thin-backup plugin ?

### ISSUE THREAD

**Issue by jawlitkp** [jenkinsci/configuration-as-code-plugin#1396]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [ ] Jenkins version
- [ ] Plugin version
- [ ] OS
- [ ] Reproduction steps

### Description

Please describe your issue here, and explain what you have already tried to resolve it.

**Comment by jetersen** [comment]
Did you try exporting it?

**Comment by jawlitkp** [comment]
Yeah I tried and it didn’t work

**Comment by jawlitkp** [comment]
This is the version I am using : configuration-as-code:1.40

**Comment by jetersen** [comment]
Than the issue should be reported to thin backup plugin.

**Comment by jetersen** [comment]
There is no way thin-backup is compatible with JCasC, someone will have to rewrite most of the plugin or take maintainership:
https://github.com/jenkinsci/thin-backup-plugin/blob/master/src/main/java/org/jvnet/hudson/plugins/thinbackup/ThinBackupPluginImpl.java

**Comment by jawlitkp** [comment]
Ok thanks. I dont see any activity for that plugin from last 3 years so not sure if they would support. Any other options for taking backup? we are running immutable jenkins on k8s.I have persistent volume as ssd disc for jobs but I am looking something to take backup in gcs

**Comment by jetersen** [comment]
@jawlitkp have you looked into https://github.com/jenkinsci/kubernetes-operator

**Comment by jawlitkp** [comment]
There was PR for it : https://github.com/jenkinsci/thin-backup-plugin/pull/18

**Comment by jawlitkp** [comment]
> @jawlitkp have you looked into https://github.com/jenkinsci/kubernetes-operator

Seeing it first-time but it looks interesting , I will dig deep

**Comment by timja** [comment]
> > @jawlitkp have you looked into [jenkinsci/kubernetes-operator](https://github.com/jenkinsci/kubernetes-operator)
> 
> Seeing it first-time but it looks interesting , I will dig deep

https://youtu.be/gpKedb038S0

**Comment by abdennour** [comment]
any news?

**Comment by StefanSpieker** [comment]
I recently took the maintainership for the thin-backup plugin, are there some hints how I should change the plugin that it works with JCasC?

**Comment by TieRein** [comment]
As a user of both plugins, I would love for this to be implemented. Thank you for your contributions Stefan!

**Comment by jetersen** [comment]
@StefanSpieker there is always the readme which has a link to this guide: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

**Comment by TieRein** [comment]
@StefanSpieker I found an example PR of a different backup plugin "Periodic Backup" that implemented CasC. Hopefully this helps: https://github.com/jenkinsci/periodicbackup-plugin/commit/43a0fbc7c7bc1bbcc6ceb37321236632594dd1fb
