### ISSUE TITLE
Verify Matrix Project plugin compatibility

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#14]
https://plugins.jenkins.io/matrix-project

**Comment by ewelinawilkosz** [comment]
matrix plugin is being configured under 'Configure Global Security' page, not 'Configure System,' and I can't find matrix plugin at the list of discovered configurators (descriptors), no global.jelly file also - @ndeloof can you confirm it is an issue now or is there already a solution I simply can't find?

**Comment by ndeloof** [comment]
@ewelinawilkosz are you testing matrix plugin (project type) or https://wiki.jenkins.io/display/JENKINS/Matrix+Authorization+Strategy+Plugin ?

**Comment by ewelinawilkosz** [comment]
Authorization strategy of course... wrong issue
