### ISSUE TITLE
Path or URL: Special characters not handled during validation via checkNewSource endpoint

### ISSUE THREAD

**Issue by haidaraM** [jenkinsci/configuration-as-code-plugin#1401]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version: 2.222.3

- [x] Plugin version: 1.41

- [ ] OS: Not relevant

### Description

When trying to replace the configuration through the UI with an URL with special characters, the URL sent to the server are truncated. 
![jcas_issue](https://user-images.githubusercontent.com/9849996/82767430-cb4dad00-9e27-11ea-928f-af6dba4c4b29.png)

In this example with a S3 presigned URL, the `Signature` and `Expires` are not sent to the server. The URL works when I submit it.

**Comment by jetersen** [comment]
Nice find as a workaround your better of overriding it with the environment variable `CASC_JENKINS_CONFIG` till the patch lands.
