### ISSUE TITLE
Does jcac supports log recorder ?

### ISSUE THREAD

**Issue by jawlitkp** [jenkinsci/configuration-as-code-plugin#1407]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [ ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [ ] Jenkins version
- [ ] Plugin version
- [ ] OS
- [ ] Reproduction steps

### Description

Please describe your issue here, and explain what you have already tried to resolve it.

**Comment by jetersen** [comment]
It's the other way around :)
Does Jenkins's log recorders support JCasC, the answer is no: https://github.com/jenkinsci/jenkins/pull/4538
