### ISSUE TITLE
Clarify README about hidden directory exclusion

### ISSUE THREAD

**Issue by skundrik** [jenkinsci/configuration-as-code-plugin#1409]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Jenkins version

- [x] Plugin version 1.41

- [ ] OS

### Description

When using JCasC configuration spec with a root folder it's not clear in the documentation that the hidden directory exclusion applies to **every** individual folder name in the whole path rather than just subfolders of the root.

### Examples:
`CASC_JENKINS_CONFIG=/jenkins/casc_configs`
:heavy_check_mark: `/jenkins/casc_configs/jenkins.yaml`
:heavy_check_mark: `/jenkins/casc_configs/dir1/config.yaml`
:x: `/jenkins/casc_configs/.dir1/config.yaml`
:x: `/jenkins/casc_configs/..dir2/config.yaml`

`CASC_JENKINS_CONFIG=/jenkins/.configs/casc_configs`
:x: `/jenkins/.configs/casc_configs/jenkins.yaml`
:x: `/jenkins/.configs/casc_configs/dir1/config.yaml`
:x: `/jenkins/.configs/casc_configs/.dir1/config.yaml`
:x: `/jenkins/.configs/casc_configs/..dir2/config.yaml`

**Comment by jetersen** [comment]
It's pretty clear; https://github.com/jenkinsci/configuration-as-code-plugin/blob/1dba3f819dc95138378d0d9a649e5a0af1e5bfd7/README.md#getting-started

**Comment by skundrik** [comment]
To me this reads as recursively traverse folders from the `CASC_JENKINS_CONFIG` and exclude the ones that are hidden.
