### ISSUE TITLE
Unable to set java options in docker template

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#141]
There is a advance option on docker template base. We can set the java options.
Using this plugin i could not se the java option by using the xml schema.

          - labelString: "labe;"
            dockerTemplateBase:
              image: "image1"
            remoteFs: "/home/jenkins"
            connector:
              ssh:
                sshKeyStrategy:
                  ManuallyConfiguredSSHKey:
                    credentialsId: "jenkins-agent-ssh-key"
                    sshHostKeyVerificationStrategy:
                      NonVerifyingKeyVerificationStrategy:
                jvmOptions:
                javaPath: "/usr/lib/jvm/java-1.8.0/jre/bin/java"
            instanceCapStr: "30"
            mode: "EXCLUSIVE"

What is the correct scheme place to set javaPath ?
The above template is base is setting fine except javaPath.

**Comment by casz** [comment]
Think your indentation is off

Should be
```
jvmOptions:
  javaPath: "/usr/lib/jvm/java-1.8.0/jre/bin/java"
```

If not that try the array style
```
jvmOptions:
  - javaPath: "/usr/lib/jvm/java-1.8.0/jre/bin/java"
  - otherParam: "sup"
```
