### ISSUE TITLE
For loop not accepted in JCasc jobdsl

### ISSUE THREAD

**Issue by iptizer** [jenkinsci/configuration-as-code-plugin#1413]
### Your checklist for this issue

- [ x ] Jenkins version
- [ x ] Plugin version
- [ x ] OS

I am using the [Jenkins helm chart](https://github.com/helm/charts/blob/master/stable/jenkins/Chart.yaml) to deploy Jenkins on Kubernetes. Helm chart version 1.23.0. (There have been a lot of updates on the chart lately, the version is from last week).

- Jenkins Version: lts
- JCasc Version: 1.41
- OS: Official Jenkins docker image

### Description

I am inserting a jobdsl script with a loop to generate a couple of multibranch jobs. I am using helm to inject these values. The helm chart then mounts this script locally. Everything is correctly inserted. The following lines show a `cat` of the inserted script:

```sh
root@jenkins-5969d5b49-z8chv:/# cat /var/jenkins_home/casc_configs/jobs.yaml
jobs:
- script: >
    def scriptpaths = ['one','two']
    for( i in scriptpaths) {
       multibranchPipelineJob("${i}") {
          branchSources {
             git {
                   id("${i}") // IMPORTANT: use a constant and unique identifier
                   remote('git@xxxxxxxx')
                   credentialsId('cloud-jenkins-ssh-private-key')
                   includes('dev')
             }
          }

          orphanedItemStrategy {
             discardOldItems {
                   numToKeep(20)
             }
          }
       }
    }
```

When executing through jcasc the following error is thrown:

```sh
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script: 1: expecting EOF, found 'for' @ line 1, column 33.
   def scriptpaths = ['one','two'] for( i in scriptpaths) {
                                   ^

1 error
[....]
```

When I do a copy & paste of the job script, paste it manually into a jobdsl build job, everything works.

**Comment by timja** [comment]
I think you're trimming whitespace,

can you try with `|` instead of `>` after your `script:`

**Comment by jetersen** [comment]
You can read more about multiline in yaml here: https://yaml-multiline.info/ and see the effects :)

**Comment by iptizer** [comment]
Yeah, totally right 🤦‍♂️, this might be one part of the problem. Nevertheless, the script is still not executed, though the error changed:

```sh
javaposse.jobdsl.dsl.DslScriptException: (script, line 3) name must be specified
	at sun.reflect.GeneratedConstructorAccessor346.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
[...]
```

Respond if you need the full stacktrace.

**Comment by jetersen** [comment]
That's your groovy script failing saying your `multibranchPipelineJob` does not have a name.
This goes beyond what support we provide.

**Comment by iptizer** [comment]
> That's your groovy script failing saying your `multibranchPipelineJob` does not have a name.
> This goes beyond what support we provide.

I don't think so. As I said, copy&paste the code directly as jobdsl seed job works. So there is no error in the groovy code.

**Comment by jetersen** [comment]
Sorry didn't look to careful to your variable use. Your hitting the Secret Source resolver.

You have either escape using `^${i}` or avoid using `${}` and just reference `$i`

**Comment by njtman** [comment]
> > That's your groovy script failing saying your `multibranchPipelineJob` does not have a name.
> > This goes beyond what support we provide.
> 
> I don't think so. As I said, copy&paste the code directly as jobdsl seed job works. So there is no error in the groovy code.

Did you try adding a `;` to the end of each code line?
For example

```
def scriptpaths = ['one','two'];
```

I've been bitten by this issue before, and it only affects me when using JCasC, not when pasting directly into a seed job.

**Comment by jetersen** [comment]
@njtman as I mentioned it matters with YAML literal you use.

Your best bet is `|` or `|-` again see the https://yaml-multiline.info/

```
jobs:
- script: |
    def scriptpaths = ['one','two']
    for( i in scriptpaths) {
       multibranchPipelineJob("$i") {
          branchSources {
             git {
                   id("$i") // IMPORTANT: use a constant and unique identifier
                   remote('git@xxxxxxxx')
                   credentialsId('cloud-jenkins-ssh-private-key')
                   includes('dev')
             }
          }

          orphanedItemStrategy {
             discardOldItems {
                   numToKeep(20)
             }
          }
       }
    }
```
