### ISSUE TITLE
no relevant demo for github-branch-source-plugin 

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/configuration-as-code-plugin#1427]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [x] Jenkins version 2.222.4
- [x] Plugin version  1.41
- [x] OS  - Kubernetes 1.16
- [x] Reproduction steps  ( check description below)

### Description
------ EXPECTED ----------
![image](https://user-images.githubusercontent.com/1788384/85934976-5e7c7580-b8f3-11ea-96b7-703213943169.png)

I am trying to translate [this configuration][1] (screenshot above) , I made the following attempt : 

```yaml
jobs:
  - script: >
      organizationFolder('toyota') {
        displayName('toyota')
        triggers {
          periodic(86400)
        }
        organizations {
          github {
            repoOwner('toyota')
            credentialsId('github-repos-scanner')
            scanCredentialsId('github-app')
            traits {
              sourceRegexFilter {
                regex('.*')
              }
            }
          }
        }
        configure { node ->
          // node represents <jenkins.branch.OrganizationFolder>
          def traits = node / navigators / 'org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator' / traits
          traits << 'org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait' {
              strategyId('3') // detect all branches
          }
          traits << 'org.jenkinsci.plugins.github_branch_source.SSHCheckoutTrait' {
              credentialsId('creds-git-puller-ssh')
          }
        }
      }
```

I expect to have something like the screenshot above , however, I got two different organizations  : 

------ Actual ----------

![image](https://user-images.githubusercontent.com/1788384/85935013-20cc1c80-b8f4-11ea-9346-3da2dbf73f65.png)

[1]: https://docs.cloudbees.com/docs/cloudbees-common/latest/_images/github-branch-source-screenshots/github-org-projects-tab.f829029.png

**Comment by oleg-nenashev** [comment]
Still valid imho
