### ISSUE TITLE
Variables are substituted in managed bash scripts

### ISSUE THREAD

**Issue by efim-a-efim** [jenkinsci/configuration-as-code-plugin#1429]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version: 2.235.1

- [x] Plugin version: 1.41

- [x] OS: Ubuntu 18.04

### Description

We are using JCasC to deploy Jenkins with some managed Bash scripts (they are stored with Managed files plugin and used in jobs). In our environment we use Hashicorp Vault and integrate it with JCasC as described [here](https://github.com/jenkinsci/hashicorp-vault-plugin#hashicorp-vault-plugin-as-a-secret-source-for-jcasc).

With this configuration JCasC plugin tries to process all bash variables (referenced like `${something}`) and replaces them with empty values. For our case it's an incorrect behavior.

This behavior is generally useful and correct, but I cannot find any mention about how to prevent variables processing. Maybe some kind of escaping is supported?

**Comment by jetersen** [comment]
Yes, escaping is supported by `^`

**Comment by jetersen** [comment]
This is not really a bug this is well documented.

**Comment by adborden** [comment]
👋  I just ran into this myself. I was embedding a Groovy script with `${variables}` and was scratching my head why the usual groovy \${} escapes didn't work. The only reference I found in the docs was the [secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/ebadef8587127ae274940c118763b738a7251152/docs/features/secrets.adoc), which really was the last place I'd look about escaping.

Mind if we re-open this and I submit a PR to update the FAQ?
