### ISSUE TITLE
CASC reload not working after configuration deletion

### ISSUE THREAD

**Issue by janisliepins** [jenkinsci/configuration-as-code-plugin#1438]
- [ 2.235.2] Jenkins version

- [1.42 ] Plugin version

- [Linux - jenkins/jenkins:lts image ] OS

### Description

If i delete existing configuration section from jenkins.yml file and perform configuration as a code reload - configuration is not deleted and is still present with last values specified in jenkins.yml file.

This configuration is added if i define it for the first time or change it - everything works as expected:
```
jenkins:
  systemMessage: "JENKINS"
````

But when i delete this "systemMessage" attribute configuration is still present in Jenkins UI and config.xml:
 ```
jenkins:
  #systemMessage: "JENKINS"
````

Is this expected behavior or bug...?
What would solution would you suggest if i want to delete existing configuration from jenkins.yml and apply this deletion?

**Comment by jetersen** [comment]
this is currently the expected.

The suggestion when using docker/kubernetes is to only persist the jobs.

JCasC has no support for cleaning config.

**Comment by timja** [comment]
you have to do an intermediate step of resetting the config,

```
jenkins:
  systemMessage: ""
```

and then you can remove it

**Comment by janisliepins** [comment]
> The suggestion when using docker/kubernetes is to only persist the jobs.

@jetersen 

Thank you for quick reply.

So with this approach my setup would be Jenkins container with one volume:
`volume:/var/jenkins_home/jobs`

And workflow (if i want to delete some configuration from Jenkins) would be:
1. Delete from jenkins.yml
2. Recreate container

Could you please comment on this more...
As i understand, goal here is to achieve more or less stateless Jenkins

**Comment by maifujalam** [comment]
I am also facing similar issue. Becasuse when I removed docker cloud from CasC and reloaded.Then also docker cloud is showing in UI.This  is a bug.

**Comment by reder9** [comment]
I am also experiencing the same, when I remove a configuration from CasC and reload it still shows in the UI even though its not there in the yaml files. Im able to add things and reload just fine but deletions dont seem to take effect.
