### ISSUE TITLE
make job-dsl optional

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#144]
seed job support is currently implemented relying on job-dsl plugin

This should be optional, and we should offer job creation support out-of-the-box with adequate design from Job types. Typically, organization folders / multibranch Pipelines should be pretty easy to implement [for jenkins essentials](https://issues.jenkins-ci.org/browse/JENKINS-49869).

**Comment by batmat** [comment]
I would love to see this initiative revived. We currently have to install job-dsl in Essentials because of this, and this would be awesome not to have to. Thanks!

**Comment by oleg-nenashev** [comment]
@ewelinawilkosz I agree with @batmat , it is a serious issue for some configurations. Would it be fine if I add it to the 1.0 release scope?

In the worst case we can make the JobDSL code as a submodule/separate plugin now

**Comment by ewelinawilkosz** [comment]
sure!

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/issues/197 supersede this issue, but we still can make it optional in the meantime

https://github.com/jenkinsci/configuration-as-code-plugin/pull/289
