### ISSUE TITLE
Jenkins startup fails with unreachable configurationPath

### ISSUE THREAD

**Issue by bradleycherrin** [jenkinsci/configuration-as-code-plugin#1449]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.235.3
- [x] Plugin version
1.43
- [x] OS
debian

### Description

As reported in [JENKINS-58629](https://issues.jenkins-ci.org/browse/JENKINS-58629) Jenkins startup fails when the configuration is unknown or invalid.  It would be better to handle these with warnings as to not prevent Jenkins from starting if an old configuration was not removed or was unreachable.

I don't mind personally working on this as it has been an issue in my free time since we have hit this in our developer community a number of times

**Comment by amuniz** [comment]
I think this should be an option in the yaml file (or some sort of environment configuration). Think of security, if there is an issue configuring security then I might want Jenkins to not start (instead of starting unsecured). So I think this should be something the user should be able to decide.

**Comment by timja** [comment]
It already is an option: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/test-harness/src/test/resources/io/jenkins/plugins/casc/impl/configurators/SelfConfiguratorTest.yml

**Comment by amuniz** [comment]
Ah, cool :+1: 
Then I think this can be closed, @bradleycherrin?

**Comment by bradleycherrin** [comment]
@amuniz that looks sufficient, yes will close
