### ISSUE TITLE
Failed Loading all plugins after installing configuration-as-code-plugin with Jenkins 2.235 till 2.253

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/configuration-as-code-plugin#1451]
## jenkins version:  
 
- image repo: docker.io/jenkins/jenkins
- tag : 2.235 or 2.253 (issue happen with both.. not tested with other versins)

## Jenkins plugins
Helm installs this list of plugins

```yaml
    # - kubernetes:1.25.7
    # - blueocean:1.23.2
    # - workflow-job:2.39
    # - workflow-aggregator:2.6
    # - credentials-binding:1.23
    # - git:4.2.2
    # - crowd2:2.0.2
    # - role-strategy:3.0 # transitive to matrix-auth
    # - job-dsl:1.77
    # - bitbucket-build-status-notifier:1.4.2
    # - bitbucket:1.1.11
    # - cloudbees-bitbucket-branch-source:2.8.0
    # - simple-theme-plugin:0.6
    # - jira-steps:1.6.0
    # - pipeline-utility-steps:2.6.1
```

Everything is working like a charm with these plugins.

When, I added `configuration-as-code:1.43`, Helm upgrade fails and logs of jenkins show the following errors : 
 
```
2020-08-24 07:48:17.967+0000 [id=27]  SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin JUnit Plugin v1.31 (junit)
java.io.IOException: Failed to load: JUnit Plugin (1.31)
 - Update required: Script Security Plugin (1.70) to be updated to 1.73 or higher
 - Update required: ECharts API Plugin (4.6.0-8) to be updated to 4.7.0-4 or higher
  at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
...
.....

2020-08-24 07:48:17.972+0000 [id=27]  SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Groovy v2.82 (workflow-cps)
java.io.IOException: Failed to load: Pipeline: Groovy (2.82)
 - Update required: Script Security Plugin (1.70) to be updated to 1.71 or higher
  at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
  at hudson.PluginManager$2$1$1.run(PluginManager.java:549
.....
```

I've tried also to downgrade to `configuration-as-code:1.43` . However, the same issue.

# Steps to reproduce : 

- Install jenkins with version mentioned above
- Install Plugins from list mentioned above

It works before.. Not sure what happen .
Howevere, I have doubt in script-security versions conflicts as a transitive plugin.

# More 

During troubleshooting ( adding/removing plugins), I am provisioning the environment from scratch. (`helm delete`, then `helm install`). 

I am doing that to make sure there is no cache.

**Comment by timja** [comment]
This is nothing to do with the configuration as code plugin

Looks like you should include the script security and echarts api plugins in your list with the right versions.

transitive dependencies are being pulled in with old versions.

**Comment by jetersen** [comment]
Not a JCasC plugin issue, upgrade your plugins as stated in the exception.
