### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#146]
I would like a guide on how to contribute with issues and pull requests. Also tips for developing the code.

**Comment by casz** [comment]
Already there: 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/howToContribute.md

**Comment by oleg-nenashev** [comment]
a common name like CONTRIBUTING.md in the root would help for sure

**Comment by casz** [comment]
well docs/CONTRIBUTING.md should do the trick too 👍

**Comment by ewelinawilkosz** [comment]
we already have an issue for that - #33 and I will follow @casz advice to implement it as CONTRIBUTING file 
so I will allow myself to close this one, please follow up on #33 if you're interested about the progress, we're planning to fix documentation in upcoming weeks

**Comment by casz** [comment]
@martinmosegaard as for tips 
https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial

useful for updating other plugins to support code as configuration plugin:
https://jenkins.io/doc/developer/plugin-development/pipeline-integration/

**Comment by ewelinawilkosz** [comment]
also both https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/IMPLEMENTATION.md and https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/PLUGINS.md contain some useful information for contributors

**Comment by casz** [comment]
perhaps this should be apart of the updated contributing.md? 😄

**Comment by ewelinawilkosz** [comment]
it will :)
