### ISSUE TITLE
Cleanup obsolete "slave" and "master" terminology from JCasC demos and docs

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#1465]
The Jenkins project now uses "agent"and "controller" as official terms. See https://issues.jenkins-ci.org/browse/JENKINS-42816 and https://groups.google.com/forum/#!topic/jenkinsci-dev/CLR55wMZwZ8 for the reference. There are some occurrences which could be cleaned up:

* Docker image names
* Configuration entries for plugins which now support "agent"/"controller" aliases. 
* Documentation text

There is no need to submit all patches in a single pull request. Contributors can cleanup terminology incrementally and submit smaller PRs.

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Jenkins version: N/A
- [ ] Plugin version: N/A
- [ ] OS: N/A

### Description

Please describe your issue here.

**Comment by spielers** [comment]
@oleg-nenashev I would like to work on this issue. I have pretty much-working knowledge of  documentation I will be happy to work on

**Comment by eshack94** [comment]
I'm also interested in helping with this. In an effort to keep the PRs small and manageable, is it okay to submit documentation PRs first?

**Comment by oleg-nenashev** [comment]
Sorry for missing comments @spielers @eshack94 , my GitHub notification inbox was flooded :( Next time please do not hesitate to just take the issue and start working on that, I check my review dashboard almost every day
