### ISSUE TITLE
 For SonarQube plugin, 'serverAuthenticationToken' is not working

### ISSUE THREAD

**Issue by aamirmalek** [jenkinsci/configuration-as-code-plugin#1473]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Jenkins version

- [ ] Plugin version

- [ ] OS

### Description

Please describe your issue here.

In the https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/sonarqube, the 'serverAuthenticationToken' is not working but the 'credentialsId' is working. 

change your document or change the code.

**Comment by jetersen** [comment]
Feel free to submit a pull request for updating the documentation.

**Comment by jetersen** [comment]
Note the comments in the example are clearly mentioning the version compatibility.
