### ISSUE TITLE
Unclear docs for multiple configuration files

### ISSUE THREAD

**Issue by shoffmeister** [jenkinsci/configuration-as-code-plugin#1480]
The documentation alludes to the plugin being able to handle multiple configuration files: "folder containing a set of config files"

If I read the code and Java documentation right, then "the plugin will perform a depth-first traversal of the directory specified, following symbolic links, but ignoring all dot files or dot directories it may encounter. All configuration files will be processed and merged in the lexicographical order of their (complete) path."

Two aspects (in one issue entry - ha!):
a) The above should actually be mentioned in the docs - it's not exactly blindingly obvious, and I don't like making decisions on how to nicely structure configuration on gut feeling ...

b) "lexicographical" has two problems: 
b1) Windows and Unix have a different appreciation of what that means, given the same culture
b2) lexicographical is culture-sensitive, so funky non-ASCII characters may have different sort order depending on current locale settings

Given that CasC is all about "perfect" reproducibility (IMHO), that may be relevant or not.

Not sure how to proceed from here; creating docs on the existing implementation is nice and well; begs the question whether the implementation is working as intended ...

*******************

https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L650

https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/file/Files.html#find(java.nio.file.Path,int,java.util.function.BiPredicate,java.nio.file.FileVisitOption...)

https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/file/Files.html#walk(java.nio.file.Path,int,java.nio.file.FileVisitOption...)

https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/io/File.html#compareTo(java.io.File)

**Comment by benjaoming** [comment]
Thanks for opening this, I just had the same issue. My very first problem encountering this plugin is as follows: I need to add a modular configuration to an already existing default configuration. This is done through Ansible.

I would think the following conf.d-like structure is what we would like to have:

```
casc_configs/00-defaults.yml
casc_configs/99-important-overrides.yml
```

But both the docs and the code is unclear about exactly the precedence and handling of file names.

Can two .yml files configure the same item? If they do, what is the expected outcome?

**Comment by benjaoming** [comment]
> Can two .yml files configure the same item? If they do, what is the expected outcome?

Empirically answering my own question: The outcome will be an exception. So -- for now -- there is no relevant notion of precedence.

```
io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/lib/jenkins/casc_configs/jenkins.yaml  in /var/lib/jenkins/casc_configs/jenkins.yaml, line 31, column 16:
    quietPeriod: 5
                 ^
```

It could however, rather than advertising in the docs a _path to a folder containing a set of config files_, be noted that multiple configuration files cannot overwrite each other's configuration items, this will be considered an invalid configuration.
