### ISSUE TITLE
More examples in demos/jobs/bitbucket.yaml

### ISSUE THREAD

**Issue by lpl-hosting** [jenkinsci/configuration-as-code-plugin#1491]
Hi everyone,

I've added some extra examples in demos/jobs/bitbucket.yaml :
https://github.com/lpl-hosting/configuration-as-code-plugin/commit/54f29841b11415132117091a8e34c3b7d54e4299

It should help with bitbucket's casc integration :)

I can launch a PR if needed :P

**Comment by jetersen** [comment]
Next time simply open the PR 😕

**Comment by lpl-hosting** [comment]
done
