### ISSUE TITLE
Verify JUnit plugin compatibility

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#15]
https://plugins.jenkins.io/junit

**Comment by ndeloof** [comment]
which junit configuration attribute would you like to configure ?

**Comment by ewelinawilkosz** [comment]
well, that's embarrassing... I just went for plugins that are most often installed without checking if they have any global configuration and it looks like JUnit may be one those which has not :|

**Comment by ndeloof** [comment]
ok, no worries, just checking :P
