### ISSUE TITLE
Subversion plugin setting does not reflected at the configuration.

### ISSUE THREAD

**Issue by gek-mcfh** [jenkinsci/configuration-as-code-plugin#1516]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.249.2
- [x] Plugin version
1.44
- [x] OS
linux

### Description

Subversion plugin setting `Subversion Workspace Version` does not reflected at the configuration.

**Comment by jetersen** [comment]
Usually that is not a bug in JCasC but a bug in the plugin which is lacking a maintainer.

**Comment by jetersen** [comment]
Subversion plugin is not following Jenkins databinding standards.
https://github.com/jenkinsci/subversion-plugin/blob/8e2a71ab256903d5c0a15b6ab0f964206ad5e72d/src/main/java/hudson/scm/SubversionSCM.java#L2178-L2189

Which are also documented here in JCasC.
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

**Comment by jetersen** [comment]
Pull request is even open for the issue: https://github.com/jenkinsci/subversion-plugin/pull/229
