### ISSUE TITLE
Allow to keep manually maintained credentials next to the ones maintained via yaml

### ISSUE THREAD

**Issue by kwin** [jenkinsci/configuration-as-code-plugin#1524]
Currently if I manually add a credential (no matter if global domain or new domain) it is cleared after I click on `Reload existing configuration` in `/configuration-as-code/`.
I found nothing on how existing configuration is supposed to be merged with the configuration provided as yaml in the documentation. But in the case of credentials is is sometimes desirable to allow credentials next to the ones being maintained in the configuration file.

**Comment by timja** [comment]
This is functionality is provided by the credentials plugin, please create an issue on jira for it https://issues.jenkins-ci.org/

**Comment by kwin** [comment]
@timja Thanks for the hint. For the record: I opened https://issues.jenkins-ci.org/browse/JENKINS-64079.
