### ISSUE TITLE
I need to be able to load jenkins.yml from an URI

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#153]
Apparently we can't load the `jenkins.yml` from an URI anymore which is what I need at the moment to get it from a repository.
Alternatively I accept git repository polling if that is better to implement.

Once we could point `CASC_JENKINS_CONFIG` to for example raw.github.com something.

**Comment by buep** [comment]
@ewelinawilkosz I need that for our demo instance - couldn't @MadsNielsen spend his time on that instead of #34 ?

**Comment by ewelinawilkosz** [comment]
"Alternatively I accept git repository polling if that is better to implement." - we'll want it at some point so I would prefer to implement that instead of support for raw file now... and I see that issue as a part of #34, perfectly ok with @MadsNielsen working on that

**Comment by buep** [comment]
That is fine, but I need something working now that is not loading from a local file, so could we get #34 finished then instead? I was expected URI load to still work.

**Comment by ewelinawilkosz** [comment]
Me too, but it got messed up at some point and @MadsNielsen was looking into that - that's why he's assigned in #34... we need to have complete solution at some point but I am perfectly ok with doing it with small steps, so we can prioritise the one you need the most now

**Comment by buep** [comment]
Need for our demo setup https://github.com/Praqma/praqma-jenkins-casc/issues/8.

**Comment by MadsNielsen** [comment]
Done!

**Comment by casz** [comment]
@MadsNielsen I would prefer you follow the convention as stated in the [CONTRIBUTING.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CONTRIBUTING.md#regarding-source-code-contribution-wow) it does say
> !! Never push directly to this repository

**Comment by MadsNielsen** [comment]
@casz Generally that is true. I did however ask the owner @ewelinawilkosz before doing this. The commit is also low risk so i got the go ahead for doing it.

**Comment by ewelinawilkosz** [comment]
thanks for pointing that out @casz 
yes, we have the rules and we try to follow them also, both me and @MadsNielsen :)
in some rare special cases we skip some steps to avoid unnecessary overhead, shouldn't happen but real life...

**Comment by casz** [comment]
low risk yet you managed to add two star imports and it required two additional commits to resolve issues with.
https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports
https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fcodestyle%2Fref-preferences-organize-imports.htm

The problem when looking at: https://github.com/jenkinsci/configuration-as-code-plugin/commits/master it seems to be the norm that you are committing directly to the repo.

**Comment by daniel-beck** [comment]
Sad to see this was apparently done outside a pull request.

I surely would have pointed out that https://github.com/jenkinsci/configuration-as-code-plugin/commit/bdfde2072cc2f2e8f28459d7defe276972d1dd88#diff-d3e792f22472bc61485d4bdf80787a8dR121 is not a good idea.

**Comment by ewelinawilkosz** [comment]
we had a discussion about it today - somewhere it seems that PR is just to much overhead but as we can see you never know... lesson learned!

**Comment by MadsNielsen** [comment]
@daniel-beck Point taken. I must admit i did this in a rush to get a use case we could demonstrate to a potential customer as having to mount in a file to a docker container to read it was a blocker for us. As such we bypassed the usual process. 

In retrospective it wasn't a good idea and we'll avoid doing it in the future, and looking at the line you pointed to, i can already see what should be changed, while looking back at our previous discussions. :-) 

Our focus for the next few weeks will be to create demo setup, with seed jobs, pipelines and a few key plugins configure, so we can showcase c-as-c to potential users of this plugin and continue improving the existing documentation.
