### ISSUE TITLE
Unable to set permissions

### ISSUE THREAD

**Issue by benkeil** [jenkinsci/configuration-as-code-plugin#154]
I try to set the "Item/Read" ("Element/Read") permission, but I get always `Mar 21, 2018 2:02:47 PM org.jenkinsci.plugins.casc.integrations.globalmatrixauth.GroupPermissionDefinition grantPermission
WARNING: Ignoring unknown permission with id: 'Item/Read'`

Any ideas?

**Comment by ewelinawilkosz** [comment]
can you post the piece of yaml you use to configure authorizationStrategy?

**Comment by benkeil** [comment]
`authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - name: IPG.TechTeam
          permissions:
            - Overall/Read
            - hudson.model.Item.Read
            - Item/Read
            - Item/Build
            - Item/Cancel
            - Item/Discover
            - Item/Workspace`

**Comment by MadsNielsen** [comment]
@benkeil The names must follow the UI. That means that Item -> Job. And hudson.model.item.Read won't work.

It's done because the form only ever submits class names which do not match the ui.

**Comment by benkeil** [comment]
The only thing that work is „Overall/Read“. In the GUI I see no Job item.

**Comment by benkeil** [comment]
But "Job/Read" works, thank you. Is that somewhere documented?

**Comment by MadsNielsen** [comment]
@benkeil We'll see if we can update it. But i see lots of `Job`persmissions. For instance this is how it looks on our instance.

![items](https://user-images.githubusercontent.com/1484793/37819670-8e80929a-2e7e-11e8-8b21-72ad62d6ac2e.png)

**Comment by ndeloof** [comment]
implemented in https://github.com/jenkinsci/matrix-auth-plugin/pull/48
