### ISSUE TITLE
Jenkins won't be able to start if JCasC sources is missing

### ISSUE THREAD

**Issue by NagleZhang** [jenkinsci/configuration-as-code-plugin#1544]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] None

### The Problem I'm facing 
I've try to migrate an other configuration to new jenkins   
after migration , if i delete the configration. Jenkins instance won't be able to restart becasue of io.FileNotFound Exception .

What I can do is recover the configuration file , and restart jenkins again. then execute code below: 
```
import io.jenkins.plugins.casc.CasCGlobalConfig
CasCGlobalConfig config = GlobalConfiguration.all().get(CasCGlobalConfig.class)
config.setConfigurationPath(null)
config.save()
```
I can not image what happend if I lost my configuration. 

### Feature Request

1. able to delete & update Configuration Source 
2. Jenkins can start normally even if Configuration Source is missing .

**Comment by timja** [comment]
if you delete the configuration you also need to delete the file on disk which has the configuration path

**Comment by NagleZhang** [comment]
what if the path is a URL ?

**Comment by NagleZhang** [comment]
> if you delete the configuration you also need to delete the file on disk which has the configuration path

What if the path is a URL ?

**Comment by jetersen** [comment]
Delete the config file for JCasC or use `CASC_JENKINS_CONFIG` change the config without messing with files.

The reason for JCasC not starting up is by design, as you would not want a instance running that is incorrectly configured.

**Comment by NagleZhang** [comment]
I've try to delete config file & unset environment `CASC_JENKINS_CONFIG`.
which cause the problem , says no file exists.

**Comment by jetersen** [comment]
We config file that you should be deleting is `io.jenkins.plugins.casc.CasCGlobalConfig.xml` at should be located at `$JENKINS_HOME`

**Comment by NagleZhang** [comment]
I got it, thanks a lot.
