### ISSUE TITLE
Add possibility to reload secrets from properties file with JCasC reload

### ISSUE THREAD

**Issue by tempora-mutantur** [jenkinsci/configuration-as-code-plugin#1555]
### Feature Request

Hi

We have a wonderful possibility to resolve secrets via .properties file in the plugin

https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#using-properties-file

https://github.com/jenkinsci/configuration-as-code-plugin/blob/25b26febfc4aa01ec0abde0295763475f7ffee4b/plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/PropertiesSecretSource.java#L38

And it seems that it's using lazy initialization so if the properties file is changed like some existing secret value is updated with a new value and if we reload JCasC configuration we won't have updated values in Jenkins.

It would be nice to have such option.

Thank you.

**Comment by jetersen** [comment]
easily implemented by using the `init` method that is called on each secret source.
