### ISSUE TITLE
Default value for env variables

### ISSUE THREAD

**Issue by lanwen** [jenkinsci/configuration-as-code-plugin#156]
For local debug it will be convenient to specify smth like:
```
    : - usernamePassword:
            scope: GLOBAL
            id: bot-creds
            username: bot-sender
            password: ${BOT_SENDER_TOKEN:-unsecured-token}
```

this will help to avoid startup fails because of missing secrets

**Comment by ewelinawilkosz** [comment]
I'm missing that too :)

**Comment by casz** [comment]
fixed in #237 so we can close this

**Comment by jcrben** [comment]
Seems like this needs documentation?

**Comment by casz** [comment]
@jcrben there is plenty of docs on parameter substitution: `${parameter:-default}` https://www.tldp.org/LDP/abs/html/parameter-substitution.html

Yes we only support parameter substitution for default.

**Comment by jcrben** [comment]
Oh, I'm pretty familiar with parameter substitution 😄 

but I shouldn't have to search the Github issues (or blindly enter stuff I'm not sure will work) to see if it's supported...

**Comment by ndeloof** [comment]
yes we clearly miss some doc, you're welcome to contribute if you have some spare cycles :)
