### ISSUE TITLE
Support "Preventive Node Monitoring"

### ISSUE THREAD

**Issue by almiroshnich** [jenkinsci/configuration-as-code-plugin#1565]
### Feature Request
This configuration is available from UI at `<base url>/computer/configure`
![image](https://user-images.githubusercontent.com/4091725/106894185-4b3a4f80-66f7-11eb-97b1-4b477f446485.png)

It would be nice to have that configuration supported by JCasC

**Comment by jetersen** [comment]
This is not a feature request for this repo.
Please raise the issue with the preventive node monitoring plugin.
Or perhaps this is part of Jenkins core?

**Comment by almiroshnich** [comment]
Created https://issues.jenkins.io/browse/JENKINS-64816

Thanks!
