### ISSUE TITLE
secrets.properties not being loaded

### ISSUE THREAD

**Issue by reasland** [jenkinsci/configuration-as-code-plugin#1570]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

Jenkins Version: 2.263.4
Plugin Version : 1.47
OS: CentOS

Please describe your issue here.

Creating a secrets.properties file in /run/secrets

Attempting to load secrets into credentials by specifying 

### jenkins.yaml

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "jenkinsadmin"
          description: "creds for use by jenkins agents"
          scope: GLOBAL
          username: "jenkinsadmin"
          password: "${jenkinsadmin_password}"

### secrets.properties

jenkinsadmin_password=abc123

Receiving log:
Feb 17, 2021 7:27:35 AM WARNING io.jenkins.plugins.casc.SecretSourceResolver$UnresolvedLookup lookup
Configuration import: Found unresolved variable 'jenkinsadmin_password'. Will default to empty string

**Comment by jetersen** [comment]
have you checkedthe the file is readable? We have tests that say it is working.

**Comment by reasland** [comment]
my bad, turns out im an idiot
set perms 777 on secrets.properties, but it looks like parent directory was too closed
