### ISSUE TITLE
Supporting  atlassian-bitbucket-server-integration plugin

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/configuration-as-code-plugin#1572]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

This is the official plugin that supports integration with Bitbucket Server.
This is the official because it's provided by Atlassian team.

I would like to share with you some materials, so the config-as-code can be implemented quickly: 

- https://plugins.jenkins.io/atlassian-bitbucket-server-integration/
- https://marketplace.atlassian.com/apps/1222132/jenkins-integration-for-bitbucket-server?hosting=server&tab=overview
- https://youtu.be/0-FugzVYJQU
- https://youtu.be/LY3zPgRr8no

Thank you

**Comment by jetersen** [comment]
This is a atlassian-bitbucket-server-integration plugin issue not a JCasC issue.

**Comment by abdennour** [comment]
Thank you @jetersen 
Your comment/ Your guide is helpful.
What do you prefer ? should i keep this therad open ?
