### ISSUE TITLE
CasC Vault source not working 

### ISSUE THREAD

**Issue by jaekunchoi** [jenkinsci/configuration-as-code-plugin#1587]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

* Jenkins version 2.263.4 
* JCASC version 1.46
* hashicorp-vault-plugin:3.7.0 
* Redhat 7 Docker
CasC Vault source with CASC_VAULT_FILE doesn't load. I have defined below in the file:
```
CASC_VAULT_TOKEN=VAULT_TOKEN
CASC_VAULT_PATHS=/dev/jenkins
CASC_VAULT_URL=VAULT_ADDR
CASC_VAULT_ENGINE_VERSION=2
```

All I get is

```
WARNING	i.j.p.c.SecretSourceResolver$UnresolvedLookup#lookup: Configuration import: Found unresolved variable 'password'. Will default to empty string
```

I don't get any Vault log entries. Is there anything wrong here?

**Comment by jetersen** [comment]
belongs to the repo hashicorp-vault-plugin, where you already have created an duplicate issue, so closing this issue.
