### ISSUE TITLE
JCASC is creating two organization when ForkPullRequestDiscoveryTrait is invoked

### ISSUE THREAD

**Issue by qalinn** [jenkinsci/configuration-as-code-plugin#1599]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x ] Jenkins version: 2.277.4

- [ x] Plugin version 1.50

- [ ] OS

### Description

Hello, 
I am trying to use jcasc plugin to configure Github Organization  folder. Everything works well excepting ![image](https://user-images.githubusercontent.com/6930622/117470447-1ab4bc80-af57-11eb-8b09-5e4e84f4b2b5.png). 
I try like this:
```
organizationFolder('MyOrgFolder') {
    description("My github organization folder")
    displayName('My Projects')
    organizations {
        github {           
            repoOwner("github_owner")
            apiUri("https://api.github.com")
            credentialsId("GITHUB_USERNAME")
            traits {
                submoduleOptionTrait {
                    extension {
                        disableSubmodules(false)
                        recursiveSubmodules(true)
                        trackingSubmodules(true)
                        reference(null)
                        threads(3)
                        timeout(15)
                        parentCredentials(true)
                    }
                }
                gitHubBranchDiscovery {
                    strategyId(1)
                }
                gitHubPullRequestDiscovery {
                    strategyId(1)
                }
                sourceRegexFilter {
                    // A Java regular expression to restrict the project names.
                    regex("test*")
                }
                wipeWorkspaceTrait()
            }
        }
    }
    // "Project Recognizers"
    projectFactories {
        workflowMultiBranchProjectFactory {
            scriptPath 'Jenkinsfile'
        }
    }
    // "Orphaned Item Strategy"
    orphanedItemStrategy {
        discardOldItems {
            daysToKeep(30)
            numToKeep(-1)
        }
    }
    configure { node ->
        node / triggers / 'com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger' {
            spec('H H * * *')
            interval(86400000)
        }

        **def traits = node / navigators / 'org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator' / traits
        traits << 'org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait' {
          strategyId(3)
          trust(class: 'org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait$TrustPermission')
        }**
    }
}
```

The problem is that when the job is running are created two github organizations as follow: 
The first one is created according with the  job dsl description excepting the ForkPullRequestDiscoveryTrait. This trait is not added.
The second organization is added and all fields are empty and the behaviour for  ![image](https://user-images.githubusercontent.com/6930622/117470447-1ab4bc80-af57-11eb-8b09-5e4e84f4b2b5.png) is added and set as in the job dsl.

![Screenshot 2021-05-07 at 17 04 50](https://user-images.githubusercontent.com/6930622/117470251-e3dea680-af56-11eb-82c1-41ac722b0734.png)

**Comment by timja** [comment]
This is not jcasc but jobdsl, I think there's an `id(121212)` attribute where you need to set a static ID so you get the same one each time.

But I'm not an expert and this isn't the right place

**Comment by qalinn** [comment]
@timja  the id is not available for github organization folder. I already tried

**Comment by timja** [comment]
This is what I use https://github.com/hmcts/cnp-jenkins-config/blob/bc85e05b3b677b8854749f72470477a493059efe/jobdsl/organisations-beta.groovy#L115

**Comment by qalinn** [comment]
@timja  thank you for the example, but  you don't have ForkPullRequestDiscoveryTrait in the example.
Could you try to add ForkPullRequestDiscoveryTrait just to see if the issue is reproducible? 
also, I found a similar issue here: https://github.com/jenkinsci/configuration-as-code-plugin/issues/1427
Please don't close the issue. I am not sure if the issue is coming from jobdsl plugin.

**Comment by timja** [comment]
jcasc has nothing to do with jobs other than running it

Another example here: https://github.com/jenkins-infra/charts/blob/master/config/default/jenkins-infra.yaml#L308
