### ISSUE TITLE
Verify Matrix Authorization Strategy plugin compatibility

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#16]
https://plugins.jenkins.io/matrix-auth

**Comment by ewelinawilkosz** [comment]
Moved from incorrect issue: matrix plugin is being configured under 'Configure Global Security' page, not 'Configure System,' and I can't find matrix plugin at the list of discovered configurators (descriptors), no global.jelly file also - @ndeloof can you confirm it is an issue now or is there already a solution I simply can't find?

**Comment by ndeloof** [comment]
should be configured the same way as LDAP plugin

```yaml
jenkins:
    authorizationStrategy: 
        globalMatrix:
            ...
```

But https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java#L171 does not rely on a DataBoundConstructor (sic). Would need to prepare a PR for this one to use the standard mechanisms.

**Comment by buep** [comment]
my colleague @MadsNielsen is working on this he said .... so assigning him.

**Comment by oleg-nenashev** [comment]
FYI I am working on #48, which may have more or less similar implementation.

**Comment by MadsNielsen** [comment]
@oleg-nenashev That's great, i might steal some stuff for inspiration. For me, this is a rather large task so i might glean on some of the stuff you do for inspiration.

**Comment by oleg-nenashev** [comment]
@MadsNielsen OK, Role Strategy support has landed in the master. For Matrix Auth support please also request review from @daniel-beck

**Comment by MadsNielsen** [comment]
@ewelinawilkosz I believe this can be closed.
