### ISSUE TITLE
JcasC does not remove deleted config settings

### ISSUE THREAD

**Issue by github-reader** [jenkinsci/configuration-as-code-plugin#1606]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.277.3 LTS

- [x] Plugin version 1.51

- [x] OS Ubuntu 18.04

### Description

JCasC updates configuration changes when I add a object, e.g. a user with permissions. It does not remove this object from Jenkins when I delete it from JCasC configuration file. Is this normal behaviour or a bug?

**Comment by timja** [comment]
normal behaviour, you need to reset it to the default first and then remove it from your configuration file, jcasc is stateless.
