### ISSUE TITLE
How do I add nice descriptions for my plugin's configuration properties?

### ISSUE THREAD

**Issue by akaryakina** [jenkinsci/configuration-as-code-plugin#1631]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [x ] Jenkins version
- [ x] Plugin version
- [ x] OS
- [ x] Reproduction steps

### Description

Hi folks, how do I add/customize descriptions for configuration elements of my plugin that are displayed at <host:port>/jenkins/configuration-as-code/reference (or <host:port>/jenkins/configuration-as-code/schema)? I tried searching the Gitter chanel, anywhere around the Internet, tried to analyze what was different in the latest Jenkins's code that made them  be generated for some of the properties, but in vain. It feels like it's using the help htmls' contents, but only for some properties, and not for the others. Could you please help me (and ideally - document it somewhere for future references of other strugglers)?

**Comment by jetersen** [comment]
same with all other plugins configure help via jelly help resources:
https://github.com/jenkinsci/git-plugin/blob/master/src/main/resources/jenkins/plugins/git/GitStep/help.html
https://github.com/jenkinsci/git-plugin/blob/master/src/main/resources/jenkins/plugins/git/GitStep/help-branch.html

**Comment by akaryakina** [comment]
Well, that's the point, it doesn't work for me. I have a global.jelly file that has:
    <j:jelly xmlns:j="jelly:core" xmlns:f="/lib/form">
        <f:section title="My Plugin Config">
            <f:entry title="MyParam" help="/plugin/myplugin/help-myparam.html" description="MyParam description">
                <f:textbox name="param" field="param"/>
            </f:entry>
        </f:section>
    </j:jelly>
And I don't see any description from either help or description rendered in reference or schema documentation for configuration-as-a-code. Is there anything else that is required?

**Comment by jetersen** [comment]
You should not type the path to the help.
You follow the convention as shown here
https://github.com/jenkinsci/git-plugin/blob/master/src/main/resources/hudson/plugins/git/GitSCM/global.jelly
https://github.com/jenkinsci/git-plugin/tree/master/src/main/resources/hudson/plugins/git/GitSCM
Where help-parameterName.html is used

**Comment by akaryakina** [comment]
Well... Thanks, but it seems like gitSCM example you provided also does not have any descriptions rendered. 
I installed the plugin, and here's the schema that I get generated by Configuration As A Code:
```
"gitSCM": {
                    "additionalProperties": false,
                    "type": "object",
                    "properties": {
                        "globalConfigEmail": {
                            "description": "",
                            "type": "string"
                        },
                        "allowSecondFetch": {
                            "description": "",
                            "type": "boolean"
                        },
                        "disableGitToolChooser": {
                            "description": "",
                            "type": "boolean"
                        },
                        "showEntireCommitSummaryInChanges": {
                            "description": "",
                            "type": "boolean"
                        },
                        "addGitTagAction": {
                            "description": "",
                            "type": "boolean"
                        },
                        "createAccountBasedOnEmail": {
                            "description": "",
                            "type": "boolean"
                        },
                        "hideCredentials": {
                            "description": "",
                            "type": "boolean"
                        },
                        "useExistingAccountWithSameEmail": {
                            "description": "",
                            "type": "boolean"
                        },
                        "globalConfigName": {
                            "description": "",
                            "type": "string"
                        }
                    }
                }
```
Note all the "description": "" values. However, some other contributions made to the configuration have descriptions:
```
                "phabricator": {
                    "additionalProperties": false,
                    "type": "object",
                    "properties": {
                        "repoUrl": {
                            "description": "Specify the phabricator instance root URL (such as http://phabricator.example.com).",
                            "type": "string"
                        },
                        "repo": {
                            "description": "Specify the repository name in phabricator (such as the foo part of phabricator.example.com/diffusion/foo/browse).",
                            "type": "string"
                        }
                    }
                },
```
I'm afraid I can't figure out what's different. Is it true that help messages from global.jelly just never get rendered as a description?
