### ISSUE TITLE
Intermittent issues pulling secrets from aws secrets manager

### ISSUE THREAD

**Issue by cwiggs** [jenkinsci/configuration-as-code-plugin#1632]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version

- [X] Plugin version

- [X] OS

### Description

Jenkins version: 2.263.1
Plugin version: 1.51
OS: Amazon Linux (container)

I've setup JCasC to pull secrets from aws secrets manager (specifically to setup Active directory as auth into Jenkins) and it was working great.  However after looking at it a bit more it looks like it works some of the time and others it throws this error:

```
FATAL: com.amazonaws.services.secretsmanager.model.AWSSecretsManagerException: null (Service: AWSSecretsManager; Status Code: 403; Error Code: null; Request ID: null; Proxy: proxy.example.org)
```

I'm pulling the config.yml from s3 so I've verified the IAM bucket policy is correct.  I've also verified Jenkins has the proper IAM policy to pull from aws secrets manager, and I've verified the proxy is not causing issues.  Plus, like I said it works some of the time.  Any idea why this might be happening?

**Comment by jetersen** [comment]
This is not a JCasC plugin problem. You should reach out to AWS plugin which provides this feature.
