### ISSUE TITLE
Extensibility: Review Extension point API, improve error propagation

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#164]
Currently the plugin offers two extension points: `SecretSource` and `Configurator`. The first one looks good, but after developing several implementations for configuration I feel that the API could be improved a bit before the public release.

* Add Javadocs for methods which are expected to be used by developers
* Improve error propagation
  * `public abstract T configure(Object config) throws Exception` - throwing Exceptions is a bad design pattern, because it requires API users to handle all possible kinds of exceptions, including runtime ones. It gives too much flexibility to plugin developers.
  * It would be better to have a more generic `ConfiguratorException extends IOException` or so, which would allow to passing information via a standard type, maybe with common metadata like Configurator reference. It would simplify the code and allow reporting issues with more details in logs/UIs
  * Other abstract/overridable methods could benefit from the same
* Add annotations to facilitate FindBugs static analysis in plugins
  * Methods like `getTarget()`/`getExtensionPoint()`do not have nullability annotations. As an Extension Point implementation developer, it would not be clear whether I am allowed to return null and what would be the behavior in the plugin

Pretty same concerns apply to the internal codebase, but it's really important to have well-defined APIs before 1.0 so that plugin developers can easily create their own implementations.

**Comment by ndeloof** [comment]
I don't share your PoV about throwing Exceptions but I'm fine with that if you consider this a requirement.

**Comment by oleg-nenashev** [comment]
Yeah, Exceptions is a holywar topic for sure. Let's discuss it a bit more before merging #165. I consider it as a "requirement", but it does not mean that other contributors agree with me. And I am not even the plugin maintainer, so generally it's a decision for you, @ewelinawilkosz and @MadsNielsen 

OTOH #165 revealed some error propagation things while refactoring the API. That's why I prefer strongly-typed checked exceptions. But yes it makes the code more heavy and enterprise-ish.

**Comment by ewelinawilkosz** [comment]
we (me and Mads) will have a look tomorrow!

**Comment by MadsNielsen** [comment]
@ewelinawilkosz Yep let's talk tomorrow and go through this change. @oleg-nenashev  Generally i'm ok with this type of refactoring. Since Java forces checked exceptions on us, better to create the specific exception with more information attached. One thing i generally include in a message is to include a URL to a help resource, so that the user can quickly browse to troubleshoot the issue if we have some kind of database of common issues.
