### ISSUE TITLE
Support shared libary

### ISSUE THREAD

**Issue by AssafKatz3** [jenkinsci/configuration-as-code-plugin#1647]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Maybe I missed it, but I couldn't find anyway to configure shared library as part of configuration.

Thanks

**Comment by timja** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/workflow-cps-global-lib

**Comment by aaron-michaux** [comment]
The above comment needs updating because the link 404s.

**Comment by lemeurherve** [comment]
@aaron-michaux here is the new link: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/pipeline-groovy-lib
