### ISSUE TITLE
Allow users with Overall/Manage permission to reload existing configuration

### ISSUE THREAD

**Issue by quilicicf** [jenkinsci/configuration-as-code-plugin#1652]
### Your checklist for this issue

- [x] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Allow users with [Overall/Manage](https://www.jenkins.io/doc/book/security/access-control/permissions/) permission to reload the existing configuration. 

> Alternate solution if the permission above can be used in an insecure way would be to define a plugin-specific permission for this if it's possible.

Currently, this is only possible when the permission `Overall/Administer` is granted but I have a use-case worth considering for lowering this for some users. 

* We have a Jenkins with a configuration committed to a properly-secured repository (branches are protected, reviews required). 
* Some modifications (like updating a secret on Vault) are not picked up by our tool that reloads the configuration when we merge commits to `master`
* This means that developers that don't have the administer permissions (for good reasons!) should still be allowed to reload the configuration so the secret changes are applied
* If only the action of reloading the configuration is allowed, since no-one can update the configuration without a code review, it should not introduce security issues. This seems to fit in the description of `Overall/Manage`

What do you think?

> Jenkins 2.289.3, JCasc 1.51

**Comment by timja** [comment]
seems fine to me, PR welcome

**Comment by quilicicf** [comment]
I can spend some time on it, but I'm really not sure where to start (no experience whatsoever in writing a Jenkins plugins). 

Can you give me a pointer? :pray:

**Comment by timja** [comment]
Change `hasAdministerOrManage` https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly#L42

Change https://github.com/jenkinsci/configuration-as-code-plugin/blob/e07cab6e7b79413489c4e265f0f2f21b0c9b9241/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L168 to `Jenkins.MANAGE`

There may be tests or may not be around this

**Comment by quilicicf** [comment]
Thanks, will get a look!

**Comment by quilicicf** [comment]
@timja #1653 
I implemented the changes but can't run it locally and no tests were broken so I've implemented this blindly. 
If you can help me make sure I've got things right that'd help a lot :pray:

**Comment by quilicicf** [comment]
I see this was merged, that's nice :-) :bowing_man: 

How does the release cycle go? Should I close the issue or is it closed at delivery?

**Comment by timja** [comment]
> I see this was merged, that's nice :-) 🙇‍♂️
> 
> How does the release cycle go? Should I close the issue or is it closed at delivery?

just released whenever, normally the issue gets closed when it's merged.

I was hoping to get the merge strategy PR in as well but it's not quite ready so let's ship
