### ISSUE TITLE
Unable to add seed job with Jcasc 

### ISSUE THREAD

**Issue by gkocur** [jenkinsci/configuration-as-code-plugin#1688]
I'm running Jenkins v2.289.3 with plugin v1.52 on k8s and trying to add seed job to configure GitHub multibranch pipeline. I'm trying to run the code form the example (with existing credentials, org and repo but I get:

```
2021-08-18 16:41:07.785+0000 [id=22]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins
groovy.lang.MissingMethodException: No signature of method: script.mutlibranchPipelineJob() is applicable for argument types: (java.lang.String, script$_run_closure1) values: [repository, script$_run_closure1@64a8d6a5]
Possible solutions: multibranchPipelineJob(java.lang.String), multibranchPipelineJob(java.lang.String, groovy.lang.Closure)
```
Any ideas how to workaround this?

**Comment by jetersen** [comment]
Not enough info.

What version of job dsl plugin?
Can you please share the script?

Clearly the error is giving a hint saying the signature is not correct.
Looks like your closure is not a proper groovy closure at least according to the exception.

**Comment by gkocur** [comment]
Thank you for your prompt answer!
Using latest job-dsl  plugin v1.77
The script:

```
jobs:
              - script: >
                  mutlibranchPipelineJob('job') {
                    branchSources {
                      github {
                        id('intouch-openapi')
                        scanCredentialsId('github-token')
                        repoOwner('organization')
                        repository('repositoryi')
                      }
                    }
                  }
```

I've changed only org and repo, don't think it changes anything.

**Comment by gkocur** [comment]
I used [this](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jobs/multibranch-github.yaml) as an example, I think my code is very similar to the the provided example (unless I'm wrong ;) ).

**Comment by jetersen** [comment]
Note the typo `mu_t_libranchPipelineJob`

Which was also spelled out in the exception 🗡️ 👯

**Comment by gkocur** [comment]
Can't express how stupid I feed now.. Was staring at this half of the day and didn't spot it.
Thank you and sorry :)

**Comment by jetersen** [comment]
No worries sometimes you just need extras eyes on it... I did not spot it immediately myself 😅
