### ISSUE TITLE
[Metrics plugin] Support adding access keys

### ISSUE THREAD

**Issue by batmat** [jenkinsci/configuration-as-code-plugin#169]
Hello,

For Jenkins Essentials, I am trying to replace https://github.com/batmat/evergreen/blob/fe866ffb14af347b015afb75026280926d184f8e/metrics-config.xml by an addition in our existing [casc config file](https://github.com/jenkins-infra/evergreen/blob/aac7a89f655c6aeb8a02cac70a47e78e55525ccf/jenkins-configuration.yaml).

After a few times trying to work out what I should do reading the dynamic JSON schema and reading mainly `jenkins.metrics.api.MetricsAccessKey.DescriptorImpl` class, I couldn't find a way to configure that access key.

Can someone tell me if this is already possible, or if not? In that case, please just tell me where and how I should file that request if elsewhere. I'll do that happily.

Thanks a lot!

PS: FWIW, our context for this use case is implementing [JENKINS-50294](https://issues.jenkins-ci.org/browse/JENKINS-50294) and the upcoming associated JEP I'm going to write next week or so.

**Comment by ewelinawilkosz** [comment]
not making any progress... wondering if that part of configure method may influence the configuration:
```
accessKeys = req.bindJSONToList(MetricsAccessKey.class, json.get("accessKeys"));
```
 `bindJSONToList` is used when @ndeloof in PLUGINS.md suggest to use Rewrite Descriptor#configure() implementation to rely on request.bindJson(this, json)
(I understand I may be completely wrong)

**Comment by ewelinawilkosz** [comment]
as @MadsNielsen pointed out we may be missing setAccessKeys DataBoundSetter - I can try to file a PR later this week

**Comment by ndeloof** [comment]
We indeed need a setter for `setAccessKeys(List<MetricsAccessKey>)`  to replace hand written json parsing in `configure`

**Comment by ewelinawilkosz** [comment]
great, thank, it seems to work now with this setter added... I will issue PR soon

FYI @batmat yaml will look like
```
metricsaccesskey:
    accessKeys:
      - key: "abs"
        description: "123"
      - description: "456"
```

I must admit I don't know the plugin so I don't know if it ever happens that we provide key on our own... but if you don't provide it is generated
