### ISSUE TITLE
Verify Script Security plugin compatibility

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#17]
https://plugins.jenkins.io/script-security

**Comment by oleg-nenashev** [comment]
It is not compatible AFAICT. Needs a custom Configurator

**Comment by jcrben** [comment]
Would be nice to preapprove or even disable script security - running up against it when using the `command` `computerLauncher`

Tried https://stackoverflow.com/a/49372857/4200039 but of course this isn't a Job DSL script...

**Comment by ndeloof** [comment]
discussion happening on https://github.com/jenkinsci/configuration-as-code-plugin/issues/415
