### ISSUE TITLE
Changes in yaml file is not reflecting in config.xml

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#176]
Issue: If there is any changes in the casc.yaml file, then it is not reflecting in config.xml even though after restart.

Eg: if i add any template for docker or kubernetes,
Then it is not reflecting in jenkins config.xml even after restart.
This is working only if we delete the config.xml and restart jenkins_master.
We cannot delete config.xml every time when we change casc.yaml file.

**Comment by ewelinawilkosz** [comment]
of course deleting config.xml can't be requirement...
can you please provide an example of configuration you change?
you mentioned templates, is it also an issue when you change e.g. system message only?

and just to have the whole picture - do you get any errors when you click 'Reload' on Jenkins Configuration as Code subpage?

**Comment by gogskrish** [comment]
Thanks for your replay. As far i understand, the main use of this config-as-code is to configure jenkins without doing it manually and taking all the inputs from yaml file. So we are using ansible to create jenkins-master. So if there is a update or configuration changes, then we will update only the casc.yaml file and restart jenkins-master. So the plugin would update and create new entry if there is a change in casc.yaml. This is the example. In the docker templates, am adding a new template in casc.yaml file which should reflect in the config.xml after restart.

where can i find reload option for configuration as code subpage ?

**Comment by gogskrish** [comment]
Do you recommend this plugin for production jenkins-master ? When is the plan to release official version of this plugin which can be used in production. between i could not find the link for this plugin in my manage jenkins page.

**Comment by casz** [comment]
@gogskrish Definitely ready for production. Just expect changes to YAML file and expect to spent time finding the needed fields. Would like to share a full example, we plan to put into production, very soon, with using docker.
So far I found it superior to groovy scripts and XML manipulation

**Comment by ewelinawilkosz** [comment]
Official release is planned for the end of May
@gogskrish If you can't find Reload button or Configurations as Code section under Manage Jenkins page I'm wondering if the plugin was installed correctly. And which version you're using - maybe the issue is in a plugin itself.
Can you please check under Manage Jenkins -> Manage Plugins -> Installed tab which version of Configuration as Code Plugin you have? Thanks in advance!

**Comment by gogskrish** [comment]
I downloaded the code and built it in my local. Upload the .hpi file manually to jenkins through manage plugins. I have one more question. when this plugin is officially released, will it support all the plugins. Can we go and see the existing config.xml, find the xml tags and classes and mention it in casc.yaml file ? 
Eg: we need to configure
1) Sonar qube plugin
2) Jira plugin
3) locale plugin
4) Mask password plugin
5) openstack workflow plugin
6) audit trial plugin.

Can we find those xml tags from existing config.xml ( because it is configured already ) and mention it in casc.yaml file. Will it work. or it will support only the plugins supported

**Comment by ndeloof** [comment]
> when this plugin is officially released, will it support all the plugins. 

JCasC has been designed to support any plugin _assuming_ they follow some design guidelines, which are in most case well adopted. So some configuration attributes may be missing but minor fixes to target plugin should be enough to fix them.

> we will update only the casc.yaml file and restart jenkins-master

A major benefits of JCasC over plain xml templating is that you don't need to restart. JCasC is mostly equivalent to submitting at same time all configuration forms, so this is just a question of 1/10 seconds.
You just need to invoke the `reload` URL with a POST (we probably should also include a CLI action for this purpose)

> Can we find those xml tags from existing config.xml

We would like to generate yaml configuration from a live jenkins instance to make migration simpler for production servers. see https://github.com/jenkinsci/configuration-as-code-plugin/issues/65.

> Will it work ?

For your specific needs simpler to give it a try and report any attribute you can't configure with JCasC. We could then check plugin design and propose a fix if required.

**Comment by gogskrish** [comment]
Thanks for your update. Waiting for the official release.

**Comment by ndeloof** [comment]
sounds to me this has been fixed. Feel free to re-open if still the case
