### ISSUE TITLE
Why is 'scmCheckoutRetryCount' listed twice in the example?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#178]
Looking at the [jenkins.yaml](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jenkins/jenkins.yaml) I've noticed that the entry `scmCheckoutRetryCount` is written twice, first with the value 2, afterwards with the value 4.

The same goes for the example in the README.md

I presume that it's a minor documentation oversight.

**Comment by ewelinawilkosz** [comment]
documentation require serious refactoring which will take place before official release
feel free to issue PRs with fixes if you like :) and of course `scmCheckoutRetryCount`should be used only once... in case there are two entries the one lower in the file overwrites the first occurance

**Comment by jonbrohauge** [comment]
Created PR https://github.com/jenkinsci/configuration-as-code-plugin/pull/179
