### ISSUE TITLE
getting 401 error while invoking jcasc reload api after config changes

### ISSUE THREAD

**Issue by rg13567** [jenkinsci/configuration-as-code-plugin#1782]
I am invoking below rest after changing my jenkins.yml and placing it to path as per CASC_JENKINS_CONFIG
Also I have set -Dcasc.reload.token as system property in javaOpts in deployment yaml
I am using the token generated from user->configure->Add new Token

tried to reload changed config with below two commands but it is giving 401 error
curl -v -X POST http://localhost:8080/reload-configuration-as-code/?casc-reload-token=API Token 
curl -v -X POST http://localhost:8080/reload-configuration-as-code/?casc-reload-token=API Token --user user:API Token

<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401 Unauthorized</h2>
<table>
<tr><th>URI:</th><td>/reload-configuration-as-code/</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>Unauthorized</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>

**Comment by timja** [comment]
the token is the auth no need for any basic auth.

make sure your tokens match.

e.g.

`-Dcasc.reload.token=dsljkfhasdj324242lhjadshjal`

Make sure your curl is quoted, otherwise query string might be dropped

```
curl -v -X POST 'http://localhost:8080/reload-configuration-as-code/?casc-reload-token=dsljkfhasdj324242lhjadshjal'
```
