### ISSUE TITLE
secrets watch stopped unexpectedly

### ISSUE THREAD

**Issue by abdullahfasih** [jenkinsci/configuration-as-code-plugin#1829]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [ ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [ ] Jenkins version 3.913.1
- [ ] Plugin version 1.55
- [ ] OS linux
- [ ] Reproduction steps

### Description

our Jenkins keeps restarting and we keep getting the error "secrets watch stopped unexpectedly"

**Comment by timja** [comment]
Doesn’t sound related to this plugin, do you have a stack trace?

**Comment by abdullahfasih** [comment]
![mm](https://user-images.githubusercontent.com/15173316/149002639-d9ec23d0-90b0-4dd2-9deb-797b467aa5fb.png)

**Comment by timja** [comment]
that's the kubernetes credentials provider plugin

**Comment by abdullahfasih** [comment]
We are also seeing this issue as well in tandem. we have updated to the latest Jcasc and it's respective dependency plugins

│ 2022-01-11 18:42:52,246 WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb1478b710>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-│
│ 787dd95-tdbs2                                                                                                                                                                  │
│ 2022-01-11 18:42:52,648 WARNING Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb1478bd50>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-6│
│ 787dd95-tdbs2                                                                                                                                                                  │
│ 2022-01-11 18:42:53,451 WARNING Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb1479a290>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-67b │
│ 787dd95-tdbs2                                                                                                                                                                  │
│ 2022-01-11 18:42:55,054 WARNING Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb1479a790>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-67b │
│ 787dd95-tdbs2                                                                                                                                                                  │
│ 2022-01-11 18:42:58,259 WARNING Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb1479acd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-67b │
│ 787dd95-tdbs2                                                                                                                                                                  │
│ [2022-01-11 18:42:58] Received unknown exception: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /reload-configuration-as-code/?casc-reload-t │
│ oken=jenkins-67b787dd95-tdbs2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb14725250>: Failed to establish a new connection: [Errno 111] C │
│ onnection refused'))                                                                                                                                                           │
│                                                                                                                                                                                │
│ [2022-01-11 18:42:58] Working on configmap jenkins/jenkins-jenkins-config-main                                                                                              │
│ [2022-01-11 18:42:58] File in configmap main.yaml ADDED                                                                                                                        │
│ 2022-01-11 18:42:58,304 WARNING Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb14837f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins- │
│ 787dd95-tdbs2                                                                                                                                                                  │
│ 2022-01-11 18:42:58,707 WARNING Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.H │
│ TTPConnection object at 0x7fcb144a9310>: Failed to establish a new connection: [Errno 111] Connection refused')': /reload-configuration-as-code/?casc-reload-token=jenkins-│
│ 787dd95-tdbs2                                                                                                                                                                  │
│ [2022-01-11 18:42:58] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-. Response: 500 Server Error
