### ISSUE TITLE
Jenkins restart loses manually added configuration, after deploying using Jcasc

### ISSUE THREAD

**Issue by shiv8080** [jenkinsci/configuration-as-code-plugin#1836]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

K8s cluster

### Reproduction steps

We are using Jenkins Jcasc to deploy and configure jenkins. This is working fine, with every deployment all required plugins and
integration of different tools with credentials is working fine.
But when we try to add new credentials or update plugins from ui and jenkins restarts, all the manually added(added from ui) 
configurations are not retained. It only retains/reloads the Jcasc configurations. 
we would like to know how we can retain manually added configurations and Jcasc configurations.

### Expected Results

Retain manually added configurations and Jcasc configurations.

### Actual Results

when we try to add new credentials or update plugins from ui and jenkins restarts, all the manually added(added from ui) 
configurations are not retained. It only retains/reloads the Jcasc configurations.

**Comment by timja** [comment]
You must either continue managing it as code or remove the jcasc configuration after initial load

**Comment by y0zg** [comment]
@timja 
Is it possible to disable CASC during jenkins restart in order to keep jobs states?
I'm mostly concerned not about manually added config, but regarding manual build for the first time of all jobs with shared libraries and paramters  https://github.com/jenkinsci/configuration-as-code-plugin/issues/1426#issuecomment-1025001262

**Comment by timja** [comment]
Not something I’ve come across before but isn’t it the same outcome you can’t reload the config or you lose these parameters? Probably your job dsl script needs to check for this or move your parameters to jobdsl

**Comment by y0zg** [comment]
Yes, I can add some more job settings for parameters with https://jenkinsci.github.io/job-dsl-plugin/#path/job-parameters
hope this helps, but I still need to test shared library
Thanks
