### ISSUE TITLE
Allow setting the CASC Reload Token by environment variable

### ISSUE THREAD

**Issue by Angelin01** [jenkinsci/configuration-as-code-plugin#1839]
### What feature do you want to see added?

According to the documentation on [Triggering Configuration Reload](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configurationReload.md), one can configure a secure token to allow reloading the configs using the `JENKINS_URL/reload-configuration-as-code` endpoint. This is even used on [Jenkins' Helm Chart](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L187).

However, the only way the token can be configured is by setting it as a system property `casc.reload.token`. Java system properties are commonly configured through the command line and appear on the process list, meaning anyone with access to the machine can see them:

```sh
$ pgrep -af -- '-Xmx4G'
1234 /etc/alternatives/java -Xmx4G -Dcasc.reload.token="yourSecretTokenHere" -Djava.awt.headless=true -DJENKINS_HOME=/var/lib/jenkins -jar /usr/lib/jenkins/jenkins.war ...
```

To help with this issue, we could add, in similar fashion to the `CASC_JENKINS_CONFIG` environment variable, a `CASC_RELOAD_TOKEN` environment variable, which would avoid showing the token on the process list and would help when bootstrapping Jenkins while setting it up with Docker or on Kubernetes.

**Comment by timja** [comment]
>  meaning anyone with access to the machine can see them

Can't they just see the environment variable too?

This token isn't particularly sensitive. Reloading configuration shouldn't have any affect, but it's there to prevent a potential denial of service by someone spamming the endpoint

**Comment by Angelin01** [comment]
> Can't they just see the environment variable too?

Environment variables can only be seen by either the user running the process or root:
```
$ cat /proc/$(pgrep -f -- "jenkins.war")/environ
cat: /proc/1234/environ: Permission denied
$ ls -l /proc/$(pgrep -f -- "jenkins.war")/environ
-r--------. 1 jenkins jenkins 0 Jan 19 15:12 /proc/1234/environ
```

> This token isn't particularly sensitive. Reloading configuration shouldn't have any affect, but it's there to prevent a potential denial of service by someone spamming the endpoint.

Either way, considering it allows access to a function that normally would only be able to be performed by a system admin, I'd find it troublesome. For example, on the Helm Chart, they have resorted to using the Pod's Name as the token. Someone with access to the pod's name might not have access to force a configuration reload. I'd argue that this in particular is their problem, but having an environment variable alternative could make bootstrapping easier for them by just using envs from secrets.

**Comment by timja** [comment]
It's fine to add support for this, should be a straight forward PR

**Comment by Angelin01** [comment]
I've looked into it quickly, and the code changes could be summarized as adding these few lines [here](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadAction.java#L71):
```diff
     private static String getReloadTokenProperty() {
+        final String envToken = System.getenv(RELOAD_TOKEN_ENV_NAME);
+        if (envToken != null && !envToken.isEmpty()) {
+            return envToken;
+        }
         return System.getProperty(RELOAD_TOKEN_PROPERTY);
     }
```

However, my Java skills are a bit rusty and I can't find a good way to write a test for this, mocking the environment variable, without adding a bunch of libs, using something like PowerMockito to mock `System.getenv` or doing a bunch of other nonsense to abstract away the reading of said env var so we can mock it by injecting it in the constructor.

What would you recommend?

**Comment by timja** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/search?q=EnvVarsRule

**Comment by jetersen** [comment]
Yup we are already using a bunch of libs! 🔩 Kudos to @stefanbirkner 👏 
https://github.com/stefanbirkner/system-rules/blob/master/src/main/java/org/junit/contrib/java/lang/system/EnvironmentVariables.java with our small additions in and a little annotation magic and EnvVarsRule:

https://github.com/jenkinsci/configuration-as-code-plugin/blob/a6983ff60e0cf198ce02d7992bcba927197174db/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java#L74-L78
https://github.com/jenkinsci/hashicorp-vault-plugin/blob/a35e28a212c2ca0f51725c643b7e338a4f90cbdf/src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java#L175-L185
