### ISSUE TITLE
Adding maven wrapper

### ISSUE THREAD

**Issue by japzio** [jenkinsci/configuration-as-code-plugin#1928]
### What feature do you want to see added?

* Add maven wrapper to the project https://github.com/apache/maven-wrapper

### Upstream changes

* https://github.com/japzio/configuration-as-code-plugin/tree/feature/maven-wrapper

**Comment by jetersen** [comment]
Rather add a devcontainer over a wrapper 😅

**Comment by japzio** [comment]
yep. it would also makes sense :-)

**Comment by jetersen** [comment]
Also working with Jenkins plugins it  is expected to have Maven installed. Imagine having plus 2000 repos with their own Maven installation or just 50 repos cloned locally 😅

**Comment by japzio** [comment]
ok. i think you can close this one.
