### ISSUE TITLE
Incorrect group id in master branch

### ISSUE THREAD

**Issue by casz** [jenkinsci/configuration-as-code-plugin#193]
@ndeloof https://github.com/jenkinsci/configuration-as-code-plugin/commit/d7fe9956a5a6e571aca1f7bdee80401321de9048
again with the commits to master 😅

Checking the repository permission updater I see you did not update or submit a PR there: https://github.com/jenkins-infra/repository-permissions-updater/blob/f2c8e11b25a886d9c9622e699e156014cf0229b5/permissions/plugin-configuration-as-code.yml#L1-L6

**Comment by ndeloof** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/689
