### ISSUE TITLE
Allow SecretSource implementations to access the original secret name or original secret prefix

### ISSUE THREAD

**Issue by chriskilding** [jenkinsci/configuration-as-code-plugin#1949]
### What feature do you want to see added?

In the Secrets Manager SecretSource we would like to use secrets which have been entered in ARN format, i.e. `arn:aws:secretsmanager:.....:<secret-id>...`

The current problem with this is that the SecretSource has a preprocessor for certain prefixes e.g. `file:` or `base64:`. It acts by sensing the prefix, doing some preprocessing based on it, and then hands the secret name on to implementations **with the prefix removed**.

This is fine if indeed you wanted one of the supported operations done on your secrets, but it's a problem if you want to use a prefix not recognised by CasC plugin, and just want to receive the secret's original name.

Please could there be an option for the SecretSource implementation to access either:

- the secret's original name
- the secret's original prefix

**Comment by jetersen** [comment]
@chriskilding I am not sure how to solve this, as far as I am aware the string substitution should leave the string as is.

You could try and write a unit tests for `resolve` and see if you can find the issue:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/e70dff8c2f2343a659d373ec33936cc37b16777c/plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java#L104-L112

My simple suggestion is to do trickery in the AWS secret resolver detect `arn_aws_` and replace it with `arn:aws:`?
Unless you can find what is wrong with string subtitution.

Perhaps we are using [`StringSubstitutor`](https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/StringSubstitutor.html ) wrongfully

**Comment by jetersen** [comment]
@chriskilding Do note the order of the substitutions.

Again it should preserve the `arn:aws` fully:

https://github.com/jenkinsci/configuration-as-code-plugin/blob/e70dff8c2f2343a659d373ec33936cc37b16777c/plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java#L42-L54

**Comment by chriskilding** [comment]
Hey, we've written a unit test for this in the SecretSource implementation, and can confirm the `arn:` prefix is **not** preserved.

Looks like there is some divergence between what we think SecretSourceResolver is doing, and what it's actually doing here...

**Comment by astrahan87** [comment]
@jetersen @chriskilding
Is there anything else needed to confirm/progress this issue?

**Comment by chriskilding** [comment]
@astrahan87 If you are able to make calls with the AWS CLI in your AWS account, there is a related question you could help us with...

We are wondering if it is possible to specify a JSON key as a suffix to the secret ARN in a `GetSecretValue` call, and thereby obtain only the value for the JSON key in question (rather than the whole JSON object).

If you have a JSON-formatted secret in Secrets Manager (or you can create one), could you try doing something like the following:

```bash
aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:<region>:<account-id>:secret:<secret-id>:<json-key>
```

If that doesn't work you might have to put a secret version qualifier in there:

```bash
aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:<region>:<account-id>:secret:<secret-id>:AWSCURRENT:<json-key>
```

**Comment by jetersen** [comment]
@chriskilding You mentioned a uni test that confirmed the issue.
Could you open a pull request for it? So it is workable one can investigate the issue?

**Comment by astrahan87** [comment]
@chriskilding The two approaches you mentioned don't work from what I can tell.
The AWS CLI has a --query option that allows [client-side filtering](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side), e.g.:
```
aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:<region>:<account-id>:secret:<secret-id> --query "SecretString"
```
However, the JSON content of the secret is returned as an escaped JSON string rather than an object, and I haven't found a way strictly with the --query parameter of getting just the value of a specific key.

**Comment by chriskilding** [comment]
@jetersen the unit test in question was written in the Secrets Manager SecretSource plugin is called `shouldRevealSecretValueWhenPlainTextSecretIsReferencedViaArn`.

https://github.com/froehr/aws-secrets-manager-secret-source-plugin/blob/fdb14cc13ff845bff85c5040e76c996ac3084029/src/test/java/io/jenkins/plugins/casc/secretsmanager/SecretSourceIT.java#L71

If you put a breakpoint at the start of the `AwsSecretsManagerSecretSource` `reveal()` method and run the test, you'll see that the `id` argument has lost the `arn:` prefix.

**Comment by chriskilding** [comment]
Pull request with a test coming up...
