### ISSUE TITLE
maven errors reported by demo.sh script from 'milestone1' branch

### ISSUE THREAD

**Issue by mramanathan** [jenkinsci/configuration-as-code-plugin#195]
Here are the steps to reproduce the issue in Mac,

1. clone the repo
2. switch to `milestone1` branch
3. run `sh ./demo.sh` . . . 

`[INFO] Scanning for projects...`
`[ERROR] [ERROR] Some problems were encountered while processing the POMs:`
`[FATAL] Non-resolvable parent POM for org.jenkins-ci.plugins:configuration-as-code:1.0`
`SNAPSHOT: Cannot access repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) in offline mode`
`and the artifact org.jenkins-ci.plugins:plugin:pom:2.11 has not been downloaded from it before. and`

. . . . . .
. . . . . .

`[ERROR]   The project org.jenkins-ci.plugins:configuration-as-code:1.0-SNAPSHOT`
`(/Users/ramanathan.muthiah/configuration-as-code-plugin/pom.xml) has 1 error`
`[ERROR]     Non-resolvable parent POM for org.jenkins-ci.plugins:configuration-as-code:1.0-`
`SNAPSHOT: Cannot access repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) in offline mode`
. . . . .
. . . . .

FWIW, details about maven, java and mac OS is here:

`Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-`
`25T01:19:05+05:30)`
`Maven home: /usr/local/Cellar/maven/3.5.3/libexec`
`Java version: 1.8.0_161, vendor: Oracle Corporation`
`Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre`
`Default locale: en_US, platform encoding: UTF-8`
`OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"`

**Comment by ndeloof** [comment]
milestone1 is outdated
