### ISSUE TITLE
move custom configurators to related plugins

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#197]
JCasC 0.x alpha do provide custom configurators for credentials, globalmatrixauth, projectmatrixauth, and rolebased-strategy plugins, and also some job-dsl specific code for seed-job generation. 

For 1.0 "official" release we should move them to target plugins as optional component.

wdyt @ewelinawilkosz ?

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/tree/move

**Comment by ewelinawilkosz** [comment]
I agree! it makes total sense to keep them together with the plugins

**Comment by ndeloof** [comment]
custom configurators are now all segregated in "support" module, so we can easily offer them for adoption to relevant plugins.
