### ISSUE TITLE
default user token  on setup Jenkins controller using jcasc

### ISSUE THREAD

**Issue by jambstud** [jenkinsci/configuration-as-code-plugin#1992]
### What feature do you want to see added?

When JCASC Jenkins controller is provisioned to be able to specify a default value for a token user to be created in order to know before the controller to be setup what will be the token value fro admin user.

**Comment by jeremymcgee73** [comment]
You should be able to use this, https://issues.jenkins.io/browse/JENKINS-68076?jql=labels%20%3D%20token
`-Djenkins.install.SetupWizard.adminInitialApiToken=`

**Comment by DanBenHa** [comment]
> You should be able to use this, https://issues.jenkins.io/browse/JENKINS-68076?jql=labels%20%3D%20token `-Djenkins.install.SetupWizard.adminInitialApiToken=`

As the property path suggests this only sets the initial API token if the setup wizard is run.
I'd assume that many people using JCasC would disable the wizard. This solution doesn't work in this case.
