### ISSUE TITLE
Unable to find config options

### ISSUE THREAD

**Issue by jin-ahn** [jenkinsci/configuration-as-code-plugin#1999]
### Describe your use-case which is not covered by existing documentation.

How do I write up a job that has as "restriction" field enabled with a "label expression" provided? as shown in the screenshot
![image](https://user-images.githubusercontent.com/66384196/173691853-b39318ab-f996-4d98-98c5-f7eecaf4d5f0.png)
```
jobs:
  - script: |
      job('jenkins') {
        logRotator 3, 3
        scm {
          git {
            remote {
              github 'infrastructure', 'ssh'
              credentials 'infrastructure-deploy'
            }
            branches 'origin/migration'
            extensions {
              cleanBeforeCheckout()
              pruneBranches()
            }
          }
        }
        triggers {}
        wrappers { timestamps() }
        steps {

        }
      }
```

**Comment by jin-ahn** [comment]
Hi @ADITYADAS1999 Yes the isssue is still open. Also, could we add documentation for concurrent builds?
![image](https://user-images.githubusercontent.com/66384196/207720673-251a08a7-d216-4526-9f4f-4b343e0d2d9f.png)

**Comment by jin-ahn** [comment]
hi @ADITYADAS1999 any updates on this? Thank you

**Comment by ADITYADAS1999** [comment]
> hi @ADITYADAS1999 any updates on this? Thank you

hi [jin-ahn](https://github.com/jin-ahn), I involve with some other issues actually.

**Comment by jin-ahn** [comment]
@ADITYADAS1999 is there anyway we can just download the job configuration directly from jenkins? This would also to see how it's being done and replicate it in our jenkins.yaml. 

This issue is becoming more and more of an obstacle for us that jasc is becoming less helpful.

**Comment by mslipets** [comment]
hi @jin-ahn,  the info you're looking for is related to [jobDSL](https://github.com/jenkinsci/job-dsl-plugin#jenkins-job-dsl-plugin) rather JCasC.. 

i.e. anything after
```yaml
jobs:
  - script: | ..
```
has [little to do](https://github.com/jenkinsci/job-dsl-plugin/wiki/JCasC) with jcasc plugin

p.s. refer to https://jenkinsci.github.io/job-dsl-plugin/#path/job
