### ISSUE TITLE
Add support for referencing Java System properties from CasC

### ISSUE THREAD

**Issue by sboardwell** [jenkinsci/configuration-as-code-plugin#2015]
### What feature do you want to see added?

Original thread on gitter: https://gitter.im/jenkinsci/configuration-as-code-plugin?at=62b562c78fe56a38b5b373c0

It would be nice to be able to reference Java System properties in a JCasC configuration. I have checked the documentation and it doesn't look like it is.

### Example

So if the JVM was started with `-Dmy.special.prop=bla`, we could then to do something like...

```yaml
jenkins:
  systemMessage: "Jenkins configured automatically with system property ${sysprop:my.special.prop}\n\n"
```

### My Use Case

I would like to create a kubernetes cloud configuration which utilises websockets. Websockets would use the external `JENKINS_URL`, which is not available through ENV vars or the like. It is, however, available as a Java System Property.

**Comment by sboardwell** [comment]
Could this be solved by adding an extra implementing class in the https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java?

**Comment by jetersen** [comment]
@sboardwell Can be solved by adding another lookup: https://github.com/jenkinsci/configuration-as-code-plugin/blob/befdf4078400809b29c659d0fb457c983aa90124/plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java?rgh-link-date=2022-07-04T07%3A38%3A19Z#L43-L48

Could also be solved by adding another secret source.

The secret source could also be in a separate plugin but properly too much work to make a dedicated plugin.

I would go for a lookup as system properties are a little special

**Comment by sboardwell** [comment]
I will work on this
