### ISSUE TITLE
Escape kubernetes comand argument

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#205]
We have to mentioned the command "${computer.jnlpmac} ${computer.name}"
for kubernetes "Arguments to pass to the command" filed in kube plugin.
If we give this in casc yaml, it is taking this as a Secret and looking for it.

We have to escape this command is some way so that it will be populated in the k8 plugin's field.

Thanks

**Comment by holmesb** [comment]
Hi @gogskrish 
How did you format this in a way that `${computer.jnlpmac} ${computer.name}` appears literally in the Jenkins webui?  We've tried prefixing with a backslash character:
'\${computer.jnlpmac} \${computer.name}'
But this just results in: Arguments to pass to the command: `\ \`
We're using JCasC 1.5 &  kubernetes plugin 1.14.3.

**Comment by casz** [comment]
@holmesb https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets

> To escape a string from secret interpolation, put ^ in front of the value. For example, Jenkins: ^${some_var} will produce the literal Jenkins: ${some_var}.

**Comment by holmesb** [comment]
Nailed it.  Thank you :-)

**Comment by carlosjer** [comment]
Hi. I tried doing this (adding ^)  but for some reason it's not being accepted as literal `${computer.jnlpmac} ${computer.name}`. I'm getting an error where it looks for the AWS credentials. I tried putting the caret in between `$` and `{` and the file got thru but I get `$^{` which is the wrong for the args.

**Comment by jr00n** [comment]
Same problem...escaping is not working yet... @casz any idea?

`pipeline {
  agent {
    kubernetes {
      yaml """
kind: Pod
metadata: 
  name: jenkins-agent
spec: 
  containers: 
    - image: "docker-registry.default.svc:5000/public/jenkins-agent-nodejs-10:production"
      args: ^${computer.jnlpmac} ^${computer.name}
      tty: false
      imagePullPolicy: Always
`

**Comment by casz** [comment]
You need to use quoting and escaping

So `args: "^${computer.jnlpmac} ^${computer.name}"`
