### ISSUE TITLE
Organization folder Branch-indexing prevent jenkins to run

### ISSUE THREAD

**Issue by matanz121** [jenkinsci/configuration-as-code-plugin#2063]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

We are using EKS 1.21. running Jenkins latest version on K8S with jcasc and helm chart latest version.
 

### Reproduction steps

1. Deploying jenkins via code - running on k8s.
2. In the startup of the jenkins pod - looking at the logs we can see branch indexing is start 
3. The more repos we have, the more branches we have - the more time it take to jenkins to be up.
4. For us it takes around 4 hours! 

### Expected Results

Run jenkins without try to index branches every time the jenkins pod is going up.

### Actual Results

Jenkins is down for around 4 hours until branch indexing is finish.

### Anything else?

Hope for a way to avoid branch indexing at startup time

**Comment by jetersen** [comment]
via JobDSL:
```
organizationFolder('Some folder name') {
  buildStrategies {
    skipInitialBuildOnFirstBranchIndexing()
  }
}
```

**Comment by matanz121** [comment]
Hi @jetersen - First thanks for your answer.
correct me if I'm wrong but "skipInitialBuildOnFirstBranchIndexing" will skip the build that going to be triggered from the scan.
Is there an option to avoid the scanning? We have an old jenkins - not running on k8s and not face the scan (branch indexing) at start up time.

**Comment by jetersen** [comment]
Turn off the `period`/`cron` trigger and rely on events from SCM to trigger branch indexing?

**Comment by jetersen** [comment]
If your using JobDSL it will trigger a branch indexing.

Using `skipInitialBuildOnFirstBranchIndexing` should prevent that from happening.

**Comment by matanz121** [comment]
We are using jCasc with JobDSL - please correct me if I'm wrong but I attached the code from our template - is that ok?
![image](https://user-images.githubusercontent.com/42091469/179753859-3f481cc8-ccd2-461f-93c5-2548cfe59322.png)

**Comment by jetersen** [comment]
and the configure block?

You can use code blocks instead of screenshots:
``````
```groovy
organizationFolder('Some folder name') {
  buildStrategies {
    skipInitialBuildOnFirstBranchIndexing()
  }
}
```
``````

```groovy
organizationFolder('Some folder name') {
  buildStrategies {
    skipInitialBuildOnFirstBranchIndexing()
  }
}
```

**Comment by jetersen** [comment]
Oh ya... I remember why your not building pull requests on bitbucket cloud.

https://jira.atlassian.com/browse/BCLOUD-5814

Hopefully you have enabled bitbucket cloud to delete branches after they have been merged?

Everytime JobDSL runs it triggers a scan because it replaces the entire org folder config and determines it needs to do another scan.

I'd suggest to use `skipInitialBuildOnFirstBranchIndexing` and you should be fine.

**Comment by matanz121** [comment]
Hi @jetersen , 
Funny to see the issue from 6-7 years ago, unfortunately we running on bitbucket and can't move to github.
more over... as a devops team we enabled the deletion of branches after they merged but most of the teams not doing it - so lot lot of branches in each repo.

below you can see the jenkins running after I killed the pod so he start again and made his "magic".
From what I can see - the folder scanning was not running - but each repo triggered a scan, maybe is there an option to disable it as well?

![image](https://user-images.githubusercontent.com/42091469/179824244-cf2c3ea3-6d22-4588-88e9-6688a9aaff5d.png)

**Comment by matanz121** [comment]
Just to demonstrate how this issue stuck us - when jenkins is going up - couple of hours the UI looks like that - 
![image](https://user-images.githubusercontent.com/42091469/179826047-7e67caa0-ae3e-4e9a-95e5-8fdb082bf7b9.png)

**Comment by jetersen** [comment]
This is not a JCasC issues this is stubborn bitbucket users who do not want to see the light :)

GitHub has great integration with Jira Cloud if that is the hard requirement.

**Comment by jetersen** [comment]
@matanz121 You should be able to visit `https://your-jenkins-url.company.com/plugin/job-dsl/api-viewer/index.html` to find the DSL for `bitbucket-scm-filter-aged-refs`

**Comment by matanz121** [comment]
@jetersen Thank you!!! Appreciate it!
