### ISSUE TITLE
Allow to export conf even if yaml with configuration exists?

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#208]
I can imagine a use case when configuration as code is being used, but more like a backup so UI changes still happens and it would be good to have the possibility to use export feature in that case - any objections?

**Comment by ndeloof** [comment]
sounds good
(/export is not blocked in this context anyway, just not documented as a link)

**Comment by casz** [comment]
This sounds like a good feature 👍

**Comment by ewelinawilkosz** [comment]
I'll just change it in jelly, so the link is always there
