### ISSUE TITLE
Broken master branch build due missing agent to controller security simplification adaption

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/configuration-as-code-plugin#2106]
When I created https://github.com/jenkinsci/configuration-as-code-plugin/pull/2096 to test JCasC on Java 17, 
my commit wasn't replayed or cherry picked on a head branch, otherwise we would have caught the issue.

Based on a quick look, JCasC didn't adopt JEP-235 to warrant backwards compatibility, but the JEP has been 
delivered in 2.326, hence testing on Java 17 fails, because 2.342 does no longer contain 
`MasterKillSwitchConfiguration`, which is needed for `AdminWhitelistRuleConfiguratorTest` to pass.

As interim solution, I propose to drop testing on Java 17 for now, until the test or the baseline is updated, to 
restore a functional master branch.

**Comment by timja** [comment]
Just drop the test if it’s not needed? Easier to fix forward if that’s the only issue

**Comment by NotMyFault** [comment]
> Just drop the test if it’s not needed? Easier to fix forward if that’s the only issue

That works too, I didn't read much into the JEP when I filed the issue, but a quick look over the deprecation note of the test class reveals that the functionality the test is for does already do nothing anymore.
