### ISSUE TITLE
job-dsl scripts are created from code, but not deleted when removed from code

### ISSUE THREAD

**Issue by ofiry-tm** [jenkinsci/configuration-as-code-plugin#2127]
### Jenkins and plugins versions report

jenkins   2.367-jdk11
jcasc      1512.vb_79d418d5fc8
job-dsl   1.81

### Reproduction steps

1. create a job named `my-job1` with a script of job-dsl in the jcasc conf (deployed with jenkins helm chart on k8s)
2. change the script: changing the name `my-job1` to  `my-job2`, and deploying the helm chart again...
3. now - i see i have 2 existing jobs:  `my-job2` and also  `my-job1` - which is weird, because i would expect the jcasc to delete the
`my-job1` - because it was created from the code (job-dsl script), and now i changed the name of the job in the script...

### Expected Results

I would expect `my-job1`  to be deleted after i deployed the helm chart with the changed name in the job-dsl script

### Actual Results

i have 2 existing jobs:  `my-job2` and also  `my-job1`

**Comment by timja** [comment]
JCasC has no sense of state management, and also knows nothing about jobs either, it's fully delegated to job-dsl.

If you want to delete jobs through automation you need to have your job-dsl delete them, e.g. have it delete any jobs it doesn't know about.

**Comment by ofiry-tm** [comment]
> JCasC has no sense of state management, and also knows nothing about jobs either, it's fully delegated to job-dsl.
> 
> If you want to delete jobs through automation you need to have your job-dsl delete them, e.g. have it delete any jobs it doesn't know about.

Thanks for the advice, can you please give a hint how to do this ?

**Comment by timja** [comment]
I don't know, it would need investigation and that's not something I plan to look at but if you do figure it out, adding it to some documentation here would be appreciated.

**Comment by alex1atd** [comment]
Any news? I have the same situation
