### ISSUE TITLE
How to make settings saved after restart.  

### ISSUE THREAD

**Issue by paragrajput** [jenkinsci/configuration-as-code-plugin#2141]
I'm new to jenkins tesing some stuff, I have realised after restart mine settings are no longer available.

JOBS and Plugins are there but the config is to do manually. 

If any docs and ideas are available then please share.!

Thanks in advance

**Comment by Su-HackZ** [comment]
Hi @paragrajput , 

Please check the JCasC plugin, it can make your settings persistent. 

https://www.jenkins.io/projects/jcasc/

**Comment by paragrajput** [comment]
Thanks @Su-HackZ
