### ISSUE TITLE
Google sso configuration

### ISSUE THREAD

**Issue by mrbmd** [jenkinsci/configuration-as-code-plugin#2142]
I have configure google sso on the DEV env,

Currently it's sets to authenticate users can do anything, was looking the way how can i add groups or users to the jenkins

**Comment by Su-HackZ** [comment]
Hi @mrbmd ,

Google sso supports the roleBased strategy for authentication there you can create groups and assign user to it. https://plugins.jenkins.io/role-strategy/


you can get the demo code from this repo 
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/role-strategy-auth

**Comment by mrbmd** [comment]
Thanks @Su-HackZ , was looking for sample code
