### ISSUE TITLE
Configuration being overwritten after each kubernetes pod restart

### ISSUE THREAD

**Issue by colinlee81** [jenkinsci/configuration-as-code-plugin#2178]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

We are deploying Jenkins into a kubernetes cluster, using a hardned docker image derived from the official docker image.
The host node for the cluster is a CentOS 7 system; agents are irrelevant to this bug.

### Reproduction steps

1. Deploy Jenkins with JCasC, with a persistent volume claim located on the local machine. We used the Jenkins helm chart for this.
2. Set the replica limit of the resulting pod to 0, then 1. Or otherwise force restart the pod.
3. Take look into the mapped pvc claim on the host system.

### Expected Results

In general, any configuration/security change from the UI should persist after a pod restart.

In the PVC folder, any modifications done to the config.xml file should stay the same; I've been modifying the <label> field to test.

### Actual Results

All settings are reset to their defaults.

Other plugins were tested; this issue only happens if JCasC is enabled.

**Comment by lemeurherve** [comment]
> ### Expected Results
> In general, any configuration/security change from the UI should persist after a pod restart.

This isn't the case. Each modification done in the UI won't be saved automatically and will be overwritten when the pod restarts. Such modification shouldn't occur when using configuration as code.

You have to check yourself what have been changed in the jcasc config by going to https://<your-instance>/configuration-as-code/viewExport, then report the change **as code** in your repository/source of your PVC content.

**Comment by colinlee81** [comment]
Sounds like we were using the plugin wrong; yeah, we have a bunch of default settings that we were using JCasC for.

Our problem stemmed from the fact that we don't control the maintenance schedule for our node/server; users were making configuration modifications, waiting a week, then coming back to see their settings reset.

We have an automated weekly backup/restore solution in place as a stopgap, which we're probably just going to keep around for now.

Thanks!
