### ISSUE TITLE
CasC Exporter does not export Role Strategy settings

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#223]
I Use Role Strategy as Authorization Strategy. When I try to export YAML, it just skips the security settings section at all

**Comment by ndeloof** [comment]
This indeed hasn't been implemented (yet) by custom Configurators.

**Comment by casz** [comment]
Perhaps best to close the issue and implement the configurator inside Role Strategy plugin?

**Comment by timja** [comment]
agreed
