### ISSUE TITLE
Include an ENV variable option like CASC_JENKINS_CONFIG for external CasC URLs 

### ISSUE THREAD

**Issue by CzapBran** [jenkinsci/configuration-as-code-plugin#2233]
### What feature do you want to see added?

In the current iteration of the Config as Code plugin, you can define multiple locations for JCasC YAML files by passing a comma separated list to the env variable CASC_JENKINS_CONFIG.  This can include either paths in the internal filesystem, or external locations (URLs).  

This feature request is solely for easier integration in the Jenkins Helm Chart.  As of now, the Jenkins Helm chart forces the CASC_JENKINS_CONFIG path to its own set path, where it creates some default config files and custom files defined in the values file.  As it stands, it is not possible to edit this path.  For YAML files in your internal repo this is a simple enough integration, simply include these CasC files in values files through the helm settings.

However, this creates a problem for the previously mentioned external files.  As of now, there is no mechanism to include URLs as CasC sources in Helm, as like previously mentioned, you can't modify the CASC_JENKINS_CONFIG value.

My proposed solution: Have two ENV variables for CASC paths; one that references internal paths, and one for external (URLs).  The internal paths would use the same CASC_JENKINS_CONFIG variable, and the new variable could be something like CASC_JENKINS_EXTERNAL_CONFIG, which would be a list of the external URLs, like previously mentioned.

I suppose for legacy support the regular variable CASC_JENKINS_CONFIG can STILL support URLs as to not break current config setups for users.

Again, this feature request is solely due to the fact that the Jenkins Helm chart currently has no mechanism to reference URLs as Config as Code sources, which seems like a major flaw.

**Comment by CzapBran** [comment]
Currently looking into it, seems like a simple enough change.  I guess I'll just wait for any discussion requesting if this feature is needed or not.  It's an odd case, as this feature is basically for the benefit of another project.  But as the Jenkins chart is officially supported by Jenkins, it seems odd that there is this gap in use-case support, and would love to see this supported

**Comment by timja** [comment]
Can't you just update this value?
https://github.com/jenkinsci/helm-charts/blob/71d82f6381b6087af98ef5ec89acd0c65b9d090d/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L229

you can specify the reload folder and your urls?

**Comment by CzapBran** [comment]
I did look into this, and tried it out.  It requires the enablement of Sidecars, which we don't use, and doesn't seem to work.  When I tried to use this approach, a folder was created with a comma in it, which obviously didn't work.  Now that I think about it, I tried setting multiple internal paths with this approach, but never an external URL, maybe in this case it works.  I'll give it a try and get back to this comment chain

**Comment by CzapBran** [comment]
@timja I'm going to close this feature request and apologise.  When I first tried this multiple path setting through the env variable, it was at the beginning of our project setup.  Since looking into it, I saw through Git Blame that this external URL support was added to the Jenkins Helm chart, so this is already present.
