### ISSUE TITLE
Keeping the Jenkins agent secret stable

### ISSUE THREAD

**Issue by gaborbernat** [jenkinsci/configuration-as-code-plugin#2250]
Currently whenever I bootstrap the instance a new jenkins agent secret is generated. How can I make it deterministic? I think this is  `secrets/jenkins.slaves.JnlpSlaveAgentProtocol.secret` that's generated on startup 🤔 Perhaps here https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/slaves/JnlpAgentReceiver.java#L40

**Comment by gaborbernat** [comment]
In the end went with manually provisioning the secrets `master.key` and `jenkins.slaves.JnlpSlaveAgentProtocol.secret`, which fixed my problem. The only downside is this needs to happen before starting the bootstrap, otherwise Jenkins would generate this key.

**Comment by brokenpip3** [comment]
hey @gaborbernat do you mind share how you were able to create the secrets you mentioned before the jenkins start? I'm trying to investigate the options that we have about this issue: https://github.com/jenkinsci/kubernetes-operator/issues/691#issuecomment-1528827175 for the jenkins operator and understand you experience would be great!

**Comment by gaborbernat** [comment]
I used some start script to start the Jenkins instance, and done it there.

**Comment by brokenpip3** [comment]
Thanks for getting back, can you please share at list the snippet? did you manually moved the files or manually create the secrets?
I'm asking so we can use the same approach in the operator project, I was not able to find any groovy example for the agent secret or the master key.
Thanks!

**Comment by brokenpip3** [comment]
Understood, so you moved the files, thanks :)
