### ISSUE TITLE
Gitlab/Github/Bitbucket multibranchPipelineJob Support

### ISSUE THREAD

**Issue by ksuhdilla** [jenkinsci/configuration-as-code-plugin#2259]
### What feature do you want to see added?

Hello, as a user of Jenkins' CasC, it would be great if we could add support to the multibranchPipeline branchSources for Gitlab, and Bitbucket. This would allow a tighter integration with these platforms and allow the initial seed jobs to come up as multi-branch pipelines with very little massaging.

```
jobs:
  - script: >
      organizationFolder('official-products')
      {
        description("This is where all the fun is")
        displayName('official-team-name')
        organizations
        {
          gitlab
          {
            serverName("gitserver")
            projectOwner("parent")
            credentialsId("jenkins-key")
          }
        }
      }
  - script: >
      multibranchPipelineJob('old-immovable-legacy-project') {
        branchSources {
          gitlab {
            serverName("gitserver")
            projectOwner("parent")
            projectName("legacyprojectl")
            credentialsId("jenkins-key")
          }
        }
      }
```

I will be more than happy to contribute to this fix if needed - but this will be my first time contributing to any Jenkins project - I'm also unaware if there was ever a philosophical reason to not add these other platforms since GitHub is supported. Is it more of a legacy feature and CasC is trying to embrace organizational folders? I love to learn, I just need a little bit of guidance

**Comment by timja** [comment]
Configuration as code plugin just delegates to other plugins for almost all behaviour.

https://github.com/jenkinsci/job-dsl-plugin/ is what provides the functionality for jobs.
Best to take a look over there and at their issue tracker.

**Comment by ksuhdilla** [comment]
Hi Timja,

Yes, I have the job-dsl-plugin installed and I have several seed jobs that come up but it's the GitLab sourceBranches that is causing exceptions. When I look at the definition for https://jenkinsci.github.io/job-dsl-plugin/#path/multibranchPipelineJob
I see it does not support GitLab only GitHub

Am I misunderstanding?

**Comment by timja** [comment]
Please discuss on the jobdsl or gitlab issue trackers or on the [community forum](https://community.jenkins.io) or the [chat channels](https://www.jenkins.io/chat/).

This isn't anything to do with the configuration as code plugin
