### ISSUE TITLE
Missing documentation link from the main page

### ISSUE THREAD

**Issue by yanksyoon** [jenkinsci/configuration-as-code-plugin#2287]
### Describe your use-case which is not covered by existing documentation.

In the [Initial Configuration](https://github.com/jenkinsci/configuration-as-code-plugin#initial-configuration) section of the main documentation, also used in the [main page](https://plugins.jenkins.io/configuration-as-code/) of the plugin, there is a missing reference to the documentation "Click the Documentation link at the bottom of the Configuration as Code page.".

The "Documentation link" doesn't exist anywhere on the page and furthermore, the [demos readme](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jenkins/README.md) mentions that "The full list is available in the generated documentation.", without a reference to where the generated document is.

Happy to help improve the documentation if there would be any guidance from the maintainers regarding where the documentations for the two issues above could be given.

Thank you!

**Comment by jetersen** [comment]
`Click the Documentation link at the bottom of the Configuration as Code page.` is link on your Jenkins instance and there for we cannot create a link to your Jenkins instance 😓

**Comment by yanksyoon** [comment]
Perhaps would it be better to clarify that in the documentation?
> When configuring the first Jenkins instance, browse the examples shown in the [demos](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos) directory of this repository. If you have a plugin that does not have an example, consult the reference help document. Click the Documentation link at the bottom of the Configuration as Code page.
We're talking about demos in the repository and then suddenly a reference to Configuration as Code page that's deployed on Jenkins doesn't seem to flow that well. :)

**Comment by jetersen** [comment]
Feel free to submit a PR.

**Comment by pyatizbyantsevia** [comment]
Let's clarify the documentation, sometimes I encounter a similar situation.

To clarify the second place in [this file](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/jenkins/README.md), I don’t understand: what kind of “generated documentation” is this, where exactly can it be found?

**Comment by jetersen** [comment]
The generated documentation is also available from within the configuration page of the plugin in your Jenkins instance as it can find all plugins and generate the documentation based on plugins you have installed.

**Comment by pyatizbyantsevia** [comment]
Thank you very much for the explanation! I deployed my Jenkins with a plugin to find this button and make sure it was easy to find.

I'm very sorry, I didn't have time to make a new commit to the old PR
