### ISSUE TITLE
CasC Exporter: ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#229]
Trying to see if I can get CasC Exporter to play with me.
Using Jenkins 2.122
CasC plugin version: 0.6-Alpha
Running on localhost inside a docker container (Docker version: 18.03.1-ce) on a Windows 10.
Our production like setup is running on linux in AWS
![image](https://user-images.githubusercontent.com/9496731/40624365-6a5ea3ea-62ac-11e8-8809-57d088d0304c.png)
 I have hand hacked some configuration-as-code.yaml, which works just fine.

curl'ing the `configuration-as-code` URL from inside the docker container seems ok

![image](https://user-images.githubusercontent.com/9496731/40624556-a22ccf76-62ad-11e8-9724-5e8ba686b8cf.png)

curl'ing the `configuration-as-code/export` URL from inside the docker container does not seem to work
![image](https://user-images.githubusercontent.com/9496731/40624616-df582814-62ad-11e8-92e3-8b9fed610374.png)

Any ideas?

**Comment by Lucas-C** [comment]
I sent a PR to fix this.
Could you please review if it is OK ?
