### ISSUE TITLE
Can't select AuthorizationStrategy = unsecured

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#24]
hudson.security.AuthorizationStrategy.Unsecured has no DataBoundConstructor. From configuration-as-code point of view it appears as a custom implementor for `newinstance` that we can't support.

Maybe we can introduce as an extended convention to search enclosing class for a constant with same name (i.e `UNSECURED`).

**Comment by ndeloof** [comment]
same issue applies to LegacySecurityRealm, but here there's even no constant we could rely on.

**Comment by kohsuke** [comment]
Half of this is fixed here, the other half is fixed in the core. There's no urgency to this ticket, so I think this is OK.
