### ISSUE TITLE
Typo / Name Change in Configuration as Code for gitscm demo

### ISSUE THREAD

**Issue by Kumaezenjae** [jenkinsci/configuration-as-code-plugin#2410]
### Describe your use-case which is not covered by existing documentation.

`unclassified:`
`  gitscm:`
  
should be

`unclassified:`
`  GitSCM:`

for versions:

- Jenkins v2.431
- git-plugin v5.2.1
- git-client v4.5.0
- configuration-as-code v1714

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

- https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/gitscm/README.md
- https://github.com/jenkinsci/git-plugin

**Comment by timja** [comment]
I would have expected it to be `scmGit`

Based on:
https://github.com/jenkinsci/git-plugin/blob/8293c49a5a053bdad6b2212728ba72e127f88a82/src/main/java/hudson/plugins/git/GitSCM.java#L1641

cc @MarkEWaite

**Comment by Kumaezenjae** [comment]
Yes it took a while to figure out as I had the same expectation based on the casc page that lists the properties for my Jenkins instance. I believe in the end the way I determined to trial the seemingly correct one above was by examining the XML file produced by doing manual configuration in the GUI. I'm unsure the nuance but using the versions above this is what I needed to get it working.

**Comment by MarkEWaite** [comment]
Thanks for the report.

I would not use `GitSCM` as the symbol for that item in configuration as code.  I'm impressed that it works for you.

The symbol displayed by "View Configuration" is `scmGit`.  It is much better to use the symbol displayed by "View Configuration" than to rely on something that will map `GitSCM` to the expected symbol.

I've submitted a documentation update as:

* #2414

**Comment by Kumaezenjae** [comment]
OK thanks for the tip. Just to clarify, scmGit was not recognized as a property of unclassified despite being listed in the view configuration page. Changing to GitSCM was somehow recognized and correctly interpreted the settings I had enabled. 

Can't imagine it was a just a typo as I tried scmGit several different times, but I'll poke at it one more time later today. In any case as long as it's working I'm in good shape for now and thank you for the quick look into the docs update!

**Comment by MarkEWaite** [comment]
> OK thanks for the tip. Just to clarify, scmGit was not recognized as a property of unclassified despite being listed in the view configuration page. Changing to GitSCM was somehow recognized and correctly interpreted the settings I had enabled.

Please double check.  I think you said earlier that the "View Configuration" page showed `scmGit`.  If the "View Configuration" page shows an item and that is not accepted by the configuration as code plugin, that is a very surprising bug, especially for an item as frequently used as `scmGit`.

**Comment by Kumaezenjae** [comment]
I confirmed that `scmGit` from the "View Configuration" page does work as expected.  I was also able to reproduce my issue from before and determined that it was related to the sequence of scripted commands I was using to (re)install jenkins and all plugins.  Thus it seems like the documentation update in #2414 that you linked above is best.  Thanks!
