### ISSUE TITLE
warning popup about master migration

### ISSUE THREAD

**Issue by gaurav517** [jenkinsci/configuration-as-code-plugin#2417]
How do we get rid of this warning popup in Jenkins (version 2.433) managed with JCasC? 

![image](https://github.com/jenkinsci/configuration-as-code-plugin/assets/15346341/ba4b8dfc-15e5-4164-9f87-1ac2b53f2b88)

When I click on Apply Migration, it looks fine.. until Jenkins restarts. 

How do we completely get rid of this warning? Thanks a lot.

**Comment by mawinter69** [comment]
Afaik there is no explicit way to configure this with JCasC.
When you say it reappears after restart I assume that you do not persists your config.xml but you regenerate it from scratch each time your Jenkins starts. My assumption would be that you have at least a basic config.xml somewhere. You would need to put there `<nodeRenameMigrationNeeded>false</nodeRenameMigrationNeeded>`.

**Comment by gaurav517** [comment]
Thanks a lot. Adding `<nodeRenameMigrationNeeded>false</nodeRenameMigrationNeeded>` in `config.xml` worked.
