### ISSUE TITLE
Jobs: "file" is undocumented

### ISSUE THREAD

**Issue by cowlinator** [jenkinsci/configuration-as-code-plugin#2509]
### Describe your use-case which is not covered by existing documentation.

```
Jobs:
  - file:
```
is undocumented.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

The only clue that this exists is in one obscure file: https://github.com/jenkinsci/configuration-as-code-plugin/blob/269ee49a18d72419762db65d0dec3a04ccd5eba1/integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withSecurityConfig.yml#L6

At the very least, add this as an example to the [demos page](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/jobs)

**Comment by cowlinator** [comment]
Also, are there any other hidden variants? Maybe a 
```
Jobs:
  - url:
```
or something? That would be good to know.

**Comment by timja** [comment]
Its documented on the plugins wiki: https://github.com/jenkinsci/job-dsl-plugin/wiki/JCasC
