### ISSUE TITLE
[feature] Verify examples in demos/*.yaml  during build pipeline

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#257]
Would it be possible to add some basic verification of the example .yaml files under the demos/ folder to the build pipeline so that there is at least a warning if they become out of date due to changes?

I don't know enough about the internals to judge if this is realistic, but as an "end user" it would add great value, especially here during the alpha/beta phase where things change quickly :-)

**Comment by ndeloof** [comment]
We indeed mostly have them duplicated within test-cases. Would be great if we can have the sort of "executable documentation". Especially now that we have plugin installation support.

**Comment by ewelinawilkosz** [comment]
+1 to that, we don't need this redundancy, maybe we can keep test yaml in demo folder or the other way around - just maintain one version, the one that is being tested

**Comment by oleg-nenashev** [comment]
Is it fixed now @v1v ?

**Comment by timja** [comment]
yes, most are tested.
