### ISSUE TITLE
Docker Plugin does not support setting environments

### ISSUE THREAD

**Issue by smueller18** [jenkinsci/configuration-as-code-plugin#266]
I am using this awesome plugin for my Jenkins provisioning. Unfortunately, it is currently not possible to define container environments for Docker Cloud templates.
I added a declaration of volumes and environments for docker templates in https://github.com/smueller18/configuration-as-code-plugin/blob/dockerplugin-environment/src/test/resources/org/jenkinsci/plugins/casc/DockerCloudTest.yml. The definition of the volumes works correctly, but the defined environments are not loaded. To verify this, I extended the test case in https://github.com/smueller18/configuration-as-code-plugin/blob/dockerplugin-environment/src/test/java/org/jenkinsci/plugins/casc/DockerCloudTest.java with the volumes and environments.

Can you have a look at my extended test script and help with this issue?

**Comment by ndeloof** [comment]
the "environment" attribute in code is named "environmentsString", and is not a list but a multi-line string
