### ISSUE TITLE
[PROPOSAL] Create a K8s CRD

### ISSUE THREAD

**Issue by stormmore** [jenkinsci/configuration-as-code-plugin#272]
This project is a really interesting one but to take it to the next level it would be awesome if this was a Custom Resource Definition with an Operator that manages Jenkins.

https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

**Comment by ndeloof** [comment]
probably something to be considered by jenkins-x project

**Comment by ndeloof** [comment]
IIUC a CRD would require to define the configuration schema as a k8s resource directly manageable by kubectl, including validation. But as the schema depends on enabled plugins and version we can't produce a generic one. 

@stormmore Can you please describe in more details what you had in mind ?

**Comment by ndeloof** [comment]
This specific topic will be discussed in a larger context as part of Cloud Native Jenkins (Jenkins Architecture SIG)
