### ISSUE TITLE
Allow accepting Restricted fields in DataBoundConfigurator (opt-in)

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#275]
Currently JCasC does not use Restricted DataBound setters and contructors. It's totally valid due to the compatibility reasons, but in some cases a Jenkins admin may want to enable them at his own risk. 

In order to do so, I propose to add support of alterable behavior once #274 is implemented.

There could be 4 modes:

* reject - do not use Restricted API (default behavior)
* beta - accept Beta API, but not others. Print a warning to the log for Beta
* warn - accept a Restricted setter/constructor, but print a warning to the log
* ignore - accept silently

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/284
sounds a reasonable workaround, anyway `ignore` sounds to be a bad option to offer. For sure we need short terms workarounds, but we shouldn't support incorrect design.
