### ISSUE TITLE
Allow altering behavior for Deprecated contructors/setters in DataBoundConfigurator

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#276]
Currently JCasC accepts deprecated constructors and setters, but it would be great if we could allow changing the behavior. In order to do so, I propose to add a JCasC setting once #274 is implemented.

I propose 3 options:

* reject - fail when deprecated API is used
* warn - accept a deprecated setter/constructor, but print a warning to the log (default behavior)
* ignore - accept, without warnings

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/284

**Comment by oleg-nenashev** [comment]
#284 fixes it
