### ISSUE TITLE
Towards 1.0-rc - Marking  Extension Points API as Beta

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#277]
One of the concerns for the 1.0 release of the plugin is the plugins API, which may need a change later. It's especially important since the plugin is expected to be used externally via extension points.

Recent releases of Jenkins offer support of `@Beta` annotations ([thread](https://groups.google.com/forum/#!searchin/jenkinsci-dev/Beta%7Csort:date/jenkinsci-dev/Gb3KJvint1U/UivjavH9AAAJ))

I would propose to annotate existing extension points as `@Beta` API so that users know that the API may potentially change. It may allow shipping a "-rc" release in public or even 1.0 with reserving an option to make some changes in API in the future if there is unavoidable need to do so.

**Comment by ndeloof** [comment]
from my PoV all implementations of Configurator should be Restricted for external use, not just Beta.
by "public API" I only consider ((Root)Element)Configurator, Attribute, model*, and maybe BaseConfigurator implementation. I suggest we create a separate `api` vs `impl` package to make this simpler to manage. 
(hope I get https://github.com/kohsuke/access-modifier/pull/13 approved).

**Comment by oleg-nenashev** [comment]
Solved by #355
