### ISSUE TITLE
Restricting non-public API

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#278]
Currently the plugin has many public classes, which are not marked as `@Restricted(NoExternalUse.class)`. 

Although it's totally up to plugin maintainers to decide whether these classes are considered a public API, it would be preferable to explicitly restrict classes which are not supposed to be used outside. It would allow doing refactorings (e.g. move/delete class, etc.) without risking breaking something.

**Comment by ndeloof** [comment]
do you know if we can use `@Restricted(NoExternalUse.class)` in a `package-info.java` class ? This would allow to restrict by default, then define an `api` package for public api

**Comment by oleg-nenashev** [comment]
Unfortunately we cannot. Could be an improvement for accmod
CC @jglick

**Comment by oleg-nenashev** [comment]
WDYT @ndeloof , anything left to do here?

**Comment by ndeloof** [comment]
all done, thanks for the reminder
(still expect to get package-level restricted annotation implemented at some time)
