### ISSUE TITLE
Support configuring YAML paths in Manage Jenkins

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#285]
As proposed by @MadsNielsen

**Comment by ewelinawilkosz** [comment]
I actually have a use case for that :) trying to prepare a documentation for users that e.g. already have Jenkins working as a service on their machines. I installed JCasC and trying to figure out how to tell Jenkins where to look for yaml 🤔

**Comment by ndeloof** [comment]
for clarification : this is about providing an alternative way to define source for yaml file(s), not to declare an additional source to come in addition with `CASC_JENKINS_CONFIG` with some merge/override/priority policy.
