### ISSUE TITLE
Ability to express "Enable Agent → Master Access Control" in configuration

### ISSUE THREAD

**Issue by odavid** [jenkinsci/configuration-as-code-plugin#29]
Hi,

I've tried to express that with the current version without success:
```groovy
import jenkins.security.s2m.AdminWhitelistRule
import jenkins.model.Jenkins

Jenkins.instance.injector.getInstance(AdminWhitelistRule).masterKillSwitch = false
```

I believe it will have to be some glue code here.

**Comment by ndeloof** [comment]
we could rely on `AdminWhitelistRule#setMasterKillSwitch()`, but need some way to define a yaml path to this extension. We can't just expose all extensions, need to define which ones have to be included and how to.

I wonder why AdminWhitelistRule is not exposed as a ManagementLink or something similar. I don't even know how one access it's configuration UI, can't find this in UI menus

**Comment by ndeloof** [comment]
ok, this is actually managed by jenkins.security.s2m.MasterKillSwitchConfiguration without an explicit setter and manual databinding. So can't be supported out-of-the-box and will require some glue code (or fix in core)

**Comment by odavid** [comment]
The UI is in "Configure Global Security/Enable Agent → Master Access Control"

**Comment by ndeloof** [comment]
yes, indeed. But this UI is exposed by `MasterKillSwitchConfiguration` which delegates to  `AdminWhitelistRule`. There's few places where such a pattern applies, mostly for backward compatibility. I think we should get some `@ManagedBy` or `@DelegateTo` annotation to document this and make this discoverable by introspection.

**Comment by odavid** [comment]
I was referring to your comment that you could not find it in the UI menus.
I understand it requires some changes in core. This is why I raised this issue instead of creating PR (: . Regards,
Ohad

**Comment by oleg-nenashev** [comment]
Working on it, important for remoting

**Comment by oleg-nenashev** [comment]
It would be great to merge it for https://github.com/jenkinsci/jenkins/pull/2930

**Comment by oleg-nenashev** [comment]
@odavid Created https://github.com/jenkinsci/configuration-as-code-plugin/pull/90

**Comment by odavid** [comment]
Thanks @oleg-nenashev.
