### ISSUE TITLE
Installing from docker image jenkins/jenkins:2.128 throws java.lang.IllegalArgumentException: No hudson.slaves.ComputerLauncher implementation found for SSHLauncher

### ISSUE THREAD

**Issue by jcrben** [jenkinsci/configuration-as-code-plugin#294]
Reproduction repo  at https://gitlab.com/jcrben-repro/jenkins-jcasc-docker

~~As of now, I believe this is loading 2.128 per https://hub.docker.com/r/jenkins/jenkins/tags/~~ locked down to 2.128

The repro case is a stripped down version of a more complex repo that I have internally at work, with agents and jobs and such.

I pulled down this repo and ran it from source locally on my mac (`mvn hpi:run`, etc) and it seemed to work, so possibly something to do with docker?

Noticed a tip for debugging jenkins docker https://github.com/jenkinsci/docker/commit/ec20d5ef79df648973d0a1e7c204da67c1813bae and will perhaps try that next.

**Comment by oleg-nenashev** [comment]
@jcrben is there any code in that repro project?
Likely you just have no SSH Slaves Plugin installed, but maybe there is a regression in the code somewhere

**Comment by jcrben** [comment]
I don't think there's any code, altho not entirely sure what counts.

In my original (internal) project I had `ssh-slaves:1.26` with the same error - just pushed up a commit to the repro adding that, same error. 

The original project also has `ssh-agent:1.15`
and `ssh-credentials:1.13` (among a bunch of others) - any other plugin suggestions?

**Comment by casz** [comment]
I can't judge when the repro repo is empty. My initial thought would be do you have https://plugins.jenkins.io/command-launcher and https://plugins.jenkins.io/ssh-slaves installed

**Comment by jcrben** [comment]
Whoops, user error with gitlab permissions. I wanted to make it visible without giving everyone write access.

https://gitlab.com/jcrben-repro/jenkins-jcasc-docker/ has files now.

I'll try the command launcher plugin when I get the chance.

**Comment by jcrben** [comment]
Looks like that adding both of those plugins (`command-launcher:latest` alone is not enough) fixes it.

But this is weird because we are using the SSHLauncher in our legacy jenkins instance, and I exported all our plugins but these two weren't in the list.

Shouldn't these be dependencies of `ssh-slaves:1.26` if it's broken without them?

**Comment by casz** [comment]
I think the [`install-plugins.sh`](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh) has yet to handle the implied plugins.

**Comment by casz** [comment]
it's not that weird, these two plugins I mentioned, used to inside the Jenkins core. Now they are plugins so hence they are implied after a certain Jenkins core.
