### ISSUE TITLE
Plugin installation tries download from wrong URL

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#298]
I am attempting to test the `plugins:` support in CasC, and find that CasC tries to download the plugins from an incorrect URL.

I have the following settings:
```
plugins:
  sites:
  - id: "default"
    url: "http://mirror.[company].com/jenkins/updates/update-center.json"
  required:
    git: 3.9.1
```

If I specify a plugin version newer than already installed, it will obviously try to download.

This fails with:
```
java.io.FileNotFoundException: http://mirror.[company].com/jenkins/updates/download/plugins/git/3.9.1/git.hpi
```

I wonder where it gets the `/updates/` part from in the attempted url?

My update center is set to `http://mirror.[company].com/jenkins/updates/update-center.json`
and if I download that json file, and search for the git plugin section, it says:
```
{
   "developerId":"stephenconnolly",
   "name":"Stephen Connolly"
}
],
"excerpt":"Integrates Jenkins with GIT SCM",
"gav":"org.jenkins-ci.plugins:git:3.9.1",
"labels":[
"scm"
],
"name":"git",
"previousTimestamp":"2018-05-12T13:55:10.00Z",
"previousVersion":"3.9.0",
"releaseTimestamp":"2018-05-30T11:41:40.00Z",
"requiredCore":"1.642.3",
"scm":"https://github.com/jenkinsci/git-plugin",
"sha1":"2L98+puA4Jme+uJTPFzdw0vDs4g=",
"sha512":"EGVN2VywYxuqWjck960bip9qZIrOOzSb8/Ei9FDAgCEj7qyrNySpGInF57rWQmTfoDuwKPLqKtoGLMJ4oNIyog==",
"title":"Git",
"url":"http://mirror.[company].com/jenkins/download/plugins/git/3.9.1/git.hpi",
"version":"3.9.1",
"wiki":"https://plugins.jenkins.io/git"
}
```

The path mentioned in the json file is `http://mirror.[company].com/jenkins/download/plugins/git/3.9.1/git.hpi` and doesn’t have a  `/updates/` part. The URL without the /update/ is the correct one, and I can download the hpi file from that manually without a problem.
I was assuming that CasC gets the URL from the `update-center.json`?

If I upgrade from the plugin UI page on my Jenkins, it works fine, so I assume that the update center URL is valid and the content of the json too.

**Comment by JKrag** [comment]
Problem is seen on Alpha-0.8

**Comment by ndeloof** [comment]
the current plugin management mechanism doesn't use the json metadata to guess the download URL, as this information isn't available per plugin release. So we use the public update center layout instead. 
Could be improved for sure, but better to just get Update Center expose the required metadata.

**Comment by ewelinawilkosz** [comment]
and this "getting Update Center expose the required metadata" is ongoing, right @ndeloof ?
@JKrag is that answer enough for you and can we close the ticket?

**Comment by ewelinawilkosz** [comment]
sure @JKrag , I'm not going to close anything just to close :) just wanted to check if you're satisfied with the answer, we can continue the discussion here if there are still some things unclear

**Comment by ndeloof** [comment]
Right, let me explain:

update center metadata (`update-center.json`) do provide download link for plugins, but only for "latest". We need additional metadata so we know all versions of plugin hosted by update center + download URL. So far we bake the download URL based on the public UC layout, but this is a fragile design (as this issue confirms). We could make this better, for sample by using the URL for latest then computing a derived per-version URL replacing `latest` with requested plugin version.

A complete implementation would require https://github.com/jenkins-infra/update-center2/pull/198

But I think for usability, and without any ETA for update center metadata, not even considering self-hosted update center would need to be adapted accordingly, we should investigate making the current design more solid. 

I'll investigate this.

**Comment by JKrag** [comment]
@ndeloof Thanks for looking into this issue. Hope you figure something out. Right now I would even settle for a Alpha-version that only supports installing "latest" ;-)
