### ISSUE TITLE
Add references to the JCasC Compatibility Wiki to the documentation

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#300]
After the discussion with @ewelinawilkosz and @ndeloof in Gitter, we agreed to create a new Wiki page listing known compatibility issues with plugins. It would help users to quickly get  information about known issues and fix statuses.

The page is here: https://wiki.jenkins.io/display/JENKINS/Plugins+compatibility+with+Jenkins+Configuration-as-Code+plugin

**Comment by casz** [comment]
May I suggest creating a configuration as code page and use sub pages? 👍

**Comment by oleg-nenashev** [comment]
TBH I would rather do it on jenkins.io once #102 is in place.
I would rather limit number of new pages being created in Jenkins Wiki.

**Comment by casz** [comment]
Sounds better with jenkins.io indeed 👍

**Comment by ewelinawilkosz** [comment]
done by @ndeloof in https://github.com/jenkinsci/configuration-as-code-plugin/commit/7b0e46f765d3d4d3eafde3eea3bd773fbed762a2
