### ISSUE TITLE
CasC Exporter: ERR_INVALID_RESPONSE - Take 2

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#301]
Trying to see if I can get CasC Exporter to play with me this time around
Using Jenkins 2.122
CasC plugin version: 0.9-Alpha
Running on an AWS instance.
![image](https://user-images.githubusercontent.com/9496731/41974005-fdffb2e8-7a16-11e8-93ab-b91998cfa4ad.png)

curl'ing the `configuration-as-code/export` URL from inside the docker container seems to work except I'm not allowed to play.
![image](https://user-images.githubusercontent.com/9496731/41974146-614012b2-7a17-11e8-9150-e01845e3bf5c.png)

It appears that the fixes to issue #229 weren't enough

**Comment by casz** [comment]
the export should be a post curl :)

**Comment by jonbrohauge** [comment]
405->403, two down 203 to go 😁 
![image](https://user-images.githubusercontent.com/9496731/41978113-6295f906-7a21-11e8-99fa-70c335439a94.png)

**Comment by jonbrohauge** [comment]
Playing with the CSRF security settings broke my Jenkins instance totally... Thank the higher powers for Docker, CASC, and a bit of Groovy....

**Comment by casz** [comment]
you can request a crumb :) https://gist.github.com/dasgoll/455522f09cb963872f64e23bb58804b2

**Comment by jonbrohauge** [comment]
@casz OK. I might be a bit daft..
I found no 'Show API Token', but I could generate a new one.

![image](https://user-images.githubusercontent.com/9496731/41979945-8f161d7c-7a25-11e8-8c12-9c17c7dce12d.png)


The token I got was: _11f8223f436d152572f73fe85d0115f1b6_

Replicating what is written in the gist I tried: `curl -s -u goll:11f8223f436d152572f73fe85d0115f1b6 http://jenkins-next.topdanmark.local/crumbIssuer/api/json`

It returned no output. And thus I am stumped by where to get the _crumb_ to put into the header `-H 'Jenkins-Crumb:[some magic crumb]'`

**Comment by jonbrohauge** [comment]
he, he, he... `-u` is _user_.....
Tried my username and got a bit further
![image](https://user-images.githubusercontent.com/9496731/41980119-051738da-7a26-11e8-92a8-4f4e74e0a974.png)
Still no crumb....

**Comment by casz** [comment]
visit: `http://YOUR_JENKINS_URL/me/configure`
Click Show API Token
![Click Show API Token](https://user-images.githubusercontent.com/1661688/41988682-25cc639a-7a3d-11e8-9baa-87ac2de67c79.png)

We have full names for username... hence the quotes around -u parameter
-u is basic autorisation, -w is write-out using it here because the crumbIssuer cannot bother with adding a newline and screws with terminal 😅
```
curl -u "username:token" -w '\n' http://YOUR_JENKINSD_URL/crumbIssuer/api/json
{"_class":"hudson.security.csrf.DefaultCrumbIssuer","crumb":"75aed9bcf4a2791a814b94aafd61ef8e","crumbRequestField":"Jenkins-Crumb"}
```

Now to call export:
-X is method, -H is header, -u is basic autorisation
```
curl -X POST -u "username:token" -H 'Jenkins-Crumb:crumb_given_above' http://YOUR_JENKINS_URL/configuration-as-code/export
```

Cannot confirm whether export works, have not gotten around to updating to 0.9 Alpha yet 😄

**Comment by jonbrohauge** [comment]
@casz Thanks for the idiot-proof step-by-step guide.

I got a response, albeit an error...
`org.jenkinsci.plugins.casc.ConfiguratorException: Can't read attribute 'customDomain' from hudson.plugins.active_directory.ActiveDirectorySecurityRealm@15b1b648` 

I guess that this is a JCASC based exception or a configuration error on my behalf. I'll investigate further and possibly create a new issue if needed. Using the export-functionality isn't that big a deal for me, more of a convenience thing. It's certainly not a  deal-breaker.

**Comment by casz** [comment]
@jonbrohauge we are currently on Jenkins ver. 2.121.1 :)
