### ISSUE TITLE
Very verbose output in Jenkins Log?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#302]
Sifting through the Jenkins log, I found this output:
```
--- [SNIP] ---
INFO: Setting class org.jfrog.hudson.ArtifactoryServer.artifactoryUrl = http://artifactory.domain.local/artifactory
Jun 27, 2018 4:03:22 PM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
INFO: Setting class org.jfrog.hudson.CredentialsConfig.username = [For my eyes only]
Jun 27, 2018 4:03:22 PM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
INFO: Setting class org.jfrog.hudson.CredentialsConfig.password = [For my eyes only]
--- [SNIP] ---
```
The above is only a snippet of the output of JCASC.
Knowing that this is an ALPHA of the plugin, I'll dismiss this as being output that will be quietened upon release. Just worried that all our _magic passwords and such_ are readable in clear text in the Jenkins log.

**Comment by jonbrohauge** [comment]
Looks like a similar issue to #225

**Comment by ewelinawilkosz** [comment]
very similar, and I believed it was solved, hmm...

**Comment by jonbrohauge** [comment]
I can get a hold of a complete dump from my log if needed.
FWIW I'm using 0.9-alpha

**Comment by ndeloof** [comment]
so I assume we fail to detect sensitive data and hide it from https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/org/jenkinsci/plugins/casc/BaseConfigurator.java#L235

**Comment by ndeloof** [comment]
@jonbrohauge just to clarify, in your YAML file you don't have this sensitive data in plain text, but use a secret placeholder like
 ```yaml
password: ${SOME_SECRET}
```
do you ?

**Comment by jonbrohauge** [comment]
@ndeloof Right now, it's a mix. In the holy name of _It's not ready for production_, I'm not all the strict. Not to worry, I'll clean out any clear text sensitive data when the plugin is ready for production usage.

**Comment by ndeloof** [comment]
just wanted to clarify if we still had #225 back or if this is just about plugin verbosity in logs. Which I can guarantee you will find useful if/once something doesn't work as expected :)
