### ISSUE TITLE
As of SSH Credentials plugin v. 1.14 files containing ssh-keys is not supported

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#305]
Link to plugin: https://wiki.jenkins.io/display/JENKINS/SSH+Credentials+Plugin

Reason for the need to update the example in [demo/credentials](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials):

https://jenkins.io/security/advisory/2018-06-25/#SECURITY-440
>SSH Credentials Plugin no longer supports SSH credentials from files on the Jenkins master file system, neither user-specified file paths nor ~/.ssh. Existing SSH credentials of these kinds are migrated to "directly entered" SSH credentials.

I'll be submitting a PR when I have something that works.

**Comment by viyh** [comment]
Just came across this change. It breaks my automated Jenkins setup that I use for the many Jenkins instances that I manage across a lot of clients. It would be really nice to have at least an option to "Use ssh key from Jenkins home" which uses the default SSH key located at ~jenkins/.ssh/id_rsa without allowing the use of an arbitrary path. This way, it complies with the standard key location, and allows for automated setup of Jenkins (by creating the Jenkins user key during setup), and doesn't require me to manually paste the key into the UI each time I set up a new Jenkins instance.
