### ISSUE TITLE
relax export so it doesn't fail but report errors

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#310]
export may fail in many places, we don't always have a symetrical get/set access to configuration
export should then catch get failure, and replace the exported element with a WARNING reporting this issue, but not break the full export. This would help newcomers to get an export of their config to understand the syntax and bake their own config file

**Comment by oleg-nenashev** [comment]
+1

Maybe errors could be also added to comments in the resulting YAML so they do not get missed by admins
