### ISSUE TITLE
Create Developer documentation for the plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#315]
Just to follow-up on https://github.com/jenkinsci/configuration-as-code-plugin/pull/200 and #281 , it seems that we need a separate developer documentation page for the plugin in the GitHub repository. Although JEP defines some top-level extension points, it seems that it is not enough for developers in some cases.

I would propose to have a developer documentation page within the repository or on jenkins.io.

WDYT @ndeloof @ewelinawilkosz ?

**Comment by ndeloof** [comment]
I fully agree this is something we NEED. On my todo-list for a long time

**Comment by oleg-nenashev** [comment]
I have added it to the 1.0 milestone then

**Comment by ndeloof** [comment]
some intial doc created as https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/DEVELOPER.md
