### ISSUE TITLE
Offer REST API for Submitting Configuration

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#327]
Currently the plugin has `configure` methods in the `ConfigurationAscCode` class. These endpoints allow doing configurations from custom YAMLs which we use in tests (JCasC Rule).

It would be great to offer admins an option to do such configuration from REST API by submitting a YAML file. It is easy to implement, and it may be really useful in some cases.

Proposed behavior:

* REST API method like `doConfigSubmit()`
* Arguments: Configuration YAML and `persist` flag
* Configuration is applied using the standard plugin logic
* If `persist` flag is set, the configuration is saved as JENKINS_HOME/jenkins.yaml

It may also make sense to support JSON and XML formats as inputs since they can be easily converted to YAML

**Comment by ndeloof** [comment]
I'm not convinced by the need for `persist`. This mostly introduce risk for file conflicts/overrides and unexpected behaviours. On a realistic infra I'd expect the `config.d` folder to be managed by ops tooling and to invoke a reload endpoint.
