### ISSUE TITLE
Offer REST API for partial configurations

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#328]
Same as #327 , but for partial configurations.

I propose to offer a new extension point, which allows submitting partial configurations (e.g. by looking up a configurator by Symbol). 

Call: `doPartialConfigSubmit` or so

Arguments:

* Configuration YAML (or JSON/XML as extra option)
* `type` - name of the configurator to be used
* `persist` flag. If set, a configuration will be persisted to `${JENKINS_HOME}/jenkins.yaml.d/${type}.yaml`. API users will be responsible for preventing conflicts

**Comment by ndeloof** [comment]
We can't just look for a configurator by symbol, we need API type + path to reach this component in jenkins data model from root configuration. 

Let's say for sample I want to post config for DefaultCrumbIssuer. 
Symbol is "standard". With this single name you can't retrieve a configurator if we don't know we target a CrumbIssuer implementation. Also it only make sense as the newly configured component is attached to Jenkins singleton. 

So actually you'll have to post 
```yaml
jenkins:
   crumbissuer: 
      default:
          excludeClientIPFromCrumb: true
```
Which is equivalent to the existing `/apply` API. 
flag to persist and set file name could be a valuable addition to this REST API anyway.

**Comment by oleg-nenashev** [comment]
> We can't just look for a configurator by symbol, we need API type + path to reach this component in jenkins data model from root configuration.

Right. In API we could try something like:

```
partialConfigSubmit?type=jenkins/crumbissuer/default&config=${ENCODED_YAML}
```

**Comment by ndeloof** [comment]
sounds feasible, but then I don't really understand the benefit vs posting a plain yaml config file targeting this specific component. We will need anyway to merge all configuration yaml to ensure a consistente configuration set before it get applied : as Databound are immutable and replaced during the configuration process we can't just apply partial configuration, we need to apply the whole configuration "model" adding this fresh new upload on top.
