### ISSUE TITLE
create description of WoW for contributors

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#33]
short document describing the process of contributing changes to the plugin

**Comment by casz** [comment]
@ewelinawilkosz perhaps better implemented as a CONTRIBUTING file https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ndeloof** [comment]
do we really need more than the existing https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CONTRIBUTING.md ?

**Comment by ewelinawilkosz** [comment]
No :) seems like contributors have no problems with contributing
