### ISSUE TITLE
SPI for configuration source

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#34]
Current prototype do load configuration from `./jenkins.yaml`
We force sure want more flexibility

- [ ] Load from a set of files
- [ ] Load from a configurable folder (env variable)
- [ ] Load from a kubernetes configMap
- [ ] Load from docker config

Defining an SPI for configuration source that a complementary plugin can implement would make this flexible enough to support extensibility to various use-cases.

**Comment by ewelinawilkosz** [comment]
We need to implement that one before #76 
Since some refactoring happened solution once implemented was overwritten...
1. we need to check which source is now supported
2. we need to agree on the list of sources we want to support

**Comment by ewelinawilkosz** [comment]
#150 is worth checking before implementing that one
