### ISSUE TITLE
Define compatibility strategy when a global configuration gets moved to another category

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#348]
It is a follow-up to the discussion in https://github.com/jenkinsci/configuration-as-code-plugin/pull/347 and to the configuration change in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/67

If a `GlobalConfiguration` changes its category (e.g. due to the refactoring in the core or plugins), it may lead to the JCasC YAML incompatibility.

I would propose to...

* Allow any configuration when it comes from the `unclassified ` category
* Offer a logic/extension for plugins to define obsolete categories somehow (like obsolete Symbols)

**Comment by oleg-nenashev** [comment]
CC @batmat.

I am fine if we do not offer compatibility for such case in 1.0, but this case probably should be documented in user docs then. Having "Compatibility" section with known risks would help users a lot

**Comment by batmat** [comment]
Though I understand your point, I think that if we do not support a smooth path from `unclassified` to some more classified category, then users will get burned over and over by plugins finally moving to some more specific category. 
And as it's unlikely to take only a few days and we're done, but more years I guess, I fear this would then **severely** impede CasC adoption. As burnt users will likely just start thinking: well this thing is awesome, but also keeps breaking every now and then, let's move on. I hope I'm proved wrong if we choose to go this path, but as I would love to see CasC become a largely used and successful initiative I prefer voicing those concerns out loud.

I do not measure the additional complexity, though: would it be really complex to support in the code the fact that if we do not find a given element in some `blah` classification, we fall back to look it up too in the `unclassified` category?

**Comment by ndeloof** [comment]
this is definitively feasible, but there's many other scenarios where backward compatibility will be an issue, and will result in same frustration. This is the price to pay for being schema-less.
