### ISSUE TITLE
JCasC compatibility Wiki and Dashboard

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#349]
I need to finalize the dashboard for #300 .
https://wiki.jenkins.io/display/JENKINS/Plugins+compatibility+with+Jenkins+Configuration-as-Code+plugin is not ready so far, because embedded JIRA queries do not work well.

**Comment by ewelinawilkosz** [comment]
@oleg-nenashev since this is Prio 1, can you please share the status? :)

**Comment by oleg-nenashev** [comment]
Dashboard is here: https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=17346
Should be okay for now until we decide how we maintain it

**Comment by casz** [comment]
Only viewable when logged in 😢 and perhaps we should link to it in the readme and other places 👍

**Comment by oleg-nenashev** [comment]
Linking should be done as a part of https://github.com/jenkinsci/configuration-as-code-plugin/issues/300

> Only viewable when logged in

Please try again, should be fixed

**Comment by casz** [comment]
```
{
  "errorMessages":[

  ],
  "errors":[
    {
      "field":"filterId",
      "error":"gadget.common.invalid.filter.id",
      "params":[
        "18650"
      ]
    }
  ]
}
```
😓

**Comment by oleg-nenashev** [comment]
Should be fixed now: https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=17346. My computer was still displaying it correctly for my provider, some weird form of caching I do not understand.

But now it works fine, I have found the error in security settings. JIRA UX rocks
