### ISSUE TITLE
Incorrect links reference in Reference Documentation page

### ISSUE THREAD

**Issue by yogeek** [jenkinsci/configuration-as-code-plugin#352]
Environment:
- Jenkins ver. 2.121.1
- JCasC 0.9-alpha

In the "Jenkins Configuration as Code Reference" page (accessed by pressing the `Documentation` link on the Configuration as Code management link page : `http://<SERVER_URL>/configuration-as-code/reference`) some links are dead because of incorrect href targets.

For example in the `Jenkins > authorizationStrategy` section, only `legacy` href target is correct (`href="#AuthorizationStrategy-legacy"`). All the others links are pointing to incorrect div id :

- `href="#AuthorizationStrategy-roleBased"` whereas div id is `RoleBasedAuthorizationStrategy-roleStrategy`
- `href="#AuthorizationStrategy-projectMatrix"` whereas div id is `ProjectMatrixAuthorizationStrategy-projectMatrix`

I am not familiar with the way the documentation is generated (I searched in the repo and found jelly files but did not manage to locate precisely the correction to make) so I could not propose a fix directly but I would be glad to help if someone indicates me the missing part :-)

**Comment by ndeloof** [comment]
Not being based on databinding JCasC don't check `ProjectMatrixAuthorizationStrategy` and such for Descriptor when trying to detect  the API extension point they implement (`AuthorizationStrategy`).

I'll handle this on https://github.com/jenkinsci/matrix-auth-plugin/pull/48

**Comment by yogeek** [comment]
If I understand correctly, the main idea (related to #197 apparently) is that the configuration of elements in JCasC YAML file will be managed in plugins code if these elements are plugins related ? 
So you're currently exporting the code from JCasC to each plugin repo by implementing a Configurator implementation, right ? 
Does it mean that the link in the reference page will be present only if the plugin is installed and provides its own documentation section ?

**Comment by ndeloof** [comment]
yes indeed, we would like specific Configurator to be hosted by plugin the add support to. And as such the documentation and schema would only be available if those plugins are installed on your jenkins master. Please note this is already the case : if MatrixAuth isn't installed the corresponding configurator won't be loaded, so no documentation generated

**Comment by yogeek** [comment]
ok thank you for the explanation :-) 
So we leave this issue opened until the refactor is finished and the reference hyperlink is fixed ?
