### ISSUE TITLE
No "plugins" in the plugin's groupId: io.jenkins.configuration-as-code

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#356]
I would like to discuss it, because the most of the plugins are using locations like`io.jenkins.plugins`. For JCasC plugin there is no "plugin" next neither in groupId nor in artifactId. It would be preferable to have it IMHO

**Comment by ndeloof** [comment]
The reason we removed it was to target a top-level project, not "just" yet another plugin

**Comment by oleg-nenashev** [comment]
What about `io.jenkins.configuration-as-code.plugins` then?

**Comment by ewelinawilkosz** [comment]
I agree we don't want to be "just" yet another plugin, but after all it is a plugin :) @oleg-nenashev proposal seems like a good compromise

**Comment by ndeloof** [comment]
Some features (plugin installer) and issues (init race condition with job loading) seems to be hard to implement by a plugin. At some point casc could become an extension to jenkins-core (to be added in /lib).

**Comment by ndeloof** [comment]
as jenkins doesn't use groupId, but only artifactId, we could publish with groupId x.y.z without impact, so who care ?
