### ISSUE TITLE
Not in export: List of plugins

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#367]
I think it would be nice if the export contained the list of required plugins under the `plugins` section? 
It might be too hard to figure out the "short" list of plugins to require (as we don't really need all their internal dependencies mentioned, but even a full list might be useful to copy-paste from.

**Comment by ndeloof** [comment]
This is by intent. There's no way to know which plugin has to be considered for such a "short" list.
Use a shrinkwrap file to get a reproducible list of plugins.

**Comment by JKrag** [comment]
@ndeloof OK. I understand the difficulty in producing a good short list.

Could you expand on the "shrinkwrap file" reference here.  I don't know what you are suggesting.

**Comment by ndeloof** [comment]
oh yes sorry,

as `plugin:` section is computed, this results in a full list of plugins to be installed with dependencies. To ensure a reproducible installation we dump a flat list of all required plugins as a "shrinkwrap" file (something comparable to npm shrinkwrap): https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/org/jenkinsci/plugins/casc/plugins/PluginManagerConfigurator.java#L291

This file is a plain text `plugins.txt` file, using same format as the one Jenkins' docker official image uses

**Comment by casz** [comment]
it is written to the JENKINS_HOME directory as plugins.txt 😅

**Comment by ndeloof** [comment]
right. Our expectation is for end-user to declare as required plugins the one they explicitly know they are using, for sample "docker" to provision agents and "github-branch-sources" for pull-requests/multi-branch job management. All the derived dependencies are not something they have to worry about, and probably don't even know there's so much of them :P
