### ISSUE TITLE
move unclassified Descriptors under "jenkins:"

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#37]
we're trying to mimic UI as much as possible, but our current solution doesn't support it

in UI we have
- jenkins
-- mailer
-- artifactorybuilder
-- ...
- tools
-- git
-- ...

when in yaml it's
- jenkins
-- ...
- mailer
- artifactorybuilder
- tools
-- git
-- ...

can we maybe treat each element UNDER jenkins as root element? so it can be matched with RootElementConfigurators even if it's not a root in yaml? does it even make sense?

**Comment by ndeloof** [comment]
Sounds reasonable. For this purpose we just need to disable RootElement support for Uncategoryzed descriptors, and add peusdo-attributes for all of them to JenkinsConfigurator.

**Comment by ndeloof** [comment]
note: we hardly can support _both_ syntax, i.e same element as root or as a jenkins child, as this would break doc and schema generation (which require a strict model)

we can later investigate a _relax_ parser to support this feature
in the meantime I suggest we adopt this approach to mimic web UI As much as possible

**Comment by ewelinawilkosz** [comment]
I agree, we don't need to support both for sure - if we can move towards mirroring UI I'd like that approach
