### ISSUE TITLE
Not in export: unclassified

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#373]
In my current 0.10-Alpha, my export does not contain any `unclassified` section at all.

In my jenkins.yaml file I currently have configurations for:

* globallibraries:
* location:
* mailer:
* logstashconfiguration:
* gitscm:
* mavenmoduleset:

These might be individual "problems" due to lack of support in plugins, but I didn't want to create 6 separate issues yet as it might be a single detail preventing the whole section to be exported.

**Comment by ndeloof** [comment]
yes indeed https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/org/jenkinsci/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java#L84 :)
