### ISSUE TITLE
Disable setup wizard

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#38]
Configuration as code should fully setup Jenkins, so setup wizard should be automatically disabled.

**Comment by daniel-beck** [comment]
Could we add a validation of sorts that prevents disabling the wizard without defining authn + authz?

**Comment by ndeloof** [comment]
sounds reasonable.
A quick look at SetupWizard seems to demonstrate there's no simple way to disable it programmatically anyway :-\

**Comment by ndeloof** [comment]
possible workaround:
introduce a servlet filter to force `UpgradeWizard#SHOW_UPGRADE_WIZARD_FLAG` session attribute

**Comment by ewelinawilkosz** [comment]
during post-FOSDEM hackathon it was decided we don't need to support case:
* without docker
* start from empty system
* launch Jenkins with jenkins.yaml

in case of docker or pre-existing Jenkins instance issue is not present

it is possible though to provide a set of scripts that will take care of skipping the wizard and pre-installing the plugin, but it won't be part of this project -> closing the ticket

**Comment by deiga** [comment]
@ewelinawilkosz AFAIK the setup wizard also needs to be circumvented when running Jenkins in Docker.
In its current state JCasC doesn't seem to actually support new Jenkins installations at all.

**Comment by casz** [comment]
@deiga instead of poking around in old issues, I suggest you join the chat on [gitter](https://gitter.im/jenkinsci/configuration-as-code-plugin)

Here is the solution you can use in docker.
Honestly, this is a docker issue, not a JCasC issue.
```
RUN echo $JENKINS_VERSION | tee \
    $jenkins_home/jenkins.install.UpgradeWizard.state \
    $jenkins_home/jenkins.install.InstallUtil.lastExecVersion
```

**Comment by ringerc** [comment]
See also #393

**Comment by ringerc** [comment]
Note that in the above you'll want `JENKINS_HOME` with the `jenkins/jenkins` Docker images, not `jenkins_home`.
