### ISSUE TITLE
CASC_VAULT_TOKEN?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#386]
Using vault to save my secrets, I have created a token-based access to use instead of username/password. Will this be possible to use this instead of: `CASC_VAULT_USER` and `CASC_VAULT_PW`?

**Comment by casz** [comment]
This is a good first issue 👍 You are welcome to contribute to it in the related file (VaultSecretSource.java)[https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/org/jenkinsci/plugins/casc/impl/secrets/VaultSecretSource.java].

**Comment by jonbrohauge** [comment]
Created PR #388 to fix this.
