### ISSUE TITLE
unclassified -> ArtifactoryBuilder - broken going from 0.9-Alpha to 0.11-Alpha

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#387]
It appears that the _ArtifactoryBuilder_ section of _unclassified_ has broken. It works in JCASC v0.9.
Got an exception on _name_
Error message got flushed along with the Jenkins-instance. Will try to dublicate and paste error message.

**Comment by ndeloof** [comment]
[ArtifactoryBuilder](https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/ArtifactoryBuilder.java#L207) is all about hand-written josn data binding, so I doubt there's much you can configure with Configuration-asCode on it.

**Comment by jonbrohauge** [comment]
Updating my local JCASC-config.yaml to reflect my PR to update the demo, gets my local test instance to work again. I noticed that the `name`-property also is removed from the SonarQube config, so I figured a conspiracy is under way 😁
