### ISSUE TITLE
Jenkinsfile incompatible with ci.jenkins.io

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/configuration-as-code-plugin#4]
The current `Jenkinsfile` in praqma/dev is incompatible with ci.jenkins.io (the CI instance of the Jenkins project that builds all plugins in the @jenkinsci organization) by selecting a node label that just doesn't exist. This adds queue items that never start.

![screen shot](https://user-images.githubusercontent.com/1831569/32785058-d117b2d4-c950-11e7-9e42-094437c22a83.png)

Since we're using a GH org folder, our ability to configure individual projects is limited.

While I personally would advocate for just using that Jenkins instance for all your CI needs, a quick fix could be to just return from the Jenkinsfile if the `JENKINS_URL.contains('.jenkins.io')` or similar.

**Comment by ewelinawilkosz2** [comment]
oops, wasn't aware that it ends up on your Jenkins. I used your advice. and you're right, I we'll try to move it to ci.jenkins.io soon
