### ISSUE TITLE
[feature] Amazon EC2 Plugin support

### ISSUE THREAD

**Issue by autogun** [jenkinsci/configuration-as-code-plugin#402]
Hope to see EC2 plugin supprt coming.
https://wiki.jenkins.io/display/JENKINS/Amazon+EC2+Plugin

**Comment by casz** [comment]
Should already support it.

**Comment by casz** [comment]
See 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/2164583d1f06c93e7e2d7b74a03d3949cfdff107/integrations/src/test/resources/org/jenkinsci/plugins/casc/EC2Cloud.yml

https://github.com/jenkinsci/configuration-as-code-plugin/blob/89d42724a697d335b2bd0938aa0af06cebdffa41/integrations/src/test/resources/org/jenkinsci/plugins/casc/EC2CloudAMIType.yml

**Comment by autogun** [comment]
@casz Thanks for the heads up!
It would be a good idea to update the main readme section of supported plugins

**Comment by oleg-nenashev** [comment]
Note that there are some known JCasC compat issues.
We track them here: https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=17346

**Comment by ndeloof** [comment]
we decided in recent project meeting to adopt an "incompatible plugins list" vs "supported plugins" as we expect many plugin to work out-of-the-box without we know about it.
