### ISSUE TITLE
Crumb config error

### ISSUE THREAD

**Issue by yogeek** [jenkinsci/configuration-as-code-plugin#408]
I would like to configure csrf protection.
This is working :
```
jenkins:
  crumbIssuer: standard
```

But when adding the option corresponding to tick "enable proxy compatibility" in UI :
```
jenkins:
  crumbIssuer: standard
    excludeClientIPFromCrumb: false
```
then I have this error
```
mapping values are not allowed here
 in /var/jenkins_home/casc_configs/csrf.yml, line 3, column 29:
        excludeClientIPFromCrumb: false
```

I did not manage to unserstand how to set it correctly in the YAML structure by reading JCasC documentation or JSON schema...
Thanks for your help !

**Comment by ndeloof** [comment]
`crumbIssuer: standard` is a shortcut notation, to add attributes you need to use the full nested syntax :

```yaml
jenkins:
  crumbIssuer: 
    standard:
       excludeClientIPFromCrumb: false
```

**Comment by ndeloof** [comment]
please prefer [gitter](https://gitter.im/jenkinsci/configuration-as-code-plugin) chat to ask for assistance

**Comment by yogeek** [comment]
@ndeloof Sorry for having used the wrong media. Thank you very much for the help and for the gitter link !
