### ISSUE TITLE
Create user scenarios for running Jenkins

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#41]
This should in result become a part of documentation, but first we'll use it to discover possible use cases and create follow up issues.

1. running from scratch with official docker image (provided by us, plugin preinstalled, wizard disabled)
2. installing plugin on working Jenkins instance (wizard not an issue)
3. pre-packaged opinionated Jenkins distributions (plugin preinstalled, wizard an issue)

**Comment by buep** [comment]
I have a few customers of ours in mind so I can write a few stories about how I see them use the configuration as code in different ways and how to adapt it.

**Comment by ewelinawilkosz** [comment]
great, let's keep it here, we'll use it to identify missing features/updates required in existing ones

**Comment by buep** [comment]
@ewelinawilkosz can you please briefly review pushed proposal on this issue?

**Comment by ewelinawilkosz** [comment]
it's looking good @buep
