### ISSUE TITLE
Is there a way to configure ScriptApproval

### ISSUE THREAD

**Issue by odavid** [jenkinsci/configuration-as-code-plugin#415]
Hi,

I am looking for a way to declare `ScriptApproval`.
Looking at [ScriptApproval.java](https://github.com/jenkinsci/script-security-plugin/blob/master/src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java) it seems there is no easy way to declare this using the `CasC ` plugin.

Am I wrong? If currently there is no way to do it, how about creating a dedicated `configurator` for it?

**Comment by casz** [comment]
I think it would require a dedicated configurator looking at the source code as you suggested.

**Comment by odavid** [comment]
This is what I thought... Will see what I can do about it...
10x!

**Comment by casz** [comment]
Oh it definitely requires changes too: [`load()`](https://github.com/jenkinsci/script-security-plugin/blob/master/src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java#L326) well mess with any configurator if I recall correctly from @ndeloof previous implementations

**Comment by ndeloof** [comment]
I don't think it will require changes, but for sure will require a custom Configurator to manage `approvedScriptHashes`, you probably want this configurator to expose a set of script to be pre-approved and `configure` to actually invoke `preapprove`. But doing so, as only a hash is stored we won't be able to export a relevant yaml structure. On the other side, asking end-user to configure hash for pre-approved scripts would be a UX non-sense.

**Comment by odavid** [comment]
Am working exactly on this kind of PR.

**Comment by odavid** [comment]
I believe at least approvedSignatures should be supported.

**Comment by ndeloof** [comment]
discussion moved to https://github.com/jenkinsci/script-security-plugin/pull/219
