### ISSUE TITLE
 Error setting kubernetes configuration at the jenkins

### ISSUE THREAD

**Issue by WoodProgrammer** [jenkinsci/configuration-as-code-plugin#417]
I've a some configuration at gist link at below: 

https://gist.githubusercontent.com/WoodProgrammer/042c96773ae387f7e70ac98735b2c641/raw/5775b6fb46e5ea12df1143eb53eb2d620b2c45b1/jenkins.yaml 

So I've made some changes at docker-compose.yml file of https://github.com/Praqma/praqma-jenkins-casc.git shown at below: 

https://gist.github.com/WoodProgrammer/d7734676c951224fcd6957f6f24053c7

But when I want to build the docker image (install the kubernetes plugin ) and up with the docker compose I've some errors at below. 

<img width="1273" alt="error" src="https://user-images.githubusercontent.com/16826090/43645209-e58c86ec-9739-11e8-8281-a92d0ef682bb.png">

How I can handle this problem . 

Best Regards .

**Comment by casz** [comment]
Sounds like miss installing the kubernetes plugin 👍

**Comment by WoodProgrammer** [comment]
plugins_extra.txt file include the kubernetes plugin, so every build is already installing that. 

credentials:2.1.17
git:3.9.0
ssh-slaves:1.26
warnings:4.66
matrix-auth:2.2
job-dsl:1.68
workflow-aggregator:2.5
timestamper:1.8.9
kubernetes

**Comment by casz** [comment]
syntax is again incorrect I should say... kubernetes:latest if you just want the latest.
