### ISSUE TITLE
images/sample_form.png is broken?

### ISSUE THREAD

**Issue by gmacario** [jenkinsci/configuration-as-code-plugin#440]
This prevents the inline image to be displayed correctly, for instance, in https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md

See https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/images/sample_form.png

![image](https://user-images.githubusercontent.com/75182/43999863-644ea88e-9e15-11e8-8bab-0da40a5a34e4.png)

**Comment by casz** [comment]
No issue here 😅 
![image](https://user-images.githubusercontent.com/1661688/44000932-fdb52850-9e28-11e8-8acd-6b4f311dd4e8.png)
Here it is again without my user styles (incognito mode):
![image](https://user-images.githubusercontent.com/1661688/44000939-2031c6ae-9e29-11e8-999f-ec34d84b72b6.png)
Looking at your extension list I could suspect those.
I suspect if you go into chrome's dev tools by pressing F12 it would also tell you why it failed to retrieve the image.

Also you can drag the address bar to show more or less of your extensions 👍

**Comment by gmacario** [comment]
Browsed https://github.com/jenkinsci/configuration-as-code-plugin with another browser (Internet Explorer), I confirm that I can display the image correctly

![image](https://user-images.githubusercontent.com/75182/44001255-edbceae0-9e2e-11e8-9060-228f449be827.png)

So it really looks like the issue was in my browser (Google Chrome) or one of the installed plugins.

Closing issue, sorry for the noise

**Comment by gmacario** [comment]
By the way, the image 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/images/sample_form.png is now correctly displayed also with the previous browser I used

Maybe I had some network glitch before (used tethering over 3G network)
