### ISSUE TITLE
Rename plugin to jenkins-configuration-as-yaml-plugin

### ISSUE THREAD

**Issue by rodrigc** [jenkinsci/configuration-as-code-plugin#449]
This plugin is extremely useful, because it would facilitate setting up Jenkins 
in a devops environment using tools such as Ansible, Puppet, Chef, Saltstack, etc.

However, the name of the plugin is a bit confusing, because the *as-code* can be confused
with *pipeline* which is *code* for Jenkins jobs.  To make it clear that this plugin is for configuring
the Jenkins server itself, I would suggest renaming the plugin to:

*jenkins-configuration-as-yaml-plugin*

**Comment by rodrigc** [comment]
the reason I am suggestion jenkins-configuration-as-yaml-plugin is because:
1.   configuration? what are you configuring? there are lots of plugins in Jenkins for configuration different things, that why I suggestion putting jenkins-configuration in the name to make it a bit more obvious that you are configuring Jenkins itself

2.  code? well code can be groovy, python, ruby, C++.....specifying that you are using yaml makes it a bit more clear

3.  "pipeline as code" has been an idea pushed forward by the Jenkins project in the past few years.  However, this plugin is not specifying a set of steps in code to run operations on the Jenkins server, like pipeline scripts........it is specifying the configuration of the Jenkins server itself.

**Comment by casz** [comment]
We are not only configuring Jenkins. we are configuring all plugins with any global configuration as well. This could even expand further as well. The plan is that the plugin might not be yaml exclusively to my understanding.

**Comment by ewelinawilkosz** [comment]
thanks again for feedback @rodrigc, it is always appreciated, but I think in this case majority is ok with current name - unless I'm wrong and more people starts complaining :) I'll revisit the issue then

but I want to address your comments

"configuration as code" or "as code" seems to be commonly used terms (https://en.wikipedia.org/wiki/Infrastructure_as_Code, https://confluence.atlassian.com/bamboo/what-is-configuration-as-code-894743909.html) and we're just following convention. 

I do believe existing documentation, starting with https://jenkins.io/projects/jcasc/ explains the motivation and scope of the plugin good enough for everyone to understand what the plugin is about (at the same time I do know the documentation in general needs improvements) 

During development the plugin (or even pre-plugin solution) went through different phases: groovy, json and we ended up with yaml. There is a reason for that but the main thing you need to know at the very beginning is that it allows you to configure Jenkins :) 

Once you're comfortable with "as code" and use google to find how to "configure Jenkins as code" you should get the plugin somewhere very close to the top of the results.

So I am closing the issue, but - as I said - if anyone, including you, is not satisfied, we can continue the discussion.
