### ISSUE TITLE
Management page shows "Last time applied : 01-Jan-1970 00:00:00 UTC"

### ISSUE THREAD

**Issue by dp304** [jenkinsci/configuration-as-code-plugin#456]
Manage Jenkins > Configuration as Code page shows incorrect "Last time applied", even if the configuration was recently updated.
Jenkins version: 2.121.2
Plugin version: 1.0-rc1

**Comment by MadsNielsen** [comment]
Yep confirmed, it should be fixed when this: https://github.com/jenkinsci/configuration-as-code-plugin/pull/438 get's in.

**Comment by ndeloof** [comment]
#438 has been merged, @MadsNielsen can you please check if this is still relevant ?

**Comment by MadsNielsen** [comment]
@ndeloof Yes, this issue has been fixed :)
