### ISSUE TITLE
Simple improved styling and layout of autogenerated documentation

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#46]
On host/plugin/configuration-as-code the helpful documentation can be found, but it is hard to read due to indentation and layout.

As a user I would like a simple styling making the indentation very visual and match the YAML configuration I'm supposed to write.

A very simple layout with font's and other styling helping read it would be nice as well. Maybe a also a table of content.

**Comment by ndeloof** [comment]
👍
The initial generated doc reuse https://jenkins.io/doc/pipeline/steps/ css style for consistency
but would deserve some usability improvements :P

**Comment by ndeloof** [comment]
@alecharp made some comparable improvements to pipeline reference documentation.

**Comment by lanwen** [comment]
please look at #96

**Comment by buep** [comment]
With the merged PR #96 I think we can close this issue as done.
