### ISSUE TITLE
Refactor ConfigurationAsCode to enable clear error messages

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/configuration-as-code-plugin#488]
I have had a quick look at the code. This is just a thought, tell me what you think =)

# Problem
I'm looking at `io/jenkins/plugins/casc/ConfigurationAsCode.java`. It is currently doing 2 (at least) things at once:
* Interpreting the YAML. Parsing and determining the configuration.
* Reading the the configuration and acts on it. Actually applying configuration.

I got an unclear error message. Same as #455. It is says: `Caused by: io.jenkins.plugins.casc.ConfiguratorException: Cannot find configurator for type class io.jenkins.plugins.casc.plugins.Plugins`.
I would like it to say something like:
`Caused by: io.jenkins.plugins.casc.ConfiguratorException: Did not recognize attribute "plugins", was expecting one of "a","b","c"`.

In my case the problem is likely not at all in the parsing of the YAML, but a bug in the plugin making it unable to apply the configuration. And again, that should be an error stating that, **instead of something that might look like a configuration error made by the user**.

# Suggested solution

1. Construct POJO:s that makes up the configuration.
1. Parse the YAML to those POJO:s. A quick goggling tells me [Jackson can do it](https://dzone.com/articles/read-yaml-in-java-with-jackson).
1. Make sure the YAML -> POJO fails for any unrecognized fields.

This:
```
    private void configureWith(List<YamlSource> sources) throws ConfiguratorException {
        lastTimeLoaded = System.currentTimeMillis();
        configureWith( YamlUtils.loadFrom(sources) );
    }

    private void configureWith(Mapping entries) throws ConfiguratorException {
        final Mapping clone = entries.clone();
        checkWith(clone);

        final ObsoleteConfigurationMonitor monitor = ObsoleteConfigurationMonitor.get();
        monitor.reset();
        ConfigurationContext context = new ConfigurationContext(registry);
        context.addListener(monitor::record);
        invokeWith(entries, (configurator, config) -> configurator.configure(config, context));
    }
```
Would take a, correctly configured, `ConfigurationAsCode` object that we know is a valid configuration (we have validated that when parsing):
```
    private void configureWith(List<ConfigurationAsCode> configurations) throws ConfiguratorException {
        ...
    }
```

And instead of search through implementations to find something that might match:
```
    private static void invokeWith(Mapping entries, ConfigratorOperation function) throws ConfiguratorException {
        for (RootElementConfigurator configurator : RootElementConfigurator.all()) {
            final Iterator<Map.Entry<String, CNode>> it = entries.entrySet().iterator();
            while (it.hasNext()) {
                Map.Entry<String, CNode> entry = it.next();
                if (! entry.getKey().equalsIgnoreCase(configurator.getName())) {
                    continue;
                }
                try {
                    function.apply(configurator, entry.getValue());
                    it.remove();
                    break;
                } catch (ConfiguratorException e) {
                    throw new ConfiguratorException(
                            configurator,
                            format("error configuring '%s' with %s configurator", entry.getKey(), configurator.getClass()), e
                    );
                }
            }
        }
    }
```

You can pick the implementation directly from the configuration. This getter should fail with a clear exception if the configurator with that name does not exist. Which would clearly show that it is a bug in this plugin, not a configuration error made by user:
```
    private static void invokeWith(ConfigurationAsCode configuration) throws ConfiguratorException {
        RootElementConfigurator configurator = RootElementConfigurator.get(configuration.getElemntName())
        function.apply(configurator, configuration);
    }
```

**Comment by ndeloof** [comment]
closing as this proposal for an explicit Pojo model is contradictory with JCasC design in it's initial implementation.
Might make sense in near future with Configuration as Code support in [Cloud Native Jenkins / Jenkins Jolt](https://jenkins.io/blog/2018/08/31/shifting-gears/) to be discussed in related SIG.
