### ISSUE TITLE
CasC-powered demo for Static configuration and Pipeline development

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#49]
I have a configuration-as-code demo, which demoes a ci,jenkins.io-alike setup for Pipeline development: https://github.com/oleg-nenashev/demo-jenkins-config-as-code

It would be great to migrate the prototype to CasC so that we get some info from close-to-real instances. It requires #48 and probably patches for some other plugins

**Comment by oleg-nenashev** [comment]
Cannot work on it at the hackathon, network does not allow building Docker images

**Comment by ewelinawilkosz** [comment]
@oleg-nenashev is that issue still valid? maybe candidate for JW or DOJ hackathon?
