### ISSUE TITLE
Integration test for Config File Provider Plugin

### ISSUE THREAD

**Issue by srempfer** [jenkinsci/configuration-as-code-plugin#492]
As there is now a updated version the plugin available (see [JENKINS-53247](https://issues.jenkins-ci.org/browse/JENKINS-53247)) I'll strip down my origin PR #477 and create a new one with only the integration tests.

**Comment by ndeloof** [comment]
👍

**Comment by ndeloof** [comment]
also see https://github.com/jenkinsci/config-file-provider-plugin/pull/54
