### ISSUE TITLE
FeatureRequest: configure master node

### ISSUE THREAD

**Issue by metux** [jenkinsci/configuration-as-code-plugin#495]
I'd like to request support for configuring the master node (eg. specify labels).

For now, it only seems to be possible via groovy script. Took me quite a while to find out how to actually do it. Groovy example:

      jenkins.model.Jenkins.instance.labelString = "docker-host"

**Comment by gmacario** [comment]
Hi @metux,

AFAIK you may configure the label on the master node with the "labelString" tag in the .yaml file.

You may have a look here:

https://github.com/gmacario/easy-jenkins/blob/master/casc_configs/default.yaml#L4
