### ISSUE TITLE
Is the GithubOrganisationFolderTest.yml valid?

### ISSUE THREAD

**Issue by corburn** [jenkinsci/configuration-as-code-plugin#499]
I was looking for alternative ways to enable branch discovery in an organizationFolder job-dsl besides using a `configure { ... }` workaround (JENKINS-46202) and found the following yaml:

https://github.com/jenkinsci/configuration-as-code-plugin/blob/2ce8f3eb6a58a50b163cef2f418f443e741137f5/integrations/src/test/resources/io/jenkins/plugins/casc/GithubOrganisationFolderTest.yml

I know job dsl scripts are valid, but is this valid for the casc jobs section?

**Comment by ndeloof** [comment]
No it doesn't, this one was exploration to support item management with jcasc using a yaml syntax (will revisit in the future)
