### ISSUE TITLE
[Feature] Support Build slave maintainers

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#5]
There is a plugin to maintain build slaves, allowing slave administrators to configure their slaves. How can that work if the slave configuration is in our new jenkins.yml file? The customer said they have delegated responsibility for this configuration based on the ownership plugin.

**Comment by oleg-nenashev** [comment]
Ownership Plugin support should be pretty straightforward.
Can add missing symbols to the plugin if needed

**Comment by ndeloof** [comment]
it's not just about symbols, Ownership Plugin can't be configured until 
- it use a `GlobalConfiguration` and not just extend `Plugin`. 
- it uses stapler data binding for configuration, no hand-written json lookups
- it uses optional nested components, no UI optional blocks

created  JENKINS-52961 for this purpose
