### ISSUE TITLE
Export without Download

### ISSUE THREAD

**Issue by llchan** [jenkinsci/configuration-as-code-plugin#522]
It would be useful to be able to export the current configuration without downloading to a file. Maybe there could be a "View Configuration" button that does the same thing without the `Content-Disposition: attachment; filename=jenkins.yaml` header?

**Comment by ndeloof** [comment]
unfortunately browsers have poor support for yaml, so rendering export this way would result in an (unnamed) file download anyway.

**Comment by ndeloof** [comment]
Maybe we could have an additional page to offer an alternate view of this with a syntax hylighter library

**Comment by llchan** [comment]
I don't think we need the browser to know that it's a yaml file, something as simple as `Content-Type: text/plain; charset=utf-8` would be good enough to show it as a text file. Syntax highlighting would be neat, but I think that's much more work than modifying a resposne header.
