### ISSUE TITLE
offer a second level of configuration source

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#530]
As suggested during Contributor Summit we could support a 2nd level of configuration sources to override configuration without considering those as conflicts.
Typically, some `/etc/defaults/jenkins.yml` would provide a reference configuration, while `~/.jenkins/jenkins.yml` would allow a user to customize and override this reference with custom stuff. This would allow him to update reference to latest without having to handle merge conflicts.

**Comment by timja** [comment]
We support multiple files in a directory or a user can merge their own config, closing as there's been no movement or interest in this in a long time afaik
