### ISSUE TITLE
demo for script approval

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#537]
actual example available in https://github.com/jenkinsci/configuration-as-code-plugin/pull/416/files

**Comment by ewelinawilkosz** [comment]
```
unclassified:
  scriptApproval:
    approvedSignatures:
      - method java.net.URI getHost
      - method java.net.URI getPort
      - new java.net.URI java.lang.String
```

is not throwing errors but is not configuring approvedSignatures either 🤔

**Comment by ewelinawilkosz** [comment]
it seems we can put literally whatever under unclassified and it won't fail :)
and then I discovered commit with scriptApprovalConfigurator was reverted - @ndeloof you remember why?

**Comment by ewelinawilkosz** [comment]
oh, new PR waiting: https://github.com/jenkinsci/script-security-plugin/pull/219
(what I nice monologue I have here 🤦‍♀️ )

**Comment by dgarzon** [comment]
@ndeloof @ewelinawilkosz Given the developers at jenkinsci/script-security-plugin#219 don't want to merge the proposed changes, can we re-revert to support this functionality?

**Comment by ndeloof** [comment]
I still think we need a fix on script-security-plugin. Just need to make an acceptable one, not relying on a custom configurator, but better make this plugin follow expected databinding conventions.

**Comment by dgarzon** [comment]
@ndeloof Thanks for the quick response. The file in question is: https://github.com/jenkinsci/script-security-plugin/blob/master/src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java. I can start implementing the changes today, but can you provide some guidance? What do you think is needed in order to get that file to "follow expected databinding conventions"? I think this implementation is old, and needs to be updated to leverage `Descriptor` and `DataBoundXX`. Am I right?

**Comment by dgarzon** [comment]
@ndeloof @ewelinawilkosz I opened a PR to that enables this functionality without glue code: https://github.com/jenkinsci/script-security-plugin/pull/233

**Comment by casz** [comment]
closing issue as work is ongoing in the rightful place.

**Comment by cwiggs** [comment]
Has this actually been fixed?  I followed the example in [JENKINS-57563](https://issues.jenkins-ci.org/browse/JENKINS-57563) but I get the same results that @ewelinawilkosz reported to begin with; JCasC applies correctly but the settings don't actually seem to be applied in the scriptApproval page.

**Comment by casz** [comment]
@cwiggs you did not mention the version of Script Security, so did you update Script Security?
Required 1.64 of Script security.

**Comment by cwiggs** [comment]
Yes, I'm running:

Jenkins 2.164.2
script-security 1.66
JCasC 1.32

**Comment by cwiggs** [comment]
I actually noticed some odd behavior with the scriptApproval setting.

Here is my JCasC security config:
```yaml
security:
  scriptApproval:
    approvedSignatures:
      - method java.lang.String indexOf int
      - method io.jenkins.plugins.casc.ConfigurationAsCode configure
      - staticMethod io.jenkins.plugins.casc.ConfigurationAsCode get
  remotingCLI:
    enabled: false
``` 

When I apply this config and cat out `/var/jenkins_home/scriptApproval.xml` It seems to show up correctly:

```xml
<?xml version='1.1' encoding='UTF-8'?>
<scriptApproval plugin="script-security@1.66">
  <approvedScriptHashes/>
  <approvedSignatures>
    <string>method io.jenkins.plugins.casc.ConfigurationAsCode configure</string>
    <string>method java.lang.String indexOf int</string>
    <string>staticMethod io.jenkins.plugins.casc.ConfigurationAsCode get</string>
  </approvedSignatures>
  <aclApprovedSignatures/>
  <approvedClasspathEntries/>
  <pendingScripts/>
  <pendingSignatures/>
  <pendingClasspathEntries/>
</scriptApproval>
```

However the GUI does not reflect these changes.  When I run the job that uses these signatures the job fails saying the signatures are not approved.  After that If I cat out `/var/jenkins_home/scriptApproval.xml` It now shows:

```xml
<?xml version='1.1' encoding='UTF-8'?>
<scriptApproval plugin="script-security@1.66">
  <approvedScriptHashes/>
  <approvedSignatures/>
  <aclApprovedSignatures/>
  <approvedClasspathEntries/>
  <pendingScripts/>
  <pendingSignatures>
    <pendingSignature>
      <context/>
      <signature>staticMethod io.jenkins.plugins.casc.ConfigurationAsCode get</signature>
      <dangerous>false</dangerous>
    </pendingSignature>
  </pendingSignatures>
  <pendingClasspathEntries/>
</scriptApproval>
```

If I manually approve the signatures the job will run successfully, even after I re-apply the JCasC config.

The job I'm running is just a job that reapplies the JCasC config:

```yaml
jobs:
  - script: >
      folder('Management')
  - script: >
      job('JcasC') {
        steps {
          systemGroovyCommand('''
          import io.jenkins.plugins.casc.ConfigurationAsCode;
          ConfigurationAsCode.get().configure()
          ''') {
            sandbox(true)
          }
        }
      }
```

**Comment by casz** [comment]
Feel free to report in the right please https://issues.jenkins-ci.org using the component `script-security-plugin`

**Comment by akostadinov** [comment]
@cwiggs and for anybody else searching - current working configuration is under `security`. See [here](https://github.com/jenkinsci/script-security-plugin/pull/250/files#diff-cebaf42ace8dcbbcb19447a8ef1435fa).

```
security:
  scriptApproval:
    approvedSignatures:
    - method java.net.URI getHost
```

And it works for me on Jenkins 2.190, casc plugin 1.36 and Script Security plugin 1.68.

**Comment by bradleydamato** [comment]
@akostadinov is this still working for you with Script Security plugin 1.77?

**Comment by cwiggs** [comment]
@bradleydamato I just used JCasC to apply approved signatures today using Script Security Plugin 1.76, JCasC plugin 1.51 on Jenkins version 2.263.1.

**Comment by bradleydamato** [comment]
@cwiggs yes, I'm actually currently having a larger issue of scripts that are already living in scriptApproval.xml requiring re-approval via the UI
