### ISSUE TITLE
No distinction between git and gerrit in Global Pipeline Libraries Source Code Management

### ISSUE THREAD

**Issue by carstensh** [jenkinsci/configuration-as-code-plugin#538]
I'm trying to configure my Global Pipeline Libraries to use plain git, though I also have the gerrit plugin installed for build triggers for other repositories.

The documentation gives me:
modernSCM CONFIGURATOR
Implementation of
Modern SCM
    scm-------------SCMSource
                                 Possible values:
                                 - git
                                 - git
                                 - fromScm

git CONFIGURATOR
Implementation of
Gerrit

and my config file has:

unclassified:
  globallibraries:
    libraries:
    - defaultVersion: "master"
      implicit: true
      includeInChangesets: false
      allowVersionOverride: true
      name: "abs"
      retriever:
        modernSCM:
          scm:
            git:
              gitTool: "git"
              id: "abslib"
              remote: "<url of remote repo>"

but this is set up as Gerrit repository in Jenkins. How can I specify to use plain git?

Thanks

**Comment by lucamilanesio** [comment]
@ndeloof thanks for the fix. Reviewing and addressing it now 😄

**Comment by lucamilanesio** [comment]
https://github.com/jenkinsci/gerrit-code-review-plugin/pull/9 has been merged

**Comment by carstensh** [comment]
I tried re-running with the latest released version of the plugin, but now I get this error message:

Configuration as Code obsolete file format:
  'git' is obsolete, please use 'gerrit'

and the repository is still set up as a Gerrit repository

Thanks

**Comment by lucamilanesio** [comment]
@carstensh let me try myself.

**Comment by carstensh** [comment]
Great, thanks!  Just for reference, this is my config yaml:

`
  globalLibraries:
    libraries:
      - name: "abslib"
        defaultVersion: "master"
        implicit: true
        allowVersionOverride: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "<url to repo>"
`

**Comment by ndeloof** [comment]
CasC should _first_ consider canonical symbol _then_ use fallback, which is colliding in this specific case. But at least when using the canonical it should be ok.
Sounds like we need a fix for this.

**Comment by casz** [comment]
This is already fixed as evident by #648

**Comment by felipecrs** [comment]
This seems to have not been fixed yet. I'm using latest versions of everything.

![Image](https://github.com/user-attachments/assets/28e89b63-60bc-4b8e-9183-03ab554f5bda)

![Image](https://github.com/user-attachments/assets/2dde8075-6db8-4df7-a7a2-5cceed3ca68c)
