### ISSUE TITLE
Do not prevent startup when configuration is invalid

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#553]
Currently, if the yaml configuration is invalid, the plugin throws an exception during initialization and thus prevents Jenkins startup. See for example https://github.com/jenkinsci/configuration-as-code-plugin/issues/550

Coupled with the fact that the Jenkins code model is so complex (as mentioned as one of the arguments for having this plugin), it makes it hard to write new configuration unless there are examples in this repo.

It would be easier to work with if the plugin just logged an error but did not prevent startup. It is a bit scary migrating to this plugin if I get punished for mistakes.

**Comment by ewelinawilkosz** [comment]
it should be taken into account when implementing #542

**Comment by ndeloof** [comment]
so the "check-configuration" CLI and endpoint so you don't need to restart jenkins to give yaml configuration a try. You also should test your yaml configuration with an isolated jenkins instance, not directly on your production master.

As in #542 our diagnostic message is terrible and need some significant improvements.

> It would be easier to work with if the plugin just logged an error but did not prevent startup

doing so I can imagine configuration not being well applied as expected on a fresh new instance and jenkins being exposed on the network with security not well set. I prefer being safe than sorry.

**Comment by martinmosegaard** [comment]
@ndeloof Thank you for the explanation. Do you have more information on how to call the "check-configuration" CLI or endpoint, or how to use the dry-run feature also mentioned in #542 ?

I could not find it in the README, and I don't know what it means that "full documentation is generated from a live instance", so I don't know where else to look. Thanks.

**Comment by ndeloof** [comment]
see JENKINS_URL/configuration-as-code on your instance for available commands and generated documentation (=> /configuration-as-code/reference)

CLI : install https://wiki.jenkins.io/display/JENKINS/Jenkins+CLI and run `help`, will list available commands, including the configuration-as-code related ones (apply-configuration and check-configuration)

endpoint:  post yaml to JENKINS_URL/configuration-as-code/check

README and plugin documentation needs some huge re-organization and polishing effort, way too confusing and missing features.

**Comment by martinmosegaard** [comment]
This may be related to general Jenkins HTTP calls, but it doesn't work great for me. First, I have to disable CSRF protection in order to POST to localhost. Then, if I have this config:

```
$ cat jenkins.yaml
jenkins:
    numExecutors: 2
```

I get this:

```
$ curl -XPOST http://127.0.0.1:8080/configuration-as-code/check -T jenkins.yaml
... a bunch of html ...
<p>A problem occurred while processing the request.
        Please check <a href="https://jenkins.io/redirect/issue-tracker">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="https://jenkins.io/redirect/users-mailing-list">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at io.jenkins.plugins.casc.yaml.YamlSource@27cb4d37  in org.kohsuke.stapler.RequestImpl@372b0ee9, line 2, column 19:
        numExecutors: 2
                      ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:94)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:80)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:80)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:38)
Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read io.jenkins.plugins.casc.yaml.YamlSource@27cb4d37
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:41)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:104)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:552)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:547)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doCheck(ConfigurationAsCode.java:363)
...
```

(If I just have a `systemMessage` in the config, it seems to work fine, as `[]` is returned.)

**Comment by ndeloof** [comment]
for use from command line you better should rely on CLI. 
REST api is for integration (typically, IDE support)
