### ISSUE TITLE
API / Running as a pipeline

### ISSUE THREAD

**Issue by hibbert** [jenkinsci/configuration-as-code-plugin#564]
Hi,

I'd want to use this for bootstrapping multiple jenkins masters. At the moment I can't see a way of using the API providing a config file, variables such as vault tokens etc and then making it run. It would also be nice to run it via a pipeline.

Thanks

**Comment by ndeloof** [comment]
Can you please elaborate on your usage scenario ? I actually don't understand what you're looking for.

> It would also be nice to run it via a pipeline.

Do you mean Jenkins master to re-configure itself ? So a programmatic equivalent of the "reload" UI action ?

**Comment by hibbert** [comment]
No worries, I'm now doing this via the docker image, setting CASC_JENKINS_CONFIG and putting my yaml files in that location + using secrets / environment variables to configure the jenkins with k8s. This way it should run when we spin up a new jenkins and on boot. It could be nice if there was an API to reapply it when it is still up though, sort of correct any misconfigurations. We're looking to bootstrap a slim configured jenkins for different teams and then they will continue the setup.

A few niggly things for me:-

* The CASC_JENKINS_CONFIG can be altered from the UI and is not overridden on boot. I don't think this is ideal, preferably you shouldn't be able to override this at all, it should all come from code with the UI just for exporting config / reloading config
* Vault token displayed in jenkins system information not such a problem because the token would be short lived but ideally if possible this shouldn't be viewable

**Comment by ndeloof** [comment]
relying on environment for credentials is indeed a bad practice, but we need some way to get this token. Or some way to tell Jenkins this specific env var should be hidden/excluded from web UI. Suggestions are welcome
