### ISSUE TITLE
Cannot export Log Parser plugin configuration

### ISSUE THREAD

**Issue by kelvSYC-twitter** [jenkinsci/configuration-as-code-plugin#565]
When attempting to export configuration for the Log Parser Plugin, the resulting yaml file contains a stack trace:

    FAILED TO EXPORT hudson.plugins.logparser.LogParserPublisher$DescriptorImpl
    java.lang.IllegalAccessException: Class io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator can not access a member of class hudson.plugins.logparser.LogParserPublisher$DescriptorImpl with modifiers \"private\"
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
    at java.lang.Class.newInstance(Class.java:436)
    at io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator.describe(DescriptorConfigurator.java:64)
   ...

Looking at the source code to the Log Parser Plugin, this is likely in reference to the constructor to the `DescriptorImpl`, which is private. This may require some specialized support to export, and maybe configure as well.  (Keep in mind that this plugin has not been updated for years.)

**Comment by oleg-nenashev** [comment]
It would be preferable to have a Jenkins JIRA issue for it

**Comment by ndeloof** [comment]
for those interested in an easy fix

see https://github.com/jenkinsci/log-parser-plugin/blob/master/src/main/java/hudson/plugins/logparser/LogParserPublisher.java#L203

need to replace hand-written data binding with `req.bindJson()` invocation and adequate setters.

Can at same time fix https://github.com/jenkinsci/log-parser-plugin/blob/master/src/main/resources/hudson/plugins/logparser/LogParserPublisher/global.jelly sot it use `field` for data-binding as well as standard path for help files

**Comment by jonbrohauge** [comment]
With massive help from @slide, I'm working on a PR to the plugin.

**Comment by jonbrohauge** [comment]
Added PR: https://github.com/jenkinsci/log-parser-plugin/pull/24 to https://issues.jenkins-ci.org/browse/JENKINS-53864

**Comment by jonbrohauge** [comment]
Linking: https://github.com/jenkinsci/configuration-as-code-plugin/issues/809

**Comment by casz** [comment]
Closing, there is an ongoing effort in the right spot. https://github.com/jenkinsci/log-parser-plugin/pull/24
