### ISSUE TITLE
Move RoleStrategy demos from test to the demo folder

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#567]
Currently YAML samples are listed here: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/integrations/src/test/resources/io/jenkins/plugins/casc

It would be great to have them also listed in the demo directory

**Comment by jonbrohauge** [comment]
@oleg-nenashev Are you suggesting a raw copy and paste operation or a more sane, well considered update of the current demos based on the test resources?

**Comment by oleg-nenashev** [comment]
Whatever works. Copy-paste is probably OK as well, while RoleStrategy
support is embedded

On Oct 2, 2018 11:34, "Jon Brohauge" <notifications@github.com> wrote:

@oleg-nenashev <https://github.com/oleg-nenashev> Are you suggesting a raw
copy and paste operation or a more sane, well considered update of the
current demos based on the test resources?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/configuration-as-code-plugin/issues/567#issuecomment-426210469>,
or mute the thread

**Comment by ndeloof** [comment]
as we move the demo we should also move this custom configurator to https://github.com/jenkinsci/role-strategy-plugin

**Comment by jonbrohauge** [comment]
Are you thinking about this PR: https://github.com/jenkinsci/role-strategy-plugin/pull/38 ?

**Comment by ndeloof** [comment]
this one is obsolete (was created to prepare the migration). We should prepare a fresh new one based on the current API and implementation.

**Comment by jonbrohauge** [comment]
@ndeloof Maybe this issue needs a new/better title since the _move demos_ part is done?

**Comment by jonbrohauge** [comment]
Created a Jira for moving the code: https://issues.jenkins-ci.org/browse/JENKINS-53931

**Comment by oleg-nenashev** [comment]
This issue was only for the demo part, not for the code migration. But thanks for the follow-up issues!
