### ISSUE TITLE
sync integration test resources into demos?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#580]
@ewelinawilkosz @oleg-nenashev @ndeloof
Inspired by #567, I was wondering if you guys (the all knowing plugin maintainers) would be interested in  having the resources from the integration tests (i.e. *.yaml) synced into/with their respective demos? Basically updating the relevant READMEs and updating/creating an example yaml-file

**Comment by ewelinawilkosz** [comment]
closing it, there is another initiative with the same goal - to ensure demos are really working
