### ISSUE TITLE
Better overview of releases

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#582]
Today, my Jenkins tells me there is a 1.1 update to configuration-as-code.
But it is hard to see the changelog.

- This page does not yet mention 1.1: https://wiki.jenkins.io/display/JENKINS/configuration+as+code+plugin
- The releases tab show a `parent-1.1` tag with a compressed file for download, but no changelog: https://github.com/jenkinsci/configuration-as-code-plugin/releases
- git log shows the same tag `parent-1.1` from October 5th, and the previous tag `configuration-as-code-1.0` from September 12.
- The changelog file, https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CHANGELOG.md, is no good.

It is hard for me to see if I should update. At least a commit like 41e9ad8 would be nice to see in a changelog.

**Comment by ndeloof** [comment]
We had to run a security release, so some documentation steps have been missed.
