### ISSUE TITLE
Cannot configure Build Failure Analyzer permissions

### ISSUE THREAD

**Issue by kelvSYC-twitter** [jenkinsci/configuration-as-code-plugin#588]
It appears that CasC cannot properly configure permissions associated with the Build Failure Analyzer plugin, mainly as `PermissionFinder.findPermissionId()` returns null when giving a permission string such as `Build Failure Analyzer/RemoveCause`, which appears to be a correct string provided by the UI.

As an aside, the error message shown when Jenkins is unable to configure this permission is not very helpful; it only shows that there is a null somewhere, and maybe that the null is caused by the fact that the `Permission` object was null, but not immediately apparent that it was because `PermissionFinder.findPermissionId()` returned null.

This was filed as [JENKINS-53865](https://issues.jenkins-ci.org/browse/JENKINS-53865) in the JIRA.

**Comment by ndeloof** [comment]
which version of configuration-as-code-plugin are you using ?
"Build Failure Analyzer/RemoveCause" should resolve to a valid permission in 1.1  (https://github.com/jenkinsci/configuration-as-code-plugin/commit/60da76fdbf8891ed1b92fb1e414a051660a95713#diff-d8fa53ed003d7c9b72564e21e6e636db)

**Comment by kelvSYC-twitter** [comment]
This was on 1.0; 1.1 was not available when I filed JENKINS-53865.
