### ISSUE TITLE
Add toml support

### ISSUE THREAD

**Issue by meekrosoft** [jenkinsci/configuration-as-code-plugin#593]
Hi,

Would you accept a pull request to add toml configuration file support?
https://github.com/toml-lang/toml

It is becoming a popular alternative to yaml in cloud native projects:
https://github.com/toml-lang/toml/wiki#projects-using-toml

Here you can see a side-by-side syntax comparison:
https://gist.github.com/oconnor663/9aeb4ed56394cb013a20

Best,
Mike

**Comment by ndeloof** [comment]
we could indeed introduce a SPI for getting various formats supported to provide a configuration tree. We already have abstracted away the yaml nature of our configuration (to avoid adherence to snakeyaml dependency)

**Comment by casz** [comment]
@meekrosoft feel free to open a PR with toml support, closing this for now.
