### ISSUE TITLE
[Feature] Redeployment after yaml updated

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#6]
When we update the global configuration in jenkins.yml in the git repository, we need the jenkins master to refresh the configuration without restarting.

**Comment by ndeloof** [comment]
We can expose a web hook to (re)run configuration-as-code on a live instance, so the yaml configuration is applied again. 
We could even offer this as a custom github web-hook implementation

**Comment by ndeloof** [comment]
This can be implemented by calling `ConfigurationAsCode#configure()` after yaml config content has been refreshed. Remaining question is to detect such change occurred.
Simplest option I have in mind is for use to expose an `UnprotectedRootAction` so some external tooling can notify jenkins on update, typically

1. config.yml is managed by Chef recipies
1. chef agent run and updates this content
1. chef recipe do notify jenkins on update

(or comparable mechanism based on kubernetes' ConfigMap, docker Config, local git clone, etc)

configuration-as-code would then track configuration file by checksum, and will actually re-configure only if some actual changes have been detected.

We could also rely on `inotify` (`java.nio.file.WatchService`) to re-configure immediately on file updates.

**Comment by ndeloof** [comment]
Suggest we first implement a `ManagementLink` to offer some UI for configuration-as-code (which files where loaded, last time loader, etc) and a human friendly "reload" button.
Then we could also have various implementations for opt-in reload mechanisms:

- [ ] watch files
- [ ] SIGHUP support 
- [ ] web hook
- [ ] ...

such options being manageable by configuration-as-code for sure !

**Comment by fwilhe** [comment]
I'm trying to find info how to trigger reloading the config via hook on github. Is this implemented? How does it work?
