### ISSUE TITLE
Add support of authorizationStrategy to JenkinsConfigurator

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#60]
Currently there is no way to pass authorizationStrategy for Jenkins instance. The plugin injects NOOP setter for that.

I hit if for Role Strategy in #48, @kohsuke hit it for Unsecure Strategy at the same time

**Comment by ndeloof** [comment]
strange, milesone 1 demo do set authorizationStrategy: loggedInUsersCanDoAnything

**Comment by oleg-nenashev** [comment]
@ndeloof That works because it is a default strategy value 🤷‍♂️
