### ISSUE TITLE
The 'replace configuration source' entry field should trim leading whitespace instead of failing

### ISSUE THREAD

**Issue by pcrews** [jenkinsci/configuration-as-code-plugin#607]
Whenever data entered into the 'replace configuration source' field contains leading whitespace such as:
`  PATH` vs.  `PATH`, we fail with the following error:
java.net.URISyntaxException: Illegal character in path at index 0: `  $PATH_TO_FILE`
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
Caused: java.lang.IllegalArgumentException: Illegal character in path at index 0: `  $PATH_TO_FILE`

Discovered this as I have two similar files and was trying to cut and paste currently listed source file as both names are similar.  The cut and paste from the 'configuration loaded from' data field contains leading whitespace that triggered this bug.

Would believe that desired behavior would be to trim whitespace from data entered into this field vs. hard failing as it currently does.

**Comment by casz** [comment]
This was fixed in #768
