### ISSUE TITLE
Documentation page not found

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#620]
To reproduce:
- In Jenkins, go to `/pluginManager`
- click on Configuration as Code, which links to https://plugins.jenkins.io/configuration-as-code
- click on the link https://wiki.jenkins-ci.org/display/JENKINS/Configuration+as+Code+Plugin/configuration-as-code
- this redirects to https://wiki.jenkins.io/display/JENKINS/Configuration+as+Code+Plugin/configuration-as-code which says "Page not found"

It is also different from the wiki linked to in the README.md, which is:
https://wiki.jenkins.io/display/JENKINS/configuration+as+code+plugin 

- [ ] Jenkins version 2.138.2
- [ ] Plugin version 1.1
- [ ] OS Linux

**Comment by sheeeng** [comment]
Found the invalid reference after we do `mvn compile` under `plugin` directory.

```shell
grep  --extended --recursive --line-number --ignore-case \
"Configuration\+as\+Code\+Plugin\/configuration-as-code" .
```

```text
./plugin/target/configuration-as-code-1.3-SNAPSHOT.pom:11:  <url>https://wiki.jenkins-ci.org/display/JENKINS/Configuration+as+Code+Plugin/configuration-as-code</url>
```
