### ISSUE TITLE
Installation of Plugins Through CASC Doesn't Trigger Jenkins Restart

### ISSUE THREAD

**Issue by fishfacemcgee** [jenkinsci/configuration-as-code-plugin#622]
# Description
I'm currently working on defining a new Jenkins box for my organization, using Ansible and this plugin to try to codify as much as possible. One thing I've run into is when Jenkins runs through the initial application/verification of the configuration files, installing a plugin does not seem to trigger a restart. I currently have two config files, with the plugin one named to be read first, alphanumerically. I've also tried having the plugin file named to be read last and it doesn't seem to change anything about whether a restart occurs.

Worth noting, is that the Jenkins UI indicates that a restart is necessary when viewing the Installed Plugins, so that seems to suggest that a restart should happen but is not being triggered.

# Questions
* I noticed there's [behavior](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/plugins/PluginManagerConfigurator.java#L148) in the code for plugin support to detect whether or not a restart should happen. I'm only installing new plugins at the moment, as opposed to updating. Would that suggest that the plugin installation is not throwing the `UpdateCenter.DownloadJob.SuccessButRequiresRestart` error that's expected?
* Is there some way to _force_ a restart through the JCASC plugin?
* I'm triggering the application/verification of JCASC files by forcing Jenkins to restart after the config files are updated.

# Version info
- Jenkins Version: 2.149
- Plugin Version: 1.2
- OS: `CentOS Linux release 7.5.1804 (Core)`

**Comment by fishfacemcgee** [comment]
D'oh. I realize now I was misunderstanding the repo README. I thought

> Current implementation do require a restart if you add a plugin.

Meant that it would restart Jenkins when adding a plugin, but I think it means a manual restart is required. Could someone clarify that?

**Comment by ndeloof** [comment]
You're right that we rely on `SuccessButRequiresRestart` to trigger a restart. I assume the plugin you selected for installation don't ask for it, but then the message you get from web UI is weird.

Please note plugin installation is experimental and mostly hack-ish, if you have any other way to manage plugin installation (maybe relying on [install-plugins script](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh)), go for it.

Also see https://issues.jenkins-ci.org/browse/JENKINS-53767 for need for this as a generic and official tool

**Comment by fishfacemcgee** [comment]
@ndeloof Thanks for the info.

Just to make sure I'm on the same page, plugin installation is actually expected to cause a restart in the current implementation, and not just for plugin updates?

I understand that plugin support is not fully realized yet. I just want to make sure I have an understanding of the current behavior.

**Comment by guice** [comment]
I'm +1'ing this. I'm running into this very same problem. I'm unable to add configurations such as Docker because `docker-plugin` has to be loaded first. But attempting to load `docker-plugin: latest` in the same file as `cloud: \n docker:` configuration is crashing Jenkins on start.

I can't `required:` plugs + configure them in the same configuration file.

**Comment by timja** [comment]
@casz can you close this please?
https://github.com/jenkinsci/configuration-as-code-plugin/pull/769#issuecomment-474399592

**Comment by fishfacemcgee** [comment]
@timja @casz I read up on the removal and I get why it's happening. Just wanted to mention that if/when you add full support for managing plug-ins back in, that'll be greatly appreciated. Managing them through Ansible is a nightmare of manually managed dependencies.

**Comment by casz** [comment]
We won't add them back :smile: 
The work should be done inside Jenkins Core as stated.
This is the issue to pile in on https://issues.jenkins-ci.org/browse/JENKINS-53767

**Comment by fishfacemcgee** [comment]
Hah, fair enough, and thanks for the link.
