### ISSUE TITLE
improve custom introspection code by relying on tiger-type

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#624]
Mechanism to detect attribute type (https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java#L171) could benefit some established utility library bundled with jenkins-core like 
https://github.com/kohsuke/tiger-types

**Comment by casz** [comment]
Shush stale this would definitely be a nice code addition!
