### ISSUE TITLE
[Epic] support IDE autocompletion

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#627]
From live data model we can generate JSON schema, but we could as well generate IDE-specific grammar files to make yaml edition easier with auto-completion error detection.

 - [ ] Atom : https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers
 - [ ] Visual Studio Code : https://code.visualstudio.com/docs/extensionAPI/language-support
 - [ ] InteliJ idea : 
 - [ ] Eclipse : 
 - [ ] NotePad++ : ?
 - [ ] Emacs : ?
 - [ ] Vim : ?

**Comment by oleg-nenashev** [comment]
CC @sladyn98 who works on VS Code
