### ISSUE TITLE
Add support for appRole authentication when retrieving secrets from Vault

### ISSUE THREAD

**Issue by robcoward** [jenkinsci/configuration-as-code-plugin#632]
Please can the Vault integration be enhanced to support AppRole-based authentication.

It should be possible to update VaultSecretSource.java to support passing AppRoleId and SecretId parameters instead of user/password or token, making a call to BetterCloud's loginByAppRole() method to obtain a token instead.

**Comment by casz** [comment]
@robcoward contribution are welcome 🤭🙌
