### ISSUE TITLE
Missing documentation for triggering configuration updates from external sources through jenkins API

### ISSUE THREAD

**Issue by miguelandres3** [jenkinsci/configuration-as-code-plugin#645]
Missing documentation for triggering configuration updates from external sources through jenkins API 

- [2.107 ] Jenkins version
- [1.1 ] Plugin version

**Comment by vaceletm** [comment]
Did you find the end points ?
According to the release notes, there are endpoints available (https://github.com/jenkinsci/configuration-as-code-plugin/commit/dbe88b67dc80535153fe2cca3f57531e427e84fa) but I struggle to identify where they are.

**Comment by casz** [comment]
`doCheck` becomes /check
`doApply` becomes /apply
and urlName is `configuration-as-code` https://github.com/jenkinsci/configuration-as-code-plugin/blob/dbe88b67dc80535153fe2cca3f57531e427e84fa/plugin/src/main/java/org/jenkinsci/plugins/casc/ConfigurationAsCode.java#L108

so logic follows it would be https://your.jenkinsurl.dot/configuration-as-code/check
and
https://your.jenkinsurl.dot/configuration-as-code/apply

**Comment by vaceletm** [comment]
It seems to be the right end points thanks!

Is there any doc we could contribute to to add those informations ?
(Or maybe it's too early in dev stage to make the end points public)

**Comment by casz** [comment]
@vaceletm there is the readme.md, feel free to sent a pull request :)

**Comment by casz** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin#triggering-configuration-reload
