### ISSUE TITLE
Export existing Jenkins configuration to YML

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#65]
To make it really easy migrate already running Jenkins instances to Configuration as Code, or to just use Jenkins itself as _editor_ for the YML file an export functionality should be supplied to the user from our UI footprint.

I imagine a kind of `Export current configuration` button or link, that will show the current Jenkins configuration as YML and make it easy to download it.

The user can then save the YML file to git and other places, and supply it back to a new or existing Jenkins instance to start using Configuration as Code Plugin.

I would expect also to be able to download the needed `plugin.yml` that described the needed plugin on my current instance.

**Comment by jstrachan** [comment]
We'd love to switch to Configuration as Code on Jenkins X - however we're a little too scared to go through all our configuration and figure out the correct YAML equivalent to get a working Jenkins with the new YAML notation. 

If anyone can figure out some way to easily generate a YAML file from a running Jenkins server (whether its a CLI thing or script or hack or real UI thing I don't much care) - I'd be most grateful!!!

**Comment by ewelinawilkosz** [comment]
@jstrachan we will try to figure out a way to do that, don't think it will be a part of first official release though... knowing you're interested (well, actually almost every meetup about JCasC brings that question) will help with prioritisation for sure!

**Comment by ewelinawilkosz** [comment]
I think it even crossed our minds :) but again, we don't want to write xml parser... having it as a workaround could be acceptable and if requests like your are coming we may need to reevaluate

**Comment by ndeloof** [comment]
for the record : pipeline snippet generator is implemented [here](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java)

**Comment by ndeloof** [comment]
A major blocker for me to implement this is one can't create a second `Jenkins` instance, as Jenkins#theInstance singleton will break.

**Comment by ndeloof** [comment]
work started under https://github.com/jenkinsci/configuration-as-code-plugin/tree/export

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/200

**Comment by v7r** [comment]
If someone stumbled on this issue from google search, here is the document on "Exporting configurations" https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configExport.md
