### ISSUE TITLE
unclassified:rebuilddescriptor accesses the incorrect class for configuring the Rebuild plugin.

### ISSUE THREAD

**Issue by markmarkyesyes** [jenkinsci/configuration-as-code-plugin#650]
### Abstract
Currently, the unclassified descriptor supports configuration for the rebuild plugin, but is accessing the [incorrect class for configuring the plugin](https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildDescriptor.java#L11). it accesses a defaulted constructor for the plugin, vs the configurable class found [here](https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildConfiguration.java#L47)

### Followup
I am pretty new to this codebase, but if someone has a suggestion as to how to contribute towards a fix for this, please let me know and point me in the right direction and I will get a PR open.

Thank you

Jenkins version: jenkins/jenkins:lts-slim Docker image
Plugin version: rebuild:latest
OS: MacOS 10.12.6

**Comment by casz** [comment]
All the code in https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildConfiguration.java 

could and should be moved to https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildDescriptor.java

a class that extends GlobalConfiguration is already describable.

How is an action allowed to have a `GlobalConfiguration` as it's descriptor :scream: 
https://github.com/jenkinsci/rebuild-plugin/blob/422197dd370610aecd1c94f80a5b5fb7911518c5/src/main/java/com/sonyericsson/rebuild/RebuildAction.java#L84

**Comment by casz** [comment]
The issue is that 

Rebuild's "Descriptor" ie. global configuration is not JCasC compliant:
https://github.com/jenkinsci/rebuild-plugin/blob/db73761b6a0a754f426f6ddc1ebfa12a932e1154/src/main/java/com/sonyericsson/rebuild/RebuildDescriptor.java#L26-L31

Please follow the very well documented best practice here: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#descriptors-global-configuration

**Comment by casz** [comment]
Consider following this workflow to [report JCasC compliance issue](https://github.com/jenkinsci/configuration-as-code-plugin/issues/new?labels=plugin-compatibility&template=3-plugin-compatibility.md)
