### ISSUE TITLE
Vault token renewal?

### ISSUE THREAD

**Issue by arnulfojr** [jenkinsci/configuration-as-code-plugin#655]
First of thanks for the hard work in the CasC project!

I'm currently running my Jenkins using the Vault secrets source with a vault token. And just wanted to ask if Jenkins periodically renews the vault token?
If so, could you point me to the docs were it is stated, please? I have surfed in the docs and quickly in the code but only found the https://github.com/jenkinsci/configuration-as-code-plugin/blob/14ed26af28/plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/VaultSecretSource.java Vault implementation.

Thanks a lot

**Comment by casz** [comment]
This was fixed in v1.8, work was done in #770 and we even added a test for it.
Since we added tests to vault in #764
