### ISSUE TITLE
add JCasC pipeline step

### ISSUE THREAD

**Issue by imod** [jenkinsci/configuration-as-code-plugin#659]
This is a copy of https://issues.jenkins-ci.org/browse/JENKINS-54463 - but JIRA seems not to be used by this project :(

Like the job-dsl plugin [1], JCasC should also provide a pipeline step to execute/run/import configurations. This would allow us to continuously update any configuration item in Jenkins without any manual interaction (e.g. checkout configs from git and apply it to jenkins). Currently this is only possible for all stuff configurable by the job-dsl plugin.

[1] https://jenkins.io/doc/pipeline/steps/job-dsl/

**Comment by casz** [comment]
addressed by #712

**Comment by imod** [comment]
@casz I agree that #712 does help, but its by far not the same thing - I expect a step top be able to checkout the configuration files from git and apply the changes - using git will make a lot of thing much easier, propagating configuration files to jenkins is a lot more complicated in many environments. So in my case #712 does not help at all.
I do have this issue on my todo list and hopefully I will get to it soon...

**Comment by casz** [comment]
@imod if that's what you expect feel free to contribute 😊 I'd love to see a updated #670 and how you would solve the permission issu

**Comment by imod** [comment]
@casz we solved the same issue for scriptler already...
