### ISSUE TITLE
Allow specification of multiple, specific configuration files

### ISSUE THREAD

**Issue by jamiejackson** [jenkinsci/configuration-as-code-plugin#667]
I'm new to jCasC, but I'd like to be able to have a base configuration, but specify another config file that defines instance-specific configurations.

Example: I've got multiple instances to configure, most configurations of which are common, but nodes are different. (I might have an unusual setup, where my project has a different Jenkins instance per tier, but that's what I have, at the moment.)

Say I had config files like:
```
config/
├── common.yml (defines common configs)
├── instance_1.yml (defines nodes particular to instance_1)
└── instance_2.yml (defines nodes particular to instance_2)
```

docker-compose, for instance, has a similar concept:

`docker-compose -f common-config.yml -f overrides_and_additions.yml ...`

Maybe jCasC could support something like this?

```
CASC_JENKINS_CONFIG=/config/common.yml;/config/instance_1.yml
```

**Comment by torstenwalter** [comment]
As long as those configuration files reside in the same directory you can specify the directory e.g. `CASC_JENKINS_CONFIG=/config/`

**Comment by casz** [comment]
Now with recursive folder search added in v1.8, this should be a non-issue
