### ISSUE TITLE
README on master branch reflects unreleased changes, leading to confusion

### ISSUE THREAD

**Issue by acrewdson** [jenkinsci/configuration-as-code-plugin#673]
Hello maintainers,

Thanks for your work on this plugin, as always. It's awesome.

A small suggestion for making things easier for users: in general a person coming to the project would expect the `README` on master (_ie_ what's shown when you go to the GitHub repo for the first time) to reflect the state of the currently-released version. But it seems like that's not the case, since the `README` currently reflects stuff that'll be in the next (unreleased) version. I lost some time to this confusion today, so I thought I'd pass this suggestion along in case other people may be similarly misled.

On the other hand, if you feel the expectation about the `README` matching the currently-released version is not right, I'd be interested in understanding that perspective, too. I may be mistaken here.

Thanks for considering this.

**Comment by acrewdson** [comment]
Hello @ewelinawilkosz 👋 I think you mentioned 1.4 might be forthcoming soon. Just wanted to check on that. Would be great to get the Vault changes released that are in master. Thanks for your time on this project, it's hugely appreciated.

**Comment by ewelinawilkosz** [comment]
yep, tomorrow is the plan

**Comment by acrewdson** [comment]
@ewelinawilkosz That's great news, thanks again!
