### ISSUE TITLE
collaboration with helm chart 

### ISSUE THREAD

**Issue by Hokwang** [jenkinsci/configuration-as-code-plugin#675]
Hello.

I deployed jenkins (lts version) using helm chart in kubernetes cluster (baremetal).

Recently helm chart is improved below.
  - set Jenkins URL
  - authorizationstrategy configurable
  - securityRealm

This can be also configurable using CasC plugin.

I am confused same feature different way,
so I ask please do co-operation with helm chart and please make more easier for user.
for now, I tried CasC with helm following demo/kubernetes-helm
but create configmap and helm install is uncomfortable.
why don't you add configmap in helm chart's CustomConfigMap ?

Many thanks.

**Comment by HerrmannHinz** [comment]
@Hokwang 
- can u provide a working example? 
- does it requires modifications to the jenkins helm chart? 

also: feel free to open a PR with an updated version of the kubernetes-helm demo.

**Comment by holmesb** [comment]
@Hokwang, with the release of v29 last week, the Jenkins helm chart now fully supports Configuration as Code.  When the CasC keys within the chart's values.yaml are changed, it can reload CasC on-the-fly without restarting Jenkins.  To achieve this, it uses a sidecar container that monitors the configmaps that store CasC and makes an API call to Jenkins to reload CasC. 

I developed this update to the helm chart, and will submit a PR to get the [demo/kubernetes-helm](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/kubernetes-helm) example updated.

**Comment by Hokwang** [comment]
@holmesb  Thanks for your comment.

But for few weeks tested CasC myself, I decided to not use CasC, 
In case of some feature which can control in helm chart, using helm chart is better,
and other feature which can control in CasC only, I should use CasC but there's many errors still now.
