### ISSUE TITLE
Unable to set useAuthenticatedEndpoint from GitLab plugin

### ISSUE THREAD

**Issue by szpak** [jenkinsci/configuration-as-code-plugin#676]
Setting `useAuthenticatedEndpoint` in [GitLabConnectionConfig](https://github.com/jenkinsci/gitlab-plugin/blob/4291a1377f2d53719c6384ad127238f6fe763668/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabConnectionConfig.java#L42) from GitLab plugin fails with:

```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type
classcom.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig : useAuthenticatedEndpoint.
Available attributes : connections
```

The configuration I use:

```
unclassified:
  ...
  gitlabconnectionconfig:
    useAuthenticatedEndpoint: false
```

In addition, that field is not visible in the .../configuration-as-code/reference. This file hasn't been changed since 2017. I wonder if the problem can be related to "Boolean" instead of "boolean" in that class? 

- [x] Jenkins version - 2.121.3
- [x] Plugin version - 1.3
- [x] OS - Linux
- [x] GitLab plugin version - 1.5.10

**Comment by jonbrohauge** [comment]
It's quite possible that the plugin is not "configured" to allow for JCasC to use it, i.e. missing setters/getters or the UI is not compatible. If this is the case, please create an issue at the plugin's issue tracker.

**Comment by szpak** [comment]
Well, I was thinking about that, but the plugin is already [supported](https://github.com/jenkinsci/configuration-as-code-plugin/blob/d06f4c4b40159acc858319d7d126108bb3a65472/integrations/src/test/resources/io/jenkins/plugins/casc/GitLabTest.yml) by casc and only that field is not visible/accessible. It's perfectly fine to set it via UI. There are a setter and a getter. Therefore, I would like to here what's wrong with that class/field to be able to fix it on the GitLab plugin side or to find out there is some limitation in the casc plugin (e.g. with `Boolean` fields) to fix it here.

I might debug it on my own, but I asked first to get know about any obvious reasons.

**Comment by szpak** [comment]
Thanks to a suggestion from @ewelinawilkosz I was able to find a reason (a package visible setter) and proposed a fix upstream (https://github.com/jenkinsci/gitlab-plugin/pull/866).

I also improved a test case for the GitLab plugin (#678) to be merged once the next version of the GitLab plugin is released.

**Comment by casz** [comment]
Closing issue as work is ongoing in the rightful place.
