### ISSUE TITLE
seed script fails to create jobs using job DSL

### ISSUE THREAD

**Issue by imalik-rms** [jenkinsci/configuration-as-code-plugin#684]
- [latest ] Jenkins version
- [1.4] Plugin version
- [docker ] OS

When using following well-indented simple job dsl script to create seed jobs, the startup fails.
The jobs section looks as :
```
jenkins:
  systemMessage: "Welcome to Jenkins "
.
.
jobs:
  - script: >
      job('apps'){}
      job('infra-tools'){}
```

The error seen in docker logs is 
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: jobs: error configuring 'jobs' with class io.jenkins.plugins.casc.support.jobdsl.SeedJobConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:626)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:649)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
	... 13 more
Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.jobs.FreeStyleJob.job() is applicable for argument types: (java.lang.String, script$_run_closure2) values: [infra-tools, script$_run_closure2@5f0b2f55]
```
However same script when run from DSL job manually ran fine.

```
Processing provided DSL script
Added items:
    GeneratedJob{name='apps'}
    GeneratedJob{name='infra-tools'}
Finished: SUCCESS
```

**Comment by ewelinawilkosz** [comment]
do you have configuration-as-code-support plugin installed too?
It is not installed automatically - we have reasons for that :) - but it is required for "jobs:" element to work

**Comment by imalik-rms** [comment]
@ewelinawilkosz yes i have both of them installed
```

  | Configuration as Code PluginThis plugin allows configuration of Jenkins based on human-readable declarative configuration files. | 1.4 |   |  
-- | -- | -- | -- | --
  | Configuration as Code Support PluginCustom configurator to support third-party plugins for the Configuration as Code plugin | 1.4 |   |  


```

**Comment by ewelinawilkosz** [comment]
I need to have a look then, will get back to you!

**Comment by imalik-rms** [comment]
thank you. im not sure if this PR for job-DSL plugin is needed to be merged to be able to make this work?? https://github.com/jenkinsci/job-dsl-plugin/pull/1142

**Comment by imalik-rms** [comment]
ok so i found out the issue after debugging specially using this debugging line -> https://github.com/imalik-rms/configuration-as-code-plugin/blob/7aaa58cbc491018d9e23d63aad61af75c7647c26/support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator.java#L67
 that when you dont have a newline between any job definitions, it screams error 
```
        job('imran') {

        }
        folder("testing") {

        }
```
is interpreted as 
```
        job('imran') {

        }folder("testing") {

        }
```
so it gives `Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 1) No signature of method: javaposse.jobdsl.dsl.jobs.FreeStyleJob.folder() is applicable for argument types: (java.lang.String, script$_run_closure2) values: [testing, script$_run_closure2@28f04c72]` error.
however , the following runs fine since it got newline between jobs/folders DSL definition
```
        job('imran') {

        }


        folder("testing") {

        }
```

**Comment by hak33m16** [comment]
Is there a reason this was closed? Is the behavior as described above expected?
