### ISSUE TITLE
Allow to run Groovy scripts in JCasC

### ISSUE THREAD

**Issue by szandala** [jenkinsci/configuration-as-code-plugin#686]
It would be vital to be able to run Groovy script as part of JCasC configuration.
First of all there will be always something, that when Yaml is insufficient and can be done only using Groovy.
While we can still run Groovy, by putting them in init.groovy.d, it is reasonable to be able to reload them along JCasC configuration

- [ ] Jenkins version: any 
- [ ] Plugin version: 1.2
- [ ] OS: any

**Comment by casz** [comment]
This is currently possible with https://github.com/jenkinsci/configuration-as-code-groovy-plugin

**Comment by szandala** [comment]
I know, I wrote this plugin :p

śr., 10 kwi 2019 o 10:08 Joseph Petersen <notifications@github.com>
napisał(a):

**Comment by casz** [comment]
Just closing a stale issue before the bot gets to it 😉

**Comment by ShailyAggarwalK** [comment]
hi,

I know this is old thread, but I can't get file parameter working to run my groovy script from file. Please share an example for that as well.
