### ISSUE TITLE
hpi:run does not load the plugin

### ISSUE THREAD

**Issue by tgatinea** [jenkinsci/configuration-as-code-plugin#698]
I've followed the README.md and I've setup my intellij environment.
I can launch the hpi:run and I can connect to http://localhost:8080/jenkins but the plugin jcasc in not installed. And therefore, http://localhost:8080/jenkins/configuration-as-code/ is not reachable.

Note that I am able to compile the plugin via 'install -Dmaven.test.skip=true' and that I get a file ./plugin/target/configuration-as-code.hpi

I don't catch what I'm doing wrong.

Jenkins version: 2.150.1
Plugin version: 1.4

**Comment by casz** [comment]
you have to run `mvn hpi:run` from plugin folder 😅

**Comment by tgatinea** [comment]
Oh! Sorry, all my fault. I missed the /plugin that was clearly written in the README.
