### ISSUE TITLE
Offer a Jenkins container image with Configuration as Code plugin install to spin up new Jenkins using our concept

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#70]
To help new users try the concept, there should be a Jenkins Configuration as Code Docker image available that can be started with a pointer to a configuration spinning up a new Jenkins from scratch with the configuration given.

I expect to be the usual Jenkins LTS image, with only two modifications:

  * setup wizard disabled
  * Latest Configuration as Code plugin installed

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/74

**Comment by daniel-beck** [comment]
If this is going to be published (i.e. not to be used with just `docker build`, please have @rtyler integrate it into our usual release flow so this receives security updates in a timely manner.

**Comment by ewelinawilkosz** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/74
https://github.com/Praqma/jenkins4casc
