### ISSUE TITLE
unable to process plugins - mapping values are not allowed here

### ISSUE THREAD

**Issue by deitch** [jenkinsci/configuration-as-code-plugin#700]
**Never report security issues in github or in other public channels (Gitter/Twitter/etc.), follow the instruction from [Jenkins Security](https://jenkins.io/security/) to report it on [Jenkins Jira](https://issues.jenkins.io)**

Please make sure to provide following information in your issue description

- [X] Jenkins version 2.158 (running docker `jenkins/jenkins:2.158-alpine`)
- [X] Plugin version 1.4
- [X] OS Docker for Mac (so technically LinuxKit 4.9.125, but get same issue running on Amazon Linux, CoreOS, etc.)

A basic `plugins` section for `jenkins.yaml` blows up. When I try to run it through the `/configuration-as-code/check` endpoint, I get a large stack trace, but consistently the same error reported, `mapping values are not allowed here`.

This is true no matter which order I place things in `plugins`

```yml
plugins:
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
```

gives the error:

```
mapping values are not allowed here
 in org.kohsuke.stapler.RequestImpl@75e87607, line 1, column 16:
    plugins:  sites:  - id: "default"    url: "http ...
```

while

```yml
plugins:
  required:
    jdk-tool: 1.2
```

gives a similar error:

```
>mapping values are not allowed here
 in org.kohsuke.stapler.RequestImpl@34700bec, line 1, column 19:
    plugins:  required:    jdk-tool: 1.2  sites:  - id ...
                      ^
```

I tried exporting from the `/configuration-as-code/` endpoint, then feeding the export back in, same error.

**Comment by deitch** [comment]
Well, if I try to turn it into something that doesn't fit the API, but has a list rather than a map, I get a parallel error:


```yml
plugins:
  - a: 1
```

Error:

```
sequence entries are not allowed here
 in org.kohsuke.stapler.RequestImpl@f7ff6f9, line 1, column 11:
    plugins:  - a: 1
```

Is anything allowed under `plugins:`?

**Comment by casz** [comment]
I assume this is only for check endpoint? so the actual config works but fails on the check?

**Comment by casz** [comment]
Have you tried attaching a debugger and figure out what's going on?

**Comment by deitch** [comment]
> I assume this is only for check endpoint? so the actual config works but fails on the check?

I wish that were so. I cannot get it to start up cleanly either. I came to the check endpoint through trying to figure out why it would not startup, hoping that would act as a "linter" or "validator" for my `jenkins.yaml`.

I will restart right now and post that error message too.

**Comment by deitch** [comment]
Same thing, unfortunately. Here is the log from Jenkins (trimmed down, of course):

```
INFO: Started all plugins
Jan 22, 2019 2:36:13 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
INFO: Failed to instantiate optional component org.jenkinsci.plugins.kubernetes.credentials.FileSystemServiceAccountCredential$DescriptorImpl; skipping
Jan 22, 2019 2:36:13 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Jan 22, 2019 2:36:14 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
...
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
...
Jan 22, 2019 2:36:14 PM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
...
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
...
Caused by: java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
...
INFO: Jenkins stopped
Jan 22, 2019 2:36:16 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (Timer-0/34) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
	at hudson.model.Descriptor.getConfigFile(Descriptor.java:905)
	at hudson.model.Descriptor.save(Descriptor.java:877)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger$DescriptorImpl$1.run(GhprbTrigger.java:776)
```

**Comment by deitch** [comment]
> I assume this is only for check endpoint? so the actual config works but fails on the check?

Is the check endpoint code different than validation that runs on startup?

**Comment by casz** [comment]
> > I assume this is only for check endpoint? so the actual config works but fails on the check?
> 
> Is the check endpoint code different than validation that runs on startup?

No, but it could be that check endpoint was removing new lines 🙈

Have you tried a basic configuration instead of plugins?

Seems like something is wrong with the file from your exception.
What's your yaml file line endings? CR? might cause trouble 🤣
Ensure you use LF

```
jenkins:
  systemMessage: "Welcome to JCASC!"
```

**Comment by deitch** [comment]
> What's your yaml file line endings? CR? might cause trouble

Doing it all on macOS, so LF only. :-)

> Have you tried a basic configuration instead of plugins?

This will sound silly, but, no, I haven't. I will do so right now. Even so, should plugins not work?

FWIW, I extend `jenkins/jenkins`, run `install-plugins.sh` for all of my plugins (which I extract using some sed/awk magic from my `jenkins.yaml` so everything is ready.

**Comment by casz** [comment]
I'd suggest you setup intellij, open project and create a task for plugin folder with hpi:run and then run it in debug. Figure out what it is failing on https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java#L71

Cause I have no clue 🙈

**Comment by deitch** [comment]
> I'd suggest you setup IntelliJ, open project and create a task for plugin folder with hpi:run and then run it in debug

... he shakes in terror...

**Comment by deitch** [comment]
Well, a perfectly clean one with just the `systemMessage:` works, but removing the plugins from the larger one still doesn't.

That means that it is failing on something in the config file, but won't tell us which?

**Comment by casz** [comment]
Start by reconstructing your yaml file line by line is another option 🤣

**Comment by deitch** [comment]
> Start by reconstructing your yaml file line by line is another option

Heh, that is what I am doing. Or section by section. I wish it had told us what part is bad.

**Comment by casz** [comment]
> > Start by reconstructing your YAML file line by line is another option
> 
> Heh, that is what I am doing. Or section by section. I wish it had told us what part is bad.

It should, depends on the version of JCASC your using. I could be that you have some illegal character that confuses the YAML parser

**Comment by deitch** [comment]
Possible. I am using 1.4, which is the latest as far as I can tell.
