### ISSUE TITLE
No constructor for root element <credentials>

### ISSUE THREAD

**Issue by tgatinea** [jenkinsci/configuration-as-code-plugin#704]
**Never report security issues in github or in other public channels (Gitter/Twitter/etc.), follow the instruction from [Jenkins Security](https://jenkins.io/security/) to report it on [Jenkins Jira](https://issues.jenkins.io)**

Please make sure to provide following information in your issue description

- [ ] Jenkins version
- [ ] Plugin version
- [ ] OS

**Comment by ewelinawilkosz** [comment]
credentials support is currently a part of configuration-as-code-support plugin - check in your installed plugins if you have it and install if not, next try to reload configuration and let me know where it leaves you

**Comment by tgatinea** [comment]
Thank you for your answer. 
That was the root cause of my issue. 
I read the REAME.md of the jcasc plugin, but I did not found any reference for the configuration-as-code-support plugin.
But now that I'm aware of this plugin, I can find that on google.

Again, thanks for your help
