### ISSUE TITLE
add support for Vault namespaces

### ISSUE THREAD

**Issue by markltbaker** [jenkinsci/configuration-as-code-plugin#710]
It's great that this has support for Hashicorp Vault for storing credentials/secrets. But if you are using the Enterprise version, namespace support is needed. This is simply an extra parameter to Vault requests to indicate which 'vault within a vault' the request is for. 

I can see the plugin uses the vault-java-driver to read from Vault and that this does not have namespace support either, so I've opened an issue to resolve that and suggested a solution: https://github.com/BetterCloud/vault-java-driver/issues/148

I should be able to get more time to work on this, if adding namespace support is something the community is interested in? Also, if anyone can review/vote for the issue on the vault-java-driver project that would be useful.

**Comment by markltbaker** [comment]
Dropped in favour of #151 that includes namespaces + other changes.

**Comment by markltbaker** [comment]
arg, wrong button.... have found there is another PR that adds Enterprise Namespace support + support for V2 keyvalue secrets, so will review that instead.   https://github.com/BetterCloud/vault-java-driver/pull/151

**Comment by markltbaker** [comment]
Support MR got approved and merged so will test this and check it works against a live Enterprise Vault instance.

**Comment by timja** [comment]
@markltbaker does this work for you?

**Comment by markltbaker** [comment]
Not had a chance to test properly yet @timja, based on others comments I've been holding off on doing so (and busy with other things)

**Comment by casz** [comment]
_Should_ work, please feel free to reopen the issue 😄

**Comment by markltbaker** [comment]
Sounds good. Thanks!
