### ISSUE TITLE
password for the proxy is not encrypted

### ISSUE THREAD

**Issue by harry-g** [jenkinsci/configuration-as-code-plugin#711]
When exporting the yaml file fith JCasC, the password for the proxy is not encrypted, as opposed to the LDAP password, which is encrypted. 
In General, you want people to be able to export JCasC-YAML e.g. as a template for other Jenkins masters without that they can see secrets.
Also this is contradicting the concept of not being able to see any secrets via Jenkins UI operation.

- [2.150.1] Jenkins version
- [1.4] Plugin version
- [RedHat7] OS

**Comment by ewelinawilkosz** [comment]
please follow the instructions from https://jenkins.io/security/ to report security issue - the issue here will be removed for security reasons
