### ISSUE TITLE
Support bcrypt hashed passwords on disk for users

### ISSUE THREAD

**Issue by mglazer** [jenkinsci/configuration-as-code-plugin#713]
In its current state, in order to create a default user on startup, one must specify the user and the password in plain text inside of a YAML file.

I would like to instead support creation of users which have pre-hashed passwords on disk so a malicious user can't read the passwords from a file on disk.

**Comment by imalik-rms** [comment]
there are many alternatives , i personally prefer using `sops` https://github.com/mozilla/sops

**Comment by mglazer** [comment]
@imalik-rms: I'm not sure I understand. Encryption is different than one-way hash on disk. In this case, Jenkins doesn't need to be able to read the clear text version of the password, it only needs to validate what the user enters matches the hash on disk.
