### ISSUE TITLE
Add documentation for testing yaml export

### ISSUE THREAD

**Issue by timja** [jenkinsci/configuration-as-code-plugin#718]
There's a TODO in the docs which should be filled out
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#model-export-test

snakeyaml looks like a good option

**Comment by imaffe** [comment]
Draft Idea using ```snakeyaml```
1. [snakeyaml documentation page](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation)
2. In external-workspace-plugin JCasC test, the yaml file contains a list of ```diskpool``` and each ```diskpool``` contains a list of ```disk```. But i think they cannot be presented by simple Java collections. So i think introducing some test class like ```DiskPoolTest``` and ```DiskTest``` having all the needed fields and then use snakeyaml to parse them. e. g
```
public class DiskPoolTest {
      List<DiskTest> disks;
      int diskPoold;
      //getters and setters
} 
```
then we can do like ```DiskPoolTest = (DiskPoolTest) yaml.load(); ```. If we do it this way, it can be put in the same folder of the test class. Not sure if this is a good practice. Working on it now.
@timja
