### ISSUE TITLE
Clean-up our Praqma repo we forked from

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#72]
![selection_010](https://user-images.githubusercontent.com/1579826/35812748-226764b8-0a92-11e8-8e4c-1a90d88cca1a.jpg)

Bit confusing to see this message when we actually only today are working in the jenkinsci fork.

We should clean up so they are in sync, or a least the the jenkinsci fork in front.

As being part of Praqma I like this really cool initiative is forked from Praqma's github account, but it doesn't constitute a really good excuse to make it look like a mess.

We also had one contribution to our Praqma repo... so users might also be confused.

If it isn't easy to clean up, we can have Github support staff break the fork.

**Comment by daniel-beck** [comment]
> We also had one contribution to our Praqma repo... so users might also be confused.

Which is one of the reasons we recommend that people delete their origin repo after we fork their plugin -- the confusion is annoying. As is the limitations GH search imposes on forks.

GitHub support can, on request, revert the fork relationship between repos, and make the jenkinsci one the canonical one.

**Comment by buep** [comment]
@ewelinawilkosz we have anything we want to keep in our Praqma repo or should we just delete it?

Deleting it seems to be the best solution, and it will then break the fork as I understand. Only problem is I can't according to GH help be sure which fork becomes the new master: https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository

So I'll probably write to GH support anyway to get them to do it.

**Comment by daniel-beck** [comment]
Yep -- may be one of the personal forks.

**Comment by ewelinawilkosz** [comment]
I don't think there is anything we need to keep from Praqma repo, feel free to remove

**Comment by buep** [comment]
Cleaned up our repo issues, and are ready to delete when GH support answers back they break the fork for us to ensure the jenkinsci becomes the new master

**Comment by buep** [comment]
@ewelinawilkosz @ndeloof the fork relation back to the Praqma repo is now removed by Github support  - they did it only 12 minutes after I asked yesterday ;-)

So this means I'll kill our Praqma version of this repo and this is now our new "master".
