### ISSUE TITLE
Questons related to code as config pluggin

### ISSUE THREAD

**Issue by santosh3702** [jenkinsci/configuration-as-code-plugin#730]
- [ Jenkins ver. 2.150] Jenkins version
- [ 1.5] Plugin version
- [Docker Container ] OS

Hi ,
I am using above configuration for Configuring the Jenkins Configuration as code.

Here Some i am having some questions:

1. How to configure Docker Unix Url(unix:///var/run/docker.sock) in Docker Builder
2. How to configure ZAP Provide URL and port numner  of ZAP
3. How to configure Gerrit trigger

**Comment by ewelinawilkosz** [comment]
hej @santosh3702 - we use issues in github for reporting bugs or missing features, if you're looking for help with configuring specific plugins I encourage you to visit https://gitter.im/jenkinsci/configuration-as-code-plugin and check if anyone there can help. 

In general when any plugin you have installed on your Jenkins is supported by JCasC you should see it in generated documentation: [Your Jenkins URL]/configuration-as-code/reference, and if you can't find anything that looks like the plugin you want to configure, then probably specific plugin is not supported. In that case you can either try to fix it on your own following https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md or hope the plugin maintainer can do that - in both cases you should start with reporting a jira issue with a label `jcasc-compatibility`. Here is a dashboard with all known compatibility issues: https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=17346
