### ISSUE TITLE
configuration-as-code-support-plugin not available

### ISSUE THREAD

**Issue by rdepke** [jenkinsci/configuration-as-code-plugin#731]
**Never report security issues in github or in other public channels (Gitter/Twitter/etc.), follow the instruction from [Jenkins Security](https://jenkins.io/security/) to report it on [Jenkins Jira](https://issues.jenkins.io)**

Please make sure to provide following information in your issue description

- [2.15.2 ] Jenkins version
- [ 1.4] Plugin version
- [CentOS7 ] OS

When I try to build an docker image with the version 1.4 it fails because the plugin is not available on the server.

> [start-build]  > build-monitor-plugin depends on build-failure-analyzer:1.9.0;resolution:=optional,workflow-aggregator:2.4;resolution:=optional,badge:1.2;resolution:=optional,claim:2.8;resolution:=optional,cloudbees-folder:5.16;resolution:=optional,credentials:2.1.10;resolution:=optional,view-job-filters:1.26;resolution:=optional,groovy-postbuild:2.3.1;resolution:=optional
Examining optional dependency build-failure-analyzer
Optional dependency build-failure-analyzer not installed already, skipping
Examining optional dependency workflow-aggregator
Optional dependency workflow-aggregator already installed, need to determine if it is at a sufficient version
Examining optional dependency badge
Optional dependency badge not installed already, skipping
Examining optional dependency claim
Optional dependency claim not installed already, skipping
Examining optional dependency cloudbees-folder
Optional dependency cloudbees-folder already installed, need to determine if it is at a sufficient version
Examining optional dependency credentials
Optional dependency credentials already installed, need to determine if it is at a sufficient version
Examining optional dependency view-job-filters
Optional dependency view-job-filters not installed already, skipping
Examining optional dependency groovy-postbuild
Optional dependency groovy-postbuild not installed already, skipping
Downloading plugin: configuration-as-code from https://updates.jenkins.io/download/plugins/configuration-as-code/1.4/configuration-as-code.hpi

> [start-build]  > configuration-as-code has no dependencies
Downloading plugin: configuration-as-code-support from https://updates.jenkins.io/download/plugins/configuration-as-code-support/1.4/configuration-as-code-support.hpi

> [start-build] Downloading plugin: configuration-as-code-support-plugin from https://updates.jenkins.io/download/plugins/configuration-as-code-support-plugin/1.4/configuration-as-code-support-plugin.hpi

**Comment by ewelinawilkosz** [comment]
the support plugin is called `configuration-as-code-support` not `configuration-as-code-support-plugin` http://mirrors.jenkins-ci.org/plugins/configuration-as-code-support/1.4/configuration-as-code-support.hpi - can you make sure you use the correct name? And can you let us know where did you take `configuration-as-code-support-plugin` from? Maybe there is a bug in our documentation :)

**Comment by jonbrohauge** [comment]
I have seen the postfix _-plugin_ slapped on a number of plugins, if the Jenkins updater cannot find the plugin in question. The error is usually due to an error in the requested version, a typo in the plugin, or an outdated remote plugin-repos. I've tried them all, so I know they are quite possible _root causes_ :wink:

**Comment by casz** [comment]
closing as works as intended
