### ISSUE TITLE
Improve handling secrets in casc.yml file

### ISSUE THREAD

**Issue by askalski85** [jenkinsci/configuration-as-code-plugin#734]
> Tim Jacomb @timja 11:12
> don't put credentials in there
> https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets
> environment variables, docker secrets, kubernetes secrets,
> hashicorp vault are all supported
> you can also write a plugin for additional secret sources
> see: https://github.com/jenkinsci/configuration-as-code-secret-ssm-plugin

However it is not recommended to put credentials to the casc.yml file, it is supported. Regardless if using environment variables or docker secrets all confidential data can be easily exposed by running a simple step on master node.

One of the ideas is to support encrypted passwords. Even if accessed they will not have any use for nobody. During loading of the casc.yml file jenkins will de crypt them and put directly to the credentials store.

**Comment by casz** [comment]
Vault is the improvement you seek, there it won't be easy to export the secrets.
I don't know how you would go about encrypting the password.

We have new `init()` function that is called on each secret source in the `configure()` context. I suggest you send a PR that could fix this issue.

**Comment by MohammadRahaman** [comment]
for Configuration as Code using yaml file -
First I applied environment variables but it doesn't read or replace the variable substitution during run time!
Second I applied docker secrets by convention but it doesn't read or replace substitution during run time.

Now I removed Active Directory configuration and it's create an image but didn't replace the secrets! 

when I use the Active Directory configuration (yaml) at that time jenkins server  hanged/slow  job.

struggling since long time to apply configuration as Code!!!!!

Any suggestions please!

**Comment by timja** [comment]
Have you read this?
https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets

**Comment by casz** [comment]
@MohammadRahaman would be great if you could show us your configuration so we can assist in fixing it.

**Comment by MohammadRahaman** [comment]
I followed same instruction as per handling secrets in configuration as code
[casc.txt](https://github.com/jenkinsci/configuration-as-code-plugin/files/3154292/casc.txt)

when I configured manually /run/secrets/some-password and run that (reload), it's working fine.

**Comment by MohammadRahaman** [comment]
Why it doesn't read /replace secrets during run time!!

**Comment by timja** [comment]
So it's working?
Otherwise will need more details, vault paths etc
also, posting a github gist is a lot easier to look at than a text file

**Comment by MohammadRahaman** [comment]
I launched that image to create an instance and logged in to that server (test) using floating IP, and I  checked configure system it doesn't replace secrets. Here is the logs just I enter below -
[0;32m    openstack: May 07, 2019 4:20:06 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor[0m
[0;32m    openstack: INFO: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ****[0m
[0;32m    openstack: May 07, 2019 4:20:06 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor[0m
[0;32m    openstack: INFO: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ${github_oauth_token}[0m
[0;32m    openstack: May 07, 2019 4:20:06 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor[0m
[0;32m    openstack: INFO: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.username = ****[0m
[0;32m    openstack: May 07, 2019 4:20:06 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor[0m
[0;32m    openstack: INFO: Setting class com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.password = ${openstack_pw}[0m

**Comment by ewelinawilkosz** [comment]
might be very dummy question, but aren't quotation marks messing with the secrets here?
like in: `password: "${openstack_pw}"`
did you try without it? e.g. `password: "${openstack_pw}"` 
@casz or @timja please correct me if I'm talking nonsense :)

**Comment by timja** [comment]
The docs have it in both forms @ewelinawilkosz 
https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets

Mostly documented with quotes though

**Comment by timja** [comment]
@casz as far as I'm aware you can already load in encrypted secrets? 
hudson.util.Secret.fromString("value").getEncryptedValue()

not the easiest to automate up front as the secret key will be generated on first startup

so I think you can do what the issue asks for but it's not the easiest

**Comment by MohammadRahaman** [comment]
@ewelinawilkosz 
I applied both way quotes and without quotes none of them approach are working!!

@casz 
I used yaml file, jenkinsfile, packer template and shell script

jenkinsfile -
		dir("scripts/casc_config/secrets") {
			writeFile file: "artifactory_api_key", text: artifactory_vars.artifactory_api_key
			writeFile file: "github_oauth_token", text: github_oauth.github_oauth_token
			writeFile file: "openstack_pw", text: openstack_vars.openstack_pw
			writeFile file: "domain_password", text: jdnet_vars.domain_password
		}

in packer -
{
		"type": "file",
		"source": "./scripts/casc_config/secrets",
		"destination": "/run",
		"generated": true
	},
-----------
------------
	{	"type": "file",
		"source": "./scripts/casc_config",
		"destination": "/tmp"
	},

in configure jenkins shell script -
#Creating Jcasc folder where we keep all jcasc config files
mkdir -p $jenkins_home/jcasc_config

#Copy Files to jcasc config folder
cp -r /tmp/casc_config/ $jenkins_home/jcasc_config
chown -R jenkins:jenkins "$jenkins_home/jcasc_config"
chown -R jenkins:jenkins "/run/secrets/"

#Setting up the CASC base folder
echo "CASC_JENKINS_CONFIG=\"$jenkins_home/jcasc_config\"" >> /etc/environment

#Cleanup jcasc config
rm -r /tmp/casc_config

that's all! Any suggestion please!!

**Comment by timja** [comment]
It looks right to me, are you positive it's not working? It won't log the secrets when it replaces them

You can see what the values are by running this in the script console:
https://gist.github.com/timja/04afb12c8ad909e400317a2ad9c88445

May need to remove any plugins you don't have installed like the azure one

**Comment by casz** [comment]
Can you try a simple example:

```
echo "CASC_JENKINS_CONFIG="$jenkins_home/jcasc_config"" >> /etc/environment
echo "MYSECRET="HELLO WORLD"" >> /etc/environment
```

inside your `$jenkins_home/jcasc_config/jenkins.yml`
```
jenkins:
  systemMessage: "${MYSECRET:-NO SECRET}\n\nJenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
```

**Comment by MohammadRahaman** [comment]
@casz 

> inside your $jenkins_home/jcasc_config/jenkins.yml as the only file inside the folder

yes only this file jenkins.yml

> Are you sure that the /etc/environment content is correct? is the jenkins_home expanded? and is the quoting correct?

I think so! if you've any suggestion or need to modify please tell me then i will apply

>  is the jenkins_home expanded? and is the quoting correct? 

Can you please elaborate more! I am not clear!

**Comment by casz** [comment]
@MohammadRahaman please `cat /etc/environment` and check if the `$jenkins_home/jcasc_config` inside `/etc/environment` is expanded correctly.
Otherwise, you have to inside the `/etc/environment` also set the `$jenkins_home` environment variable

**Comment by casz** [comment]
At this point, this is a basic Linux environment setup issue and has nothing to do with JCasC so far.

**Comment by casz** [comment]
Could you share your `/etc/environment` content?

please just copy paste inside a code block.

``````
```
my code here
```
``````

**Comment by MohammadRahaman** [comment]
@casz 
```
root@test-casc-plugin:~# cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
CASC_JENKINS_CONFIG="/var/lib/jenkins/jcasc_config"
```
please tell me is this ok otherwise 

How do I expand ```$jenkins_home```?

**Comment by casz** [comment]
`CASC_JENKINS_CONFIG="/var/lib/jenkins/jcasc_config"` seems that `$jenkins_home` expanded to `/var/lib/jenkins` which is correct 😅 

Did you try my basic example of secret?

by echoing this `echo "MYSECRET="HELLO WORLD"" >> /etc/environment` into `/etc/environment` 

and then set the content of `jenkins.yml` to
```
jenkins:
  systemMessage: "${MYSECRET:-NO SECRET}\n\nJenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
```

**Comment by casz** [comment]
You could also use the `/run/secrets/MYOTHERSECRET` and then inside the systemMessage:
```
jenkins:
  systemMessage: "${MYSECRET:-NO SECRET}\n\n${MYOTHERSECRET:-NO FILE SECRET}\n\nJenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
```

Remember Linux is case sensitive so the filename `KEY` has to match the secret `${KEY}`

**Comment by casz** [comment]
How do you start `Jenkins` systemd or command? Are you sure it running under the `jenkins` user

**Comment by MohammadRahaman** [comment]
when run it manually it's work and replace secrets in configuration but it doesn't work when i try to build job and secrets on the fly!!

**Comment by casz** [comment]
@MohammadRahaman JCasC secrets are not shared outside of JCasC context, `jobs` node in `*.yml` files has JCasC secret context because is apart of the JCasC context.

You have to create credentials in JCasC and use pipeline steps or freestyle configuration to expose those credentials to the steps that need them.

See
https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials

Please do not confuse your Jenkins pipeline scripts with JCasC.
JCasC is only intended for global configuration and initial jobs configuration.

**Comment by casz** [comment]
[See the demos on how to create credentials inside JCasC](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials)

**Comment by MohammadRahaman** [comment]
@casz 

So how can I pass my environment variables / docker secrets (by convention) if it's not supported on the fly!!

Do I need to create separate environment variable files as the same folder where I kept my jenkins.yaml file and using that environment variables from that folder!! 
If so how can I keep in safe our secrets!! 
Or this is one time activity, once JCasC plugin is fully up means passing all environment variables during build job in jenkins and creating an image then delete all secrets!! Is this you are talking about if I understood right!

And JCasC can't read the environment variables from other places! it has to be as the same place means same folder where yaml file are there!
Though our all environment variables are set up in production server where we run the jenkins job!

**Comment by MohammadRahaman** [comment]
@casz 

root@test-casc-plugin:/var/lib/jenkins/jcasc_config# echo "MYSECRET="HELLO WORLD"" >> /etc/environment
root@test-casc-plugin:/var/lib/jenkins/jcasc_config# vi jenkins.yml

![sample code](https://user-images.githubusercontent.com/50378758/57408322-f4fb4e00-71aa-11e9-9f02-7403e689d851.PNG)

here is the sample code output which I run manually !

**Comment by casz** [comment]
What version of JCasC are you using?
I think you need to understand what JCasC is trying to solve.
A declarative way of provisioning your Jenkins.

**Comment by MohammadRahaman** [comment]
@casz 

JCasC version 1.14

**Comment by casz** [comment]
... your running as root in the commands you show above... 
Yet the files are protected and owned by `jenkins` user?

Would you consider running Jenkins inside a docker image?

**Comment by MohammadRahaman** [comment]
@casz 

> Would you consider running Jenkins inside a docker image?

No, it's not allowed

>  JCasC secrets are not shared outside of JCasC context, jobs node in *.yml files has JCasC secrets context because it is apart of the JCasC context.

what do you mean by outside of JCasC context?  Can you please clarify!

> You have to create credentials in JCasC and use pipeline steps or freestyle configuration to expose those credentials to the steps that need them

You meant I've to create all of the credentials in JCasC folder same as yaml file where I kept. When we build job in jenkins on that time it will read or passing values from that folder where I kept jenkins.yaml file (var = value, and yaml file just mention like that ${var})! I've to remove everything from jenkinsfile which is related with JCasC. If my understanding is right!

**Comment by casz** [comment]
I honestly cannot help you.

**Comment by timja** [comment]
I'm going to close this as I can't see any specific ask here, feel free to open again with concrete suggestions or come chat on gitter https://gitter.im/jenkinsci/configuration-as-code-plugin

**Comment by CollinLeishman** [comment]
If you are here because you've been following this tutorial(or a similar one) https://www.digitalocean.com/community/tutorials/how-to-automate-jenkins-setup-with-docker-and-jenkins-configuration-as-code

You probably skipped adding `configuration-as-code:latest`  to plugins.txt!
For me, I went to our long running jenkins instance and got the plugins that were installed instead of copying the ones in the tutorial. Hoping this helps anyone else who did the same.

**Comment by mvrabel** [comment]
@askalski85 @MohammadRahaman 
Encrypted [passwords are possible, it's even in the official documentation.]( https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/embedded-userdatabase).
I've found it after hours and hours of searching kind of by accident. 

It's the best currently possible way to store passwords in .yaml files IMO.

```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "hashedadmin"
          # password is 'password'
          password: "#jbcrypt:$2a$10$LP4bMhwyCPnsDm.XRcTZSuBqWYKGAiDAsQXrSrJGYcEd9padaPgsC"
```
It's mind blowing that no blog/tutorial/reference/SO answer references it.

There's one catch, **you have to create the hash with Java implementation**. Python hashes don't work with Jenkins.

In general hashes from one implementation to another are compatible like this:
java -> java ✅ 
java -> python ✅ 
python -> python ✅
python -> java 🟥

**Comment by thehale** [comment]
<sup>I know this is a late comment on an old discussion. Adding some updated context for future me's...</sup>

> There's one catch, you have to create the hash with Java implementation. Python hashes don't work with Jenkins.

Python generated hashes appear to be identical now (Python 3.9.21, [bcrypt==4.2.1](https://pypi.org/project/bcrypt/))

```python
>>> import bcrypt; bcrypt.hashpw(b"password", salt=b"$2a$10$LP4bMhwyCPnsDm.XRcTZSu")
b'$2a$10$LP4bMhwyCPnsDm.XRcTZSuBqWYKGAiDAsQXrSrJGYcEd9padaPgsC'  # Same as the JCasC example
```

**Generate a Jenkins password hash with Python**
```python
import bcrypt
jenkins_hash = "#jbcrypt:" + bcrypt.hashpw(b"password", bcrypt.gensalt(prefix=b"2a")).decode()
```

> [!NOTE]
> The password hash [must be prefixed with `#jbcrypt:`](https://github.com/jenkinsci/jenkins/blob/23f2b9ef593320719b617fee135d3890a8e78fda/core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java#L1071) for JCasC to identify the string as a password hash, even if the hash was generated from a different programming language's bcrypt implementation.
> 
> Additionally, [Jenkins only accepts `2a` for a salt prefix](https://github.com/jenkinsci/jenkins/blob/23f2b9ef593320719b617fee135d3890a8e78fda/core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java#L947) -- any other common bcrypt prefix (e.g. `2b`, `2x`, `2y`) results in `java.lang.IllegalArgumentException: The hashed password was hashed with the correct algorithm, but the format was not correct`.
