### ISSUE TITLE
When config url env var changed plugin still uses old url from global config

### ISSUE THREAD

**Issue by angry-cellophane** [jenkinsci/configuration-as-code-plugin#739]
The case:
1. There is a jenkins instance with the plugin installed running in a docker container. JENKINS_HOME directory is kept on persistent storage, so all jenkins config files are persistent.
2. CASC_JENKINS_CONFIG env variable is set up and points to https://my-config-server.com/branch1/jenkins.yaml
3. Jenkins needs to be upgraded to a new docker image. Some plugins have breaking changes so the config url should be changed as well.
4. CASC_JENKINS_CONFIG env variable changed to https://my-config-server.com/branch2/jenkins.yaml, docker container restarted with the new image.

Expected result: jenkins fetches the yaml config file from branch2.
Actual result: jenkins fetches the config file from from branch1.

As I see the reason for it is this line of code - https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L304
```java
    private List<String> getStandardConfig() {
        List<String> configParameters = getBundledCasCURIs();
        CasCGlobalConfig casc = GlobalConfiguration.all().get(CasCGlobalConfig.class);
        String cascPath = casc != null ? casc.getConfigurationPath() : null;

        String configParameter = System.getProperty(
                CASC_JENKINS_CONFIG_PROPERTY,
                System.getenv(CASC_JENKINS_CONFIG_ENV)
        );

        if (!StringUtils.isBlank(cascPath)) {
            configParameter = cascPath;
        }
        // ....
}
```

That means if there is already a url in the global config Jenkins will never use other options like env var. It causes an issue with the case of running jenkins in docker and requires interaction with Jenkins (change the caas plugin's global config first and dump it onto the disk) in order to change the config's url (that will fail in case of breaking changes in some other plugins).

- Jenkins version - 2.150.1
- Plugin version - 1.4

**Comment by angry-cellophane** [comment]
So what do you think about using system property/env var over global config all the time? Any issues with this approach?

**Comment by angry-cellophane** [comment]
Still relevant

**Comment by casz** [comment]
Feel free to contribute :sweat_smile:

**Comment by angry-cellophane** [comment]
too late, already merge :)

**Comment by casz** [comment]
Wanted to get a release out the door :package:
