### ISSUE TITLE
Requesting better Exception for environment variable reference

### ISSUE THREAD

**Issue by Manny2014** [jenkinsci/configuration-as-code-plugin#742]
**Never report security issues in github or in other public channels (Gitter/Twitter/etc.), follow the instruction from [Jenkins Security](https://jenkins.io/security/) to report it on [Jenkins Jira](https://issues.jenkins.io)**

Please make sure to provide following information in your issue description

- [2.165] Jenkins version
- [1.5 ] Plugin version
- [ Docker-ce 18.09.2] OS

REQUEST:

Requesting that the execption returns the ${VARIABLE} name that is not able to find, as opposed to a Null pointer exception.

CURRENT ERROR:

java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696

**Comment by casz** [comment]
Without a full stack trace, it can be hard to know which line you're suggesting an improvement for. Feel free to contribute.
