### ISSUE TITLE
Create and maintain a casc demo instance online

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#75]
To show the concept for real and running we have discussed to have a demon instance running live people can visit and also browse the documentation and configuration of as we propose it to be used.

We can host such one in Praqma, and I see two options for us:

  1. our current Jenkins cloud instance running the old concept JenkinsAsCodeReference could be migrated casc, but we miss a series of plugin to do that
  2. we could create an deploy a new one we where we would then only host this plugin and a pipeline for it

No matter what option we go for, we should point the users to this "demo" instance as an example and supply them with information like:

  * our `jenkins.yml` and `plugin.yml` files - public repository
  * documentation on how we maintain the instance (deployment, upgrades etc)
  * how they could clone the project, and create a copy test instance of it themselves (without our credentials it would only work with how far their own credentials reach though)

**Comment by ndeloof** [comment]
This could be hosted on jenkins.io infrastructure. I'm sure @olblak would be happy to handle this for us

**Comment by ndeloof** [comment]
created https://issues.jenkins-ci.org/browse/INFRA-1494 for this

**Comment by ndeloof** [comment]
This doesn't really make sense anymore
