### ISSUE TITLE
Why not recurse in subdirectories searching for yaml files

### ISSUE THREAD

**Issue by readerx** [jenkinsci/configuration-as-code-plugin#751]
VERSIONS:

- [2.165 ] Jenkins version
- [1.6 ] Plugin version
- [linux/kubernetes ] OS

WHAT I DID:

There are a number of different types of configurations, like:
/var/jenkins_home/casc_configs/kubernetes-slave/<slave1.yamls、slave2.yaml .......>
/var/jenkins_home/casc_configs/credentials/<credentials1.yaml、credentials2.yaml.......>
/var/jenkins_home/casc_configs/default/<a.yaml、b.yaml........>
/var/jenkins_home/casc_configs/authorization-strategy/<auth1.yaml、auth2.yaml.......>
.......

RESULET:

plugin can't load configs

**Comment by casz** [comment]
Your welcome to contribute 😄

**Comment by ewelinawilkosz** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/629 conscious decision

**Comment by casz** [comment]
Oh I missed the fact that we removed that functionality 😓

**Comment by readerx** [comment]
> 
> 
> #629 conscious decision

Why not ignore the hidden subdirectories (start with . )
