### ISSUE TITLE
the generated JSON schema fails validation

### ISSUE THREAD

**Issue by techlunacy** [jenkinsci/configuration-as-code-plugin#760]
Details:
- [ 2.150.2] Jenkins version
- [ 1.12 ] Plugin version
- [Red Hat Enterprise Linux Server release 6.9 (Santiago) ] OS

I am trying to validate my jenkins.yaml file with the schema using pajv and am getting this result:
```
./node_modules/.bin/pajv validate -s schema.json -d jenkins.yaml                            
schema schema.json is invalid
error: schema is invalid: data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should be equal to one of the allowed values, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should be array, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should match some schema in anyOf, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items should be array, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items should match some schema in anyOf
```

this looks like a different issue to #638  but somewhat related.
It looks like the jobs? part of the schema is invalid

thanks

**Comment by BlueAndi** [comment]
I can confirm this for v1.7 of JcasC. There are e.g. duplicated object keys and etc.

BTW is there a schema somewhere to download, which is valid? This could help to continue.

**Comment by BlueAndi** [comment]
I fixed the schema manually (as good as I could).
[schema.zip](https://github.com/jenkinsci/configuration-as-code-plugin/files/2970468/schema.zip)

**Comment by casz** [comment]
The schema is generated dynamically depending on plugins you have installed 😄

**Comment by casz** [comment]
The schema hints at jobdsl having issues so go blame them? 😄

**Comment by BlueAndi** [comment]
@casz You are right, of course. :-)
Can you give an entry point, where to find the generator and how it is generated from the plugins?

**Comment by casz** [comment]
@BlueAndi this would be the one: https://github.com/jenkinsci/configuration-as-code-plugin/blob/2f50bb369320c37f193456bfcd87d207a2e7e1fd/plugin/src/main/resources/io/jenkins/plugins/casc/DescribableAttribute/schema.jelly

**Comment by BlueAndi** [comment]
@casz Thanks, lets see how far I get.

**Comment by timja** [comment]
Is this still an issue?

**Comment by techlunacy** [comment]
@timja still getting it at 1.12 and maybe 1.13 but i  need to wait a day or so before i can confirm on 1.13

**Comment by timja** [comment]
The last fixes that were done around here were in 1.11 so no need.
Is it the same error as what you reported? the schema is dynamic to which plugins are installed.

**Comment by techlunacy** [comment]
it is the same error from what i can see
```
schema schema.json is invalid
error: schema is invalid: data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should be equal to one of the allowed values, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should be array, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items.type should match some schema in anyOf, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items should be array, data.definitions['[javaposse.jobdsl.dsl.GeneratedItems;'].items should match some schema in anyOf

```

**Comment by timja** [comment]
Thanks,
This is something that I would like to improve upon at some point (contributions absolutely welcomed though!)

With the current setup we have no tests around it, and it's all built in the view.
If it makes sense ideally we would like this to be re-written into java with some good test coverage around it.

It looks to be an issue with jobdsl, it would need a deeper look though to see if we're doing something wrong of if there needs to be a fix on the jobdsl side

**Comment by timja** [comment]
@casz Turns out we're bundling that job dsl snippet in the support plugin:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/7e91b97e2debd2c0ef88a4d7b785a3eb0169e002/support/src/main/resources/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator/schema.jelly#L8

And its completely wrong :(
The attribute there is invalid, working on another issue I noticed then will try figure out what is supposed to be there

**Comment by casz** [comment]
the schema is also located in jobdsl now after 1.73 :sweat_smile:

**Comment by timja** [comment]
I was wondering why after I "fixed" it in the support plugin it was still showing up wrong...

**Comment by BlueAndi** [comment]
How does the invalid generated part looks like?

**Comment by timja** [comment]
lots of descriptors aren't defined, and i can't validate against credentials or matrix-auth without it failing

don't know enough about json-schema to see why though

schema, yaml and validation errors in this gist:
https://gist.github.com/timja/d2b8ba55d7af3113826adbcc154c06ab#file-gistfile1-txt

the schema has been patched to remove anything that was causing `pajv` to not parse it

**Comment by BlueAndi** [comment]
The schema itself contains a lot of duplicated object keys. E.g. line 1547 equal to 1554 and etc.
This seems to be a separate problem.

**Comment by BlueAndi** [comment]
Regarding the 3rd problem the question is e.g. for globalNodeProperties, can it have an array of values or only one with a dedicated type? This would answer where to fix it, in the schema or in the configuration.

**Comment by Misteur-Z** [comment]
Jenkins LTS `2.164.3`
CasC plugin `1.17`
node `8.16.0`
npm `6.9.0`
pajv `1.2.0`

```
pajv -s /tmp/jenkins-casc-schema.json -d jenkins.yaml 
$ref: keywords ignored in schema at path "#/properties/configuration-as-code"
$ref: keywords ignored in schema at path "#/properties/jenkins"
$ref: keywords ignored in schema at path "#/properties/authorizationStrategy"
$ref: keywords ignored in schema at path "#/properties/clouds/items"
$ref: keywords ignored in schema at path "#/properties/podRetention"
$ref: keywords ignored in schema at path "#/properties/templates/items"
$ref: keywords ignored in schema at path "#/properties/annotations/items"
$ref: keywords ignored in schema at path "#/properties/containers/items"
$ref: keywords ignored in schema at path "#/properties/envVars/items"
$ref: keywords ignored in schema at path "#/properties/livenessProbe"
$ref: keywords ignored in schema at path "#/properties/ports/items"
$ref: keywords ignored in schema at path "#/properties/envVars/items"
$ref: keywords ignored in schema at path "#/properties/imagePullSecrets/items"
$ref: keywords ignored in schema at path "#/properties/nodeProperties/items"
$ref: keywords ignored in schema at path "#/properties/locations/items"
$ref: keywords ignored in schema at path "#/properties/env/items"
$ref: keywords ignored in schema at path "#/properties/inheritanceStrategy"
$ref: keywords ignored in schema at path "#/properties/podRetention"
$ref: keywords ignored in schema at path "#/properties/volumes/items"
$ref: keywords ignored in schema at path "#/properties/workspaceVolume"
schema /tmp/jenkins-casc-schema.json is invalid
error: can't resolve reference #/definitions/org.csanchez.jenkins.plugins.kubernetes.NonConfigurableKubernetesCloud from id http://jenkins.io/configuration-as-code#
```
Plugins installed
```
blueocean:1.16.0
configuration-as-code-support:1.17
configuration-as-code:1.17
git:3.10.0
github-oauth:0.32
hashicorp-vault-plugin:2.2.0
jdk-tool:1.2
kubernetes:1.15.5
matrix-auth:2.4.2
pipeline-githubnotify-step:1.0.4
pipeline-model-definition:1.3.8
```

**Comment by oleg-nenashev** [comment]
CC @MRamonLeon

**Comment by sladyn98** [comment]
@casz @timja Had a look at this issue.If I understand correctly there are some issues with the json schema which include
1) Missing defnitions in the schema
2) Validation issues
3) jobdsl plugin issues (not quite clear)
Am I correct ?

**Comment by timja** [comment]
Yes some are also incorrectly generated I believe
