### ISSUE TITLE
Users should be warned about invalid configuration

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#77]
Considering valid YML but a user trying to configure something that is not working, how can the user be informed the configuration is wrong?

**Comment by buep** [comment]
For example trying to configure a plugin not installed.

**Comment by oleg-nenashev** [comment]
The current code lacks proper error propagation in many places. It requires a major refactoring before the release

**Comment by ewelinawilkosz** [comment]
@ndeloof that sounds like part of your tooling proposal, am I correct?
should we keep this issue or create a number of new ones once we have more specific plan? (unless you already have one)

**Comment by oleg-nenashev** [comment]
Last time I checked the plugin (1 week ago), it was still printing some errors to logs and then continuing starting up Jenkins. Is it something in the scope of this ticket? Or should I create a new one?

**Comment by oleg-nenashev** [comment]
@buep In the recent patches we have a Dry run mode (CC @ndeloof ). Would it be enough to close this issue assuming it is documented?

One of the things we could add is running Dry run each time before running full configuration so that we get YAML fully verified before we start applying changes.

**Comment by buep** [comment]
Dry run sounds like a good approach for now, but will it detect "For example trying to configure a plugin not installed." ?

**Comment by ndeloof** [comment]
it will : such a plugin's configuration will be detected as invalid. But JCasC can't tell you which plugin is missing.

**Comment by oleg-nenashev** [comment]
> But JCasC can't tell you which plugin is missing.

Could be a subject for future improvement (e.g. by integrating with a Global `@Symbol` registry on Jenkins Infra). But I am fine with the current state

**Comment by ewelinawilkosz** [comment]
to close this ticket I believe we have to document how to use dry mode - or is it already documented? and create a new one where we will discuss adding dry run to each reload/applying configuration
does it makes sense to you? @buep @oleg-nenashev @ndeloof 

Any volunteer  to update docs?

**Comment by x10an14** [comment]
I'd like to volunteer to update the docs, but I'm unaware of how to "enable" this dry-run config. =/

**Comment by ewelinawilkosz** [comment]
let's wait for it to be implemented and you can take over documenting if you're still interested :)

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/jira-plugin/pull/160

**Comment by ndeloof** [comment]
I'm sure we could improve diagnostic in future, but afaict we have a solid basis now
