### ISSUE TITLE
How to configure administrative monitors?

### ISSUE THREAD

**Issue by simonvanderveldt** [jenkinsci/configuration-as-code-plugin#774]
We'd like to configure (read: disable) some administrative monitors, but `AdministrativeMonitorsConfiguration` appears to be empty in the configuration as code documentation view in Jenkins.
Does this mean casc currently doesn't support configuration of administrative monitors?

**Comment by jansohn** [comment]
I'll second this. We'd like to disable the `ReverseProxySetupMonitor`...

**Comment by timja** [comment]
Can you create a jira issue with component `core` and label: jcasc-compatibility
it'll then show up on the dashboard here:
https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341

**Comment by jansohn** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-56937

**Comment by timja** [comment]
Looking at the code it's unlikely this will work without a custom configurator...

**Comment by simonvanderveldt** [comment]
shh stalebot

**Comment by timja** [comment]
Closing in favour of jira issue, PR here:
https://github.com/jenkinsci/jenkins/pull/4552

**Comment by nikolai-derzhak-distillery** [comment]
I would like to bring to your attention that would be good to add list of supported  items in documentation.
As I was hunting for exact value for next plugin updates for a while:
```
          jenkins:
            disabledAdministrativeMonitors:
              - hudson.model.UpdateCenter$CoreUpdateMonitor
```

**Comment by timja** [comment]
> I would like to bring to your attention that would be good to add list of supported items in documentation.
> As I was hunting for exact value for next monitor of plugin updates for a while:
> 
> [javadoc.jenkins.io/hudson/model/UpdateCenter.CoreUpdateMonitor.html](https://javadoc.jenkins.io/hudson/model/UpdateCenter.CoreUpdateMonitor.html)
> 
> ```
>           jenkins:
>             disabledAdministrativeMonitors:
>               - hudson.model.UpdateCenter$CoreUpdateMonitor
> ```

Best to configure it in the UI and then export it, there's a lot of different possible values

**Comment by nikolai-derzhak-distillery** [comment]
> > I would like to bring to your attention that would be good to add list of supported items in documentation.
> > As I was hunting for exact value for next monitor of plugin updates for a while:
> > [javadoc.jenkins.io/hudson/model/UpdateCenter.CoreUpdateMonitor.html](https://javadoc.jenkins.io/hudson/model/UpdateCenter.CoreUpdateMonitor.html)
> > ```
> >           jenkins:
> >             disabledAdministrativeMonitors:
> >               - hudson.model.UpdateCenter$CoreUpdateMonitor
> > ```
> 
> Best to configure it in the UI and then export it, there's a lot of different possible values

I wish I knew that method :) Thank you !
