### ISSUE TITLE
How to add config to existing ones and dont just replace it ? 

### ISSUE THREAD

**Issue by jomeier** [jenkinsci/configuration-as-code-plugin#781]
Hi,

how do I have to write CasC config files in a way that this configuration is added to existing ones (like kubernetes pod templats) ? 

Currently my configuration always replaces existing ones completely. I want to preserve the config which is already configured.

My use case is that I want to add kubernetes pod templates to a Jenkins instance which already has pod templates defined.

Best regards,

Josef

**Comment by casz** [comment]
these questions are better asked on https://gitter.im/jenkinsci/configuration-as-code-plugin

**Comment by casz** [comment]
Answered on gitter 😄

>@jomeier using `CASC_JENKINS_CONFIG` pointing to a folder where you can add files to add more configuration.
>The configuration process is not additive. it is whatever is in the files that `CASC_JENKINS_CONFIG` can see and will overwrite any configuration that is covered in those yaml files
>Export it as much as possible and then cover the rest that wasn't exported is your only option
