### ISSUE TITLE
S3 Artifact Plugin

### ISSUE THREAD

**Issue by ncsurfus** [jenkinsci/configuration-as-code-plugin#797]
I'm not sure if this goes here (let me know). I'm having an issue getting the artifact-manager-s3 plugin working with casc. I've based my configuration from the one below. Has something changed?

https://github.com/jenkinsci/configuration-as-code-plugin/blob/2f50bb369320c37f193456bfcd87d207a2e7e1fd/integrations/src/test/resources/io/jenkins/plugins/casc/ArtifactManagerS3.yml

- [2.164.1] Jenkins version
- [1.8] Plugin version
- [docker - jenkins/jenkins:lts] OS

**Comment by timja** [comment]
What happens would be useful?
do you get errors or stack traces?
or what config do you end up with?

what version of that plugin are you using?

**Comment by ncsurfus** [comment]
I don't actually get any errors. The configuration in Jenkins is just empty. I'm using the latest version (1.2) of the artifact-manager-s3 plugin.

**YAML**
![Screen Shot 2019-03-25 at 10 30 16 AM](https://user-images.githubusercontent.com/11602079/54932571-059c8100-4ee9-11e9-93ab-e50628fafdbd.png)

**AWS Config**
![Screen Shot 2019-03-25 at 10 23 16 AM](https://user-images.githubusercontent.com/11602079/54932505-ea317600-4ee8-11e9-973f-a33059c18f56.png)

**Configure System Config**
![Screen Shot 2019-03-25 at 10 23 50 AM](https://user-images.githubusercontent.com/11602079/54932506-eaca0c80-4ee8-11e9-92c5-9de0cb84f64a.png)

**Comment by ncsurfus** [comment]
Ah, I'm sorry everyone. Apparently I just needed to rebuild my docker image. I should've done this last night, but I was racing against my laptop's battery life.

Thanks for your help!
