### ISSUE TITLE
When using configuration-as-code-tests on project "configuration" page dont work.

### ISSUE THREAD

**Issue by ingwarsw** [jenkinsci/configuration-as-code-plugin#798]
- [ 2.107.1 ] Jenkins version
- [ 1.7, 1.8 ] Plugin version
- [ Mac (but suppose all are affected) ] OS

When adding `configuration-as-code` with classifier `tests` into `test` scope requests that are calling `configuration` page are failing.

Maven dependency added:
```
    <dependency>
      <groupId>io.jenkins</groupId>
      <artifactId>configuration-as-code</artifactId>
      <version>${configuration-as-code.version}</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
```

Code that will fail when used as part of test
```
rule.createWebClient().goTo("configure");
```

Exception
```
org.apache.commons.jelly.JellyTagException: jar:file:/Users/ingwar/.m2/repository/org/jenkins-ci/main/jenkins-core/2.107.1/jenkins-core-2.107.1.jar!/jenkins/model/Jenkins/configure.jelly:59:84: <st:include> No page found 'config.jelly' for class io.jenkins.plugins.casc.impl.configurators.DescriptorConfiguratorTest$FooBar
```

Seems like class `DescriptorConfiguratorTest` should not be in this artefact, cause its part of this project tests..

On the other hand only this jar have `ConfiguredWithCode` and `JenkinsConfiguredWithCodeRule`

For a quick and dirty fix see https://github.com/jenkinsci/google-compute-engine-plugin/pull/54/commits/25f1ee850c40397b163e5a94f5b9ff304fa33f78

**Comment by casz** [comment]
Feel free to send a PR that excludes the FooBar class: https://github.com/jenkinsci/configuration-as-code-plugin/blob/4ae305f2c99d7ce55d168a58773c9bedaad5e011/plugin/pom.xml#L74 😄

**Comment by ingwarsw** [comment]
@casz I can do that, but in long term Im not sure if it would be not better to move that code to `src` or even own subproject.. what do you thing?

**Comment by casz** [comment]
We could perhaps move misc package to SRC
