### ISSUE TITLE
[Feature] Test configuration

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#8]
How can we test that YML file is persisted as the exact global configuration I imagine…

**Comment by ndeloof** [comment]
We can generate yaml file from a live jenkins instance, checking all configurable component and comparing with their default state. Something comparable to pipeline's snippet generator.

**Comment by ewelinawilkosz** [comment]
dryrun implemented (https://github.com/jenkinsci/configuration-as-code-plugin/pull/331)
introducing it for each run: #77
