### ISSUE TITLE
Un-installing plugins

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#80]
What happens if I remove a plugin from the `plugins.yml` file when we support plugin installations?

We need to be able to un-install plugins, so there is always a 1:1 match between the configuration as code and the running instance.

**Comment by ewelinawilkosz** [comment]
nice to have bot not in 1.0 for sure

**Comment by casz** [comment]
We no longer support plugin installation as of v1.8 see #769
