### ISSUE TITLE
NPE when apply yaml on kubernetes

### ISSUE THREAD

**Issue by runzexia** [jenkinsci/configuration-as-code-plugin#800]
```
java.lang.NullPointerException
	at io.jenkins.plugins.casc.ConfigurationAsCode.collectProblems(ConfigurationAsCode.java:235)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doCheckNewSource(ConfigurationAsCode.java:211)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:537)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
```
the yaml could apply in 1.0 version, but not 1.8

```
jenkins:
  mode: EXCLUSIVE
  numExecutors: 5
  scmCheckoutRetryCount: 2
```
Please make sure to provide following information in your issue description

- [X] Jenkins version 1.138.4
- [X] Plugin version
- [X] docker

**Comment by timja** [comment]
Could you simplify your config down please?
Trial and error it a bit to find the issue

**Comment by runzexia** [comment]
@timja I found that this seems to be related to the configmap of k8s, I copied a yaml and used this yaml and there is no problem.

**Comment by runzexia** [comment]
@timja  use `/var/jenkins_home/casc_configs/jenkins.yaml` is ok
but could not use `/var/jenkins_home/casc_configs/..data/jenkins.yaml`

**Comment by casz** [comment]
Yes, JCasC will ignore hidden files such as `..data/jenkins.yaml`

**Comment by runzexia** [comment]
@casz  this doc tell me that I should use yaml under the .data directory.
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/kubernetes-helm/README.md
 and issue https://github.com/jenkinsci/configuration-as-code-plugin/issues/425

**Comment by f1nger** [comment]
I guess this PR broked ..data: https://github.com/jenkinsci/configuration-as-code-plugin/pull/753 
But this is working for me: CASC_JENKINS_CONFIG "value: /var/jenkins_home/casc_configs/jenkins.yaml" (symlink to ..data by kubernetes configmap)
Although in doc "It dosn't follow symbolic links".

**Comment by casz** [comment]
@f1nger that depends on how you look at it :sweat_smile:

I see it as fixing it since people wanted recursive folder lookup and that's what the ..data folder did, it broke recursive folder lookup.

@runzexia Docs can be outdated. I welcome you to contribute! :smiley: 

The project is open source after all and we cannot maintain everything while keeping our sanity and our job :sweat: I for one don't use kubernetes together with JCasC at the moment :cry:

**Comment by casz** [comment]
># Tell the plugin where to find its config. The '..data'
># part is needed for now due to this bug:
># https://github.com/jenkinsci/configuration-as-code-plugin/issues/425

Please read that section again.

The **'..data' part** is needed for now due to this bug: https://github.com/jenkinsci/configuration-as-code-plugin/issues/425

So yes #753 indeed fixed it, however docs are not updated.

**Comment by runzexia** [comment]
I will try to update the docs
