### ISSUE TITLE
Load configuration from object in S3

### ISSUE THREAD

**Issue by conn** [jenkinsci/configuration-as-code-plugin#801]
It would be useful if `CASC_JENKINS_CONFIG` could point to an `s3://` URL and load configuration from there. While you could use a signed S3 URL, the expiration date for such has a maximum of a week. It would be trivial to point to an S3 URL when using an instance or service role; in other cases, additional configuration for AWS credentials would be needed.

**Comment by timja** [comment]
Might be good for this to be a separate plugin?
Changes in here could be made if that doesn't work very well currently

**Comment by casz** [comment]
Ya this sounds like an extension plugin :smile:

**Comment by conn** [comment]
Wouldn't that be dependent on https://github.com/jenkinsci/configuration-as-code-plugin/issues/34 ?

**Comment by jbouse** [comment]
I can help with testing if this gets worked on. I'm currently storing my config into an S3 bucket but using a custom bucket policy to allow my Jenkins instance to use the S3 HTTPS URL to retrieve the files.

**Comment by kmcquade** [comment]
@jbouse you might want to check out https://github.com/odavid/my-bloody-jenkins#environment-variables. See his note on the environment variable JENKINS_ENV_CONFIG_YML_URL.

We just use that and assign an IAM role to the ECS task. Using my-bloody-jenkins, our Jenkins instances just grab the config.yml file at boot and polls for changes every 30 seconds :)

**Comment by kmcquade** [comment]
@conn you can do that with https://github.com/odavid/my-bloody-jenkins. If you have restrictions on your environment you can write similar scripts to the config-related files in the `bin` directory of that repo.

**Comment by timja** [comment]
This won't be supported in this plugin, once https://github.com/jenkinsci/configuration-as-code-plugin/issues/34 is solved then it can be implemented in another plugin, follow https://github.com/jenkinsci/configuration-as-code-plugin/issues/34 for updates
