### ISSUE TITLE
Unset configuration not described

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#82]
If I change my configuration code, say omitting a section for a plugin in the `jenkins.yml` file the configuration needs to be unset on the running instance also (as in back to defaults).

There always needs a 1:1 relation between the configuration and instance running, or a least a way to report it and detect it.

This features partly related to #80 as well as an earlier discussion today on Jenkins hackfest around we don't support mix and match of manual and configuration as code.
Either the user manually configure Jenkins, or the user gets everything from configuration as code.

**Comment by ndeloof** [comment]
this will be the case for anything DataBound (immutable or reset to default before applying changes) but not for others like `JenkinsConfigurator`. 
Maybe we should keep track of the applied configuration so we can compute a _diff_ ?

**Comment by ewelinawilkosz** [comment]
duplicated in #191 
closing this one
