### ISSUE TITLE
Please include "Breaking changes" section in the release changelog

### ISSUE THREAD

**Issue by kmcquade** [jenkinsci/configuration-as-code-plugin#822]
### Feature Request

Please explicitly call out breaking changes / backwards incompatibilities list as part of the Changelog in releases. That will make it MUCH easier to predict when we should alter the JCasC.

Thanks for the great work. This plugin is a lifesaver.

**Comment by casz** [comment]
I think we already have done that? At least in the recent releases

**Comment by timja** [comment]
We've added a removed section to the top of our release template, the next release has removed matrix-auth in it.

And we'll do our best to call out any breaking changes.
