### ISSUE TITLE
Unordered loading of a directory of config

### ISSUE THREAD

**Issue by rjbwtr** [jenkinsci/configuration-as-code-plugin#824]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [2.171] Jenkins version

- [1.10] Plugin version

- [CentOS7] OS

### Description

Config that is loaded from a directory is loaded in an unordered manner. This means that based on the underlying filesystem, config files will be processed in an unpredictable manner.

If I've understood the code correctly, it seems that the code will load in the order in which the config is added to the configParameters list. The list of YAML files returned by getBundledCasCURIs appears to be naturally sorted: https://github.com/jenkinsci/configuration-as-code-plugin/blob/bdb01f77d9c6f6c6abae76306189c23a206ffb14/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L338

I think that potentially doing the sort here might be the way to go? https://github.com/jenkinsci/configuration-as-code-plugin/blob/bdb01f77d9c6f6c6abae76306189c23a206ffb14/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L563

I'm not 100% sure though. We could assign the `stream.collect` to a variable and then return the `list.sort()` of whatever has been collected?

Apologies if my thinking here is faulty. I'd appreciate any thoughts and feedback on this.

For reference, I'm loading files from an EXT4 filesystem.

Thanks!

**Comment by apr-1985** [comment]
Also hitting this issue where we want to define a base Role Based access config, but allow a team to override this config with their own config file.  However the load order is random so we cannot know which settings get applied on each run

**Comment by casz** [comment]
I welcome you to contribute :blush:
