### ISSUE TITLE
Kube auth support

### ISSUE THREAD

**Issue by awolde** [jenkinsci/configuration-as-code-plugin#828]
### Feature Request

Is there support for Kubernetes auth? I want to do authentication similar to this with Vault
```
curl --request POST --data "{\"jwt\": \"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" , \"role\": \"my-role\"}" $CASC_VAULT_URL/v1/auth/kube/login
```

**Comment by casz** [comment]
We are using `vault-java-driver`
They have [PR open for kube auth](https://github.com/BetterCloud/vault-java-driver/pull/122) 😄

**Comment by timja** [comment]
Supported in 3.1.0 of hashicorp-vault-plugin https://github.com/jenkinsci/hashicorp-vault-plugin/releases
