### ISSUE TITLE
CASC Configuration Doesn't Support configuration with a file in a hidden folder

### ISSUE THREAD

**Issue by mglazer** [jenkinsci/configuration-as-code-plugin#833]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version

- [X] Plugin version

- [X] OS

### Description

* Jenkins Version: 2.164.1
* CASC Version: 1.11
* OS: Any

*Reproduction Steps*:

* Set the `CASC_JENKINS_CONFIG` environment variable to a configuration file which happens to be nested in a hidden folder (for environmental reasons this is how my deployment environment operates). ie: `/opt/jenkins/.config/jenkins.yml`

*Expected*:

* Configuration is loaded.

*Actual*:

* Configuration is not loaded.

*Workaround*:

* You need to specify the file as `file:///opt/jenkins/.config/jenkins.yml`

**Comment by casz** [comment]
we specifically don't allow hidden folders because of kubernetes.

**Comment by mglazer** [comment]
I'm not sure I understand. You do if you specify the file URI, this just happens to be slightly confusing behavior.

**Comment by casz** [comment]
the test code describes the issue :laughing: 
I'll do my best here.
Some prefer pointing to a folder and when you mix that with Kubernetes config maps which generate a `..data` folder to hold the actual files you get duplicate YAML files which create conflicts in the config.

See which has links to other issues
https://github.com/jenkinsci/configuration-as-code-plugin/pull/753
