### ISSUE TITLE
Configuration of cloud section

### ISSUE THREAD

**Issue by savujevi** [jenkinsci/configuration-as-code-plugin#837]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] 2.173

- [x] 1.11

- [x] RHEL 7

### Description

Hello developers,

I used to configure the cloud section in the yaml file and have following problem:
`args: "${computer.jnlpmac} ${computer.name}"` ends up with an empty field in the ui of the jenkins in the cloud section.

Could you please tell me how to escape the string ?

Thanks for your support.

Best regards
    Sascha Vujevic

**Comment by timja** [comment]
See this comment: https://github.com/jenkinsci/configuration-as-code-plugin/issues/835#issuecomment-484132522
