### ISSUE TITLE
Clean up labels

### ISSUE THREAD

**Issue by casz** [jenkinsci/configuration-as-code-plugin#855]
@ewelinawilkosz @timja 

I want to clean up some of our labels

<details><summary>Full list</summary>

```
good first issue
Status - in progress
Action - awaiting feed-back
Action - needs grooming
Prio 1 - must have
Prio 2 - should have
Prio 3 - could have
Prio 4 - won’t have
Size 0 - Briefing
Size 1 - small
Size 2 - medium
Size 3 - large
Size 4 - too big
Status - duplicate
Status - workable
Status - up Next
hackathon
beta-release
help wanted
question
wontfix
invalid
duplicate
enhancement
bug
Work in progress
documentation
do not merge
pending PR
hacktoberfest
needs-plugin-issue
feature
fix
chore
test
pinned
plugin-compatibility
stale
reverted
```

</details>

Here's what I suggest

<details><summary>Remove</summary>
<p>

label : reason
```
Status - in progress : unused
Action - awaiting feed-back : unused
Action - needs grooming : unused
Prio 1 - must have : unused
Prio 2 - should have : unused
Prio 3 - could have : unused
Prio 4 - won’t have : unused
Size 0 - Briefing : unused
Size 1 - small : unused
Size 2 - medium : unused
Size 3 - large : unused
Size 4 - too big : unused
Status - duplicate : unused
Status - workable : unused
Status - up Next : unused
beta-release : unused
Work in progress : replaced by WIP[bot]
do not merge : replaced by WIP[bot]
pending PR : debatable just as easily marked by WIP or 🚧
needs-plugin-issue - replaced by plugin-compatibility
invalid : replaced by stale[bot]
```

</p>
</details>

<details><summary>Stay</summary>
<p>

label : reason
```
good first issue : used by github for finding new contributors
help wanted : used by github for finding new contributors
hackathon : useful for hackathon events
question : signal value
wontfix : useful to find things we wontfix
duplicate : signal value
enhancement : enhancement we want to get to (exempted from stale[bot])
bug : signal value
documentation : release drafter
hacktoberfest : event
feature : release drafter
fix : release drafter
chore : release drafter
test : release drafter
pinned : exempted from stale[bot]
plugin-compatibility : used by issue template
stale : stale[bot]
reverted : release drafter
```

</p>
</details>

Some that require extra explanation.

`invalid` would be the same as stale since stale[bot] will clean up if a user doesn't reply within 7 days if we mark it stale.

`Work in progress`/`do not merge` add WIP or 🚧 to PR title.
I will update the PR template to make this clear.

I suggest we use 🚧 as a convention as we do like emojis :trollface: 

Perhaps we should replace `enhancement` with `feature` to avoid confusion  
(I prefer the word feature over enhancement)

I would like to use [probot/settings](https://github.com/probot/settings) to achieve this cleanup :sweat_smile:

**Comment by timja** [comment]
Looks good to me, only thought is that the work in progress label might be more obvious to people to add, its supported by wip bot: https://github.com/wip/app#configuration

but happy enough without it too

**Comment by casz** [comment]
People without commit access cannot add labels @timja 😆

**Comment by timja** [comment]
I thought that too but on this issue the user added one:
https://github.com/jenkinsci/configuration-as-code-plugin/issues/828

**Comment by casz** [comment]
No that is because of templates 😆 See https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/ISSUE_TEMPLATE/2-feature-request.md

**Comment by casz** [comment]
For PR's I would love to use https://github.com/TimonVS/pr-labeler-action

**Comment by casz** [comment]
@timja what about
> Perhaps we should replace enhancement with feature to avoid confusion

**Comment by timja** [comment]
yeah makes sense
