### ISSUE TITLE
Make the roadmap more public and easy to find

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#86]
I think a lot of the roadmap is still in our head and maybe implicitly to some extend in the issues.

Overall we have some points in the horizon we aim for....

* February - first release of the plugin, we have many of the features planned for our MVP
* Q2 2018 - Praqma plan to roll out to some customers that will be early adopters  of this new project
* Jenkins Summit - some more public presentation... many more features?

We could maybe create a roadmap file explaining what we aim for in the future, and what the big picture plans at least this year.

**Comment by daniel-beck** [comment]
Perhaps a section on jenkins.io like Blue Ocean has?

https://jenkins.io/projects/blueocean/
https://jenkins.io/projects/blueocean/roadmap/

It's JSON driven IIRC.

**Comment by buep** [comment]
Good inputs and it looks nice :-) Can you point to the code? 

We would also like to get on the projects page I think - how is that possible? We discussed it early in the stages of the projects, but we probably forgot it again.

**Comment by daniel-beck** [comment]
@buep Click 'Improve this page' on the bottom left will show the page's source code in GitHub.

Not sure what the project maturity threshold for presentation on the site is, but I don't think you're far away. Technically you only need to file a PR, but perhaps best to discuss on the dev list first (and involve @rtyler) to not waste time unnecessarily.

**Comment by oleg-nenashev** [comment]
Would be great to have it as a subproject.

**Comment by ewelinawilkosz** [comment]
I will prepare a PR when we have an official release ready
I will reuse Blue Ocean layout - like it a lot and already prepared a first draft (see #102)

**Comment by ewelinawilkosz** [comment]
we'll focus on maintaining issues and milestones up to date and that will serve as a roadmap
jcasc as a subproject at jenkins.io is already live
