### ISSUE TITLE
Support "shortest timeout" at build stuck plugin

### ISSUE THREAD

**Issue by bmaehr** [jenkinsci/configuration-as-code-plugin#867]
### Feature Request

It would be really nice if the last setting 'shortest timeout' for the build stuck plugin in elastic mode would be supported.

**Comment by timja** [comment]
you should raise this issue with the plugin
https://github.com/jenkinsci/configuration-as-code-plugin/issues/809

If they use jira for tracking then add the `jcasc-compatibility` label
