### ISSUE TITLE
FAILED TO EXPORT org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud

### ISSUE THREAD

**Issue by cmays20** [jenkinsci/configuration-as-code-plugin#871]
- Jenkins version: 2.175

- Plugin version: 1.13

- OS: Alpine Docker container

- Kubernetes Plugin: 1.15.2 

### Description

I am getting the following error when trying to View my configuration:

`templates: "FAILED TO EXPORT org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud#templates:\
        \ java.lang.NullPointerException  at org.csanchez.jenkins.plugins.kubernetes.PodTemplate.getYaml(PodTemplate.java:622)\n\
        Caused: java.lang.reflect.InvocationTargetException  at sun.reflect.GeneratedMethodAccessor1658.invoke(Unknown\
        \ Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\
        \  at java.lang.reflect.Method.invoke(Method.java:498)  at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:244)\n\
        Caused: io.jenkins.plugins.casc.ConfiguratorException: Can't read attribute\
        \ 'yaml' from PodTemplate{, nodeUsageMode=EXCLUSIVE}  at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:262)\
        \  at io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:175)  at io.jenkins.plugins.casc.Attribute.equals(Attribute.java:207)\
        \  at io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:384)\
        \  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:249)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:193)  at io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:385)\
        \  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:249)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:233)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:233)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:193)  at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:162)"`

**Comment by timja** [comment]
Looks like an issue with the kubernetes plugin?
There's a null pointer in their code,

```
org.csanchez.jenkins.plugins.kubernetes.PodTemplate.getYaml(PodTemplate.java:622)
```

Potentially caused by your config? which would be needed to reproduce it potentially?

**Comment by cmays20** [comment]
I haven't actually configured anything using CasC yet.  I did the configuration manually in the GUI to get a baseline.  I was hoping to use the View/Export feature of CasC to get started but got the above error.  This stacktrace shows up in the CasC output when I hit "View Configuration".

I have attached images of my kubernetes plugin configuration.

<img width="2613" alt="Screen Shot 2019-05-01 at 11 19 39 AM" src="https://user-images.githubusercontent.com/13873549/57027855-256b4700-6c03-11e9-986f-6f3c604d6352.png">
<img width="2332" alt="Screen Shot 2019-05-01 at 11 21 26 AM" src="https://user-images.githubusercontent.com/13873549/57027922-4df34100-6c03-11e9-9076-72637bd274e9.png">
<img width="2556" alt="Screen Shot 2019-05-01 at 11 21 11 AM" src="https://user-images.githubusercontent.com/13873549/57027925-4e8bd780-6c03-11e9-8bf8-c3477d698be0.png">

**Comment by cmays20** [comment]
Also, the rest of my configuration does show up.  There is only an exception in the templates section of the cloud-> kubernetes section.  The rest of the CasC View output looks good.

**Comment by casz** [comment]
Than JCasC works as intended

**Comment by cmays20** [comment]
Not sure I am following.  Can you expand on that and possibly point out what is going wrong for me.

**Comment by cmays20** [comment]
Ok, I get it now and I think they have a PR to fix already.  I will close this.

**Comment by zerkms** [comment]
@cmays20 coule you please provide a link to the corresponding PR?

**Comment by cmays20** [comment]
Sorry for the late reply, but I believe the PR was merged in early May. I haven't had a chance to test it out though.
