### ISSUE TITLE
Subversion plugin is not supported by JCasc

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/configuration-as-code-plugin#872]
- [x] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against
https://issues.jenkins-ci.org/browse/JENKINS-54782

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [x] Link to [Jenkins JIRA issue][jenkins-jira]
https://issues.jenkins-ci.org/browse/JENKINS-54782

- [x] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to plugin's GitHub repository
https://github.com/jenkinsci/subversion-plugin

- [x] Link to Plugin Compatibility Tracker #809

Is missing from supported Plugins Dashboard view

**Comment by timja** [comment]
No need to create an issue on our repo, linking is only for cross repo.
You may want to rewrite the ask on the jira to support jcasc, not how can I do it
