### ISSUE TITLE
Getting the right info without download config

### ISSUE THREAD

**Issue by bassplay3r** [jenkinsci/configuration-as-code-plugin#878]
- [x] Jenkins version
2.164.2
- [x] Plugin version
1.14
- [x] OS
Linux amd64 3.10.0-862.el7.x86_6

### Description
I'm trying to wrap my head around getting the right JCasC info into my chart. Right now I have charts/stable/jenkins as a requirement to my chart and then override it's settings with my own values.yaml.  I was able to the use Download Configuration to get the initial LDAP config I setup

Now the  Download and View Configuration fail to export several key configuration settings I need. 
configurations: "FAILED TO EXPORT hudson.security.LDAPSecurityRealm#configurations:\

I get that it may break:
Export is not intended to offer a directly usable jenkins.yaml configuration. It can be used for inspiration writing your own, be aware export can be partial, or fail for some components. 

How do I find the the right configuration data without the download/view configuration functionality?

**Comment by timja** [comment]
Could you add the full stack trace?
Here's a demo for it:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/ldap

If what you need isn't there either you need to read the code and look at the attribute names or raise an issue against the plugin

Ideally an issue should be raised against the plugin anyway as anything that doesn't export is likely a bug.

These days export works quite well.

**Comment by bassplay3r** [comment]
There is two stack traces 

  securityRealm:
    ldap:
      configurations: "FAILED TO EXPORT hudson.security.LDAPSecurityRealm#configurations:\
        \ java.lang.NullPointerException  at hudson.util.Secret$1.convert(Secret.java:316)\
        \  at hudson.util.Secret$1.convert(Secret.java:314)  at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:544)\
        \  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:239)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:193)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:255)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:233)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:233)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:197)  at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:162)"
      disableMailAddressResolver: false


  jdk:
    defaultProperties:      configurations: "FAILED TO EXPORT hudson.security.LDAPSecurityRealm#configurations:\
        \ java.lang.NullPointerException  at hudson.util.Secret$1.convert(Secret.java:316)\
        \  at hudson.util.Secret$1.convert(Secret.java:314)  at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:544)\
        \  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:239)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:193)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:255)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:233)\
        \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:233)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
        \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
        \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
        \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:197)  at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:162)"

**Comment by bassplay3r** [comment]
![image](https://user-images.githubusercontent.com/37637605/57317804-f9e6d180-70c6-11e9-9a8b-955f337a3523.png)

**Comment by casz** [comment]
The error is pretty obvious, you have to specify a manager password

**Comment by bassplay3r** [comment]
I thought that once LDAP is configured Jenkins did not use the local users. Its been working fine for me since I login using my LDAP creds to login and I have set " Logged-in users can do anything". I put a dummy password in the config and the view config worked fine. Thanks so much for the help

**Comment by casz** [comment]
Though there could be a bug at `io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:239)` I'll check it out :sweat:

**Comment by timja** [comment]
I'm assuming that value is null here:
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/util/Secret.java#L306

**Comment by timja** [comment]
Maybe this returns null?
`a.getValue(instance)` and we could add a null check there?

**Comment by casz** [comment]
That was my plan @timja :wink:

**Comment by casz** [comment]
Though if you beat me to it, that's fine too :laughing:

**Comment by timja** [comment]
Beat you @casz https://github.com/jenkinsci/configuration-as-code-plugin/pull/882
