### ISSUE TITLE
Let's gather inputs on how to test configuration as code from end-user perspective

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#88]
I know there are some tests already, but I propose we consider also a more holistic view on testings that would include we ensure "everything" works... to some extend. Obviously completely automated.

Want I wish for in the end is that when ever we change something, in the end we would eventually as least before releasing ensure that:

* new version fit all our recommended ways to run it, e.g. the Kubernetes example still works
* all the end-user ways of starting configuration as code still works, e.g. a container injecting the `jenkins.yml` file
* all plugins we have white listed to work, are still working... or well we at least check them in a simple way
* compatibility testing of some kind, where we automatically maintain a kind of compatibility matrix of core version and plugins version we have tested with

I have no clue how to automate all this, and we should probably only do part of it - but let's discuss good ideas.

**Comment by ndeloof** [comment]
Our automated test already configure jenkins based on some yaml sample, and can check instance health in various ways, so we can just build on top of it.
