### ISSUE TITLE
Kubernetes Plugin: Kubernetes Pod template ${computer.jnlpmac} ${computer.name} goes blank

### ISSUE THREAD

**Issue by nayakmahesh** [jenkinsci/configuration-as-code-plugin#886]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

Please describe your issue here.

**Comment by casz** [comment]
There is this search feature that exist on GitHub
There also a readme explaining how to handle secrets.
https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets
https://github.com/jenkinsci/configuration-as-code-plugin/search?q=computer.jnlpmac+is%3Aissue&type=Issues

**Comment by nayakmahesh** [comment]
I did lot of search with different combination but didnot hit upon this issue. Thanks for input it works fine with args: "^${computer.jnlpmac} ^${computer.name}". Closing the issue
