### ISSUE TITLE
provide build_timestamp configuration demo

### ISSUE THREAD

**Issue by peterbosalliandercom** [jenkinsci/configuration-as-code-plugin#891]
[jenkins-jira]: https://issues.jenkins-ci.org
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [ ] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [ ] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [ ] Link to [Jenkins JIRA issue][jenkins-jira]

- [ ] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [ ] Link to plugin's GitHub repository

- [x] Link to Plugin Compatibility Tracker #809

### Description
Please add the https://wiki.jenkins.io/display/JENKINS/Build+Timestamp+Plugin
to the casc demo and to the plugin itself.

**Comment by casz** [comment]
...
