### ISSUE TITLE
Question: exporting jobs

### ISSUE THREAD

**Issue by rnelson0** [jenkinsci/configuration-as-code-plugin#893]
I've noticed a number of issues where someone is adding jobs when importing the configuration. Is it possible for CasC to export existing jobs, and if so, how?

**Comment by timja** [comment]
No currently impossible, requires changes in jenkins core.
We rely on job-dsl for creating jobs, ideally there would be support in the core for it though

**Comment by rnelson0** [comment]
So do I have to have job-dsl installed to import the jobs? I didn't see it listed as a dependency but the readme hints at it.

**Comment by casz** [comment]
@rnelson0 https://github.com/jenkinsci/job-dsl-plugin#readme has a lovely readme with even more docs.
