### ISSUE TITLE
[Feature] Make UI read-only once managed by CasC

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#9]
Refresh button - so I can reload configuration from files, without restarting Jenkins
Optional locking down changes in the UI blocking users from changing it without updating the config file
Export configuration - if I have Jenkins already configured, or just made some changes in UI and want to keep them in the file

**Comment by ndeloof** [comment]
comparable to https://github.com/jenkinsci/configuration-as-code-plugin/issues/6 IIUC.

lock down of the UI is a major feature I'd like to implement, not sure yet if this is possible.

**Comment by ewelinawilkosz** [comment]
Right, the actual redeployment is in #6 so this issue should be about lock down only

**Comment by ewelinawilkosz** [comment]
issue discussed during post-FOSDEM hackathon and here is the conclusion:

We are going to introduce the new permission to “read but not submit global config” ala Job DSL
Once the basic capabilities are proven, the details can be tweaked

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-12548 is somewhat related to this issue

**Comment by LinuxSuRen** [comment]
Looking forward to this feature.

**Comment by casz** [comment]
🎆 🎉 🥇 😍 @timja Thanks for landing this feature!
