### ISSUE TITLE
FAILED TO EXPORT hudson.model.Hudson#globalNodeProperties

### ISSUE THREAD

**Issue by bassplay3r** [jenkinsci/configuration-as-code-plugin#901]
- [ x] Jenkins version
Jenkins ver. 2.164.3

- [ x] Plugin version
1.17

- [x ] OS
K8s 1.12.1

### Description
Tried to export and I get this error

  globalNodeProperties: "FAILED TO EXPORT hudson.model.Hudson#globalNodeProperties:\
    \ java.lang.ClassCastException: java.util.ArrayList cannot be cast to hudson.slaves.EnvironmentVariablesNodeProperty$Entry\
    \  at hudson.slaves.EnvironmentVariablesNodeProperty.toMap(EnvironmentVariablesNodeProperty.java:128)\
    \  at hudson.slaves.EnvironmentVariablesNodeProperty.<init>(EnvironmentVariablesNodeProperty.java:60)\n\
    Caused: java.lang.reflect.InvocationTargetException  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native\
    \ Method)  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\
    \  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\
    \  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:256)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:233)\
    \  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:233)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)\
    \  at io.vavr.control.Option.map(Option.java:373)  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)\
    \  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)\
    \  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)  at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:162)"

**Comment by timja** [comment]
This was fixed in https://github.com/jenkinsci/configuration-as-code-plugin/pull/898
Currently unreleased

**Comment by oleg-nenashev** [comment]
What is the ETA for the release @casz ? Hit it as well in https://github.com/jenkinsci/configuration-as-code-plugin/issues/902 .

**Comment by casz** [comment]
I can definitely do a release, but I just really want the empty support plugin, but if I have to I can 😓

**Comment by oleg-nenashev** [comment]
@casz I am trying to facilitate the credentials plugin release
