### ISSUE TITLE
Configuration as code is not handling deployment properties

### ISSUE THREAD

**Issue by buep** [jenkinsci/configuration-as-code-plugin#91]
Several times during the last two days after FOSDEM we have had inputs, or discussions or misunderstandings about the plugin also handles for example more deployment related properties of Jenkins (how memory master can use, system- and java properties etc.)

We're still early in the project, but some improved communication about what precise, more important what not configuration as code is.

Just some thought ...

**Comment by daniel-beck** [comment]
Would rather not see this try to become Chef/Puppet/etc.

**Comment by ewelinawilkosz** [comment]
We'll provide some examples - docker, kubernetes, scripts to make it easier to deploy but plugin is about what happens INSIDE master. I agree, we need to communicate it more precisely - if we end up at jenkins.io (#86) it should contain improved information

**Comment by buep** [comment]
We all completely agree, it just about being more clear in our communication and documentation.

**Comment by ndeloof** [comment]
if we introduce this as automation for jenkins setup process based on manual configuration on web UI, this would not create expectation on the infrastructure (JVM, ssl certificates, etc) which one can't managed on jenkins UI. right ?

**Comment by ewelinawilkosz** [comment]
right @ndeloof 
so the issue is about making documentation clear after all - am I correct @buep ?

**Comment by buep** [comment]
yes

**Comment by oleg-nenashev** [comment]
The plugin provides all required APIs and CLIs now, so any configuration management tool can integrate with it if needed. Having an example would be useful tho
