### ISSUE TITLE
CasC ciphers values already ciphered when running under test

### ISSUE THREAD

**Issue by MRamonLeon** [jenkinsci/configuration-as-code-plugin#913]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
Jenkins 2.73.3, 2.164.1, 2.165

- [x] Plugin version
JCasC 1.19, 1.20-snapshot
Credentials 2.19, 2.20

- [x] OS
Linux

### Description

Jenkins 2.73.3, 2.164.1, 2.165 when running " *under test* ", let's say `mvn hpi:run` or `mvn test`, ciphers the tokens even though they are ciphered in the YAML, whereas **the same Jenkins running normally doesn't cipher the tokens if they are already ciphered**.

When configuring with the attached yml:

If Jenkins is **running normally** (java -jar ...), in the viewExport page (View Configuration button) it shows:

_{AQAAABAAAAAQ93qR7ipIm+dYmOZ1AXqSLWDj9V+KUrHew/fiyPNoHTo=}_

The same as in the file.

But when **running under test**, with mvn hpi:run or running integration tests (mvn package) it shows:

**usernamePassword**:

_{AQAAABAAAABA1e/z7rT6SsbMm5XmaDkHn0N8YeoHYRm8JltNZh68IZumi/SmbDrI+nH8Z51YNwSokbUbxkq85QMMe5CkEDLL+YNkXGcnAMwvSgTLLH71dlc=}_

**basicSSHUserPrivateKey**:
_{AQAAABAAAABAb5Y+gVJlthgpEfLXRvFmnYtPqeTnxFDzNaKpRPDhpbWw70t7h4W1jI9h5u7TEafPxk6AhWmq+BoWkzAQtKLvzYFLCUwE2xNusw5nXeKVklY=}_

Even though both secrets are the same in the yaml file. Not sure if it's expected.

Also filed in: https://issues.jenkins-ci.org/browse/JENKINS-57863

**Comment by casz** [comment]
@MRamonLeon could you add a failing unit test so we have something to work towards?

**Comment by casz** [comment]
Hi @MRamonLeon I would still like a failing unit test.

This should be simple enough to fix as the should be an easy way to detect whether the string is already encrypted

Though at the same time I wonder if this issue is related to JCasC.
