### ISSUE TITLE
Introduce a new JCasC Test Harness Library

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#917]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

It looks like we have a lot of test framework functionality for JCasC:

* https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithCodeRule.java and dependencies
* Roundtrip tests from @MRamonLeon : https://github.com/jenkinsci/configuration-as-code-plugin/pull/908
* WiP - JCasC support in the Plugin benchmarking support by @AbhyudayaSharma: https://github.com/jenkinsci/jenkins-test-harness/pull/135
 
Currently it is hard to reuse this code, because it is located within the test suites, so an odd dependency is needed. Also, it makes the downstream plugins to pull in more test dependencies than we really want.

```
    <dependency>
      <groupId>io.jenkins</groupId>
      <artifactId>configuration-as-code</artifactId>
      <version>${configuration-as-code.version}</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
```

What if we introduce a new `configuration-as-code-test-harness` component which would ship it in a library?

```
    <dependency>
      <groupId>io.jenkins</groupId>
      <artifactId>configuration-as-code-test-harness</artifactId>
      <version>${configuration-as-code.version}</version>
      <scope>test</scope>
    </dependency>
```

**Comment by timja** [comment]
Yes, I believe we discussed it before, last time there was a packaging issue with the test classifier, we did the quick fix at the time but a separate module would be good in my opinion

**Comment by MRamonLeon** [comment]
LGTM :heart:

**Comment by timja** [comment]
resolved in https://github.com/jenkinsci/configuration-as-code-plugin/pull/1215

**Comment by oleg-nenashev** [comment]
I believe it is fixed by @timja in https://github.com/jenkinsci/configuration-as-code-plugin/pull/1215

**Comment by oleg-nenashev** [comment]
ERR_RACE_CONDITION
