### ISSUE TITLE
Persist non CASC credentials between CASC reloads. 

### ISSUE THREAD

**Issue by KjellTillstrand** [jenkinsci/configuration-as-code-plugin#923]
We are using Jenkins together with Nexus, Ansible Tower and Gitlab for delivering a pipeline delivery service. Each of our teams are getting a own Jenkins master instance fully configured running on a docker platform. 

The issue I'm having is that I'm populating the Jenkins master with a bunch of Credentials via JCASC, and thats working fine. 

The teams however are creating there own credentials and those are lost when we restart the container. Everything else is persisted as the Jenkins_home folder is a docker volume. It would be good to keep the non CASC credentials on a restart.

**Comment by casz** [comment]
The team shouldn't be creating credentials outside of JCasC.

I'd suggest you look vault it should solve your issue and also solve the multiple team issue :sweat:

**Comment by timja** [comment]
You can have multiple jcasc files and then the team can add their own credentials to their jenkins master config

**Comment by timja** [comment]
The configuration-as-code plugin doesn't host the credentials configurator anymore, it's with the [credentials-plugin](https://github.com/jenkinsci/credentials-plugin) which has it's issues on jira, 

I wouldn't recommend this anyway as explained above
