### ISSUE TITLE
No configurator found for type class com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentialsModule

### ISSUE THREAD

**Issue by pfallclear** [jenkinsci/configuration-as-code-plugin#924]
Jenkins ver. 2.164.3
Plugin version: 1.16
OS: Linux Docker GKE

Hello,
We are trying to use this plugin to configure a global oauth credential for a Google Compute service account as such:
```
    credentials:
      system:
        domainCredentials:
        - credentials:
          - googleRobotPrivateKey:
              projectId: "allclearid-corp"
              serviceAccountConfig:
                json:
                  filename: "secret.json"
                  secretJsonKey: ${MASTER_SERVICE_ACCOUNT}
```
where the Kubernetes secret json is mapped at the MASTER_SERVICE_ACCOUNT path in the pod.
  
The plugin is reporting this error at the CasC View Configuration screen:
"FAILED TO EXPORT com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials#module:
\ No configurator found for type class com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentialsModule"

![image](https://user-images.githubusercontent.com/51798100/59459409-57ff8680-8de2-11e9-8bb4-e48f3d8ee021.png)

There is also a warning in the startup log from the oauth plugin code:
```
Jun 12, 2019 10:24:37 PM com.google.jenkins.plugins.computeengine.ComputeEngineComputerLauncher log
SEVERE: Could not get cloud Cloud Delivery
Jun 12, 2019 10:24:37 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.projectId = allclearid-corp
Jun 12, 2019 10:24:37 PM io.jenkins.plugins.casc.BaseConfigurator createAttribute
WARNING: Can't handle class com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig#jsonKeyFileUpload: type is abstract but not Describable.
Jun 12, 2019 10:24:37 PM io.jenkins.plugins.casc.Attribute setValue
INFO: Setting com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig@44cd36df.filename = jenkins-master.json
Jun 12, 2019 10:24:37 PM io.jenkins.plugins.casc.Attribute setValue
INFO: Setting com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig@44cd36df.secretJsonKey = {KEYTEXT_ELIDED}
Jun 12, 2019 10:24:37 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.serviceAccountConfig = {json={}}
```
Any additional debugging information you can provide would be much appreciated.

Thanks!

**Comment by casz** [comment]
This issue should be reported over at https://github.com/jenkinsci/google-oauth-plugin

**Comment by casz** [comment]
Regarding
`WARNING: Can't handle class com.google.jenkins.plugins.credentials.oauth.JsonServiceAccountConfig#jsonKeyFileUpload: type is abstract but not Describable.`
Please update to a newer version of JCasC

**Comment by pfallclear** [comment]
Thank you, we'll give that a try and if not resolved will follow up with the google oauth plugin project. Was wondering if the first message from the CasC plugin: No configurator found for type class com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentialsModule
could be caused by the oauth plugin not being registered with CasC somehow? The oauth plugin is installed and we can manually upload the credentials through the UI, but see these errors repeat on every restart.

**Comment by casz** [comment]
Definitely an issue with google oauth plugin: https://github.com/jenkinsci/google-oauth-plugin/blob/c1c6104935c0a9106b9df0176c6aecff2dcbad22/src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentials.java#L47

This explains why: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/COMPATIBILITY.md

**Comment by pfallclear** [comment]
Thanks for looking at it, we'll try the upgrade and see if it resolves or yields new info.
