### ISSUE TITLE
Document how to add a description to Jenkins' main view

### ISSUE THREAD

**Issue by quilicicf** [jenkinsci/configuration-as-code-plugin#928]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Hi, 

I'd like to add a description to Jenkins' landing page via configuration as code and can't find if it's possible/how to do it. 

What I'd like to do is update the `description` field of the `All` view that's displayed when opening Jenkins. 

Is that doable?

**Comment by timja** [comment]
should be possible on 2.180+ of jenkins, configure it manually and then export it

**Comment by quilicicf** [comment]
Damn, using 2.176. 
Will try with 2.180 and close this ticket if appropriate.

**Comment by Smasherr** [comment]
I think that's:
```
jenkins:
  systemMessage:
```

**Comment by timja** [comment]
> I think that's:
> 
> ```
> jenkins:
>   systemMessage: "<h1>Welcome</h1>"
> ```

Yes that's right, I misread it earlier

**Comment by casz** [comment]
Already thoroughly documented: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/jenkins

**Comment by timja** [comment]
Probably not the most discoverable though, I didn't find it when I wanted it at first, but the easiest way is just to configure it in the UI and export it

**Comment by quilicicf** [comment]
Got it working!
