### ISSUE TITLE
DataBoundConfigurator passes null to constructor when CNode is not present

### ISSUE THREAD

**Issue by AbhyudayaSharma** [jenkinsci/configuration-as-code-plugin#951]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version - 2.164.1

- [X] Plugin version - 1.24-rc834.e55a938c5ddd

- [X] OS - Windows 10 1903, JDK 1.8.0_181

### Description

`DataBoundConfigurator` passes `null` to the constructor causing a `NullPointerException` when a `CNode` corresponding to a parameter is not present. See the stack trace below.
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: folderBased: Failed to construct instance of class io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy.
 Constructor: public io.jenkins.plugins.folderauth.FolderBasedAuthorizationStrategy(java.util.Set,java.util.Set).
 Arguments: [java.util.HashSet, null].
 Expected Parameters: globalRoles java.util.Set<io.jenkins.plugins.folderauth.roles.GlobalRole>, folderRoles java.util.Set<io.jenkins.plugins.folderauth.roles.FolderRole>
    at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:168)
```

**Comment by timja** [comment]
No need to create an issue and a PR
