### ISSUE TITLE
SCM checkout locks CasC directory

### ISSUE THREAD

**Issue by namyel** [jenkinsci/configuration-as-code-plugin#959]
### Description

I have my CasC yaml files checked out from subversion and I would like to update them directy on Jenkins-Master by a Jenkins Pipeline-Job by using the checkout scm step from svn. Whenever the checkout needs write access, the CasC-directory becomes locked in read and write access until I restart the Jenkins. So I don't have any possibility to update the casc files on this way while the jenkins runs. Updating the CasC-directory without changes in repository works fine, but it crashes when there are files to change by the update-step.

My CasC-directory contains one yaml-file in the main-folder and additionaly some specific yaml-files inside a subfolder. All files become locked after (failing) write-access by the checkout-step. Manually updating and changing the yamls works without problems until the first checkout-attempt by the pipeline-step.

### Environment
- Jenkins LTS 2.176.2
- CasC-Plugin 1.23
- Pipeline: SCM Step Plugin 2.9
- Subversion Plugin 2.12.1
- Jenkins Master OS: Windows Server 2016 Standard

## Stacktrace

> jenkins.util.io.CompositeIOException: Unable to remove file e:\Jenkins_INT\casc\INT\env.yaml
> 	at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:248)
> 	at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:201)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:212)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:211)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:83)
> 	at hudson.Util.deleteContentsRecursive(Util.java:259)
> 	at hudson.Util.deleteContentsRecursive(Util.java:248)
> 	at hudson.scm.subversion.CheckoutUpdater$SubversionUpdateTask.perform(CheckoutUpdater.java:93)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:176)
> 	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:134)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:1041)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:1017)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:990)
> 	at hudson.FilePath.act(FilePath.java:1076)
> 	at hudson.FilePath.act(FilePath.java:1059)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:937)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:864)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
> 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> java.nio.file.AccessDeniedException: e:\Jenkins_INT\casc\INT\env.yaml
> 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
> 	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
> 	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
> 	at java.nio.file.Files.deleteIfExists(Files.java:1165)
> 	at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:233)
> 	at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:201)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:212)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:211)
> 	at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:222)
> 	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:83)
> 	at hudson.Util.deleteContentsRecursive(Util.java:259)
> 	at hudson.Util.deleteContentsRecursive(Util.java:248)
> 	at hudson.scm.subversion.CheckoutUpdater$SubversionUpdateTask.perform(CheckoutUpdater.java:93)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:176)
> 	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:134)
> 	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:168)
> 	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:1041)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:1017)
> 	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:990)
> 	at hudson.FilePath.act(FilePath.java:1076)
> 	at hudson.FilePath.act(FilePath.java:1059)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:937)
> 	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:864)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
> 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
> 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by timja** [comment]
Not really sure what the ask is? Casc isn't related to scm checkout, you just need to provide a yaml file.

**Comment by namyel** [comment]
Sorry for the bad understandability.
My casc-files are under version control in SVN and i cannot update my working copy on the running jenkins master by using the pipeline-step "checkout".
It thought there could be a conflict in accessing the casc files - whose config is currently loaded with the casc-plugin - during svn update.
Your answer sounds like that is not very plausible?!

I could not identify another reason yet because the same checkout procedure seemed to be possible everywhere else in jenkins-home-directory but not in the casc-directory.
If there could not be any relation to the casc plugin, please close the issue.

**Comment by timja** [comment]
Ah, there is a bug on jira about a file handle not being closed, it may be related to casc then.

**Comment by casz** [comment]
I may have a solution to the problem 😓

YamlSource needs to implement close able.
