### ISSUE TITLE
Log severity should be WARN or ERROR when sources couldn't be provided 

### ISSUE THREAD

**Issue by jseadragon** [jenkinsci/configuration-as-code-plugin#961]
### Feature Request

I've noticed that when my Configuration as Code fails to be applied, we get this message in the log:
```
Jul 23, 2019 2:24:48 AM io.jenkins.plugins.casc.ConfigurationAsCode doReplace
INFO: Provided sources could not be applied
```
It seems like this should be an `ERROR` or a `WARN` level message. Is it reasonable to update this? I also agree that there should be a notification in the UI, but at a minimum I think this should be a more severe log than an `INFO`, as it's easy to miss.

See [ConfigurationAsCode.java +182](https://github.com/jenkinsci/configuration-as-code-plugin/blob/70714a77190a884bdffcf4a781728f5a4b69618d/plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java#L182)

**Comment by oleg-nenashev** [comment]
+1 for WARN as a quick fix

**Comment by casz** [comment]
@jseadragon feel free to send a pull request 😉

**Comment by jseadragon** [comment]
Sure thing. I’ll put a PR up. 

Jonathan
