### ISSUE TITLE
README.md screenshot shows invalid configuration for installing plugins

### ISSUE THREAD

**Issue by andrew-garner** [jenkinsci/configuration-as-code-plugin#965]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version

- [X] Plugin version

- [X] OS

### Description

[README.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md) in the root of this repository contains a screenshot which shows configuration for installing plugins using CasC. Support for this was removed in v1.8 but the presence of this config in the screenshot combined with outdated internet articles and a [CloudBees blog article](https://www.cloudbees.com/blog/jenkins-configuration-code-plugins) can lead users (like me) to waste time trying to configure this before realising this feature has been removed.

See https://github.com/jenkinsci/configuration-as-code-plugin#initial-configuration

![image](https://user-images.githubusercontent.com/51700042/62057062-c6739900-b216-11e9-97eb-d7009fec6df1.png)

**Comment by casz** [comment]
@andrew-garner feel free to take a new screenshot and submit a PR 😅

**Comment by agarthetiger** [comment]
Raised @casz 😄
