### ISSUE TITLE
Move Vault support to another plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#968]
There is a https://github.com/jenkinsci/hashicorp-vault-plugin plugin which implements Vault functionality for Jenkins. It uses Vault API libraries as well as the JCasC plugin, and there are binary compatibility issues: https://github.com/jenkinsci/configuration-as-code-plugin/issues/922

There is no practical reason to depend on a specific technology provider library in a gneric JCasC plugin. As suggested in https://github.com/jenkinsci/hashicorp-vault-plugin/pull/23 , I suggest moving the code to a separate plugin or to Hashicorp Vault Plugin directly.

It could also help us to ensure that Secret Source extensions are really extensible

**Comment by casz** [comment]
I think the best option would be to move it to hashicorp-vault-plugin if it is okay with the maintainers :) @ptierno 👋

**Comment by timja** [comment]
Agree with moving it, @ptierno hasn't been very active recently though so may need someone to maintain it:
https://github.com/ptierno

**Comment by casz** [comment]
I'd be happy to maintain hashicorp vault plugin :swea

**Comment by timja** [comment]
Maybe start a dev mailing list thread?

**Comment by casz** [comment]
on it!

**Comment by casz** [comment]
https://groups.google.com/forum/#!topic/jenkinsci-dev/5d1y7HPD1z4

**Comment by oleg-nenashev** [comment]
IMHO it was a bit premature to request access without waiting for few days for the maintainer's response. But it is up to you

**Comment by casz** [comment]
😅 He can also decide to answer on the email and he is, of course, welcome to say no 😉
As @timja said he hasn't been active on GitHub

**Comment by yogeek** [comment]
@casz I can confirm that @ptierno is not active anymore : I tried to contact him several times for a successful merge to be released and even try its gmail address that I found somewhere and never had an answer...
Anyway, thanks for taking over this plugin !

**Comment by casz** [comment]
I'll see if I can get the move done today :)
