### ISSUE TITLE
Plugin Download 404 

### ISSUE THREAD

**Issue by ldelgadop44** [jenkinsci/configuration-as-code-plugin#979]
##**### Jenkins Download**

I have been trying download configuration-as-code pluggin and does not work. 

`curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/2.176/latest/configuration-as-code.hpi -o /usr/share/jenkins/ref/plugins/configuration-as-code.jpi`

**Request response:** _curl: (22) The requested URL returned error: 404 Not Found_

**Comment by oleg-nenashev** [comment]
Looks like a mirror issue

**Comment by casz** [comment]
Not sure this is something we can resolve here.
Best create an infra ticket on https://issues.jenkins-ci.org
