### ISSUE TITLE
Root Configurator Generation for New JSON Schema. 

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/configuration-as-code-plugin#991]
Generate the root configurators for the schema and generate a basic test suite for the inital schema generation.
We follow the `jelly.schema` files  for generation.
We have split the schema into 6 parts one for each configurator.

`plugin/src/main/resources/io/jenkins/plugins/casc/Attribute/schema.jelly
 plugin/src/main/resources/io/jenkins/plugins/casc/BaseConfigurator/schema.jelly
 plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/schema.jelly 
 plugin/src/main/resources/io/jenkins/plugins/casc/DescribableAttribute/schema.jelly
 plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/ConfigurableConfigurator/schema.jelly
 plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator/schema.jelly`

Refer to the  PR https://github.com/jenkinsci/configuration-as-code-plugin/pull/980.

**Comment by sladyn98** [comment]
@oleg-nenashev Can you add the jcasc label.

**Comment by casz** [comment]
does not make sense to label it jcasc when it is on the repo for jcasc 😆 Also our labels are under version control 😅
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/settings.yml#L14

**Comment by sladyn98** [comment]
@casz  Oh sorry for that :P

**Comment by timja** [comment]
> does not make sense to label it jcasc when it is on the repo for jcasc 😆 Also our labels are under version control 😅
> [/.github/settings.yml@`master`#L14](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/settings.yml#L14) [](/jenkinsci/configuration-as-code-plugin/blob/HEAD@{2019-08-21T09:05:36Z}/.github/settings.yml#L14)

probably dev-tools would be useful?
@sladyn98 could you send a PR?

**Comment by sladyn98** [comment]
@timja Yeah definitely on it.

**Comment by sladyn98** [comment]
To - Do Items
a) Add Support for Custom Configurable Configurators
b) Descriptor List for all configurators
@casz The schema for the attributes for the Base, Root and HeteroDescribable Configurators has been added.However I have not added the schema for all of the Descriptors for the configurators.
Would they be duplicates of the above. I am not too sure.?

**Comment by casz** [comment]
they won't be duplicated if you structure the loop and if conditions of `instanceof` so you get the expected order.
