### ISSUE TITLE
IDE integrations For JCasC.

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/configuration-as-code-plugin#992]
IDE autocompletion with error detection for the jcasc yaml files.
Focus on popular IDE’s:
Intellij - https://github.com/JetBrains/Grammar-Kit
VSCode - https://code.visualstudio.com/docs/extensionAPI/language-support

We could deal with this is two stages :

- [ ] Intellij
- [ ] VSCode

If time permits we could add further IDE integrations.

**Comment by oleg-nenashev** [comment]
We agreed that VS Code is a top priority. Then we can consider doing IDEA once VS Code is completed
