### ISSUE TITLE
Test Framework for New JSON Schema

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/configuration-as-code-plugin#997]
As suggested by @oleg-nenashev https://github.com/jenkinsci/configuration-as-code-plugin/pull/1027#discussion_r318319668
We would be adding Unit tests for the Schema.
Inital plans:

- [ ]  Add examples in tests for valid and invalid configurators , could be typos etc.

- [ ] Add examples in tests for valid and invalid data types, eg int , string.

- [ ] Separate Test for the testing the schema Generated is valid.

**Comment by oleg-nenashev** [comment]
One comment here: Test Framework != Tests. Test framework is supposed to simplify writing tests by moving common logic into various utility methods. Is this part considered here?

**Comment by sladyn98** [comment]
Yeah we would just have to add a file and call a few common methods. I could include it in the next PR of the next schema. So to answer your question It has been considered.
